import React from "react"
import { createPortal } from "react-dom"
import useEvent from "react-use-event-hook"
import * as RHF from "react-hook-form"
import * as EG2 from "@halllky/editable-grid"
import { ChevronDownIcon, ChevronRightIcon, MagnifyingGlassIcon, XMarkIcon } from "@heroicons/react/24/outline"
import { usePagedSearch, type SearchResult } from "../search/usePagedSearch"
import { useSearchConditionForm, type SearchConditionBase, type SearchConditionModule, type UseSearchConditionFormReturn } from "../form/useSearchConditionForm"
import { useOpenDialogInHost, type OpenDialogInHost } from "./SearchDialogHost"
import { buttonColumn } from "../grid/ButtonColumn"

/**
 * 検索ダイアログの定義。検索ダイアログごとに異なる部分だけをここで指定する。
 * どの検索ダイアログにも共通の振る舞いは defineSearchDialog が決めるので、ここでは指定できない。
 *
 * TOpenParams はダイアログを開くときに呼び出し元から渡すパラメータ。不要な場合は void にする。
 */
export type SearchDialogDefinition<
  TSearchCondition extends SearchConditionBase,
  TItem,
  TOpenParams = void,
> = {
  /** ダイアログのタイトル。「〇〇 検索」の〇〇の部分 */
  title: string
  /** 検索条件の自動生成モジュール。検索条件欄のフォームの組み立てに使う */
  autoGenerated: SearchConditionModule<TSearchCondition>
  /**
   * ダイアログを開いたときの検索条件。並び順の初期値もここで指定する。
   * skip と take はダイアログがページングのために上書きするので、指定しても無視される。
   * 未指定の場合は createNewSearchCondition の戻り値。
   */
  getDefaultSearchCondition?: (params: TOpenParams) => TSearchCondition
  /**
   * 検索条件欄。form 要素の内側に描画される。
   * 検索ボタン・クリアボタンはダイアログが描画するので、ここには含めない。
   */
  SearchCondition: (props: SearchDialogConditionProps<TSearchCondition, TOpenParams>) => React.ReactNode
  /**
   * 検索結果欄のグリッドの列定義。
   * 選択のための列（選択ボタン・チェックボックス）はダイアログが付けるので、ここには含めない。
   */
  getResultColumns: (params: TOpenParams) => EG2.EditableGridColumn<TItem>[]
  /**
   * サーバー側の検索処理を呼ぶ。
   * condition の skip と take はダイアログが設定したものになっている。
   * signal は、検索中に次の検索が始まったりダイアログが閉じられたりしたときに中断するためのもの。サーバー呼び出しに渡すこと。
   */
  search: (condition: TSearchCondition, signal: AbortSignal) => Promise<SearchResult<TItem>>
  /**
   * 検索結果のアイテムを一意に識別する文字列を返す。
   * 複数選択で、ページを移動しても選択状態を保つのに使う。
   */
  getItemKey: (item: TItem) => string
  /** 外部参照の入力欄（入力コンポーネントの RefTo と、列定義ヘルパーの refTo）から使うときの情報 */
  refField: SearchDialogRefFieldDefinition<TSearchCondition, TItem, TOpenParams>
}

/** 外部参照の入力欄から検索ダイアログを使うときの情報 */
export type SearchDialogRefFieldDefinition<TSearchCondition extends SearchConditionBase, TItem, TOpenParams> = {
  /**
   * 入力欄にコードとして表示し、手入力を受け付ける値の、アイテムから見たパス。
   * 文字列型の項目だけを指定できる。数値や日付など、検索条件で範囲指定になる型の項目は扱えない。
   */
  codePath: RHF.Path<TItem>
  /** 入力欄に名称として表示する値の、アイテムから見たパス。コードと同じく文字列型の項目だけを指定できる */
  namePath: RHF.Path<TItem>
  /**
   * 画面表示用データの入力欄で、手入力されたコードを照合するときの検索条件。
   * 検索結果がちょうど1件ならそれを選んだものとし、2件以上ならエラーとする。
   * 検索条件のフォームの入力欄ではコードの照合を行わないので呼ばれない。
   */
  createConditionFromCode: (code: string, params: TOpenParams) => TSearchCondition
  /**
   * 選んだアイテムを、検索条件のフォームで外部参照の絞り込み条件として使える形に変換する。
   * 検索条件のフォームの入力欄から使うときだけ呼ばれる。
   */
  toFilter: (item: TItem) => RHF.FieldValues
}

/** 検索条件欄が受け取る props */
export type SearchDialogConditionProps<TSearchCondition extends SearchConditionBase, TOpenParams> = Pick<
  UseSearchConditionFormReturn<TSearchCondition>,
  'Input' | 'FieldLabel' | 'formMethods'
> & {
  /** ダイアログを開くときに呼び出し元から渡されたパラメータ */
  params: TOpenParams
}

/** defineSearchDialog の戻り値 */
export type SearchDialog<TItem, TOpenParams = void> = {
  /**
   * ダイアログを開く関数を返すフック。
   * ダイアログは SearchDialogHost の中に描画されるので、呼び出し側でダイアログを描画する必要はない。
   */
  useOpen: () => OpenSearchDialog<TItem, TOpenParams>
  /** ui フォルダ内部でのみ使用する。外部参照の入力欄から使う */
  refField: {
    /** 入力欄にコードとして表示する値の、アイテムから見たパス */
    codePath: RHF.Path<TItem>
    /** 入力欄に名称として表示する値の、アイテムから見たパス */
    namePath: RHF.Path<TItem>
    /** 手入力されたコードを照合する */
    findByCode: (code: string, params: TOpenParams, signal?: AbortSignal) => Promise<FindByCodeResult<TItem>>
    /** 選んだアイテムを、検索条件のフォームで外部参照の絞り込み条件として使える形に変換する */
    toFilter: (item: TItem) => RHF.FieldValues
    /**
     * 1件だけ選ぶダイアログを開く。選ばずに閉じたら undefined を返す。
     * グリッドの列のようにフックを呼べない場所からも開けるよう、ダイアログの描画先を引数で受け取る。
     */
    selectOne: (openDialogInHost: OpenDialogInHost, params: TOpenParams) => Promise<TItem | undefined>
  }
}

/** コードの照合結果 */
export type FindByCodeResult<TItem>
  /** ちょうど1件見つかった */
  = { type: 'found', item: TItem }
  /** 見つからなかった */
  | { type: 'not-found' }
  /** 2件以上見つかった。通常はコードが一意になるよう検索条件を定義するので、定義の誤り */
  | { type: 'ambiguous', count: number }
  /** 検索処理がエラーを返したか、中断された */
  | Exclude<SearchResult<never>, { type: 'ok' }>

/**
 * 検索ダイアログを開く関数。
 * どちらも、ユーザーが選択を確定したら選んだものを、選ばずに閉じたら undefined を返す。
 */
export type OpenSearchDialog<TItem, TOpenParams> = {
  /** 1件だけ選ぶ */
  selectOne: (...args: OpenArgs<TOpenParams>) => Promise<TItem | undefined>
  /**
   * 複数選ぶ。
   * 何も選ばずに確定した場合は空配列を返す。
   */
  selectMany: (...args: OpenArgs<TOpenParams>) => Promise<TItem[] | undefined>
}

/** パラメータが void ならダイアログを開く関数に引数を渡さなくてよい */
type OpenArgs<TOpenParams> = [TOpenParams] extends [void] ? [] : [params: TOpenParams]

/**
 * 検索ダイアログを定義する。
 * モジュールのトップレベルで呼び、戻り値を export して使う。
 *
 * どの検索ダイアログも、以下の振る舞いをこの関数が決める。定義側で変えることはできない。
 *
 * ## 呼び出し方と戻り値の受け取り方
 * - useOpen が返す selectOne / selectMany を呼ぶとダイアログが開く。
 *   戻り値の Promise は、ユーザーが選択を確定するか、選ばずに閉じたときに解決する。
 * - 外部参照の入力欄（入力コンポーネントの RefTo と列定義ヘルパーの refTo）は、
 *   SearchDialogRegistry の対応表から検索ダイアログを引いて使う。画面側で検索ダイアログを指定する必要はない。
 *
 * ## 検索
 * - ダイアログを開くと、初期の検索条件ですぐに検索する。
 * - 検索ボタンか、検索条件欄での Enter で検索する。クリアボタンで検索条件を初期の状態に戻す。
 * - 検索中に次の検索を始めた場合とダイアログを閉じた場合は、検索中の処理を中断する。
 * - 検索処理が返したエラーは、サーバー側メッセージとして検索条件欄に表示する。検索条件欄の入力値の検証エラー（クライアント側エラー）も同じ場所に表示する。
 * - 検索条件欄は折りたためる。検索結果を広く表示するため。
 *
 * ## ページング
 * - 1ページの件数は固定。フッターに前へ・次へのボタン、現在のページ番号、総件数を表示する。
 * - ページを移動しても検索条件は変わらない。検索し直すと先頭のページに戻る。
 *
 * ## 選択
 * - 1件選ぶ場合: 各行の先頭に選択ボタンを置く。選択ボタンのクリック、行のダブルクリック、行を選んだ状態での Enter で確定し、ダイアログを閉じる。
 * - 複数選ぶ場合: 各行の先頭にチェックボックスを置く。チェックはページを移動しても保たれる。
 *   フッターに選択中の件数と確定ボタンを表示し、確定ボタンで確定してダイアログを閉じる。
 *
 * ## 閉じる
 * - 閉じるボタン・Escape キー・ダイアログの外側のクリックで、選ばずに閉じる。
 */
export function defineSearchDialog<
  TSearchCondition extends SearchConditionBase,
  TItem,
  TOpenParams = void,
>(definition: SearchDialogDefinition<TSearchCondition, TItem, TOpenParams>): SearchDialog<TItem, TOpenParams> {

  /** ダイアログを開き、閉じたら選ばれたものを返す */
  const open = <TMode extends SelectMode>(openDialogInHost: OpenDialogInHost, mode: TMode, params: TOpenParams) => {
    return openDialogInHost<SelectResult<TItem, TMode> | undefined>(close => (
      <SearchDialogView
        definition={definition}
        mode={mode}
        params={params}
        onClose={close as (result: SelectResult<TItem, SelectMode> | undefined) => void}
      />
    ))
  }

  return {
    useOpen: () => {
      const openDialogInHost = useOpenDialogInHost()
      return React.useMemo(() => ({
        selectOne: (...args: OpenArgs<TOpenParams>) => open(openDialogInHost, 'one', args[0] as TOpenParams),
        selectMany: (...args: OpenArgs<TOpenParams>) => open(openDialogInHost, 'many', args[0] as TOpenParams),
      }), [openDialogInHost])
    },
    refField: {
      codePath: definition.refField.codePath,
      namePath: definition.refField.namePath,
      findByCode: async (code, params, signal) => {
        // 2件以上あるかどうかは総件数で分かるので、2件目までを取得すれば足りる
        const condition = {
          ...definition.refField.createConditionFromCode(code, params),
          skip: '0',
          take: '2',
        }
        const result = await definition.search(condition, signal ?? new AbortController().signal)
        if (result.type !== 'ok') return result
        const { currentPageItems, totalCount } = result.returnValue
        if (totalCount === 0 || currentPageItems.length === 0) return { type: 'not-found' }
        if (totalCount > 1) return { type: 'ambiguous', count: totalCount }
        return { type: 'found', item: currentPageItems[0] }
      },
      toFilter: definition.refField.toFilter,
      selectOne: (openDialogInHost, params) => open(openDialogInHost, 'one', params),
    },
  }
}

/** 1ページの件数 */
const PAGE_SIZE = 20

/** 1件選ぶか複数選ぶか */
type SelectMode = 'one' | 'many'
/** 選択を確定したときの結果 */
type SelectResult<TItem, TMode extends SelectMode> = TMode extends 'one' ? TItem : TItem[]

/** 検索ダイアログの本体 */
function SearchDialogView<TSearchCondition extends SearchConditionBase, TItem, TOpenParams>({ definition, mode, params, onClose }: {
  definition: SearchDialogDefinition<TSearchCondition, TItem, TOpenParams>
  mode: SelectMode
  params: TOpenParams
  onClose: (result: TItem | TItem[] | undefined) => void
}) {

  //#region 状態

  // ダイアログを開いたときの検索条件。クリアボタンでもこれに戻す
  const [defaultCondition] = React.useState(() => definition.getDefaultSearchCondition?.(params)
    ?? definition.autoGenerated.createNewSearchCondition())

  // 検索条件欄のフォーム
  const conditionForm = useSearchConditionForm(definition.autoGenerated, { defaultValues: defaultCondition })
  const { formMethods, Input, FieldLabel, RootErrors, setServerMessages, clearServerMessages } = conditionForm

  // 検索の実行と結果。ページを移動するときは、最後に検索した条件を使う
  const { searched, isSearching, searchPage } = usePagedSearch(definition.search, setServerMessages)

  // 複数選択で選ばれているもの。キーはアイテムを一意に識別する文字列
  const [selectedItems, setSelectedItems] = React.useState<ReadonlyMap<string, TItem>>(new Map())

  // 検索条件欄を折りたたんでいるかどうか
  const [isConditionCollapsed, setIsConditionCollapsed] = React.useState(false)

  const dialogRef = React.useRef<HTMLDivElement>(null)
  const gridRef = React.useRef<EG2.EditableGridRef<TItem>>(null)

  //#endregion 状態

  //#region 検索

  // ダイアログを開いたら初期の検索条件で検索する（サーバーとの同期）。閉じたときの中断は usePagedSearch が行う
  React.useEffect(() => {
    searchPage(defaultCondition, 0, PAGE_SIZE)
  }, [])

  // ダイアログを開いたら、検索条件欄の最初の入力欄にフォーカスを移す。Escape キーで閉じられるよう、入力欄が無ければダイアログ自体に移す（DOM との同期）
  React.useEffect(() => {
    const firstInput = dialogRef.current?.querySelector<HTMLElement>('form input, form select, form textarea')
    if (firstInput) firstInput.focus()
    else dialogRef.current?.focus()
  }, [])

  const handleSearch = formMethods.handleSubmit(condition => searchPage(condition, 0, PAGE_SIZE))
  const handleClear = () => {
    formMethods.reset(defaultCondition)
    clearServerMessages()
  }
  const handleMovePage = (pageIndex: number) => {
    if (searched) searchPage(searched.condition, pageIndex, PAGE_SIZE)
  }

  //#endregion 検索

  //#region 選択

  const items = searched?.result.currentPageItems ?? EMPTY_ITEMS as TItem[]
  const handleSelectOne = (item: TItem) => onClose(item)
  const handleToggleItem = (item: TItem) => {
    const key = definition.getItemKey(item)
    setSelectedItems(prev => {
      const next = new Map(prev)
      if (next.has(key)) next.delete(key)
      else next.set(key, item)
      return next
    })
  }
  const handleConfirmMany = () => onClose(Array.from(selectedItems.values()))

  // 1件選ぶ場合は、行のダブルクリックで確定する。ダブルクリックの1回目のクリックで行が選ばれている
  const handleGridDoubleClick = () => {
    if (mode !== 'one') return
    const selected = gridRef.current?.getSelectedRows()[0]
    if (selected) handleSelectOne(selected.row)
  }

  //#endregion 選択

  //#region グリッド

  const rowKeys = React.useMemo(() => items.map((_, index) => String(index)), [items])
  const getLatestRowObject = React.useCallback((index: number) => items[index], [items])

  // 先頭に選択のための列を付ける。行を選んだ状態でのキー操作は、どの列のセルを選んでいても受け付ける
  // 列定義は選択状態が変わったときだけ作り直したいが、列の中のイベントからは最新の関数を呼びたいので、参照を固定する
  const handleSelectOneEvent = useEvent(handleSelectOne)
  const handleToggleItemEvent = useEvent(handleToggleItem)
  const columns = React.useMemo((): EG2.EditableGridColumn<TItem>[] => {
    const onCellKeyDown: EG2.EditableGridLeafColumn<TItem>['onCellKeyDown'] = ({ row, event }) => {
      if (mode === 'one' && event.key === 'Enter') {
        event.preventDefault()
        handleSelectOneEvent(row)
      } else if (mode === 'many' && event.key === ' ') {
        event.preventDefault()
        handleToggleItemEvent(row)
      }
    }
    // 検索結果のグリッドは読み取り専用だが、選択は値を変える操作ではないのでボタンを表示する。
    // この列のセルでの Enter は、ボタンのクリックとして扱われる
    const selectColumn: EG2.EditableGridColumn<TItem> = mode === 'one' ? buttonColumn<TItem>(
      '選択',
      row => handleSelectOneEvent(row),
      { columnId: '__select__', isFixed: true, showWhenReadOnly: true },
    ) : {
      columnId: '__select__',
      defaultWidth: 40,
      disableResizing: true,
      isFixed: true,
      renderHeader: () => null,
      getValuesForRender: row => [selectedItems.has(definition.getItemKey(row))] as const,
      renderBody: ({ deps: [isSelected], getRow }) => (
        <div className="flex justify-center items-center h-full">
          <input
            type="checkbox"
            checked={isSelected}
            onMouseDown={e => e.stopPropagation()}
            onChange={() => handleToggleItemEvent(getRow())}
            className="cursor-pointer"
          />
        </div>
      ),
      onCellKeyDown,
    } satisfies EG2.EditableGridLeafColumn<TItem, readonly [boolean]>
    return [
      selectColumn,
      ...definition.getResultColumns(params).map(column => withCellKeyDown(column, onCellKeyDown)),
    ]
    // 選択状態はチェックボックスの表示に使うので、変わったら列を作り直して描画し直す
  }, [mode, selectedItems])

  //#endregion グリッド

  //#region レンダリング

  const totalCount = searched?.result.totalCount ?? 0
  const pageIndex = searched?.pageIndex ?? 0
  const pageCount = Math.max(1, Math.ceil(totalCount / PAGE_SIZE))

  return createPortal(
    // 外側のクリックで閉じる。シェード自体が押されたときだけ反応させる
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-8 bg-black/40"
      onMouseDown={e => { if (e.target === e.currentTarget) onClose(undefined) }}
    >
      {/* ダイアログ本体。Escape キーで閉じる。中の要素が Escape キーを処理した場合は閉じない */}
      <div
        ref={dialogRef}
        role="dialog"
        tabIndex={-1}
        onKeyDown={e => {
          if (e.key === 'Escape' && !e.defaultPrevented) {
            e.preventDefault()
            onClose(undefined)
          }
        }}
        className="flex flex-col w-full max-w-4xl h-full max-h-[48rem] bg-white rounded shadow-lg outline-none overflow-hidden"
      >

        {/* ヘッダ。タイトルのクリックで検索条件欄を折りたたむ */}
        <div className="flex items-center px-4 py-2 border-b border-gray-200">
          <button
            type="button"
            onClick={() => setIsConditionCollapsed(prev => !prev)}
            className="flex items-center gap-1 font-bold text-lg select-none cursor-pointer"
          >
            {isConditionCollapsed
              ? <ChevronRightIcon className="w-5 h-5" />
              : <ChevronDownIcon className="w-5 h-5" />}
            {definition.title} 検索
          </button>
          <div className="flex-1" />
          <button type="button" onClick={() => onClose(undefined)} title="閉じる" className="p-1 rounded hover:bg-gray-200 cursor-pointer">
            <XMarkIcon className="w-6 h-6" />
          </button>
        </div>

        {/* 検索条件欄 */}
        {!isConditionCollapsed && (
          // 検証はブラウザに任せず react-hook-form の検証ルールで行う
          <form noValidate onSubmit={handleSearch} className="flex flex-col gap-2 px-4 py-2 border-b border-gray-200">
            <RootErrors />
            <definition.SearchCondition Input={Input} FieldLabel={FieldLabel} formMethods={formMethods} params={params} />
            {/* 検索・クリア */}
            <div className="flex justify-end gap-2">
              <DialogButton onClick={handleClear}>クリア</DialogButton>
              <DialogButton submit fill disabled={isSearching}>
                <MagnifyingGlassIcon className="w-4 h-4" />
                検索
              </DialogButton>
            </div>
          </form>
        )}

        {/* 検索結果欄 */}
        <div className="flex-1 min-h-0 flex flex-col gap-1 px-4 py-2">
          <div className="text-sm text-gray-600 select-none">
            {isSearching ? '検索中...' : `全${totalCount}件`}
          </div>
          <div className="flex-1 min-h-0 flex flex-col" onDoubleClick={handleGridDoubleClick}>
            <EG2.EditableGrid
              ref={gridRef}
              rowKeys={rowKeys}
              getLatestRowObject={getLatestRowObject}
              columns={columns}
              isReadOnly
              clearSelectionOnBlur
              className="flex-1 border border-gray-300"
            />
          </div>
        </div>

        {/* フッタ。ページングと、複数選択の確定 */}
        <div className="flex items-center gap-2 px-4 py-2 border-t border-gray-200">
          <DialogButton onClick={() => handleMovePage(pageIndex - 1)} disabled={isSearching || pageIndex <= 0}>前へ</DialogButton>
          <span className="text-sm select-none">{pageIndex + 1} / {pageCount}</span>
          <DialogButton onClick={() => handleMovePage(pageIndex + 1)} disabled={isSearching || pageIndex + 1 >= pageCount}>次へ</DialogButton>
          <div className="flex-1" />
          {mode === 'many' && (
            <>
              <span className="text-sm select-none">{selectedItems.size}件選択中</span>
              <DialogButton fill onClick={handleConfirmMany}>確定</DialogButton>
            </>
          )}
        </div>
      </div>
    </div>,
    document.body,
  )

  //#endregion レンダリング
}

const EMPTY_ITEMS: unknown[] = []

/** ダイアログ内のボタン */
function DialogButton({ submit, fill, disabled, onClick, children }: {
  submit?: boolean
  fill?: boolean
  disabled?: boolean
  onClick?: () => void
  children?: React.ReactNode
}) {
  return (
    <button
      type={submit ? 'submit' : 'button'}
      onClick={onClick}
      disabled={disabled}
      className={`flex items-center gap-1 px-3 py-1 text-sm rounded border select-none ${fill
        ? 'bg-teal-600 text-white border-transparent hover:bg-teal-700'
        : 'bg-white text-teal-700 border-teal-700 hover:bg-gray-50'
        } ${disabled ? 'opacity-50 cursor-not-allowed' : 'cursor-pointer'}`}
    >
      {children}
    </button>
  )
}

/** 列定義の各リーフ列に、行を選んだ状態でのキー操作を足す。列定義側のキー操作が先に呼ばれる */
function withCellKeyDown<TItem>(
  column: EG2.EditableGridColumn<TItem>,
  onCellKeyDown: NonNullable<EG2.EditableGridLeafColumn<TItem>['onCellKeyDown']>,
): EG2.EditableGridColumn<TItem> {
  if ('columns' in column) {
    return { ...column, columns: column.columns.map(leaf => withCellKeyDown(leaf, onCellKeyDown) as EG2.EditableGridLeafColumn<TItem>) }
  }
  return {
    ...column,
    onCellKeyDown: args => {
      column.onCellKeyDown?.(args)
      if (!args.event.defaultPrevented) onCellKeyDown(args)
    },
  }
}

