BEGIN TRANSACTION;
CREATE TABLE "BUSHO" (
    "BUSHO_CD" TEXT NOT NULL CONSTRAINT "PK_BUSHO" PRIMARY KEY,
    "BUSHO_NAME" TEXT NOT NULL,
    "CreatedAt" TEXT NULL,
    "CreateUser" TEXT NULL,
    "UpdatedAt" TEXT NULL,
    "UpdateUser" TEXT NULL,
    "Version" INTEGER NOT NULL
);

CREATE TABLE "EMPLOYEE" (
    "ID" TEXT NOT NULL CONSTRAINT "PK_EMPLOYEE" PRIMARY KEY,
    "NAME" TEXT NOT NULL,
    "NAME_KANA" TEXT NULL,
    "TAISHOKU" TEXT NULL,
    "CreatedAt" TEXT NULL,
    "CreateUser" TEXT NULL,
    "UpdatedAt" TEXT NULL,
    "UpdateUser" TEXT NULL,
    "Version" INTEGER NOT NULL
);

CREATE TABLE "患者マスタ" (
    "CUSTOMER_ID" TEXT NOT NULL CONSTRAINT "PK_患者マスタ" PRIMARY KEY,
    "CUSTOMER_NAME" TEXT NOT NULL,
    "CUSTOMER_KANA" TEXT NULL,
    "BIRTH_DATE" TEXT NULL,
    "GENDER" INTEGER NULL,
    "EMAIL" TEXT NULL,
    "PHONE" TEXT NULL,
    "CreatedAt" TEXT NULL,
    "CreateUser" TEXT NULL,
    "UpdatedAt" TEXT NULL,
    "UpdateUser" TEXT NULL,
    "Version" INTEGER NOT NULL
);

CREATE TABLE "機器分類マスタ" (
    "CATEGORY_ID" TEXT NOT NULL CONSTRAINT "PK_機器分類マスタ" PRIMARY KEY,
    "CATEGORY_NAME" TEXT NULL,
    "CreatedAt" TEXT NULL,
    "CreateUser" TEXT NULL,
    "UpdatedAt" TEXT NULL,
    "UpdateUser" TEXT NULL,
    "Version" INTEGER NOT NULL
);

CREATE TABLE "供給業者マスタ" (
    "SUPPLIER_ID" TEXT NOT NULL CONSTRAINT "PK_供給業者マスタ" PRIMARY KEY,
    "SUPPLIER_NAME" TEXT NULL,
    "CONTACT_PERSON" TEXT NULL,
    "PHONE" TEXT NULL,
    "EMAIL" TEXT NULL,
    "CreatedAt" TEXT NULL,
    "CreateUser" TEXT NULL,
    "UpdatedAt" TEXT NULL,
    "UpdateUser" TEXT NULL,
    "Version" INTEGER NOT NULL
);

CREATE TABLE "AUTHORITY" (
    "Parent_ID" TEXT NOT NULL,
    "AUTHORITY_LEVEL" INTEGER NOT NULL,
    "CreatedAt" TEXT NULL,
    "CreateUser" TEXT NULL,
    "UpdatedAt" TEXT NULL,
    "UpdateUser" TEXT NULL,
    CONSTRAINT "PK_AUTHORITY" PRIMARY KEY ("Parent_ID", "AUTHORITY_LEVEL"),
    CONSTRAINT "FK_EMPLOYEE_AUTHORITY" FOREIGN KEY ("Parent_ID") REFERENCES "EMPLOYEE" ("ID") ON DELETE CASCADE
);

CREATE TABLE "SHOZOKU" (
    "Parent_ID" TEXT NOT NULL,
    "NENDO" INTEGER NOT NULL,
    "診療科_BUSHO_CD" TEXT NOT NULL,
    "CreatedAt" TEXT NULL,
    "CreateUser" TEXT NULL,
    "UpdatedAt" TEXT NULL,
    "UpdateUser" TEXT NULL,
    CONSTRAINT "PK_SHOZOKU" PRIMARY KEY ("Parent_ID", "NENDO"),
    CONSTRAINT "FK_BUSHO_SHOZOKU_X6518C1A" FOREIGN KEY ("診療科_BUSHO_CD") REFERENCES "BUSHO" ("BUSHO_CD"),
    CONSTRAINT "FK_EMPLOYEE_SHOZOKU" FOREIGN KEY ("Parent_ID") REFERENCES "EMPLOYEE" ("ID") ON DELETE CASCADE
);

CREATE TABLE "医療従事者プロフィール" (
    "医療従事者_ID" TEXT NOT NULL CONSTRAINT "PK_医療従事者プロフィール" PRIMARY KEY,
    "PHOTO_URL" TEXT NULL,
    "SELF_INTRODUCTION" TEXT NULL,
    "SPECIALTY" TEXT NULL,
    "CreatedAt" TEXT NULL,
    "CreateUser" TEXT NULL,
    "UpdatedAt" TEXT NULL,
    "UpdateUser" TEXT NULL,
    "Version" INTEGER NOT NULL,
    CONSTRAINT "FK_EMPLOYEE_医療従事者プロフィール_X30E339A" FOREIGN KEY ("医療従事者_ID") REFERENCES "EMPLOYEE" ("ID")
);

CREATE TABLE "診療科マスタ" (
    "STORE_ID" TEXT NOT NULL CONSTRAINT "PK_診療科マスタ" PRIMARY KEY,
    "STORE_NAME" TEXT NULL,
    "PHONE" TEXT NULL,
    "科長_ID" TEXT NOT NULL,
    "CreatedAt" TEXT NULL,
    "CreateUser" TEXT NULL,
    "UpdatedAt" TEXT NULL,
    "UpdateUser" TEXT NULL,
    "Version" INTEGER NOT NULL,
    CONSTRAINT "FK_EMPLOYEE_診療科マスタ_X170D2D7" FOREIGN KEY ("科長_ID") REFERENCES "EMPLOYEE" ("ID")
);

CREATE TABLE "保管庫マスタ" (
    "WAREHOUSE_ID" TEXT NOT NULL CONSTRAINT "PK_保管庫マスタ" PRIMARY KEY,
    "WAREHOUSE_NAME" TEXT NULL,
    "管理責任者_ID" TEXT NOT NULL,
    "CreatedAt" TEXT NULL,
    "CreateUser" TEXT NULL,
    "UpdatedAt" TEXT NULL,
    "UpdateUser" TEXT NULL,
    "Version" INTEGER NOT NULL,
    CONSTRAINT "FK_EMPLOYEE_保管庫マスタ_XD847631" FOREIGN KEY ("管理責任者_ID") REFERENCES "EMPLOYEE" ("ID")
);

CREATE TABLE "CUSTOMER_ADDRESS" (
    "Parent_CUSTOMER_ID" TEXT NOT NULL CONSTRAINT "PK_CUSTOMER_ADDRESS" PRIMARY KEY,
    "POSTAL_CODE" TEXT NULL,
    "PREFECTURE" TEXT NULL,
    "CITY" TEXT NULL,
    "ADDRESS_LINE" TEXT NULL,
    "CreatedAt" TEXT NULL,
    "CreateUser" TEXT NULL,
    "UpdatedAt" TEXT NULL,
    "UpdateUser" TEXT NULL,
    CONSTRAINT "FK_患者マスタ_CUSTOMER_ADDRESS" FOREIGN KEY ("Parent_CUSTOMER_ID") REFERENCES "患者マスタ" ("CUSTOMER_ID") ON DELETE CASCADE
);

CREATE TABLE "MEMBERSHIP" (
    "Parent_CUSTOMER_ID" TEXT NOT NULL CONSTRAINT "PK_MEMBERSHIP" PRIMARY KEY,
    "RANK" INTEGER NULL,
    "JOIN_DATE" TEXT NULL,
    "LAST_VISIT" TEXT NULL,
    "CreatedAt" TEXT NULL,
    "CreateUser" TEXT NULL,
    "UpdatedAt" TEXT NULL,
    "UpdateUser" TEXT NULL,
    CONSTRAINT "FK_患者マスタ_MEMBERSHIP" FOREIGN KEY ("Parent_CUSTOMER_ID") REFERENCES "患者マスタ" ("CUSTOMER_ID") ON DELETE CASCADE
);

CREATE TABLE "予約" (
    "RESERVATION_ID" TEXT NOT NULL CONSTRAINT "PK_予約" PRIMARY KEY,
    "RESERVATION_DATETIME" TEXT NOT NULL,
    "患者_CUSTOMER_ID" TEXT NOT NULL,
    "RESERVATION_TYPE" INTEGER NULL,
    "RESERVATION_NOTE" TEXT NULL,
    "担当医_ID" TEXT NOT NULL,
    "CreatedAt" TEXT NULL,
    "CreateUser" TEXT NULL,
    "UpdatedAt" TEXT NULL,
    "UpdateUser" TEXT NULL,
    "Version" INTEGER NOT NULL,
    CONSTRAINT "FK_EMPLOYEE_予約_XDECF289" FOREIGN KEY ("担当医_ID") REFERENCES "EMPLOYEE" ("ID"),
    CONSTRAINT "FK_患者マスタ_予約_XFB576B4" FOREIGN KEY ("患者_CUSTOMER_ID") REFERENCES "患者マスタ" ("CUSTOMER_ID")
);

CREATE TABLE "医療機器マスタ" (
    "PRODUCT_ID" TEXT NOT NULL CONSTRAINT "PK_医療機器マスタ" PRIMARY KEY,
    "PRODUCT_NAME" TEXT NOT NULL,
    "PRICE" INTEGER NOT NULL,
    "機器分類_CATEGORY_ID" TEXT NULL,
    "供給業者_SUPPLIER_ID" TEXT NULL,
    "CreatedAt" TEXT NULL,
    "CreateUser" TEXT NULL,
    "UpdatedAt" TEXT NULL,
    "UpdateUser" TEXT NULL,
    "Version" INTEGER NOT NULL,
    CONSTRAINT "FK_供給業者マスタ_医療機器マスタ_X89DCA22" FOREIGN KEY ("供給業者_SUPPLIER_ID") REFERENCES "供給業者マスタ" ("SUPPLIER_ID"),
    CONSTRAINT "FK_機器分類マスタ_医療機器マスタ_X7D2BEB8" FOREIGN KEY ("機器分類_CATEGORY_ID") REFERENCES "機器分類マスタ" ("CATEGORY_ID")
);

CREATE TABLE "QUALIFICATIONS" (
    "Parent_医療従事者_ID" TEXT NOT NULL,
    "QUALIFICATION_NAME" TEXT NOT NULL,
    "ACQUISITION_DATE" TEXT NULL,
    "EXPIRY_DATE" TEXT NULL,
    "CreatedAt" TEXT NULL,
    "CreateUser" TEXT NULL,
    "UpdatedAt" TEXT NULL,
    "UpdateUser" TEXT NULL,
    CONSTRAINT "PK_QUALIFICATIONS" PRIMARY KEY ("Parent_医療従事者_ID", "QUALIFICATION_NAME"),
    CONSTRAINT "FK_医療従事者プロフィール_QUALIFICATIONS" FOREIGN KEY ("Parent_医療従事者_ID") REFERENCES "医療従事者プロフィール" ("医療従事者_ID") ON DELETE CASCADE
);

CREATE TABLE "BUSINESS_HOURS" (
    "Parent_STORE_ID" TEXT NOT NULL CONSTRAINT "PK_BUSINESS_HOURS" PRIMARY KEY,
    "OPENING_TIME" TEXT NULL,
    "CLOSING_TIME" TEXT NULL,
    "CreatedAt" TEXT NULL,
    "CreateUser" TEXT NULL,
    "UpdatedAt" TEXT NULL,
    "UpdateUser" TEXT NULL,
    CONSTRAINT "FK_診療科マスタ_BUSINESS_HOURS" FOREIGN KEY ("Parent_STORE_ID") REFERENCES "診療科マスタ" ("STORE_ID") ON DELETE CASCADE
);

CREATE TABLE "STORE_ADDRESS" (
    "Parent_STORE_ID" TEXT NOT NULL CONSTRAINT "PK_STORE_ADDRESS" PRIMARY KEY,
    "POSTAL_CODE" TEXT NULL,
    "PREFECTURE" TEXT NULL,
    "CITY" TEXT NULL,
    "ADDRESS_LINE" TEXT NULL,
    "CreatedAt" TEXT NULL,
    "CreateUser" TEXT NULL,
    "UpdatedAt" TEXT NULL,
    "UpdateUser" TEXT NULL,
    CONSTRAINT "FK_診療科マスタ_STORE_ADDRESS" FOREIGN KEY ("Parent_STORE_ID") REFERENCES "診療科マスタ" ("STORE_ID") ON DELETE CASCADE
);

CREATE TABLE "勤務スケジュール" (
    "医療従事者_ID" TEXT NOT NULL,
    "診療科_STORE_ID" TEXT NOT NULL,
    "DATE" TEXT NOT NULL,
    "START_TIME" TEXT NULL,
    "END_TIME" TEXT NULL,
    "BREAK_TIME" INTEGER NULL,
    "REMARKS" TEXT NULL,
    "CreatedAt" TEXT NULL,
    "CreateUser" TEXT NULL,
    "UpdatedAt" TEXT NULL,
    "UpdateUser" TEXT NULL,
    "Version" INTEGER NOT NULL,
    CONSTRAINT "PK_勤務スケジュール" PRIMARY KEY ("医療従事者_ID", "診療科_STORE_ID", "DATE"),
    CONSTRAINT "FK_EMPLOYEE_勤務スケジュール_X30E339A" FOREIGN KEY ("医療従事者_ID") REFERENCES "EMPLOYEE" ("ID"),
    CONSTRAINT "FK_診療科マスタ_勤務スケジュール_X6518C1A" FOREIGN KEY ("診療科_STORE_ID") REFERENCES "診療科マスタ" ("STORE_ID")
);

CREATE TABLE "診療履歴" (
    "ORDER_ID" TEXT NOT NULL CONSTRAINT "PK_診療履歴" PRIMARY KEY,
    "ORDER_DATE" TEXT NOT NULL,
    "患者_CUSTOMER_ID" TEXT NOT NULL,
    "診療科_STORE_ID" TEXT NULL,
    "担当医_ID" TEXT NOT NULL,
    "CreatedAt" TEXT NULL,
    "CreateUser" TEXT NULL,
    "UpdatedAt" TEXT NULL,
    "UpdateUser" TEXT NULL,
    "Version" INTEGER NOT NULL,
    CONSTRAINT "FK_EMPLOYEE_診療履歴_XDECF289" FOREIGN KEY ("担当医_ID") REFERENCES "EMPLOYEE" ("ID"),
    CONSTRAINT "FK_患者マスタ_診療履歴_XFB576B4" FOREIGN KEY ("患者_CUSTOMER_ID") REFERENCES "患者マスタ" ("CUSTOMER_ID"),
    CONSTRAINT "FK_診療科マスタ_診療履歴_X6518C1A" FOREIGN KEY ("診療科_STORE_ID") REFERENCES "診療科マスタ" ("STORE_ID")
);

CREATE TABLE "WAREHOUSE_ADDRESS" (
    "Parent_WAREHOUSE_ID" TEXT NOT NULL CONSTRAINT "PK_WAREHOUSE_ADDRESS" PRIMARY KEY,
    "POSTAL_CODE" TEXT NULL,
    "PREFECTURE" TEXT NULL,
    "CITY" TEXT NULL,
    "ADDRESS_LINE" TEXT NULL,
    "CreatedAt" TEXT NULL,
    "CreateUser" TEXT NULL,
    "UpdatedAt" TEXT NULL,
    "UpdateUser" TEXT NULL,
    CONSTRAINT "FK_保管庫マスタ_WAREHOUSE_ADDRESS" FOREIGN KEY ("Parent_WAREHOUSE_ID") REFERENCES "保管庫マスタ" ("WAREHOUSE_ID") ON DELETE CASCADE
);

CREATE TABLE "POINT_HISTORY" (
    "Parent_Parent_CUSTOMER_ID" TEXT NOT NULL,
    "HISTORY_ID" TEXT NOT NULL,
    "DATE" TEXT NULL,
    "POINTS" INTEGER NULL,
    "REASON" TEXT NULL,
    "CreatedAt" TEXT NULL,
    "CreateUser" TEXT NULL,
    "UpdatedAt" TEXT NULL,
    "UpdateUser" TEXT NULL,
    CONSTRAINT "PK_POINT_HISTORY" PRIMARY KEY ("Parent_Parent_CUSTOMER_ID", "HISTORY_ID"),
    CONSTRAINT "FK_MEMBERSHIP_POINT_HISTORY" FOREIGN KEY ("Parent_Parent_CUSTOMER_ID") REFERENCES "MEMBERSHIP" ("Parent_CUSTOMER_ID") ON DELETE CASCADE
);

CREATE TABLE "診察記録" (
    "予約_RESERVATION_ID" TEXT NOT NULL CONSTRAINT "PK_診察記録" PRIMARY KEY,
    "START_TIME" TEXT NULL,
    "END_TIME" TEXT NULL,
    "TEMPERATURE" TEXT NULL,
    "BLOOD_PRESSURE_HIGH" INTEGER NULL,
    "BLOOD_PRESSURE_LOW" INTEGER NULL,
    "NOTE" TEXT NULL,
    "CreatedAt" TEXT NULL,
    "CreateUser" TEXT NULL,
    "UpdatedAt" TEXT NULL,
    "UpdateUser" TEXT NULL,
    "Version" INTEGER NOT NULL,
    CONSTRAINT "FK_予約_診察記録_XF01C7D4" FOREIGN KEY ("予約_RESERVATION_ID") REFERENCES "予約" ("RESERVATION_ID")
);

CREATE TABLE "INVENTORY" (
    "Parent_PRODUCT_ID" TEXT NOT NULL,
    "保管庫_WAREHOUSE_ID" TEXT NOT NULL,
    "STOCK_QUANTITY" INTEGER NULL,
    "INVENTORY_DATE" TEXT NULL,
    "CreatedAt" TEXT NULL,
    "CreateUser" TEXT NULL,
    "UpdatedAt" TEXT NULL,
    "UpdateUser" TEXT NULL,
    CONSTRAINT "PK_INVENTORY" PRIMARY KEY ("Parent_PRODUCT_ID", "保管庫_WAREHOUSE_ID"),
    CONSTRAINT "FK_保管庫マスタ_INVENTORY_X48C69C7" FOREIGN KEY ("保管庫_WAREHOUSE_ID") REFERENCES "保管庫マスタ" ("WAREHOUSE_ID"),
    CONSTRAINT "FK_医療機器マスタ_INVENTORY" FOREIGN KEY ("Parent_PRODUCT_ID") REFERENCES "医療機器マスタ" ("PRODUCT_ID") ON DELETE CASCADE
);

CREATE TABLE "PRODUCT_DETAIL" (
    "Parent_PRODUCT_ID" TEXT NOT NULL CONSTRAINT "PK_PRODUCT_DETAIL" PRIMARY KEY,
    "DESCRIPTION" TEXT NULL,
    "CreatedAt" TEXT NULL,
    "CreateUser" TEXT NULL,
    "UpdatedAt" TEXT NULL,
    "UpdateUser" TEXT NULL,
    CONSTRAINT "FK_医療機器マスタ_PRODUCT_DETAIL" FOREIGN KEY ("Parent_PRODUCT_ID") REFERENCES "医療機器マスタ" ("PRODUCT_ID") ON DELETE CASCADE
);

CREATE TABLE "ORDER_DETAILS" (
    "Parent_ORDER_ID" TEXT NOT NULL,
    "医療機器_PRODUCT_ID" TEXT NOT NULL,
    "QUANTITY" INTEGER NOT NULL,
    "UNIT_PRICE" INTEGER NOT NULL,
    "SUBTOTAL" INTEGER NOT NULL,
    "CreatedAt" TEXT NULL,
    "CreateUser" TEXT NULL,
    "UpdatedAt" TEXT NULL,
    "UpdateUser" TEXT NULL,
    CONSTRAINT "PK_ORDER_DETAILS" PRIMARY KEY ("Parent_ORDER_ID", "医療機器_PRODUCT_ID"),
    CONSTRAINT "FK_医療機器マスタ_ORDER_DETAILS_X5D5C85D" FOREIGN KEY ("医療機器_PRODUCT_ID") REFERENCES "医療機器マスタ" ("PRODUCT_ID"),
    CONSTRAINT "FK_診療履歴_ORDER_DETAILS" FOREIGN KEY ("Parent_ORDER_ID") REFERENCES "診療履歴" ("ORDER_ID") ON DELETE CASCADE
);

CREATE TABLE "PAYMENT_INFO" (
    "Parent_ORDER_ID" TEXT NOT NULL CONSTRAINT "PK_PAYMENT_INFO" PRIMARY KEY,
    "PAYMENT_TYPE" INTEGER NOT NULL,
    "PAYMENT_DATE" TEXT NULL,
    "PAYMENT_STATUS" INTEGER NULL,
    "CreatedAt" TEXT NULL,
    "CreateUser" TEXT NULL,
    "UpdatedAt" TEXT NULL,
    "UpdateUser" TEXT NULL,
    CONSTRAINT "FK_診療履歴_PAYMENT_INFO" FOREIGN KEY ("Parent_ORDER_ID") REFERENCES "診療履歴" ("ORDER_ID") ON DELETE CASCADE
);

CREATE TABLE "SHIPPING_INFO" (
    "Parent_ORDER_ID" TEXT NOT NULL CONSTRAINT "PK_SHIPPING_INFO" PRIMARY KEY,
    "SHIPPING_METHOD" INTEGER NOT NULL,
    "CreatedAt" TEXT NULL,
    "CreateUser" TEXT NULL,
    "UpdatedAt" TEXT NULL,
    "UpdateUser" TEXT NULL,
    CONSTRAINT "FK_診療履歴_SHIPPING_INFO" FOREIGN KEY ("Parent_ORDER_ID") REFERENCES "診療履歴" ("ORDER_ID") ON DELETE CASCADE
);

CREATE TABLE "PRESCRIPTIONS" (
    "Parent_予約_RESERVATION_ID" TEXT NOT NULL,
    "MEDICINE_ID" TEXT NOT NULL,
    "MEDICINE_NAME" TEXT NULL,
    "DOSAGE" INTEGER NULL,
    "USAGE" TEXT NULL,
    "DAYS" INTEGER NULL,
    "REMARKS" TEXT NULL,
    "CreatedAt" TEXT NULL,
    "CreateUser" TEXT NULL,
    "UpdatedAt" TEXT NULL,
    "UpdateUser" TEXT NULL,
    CONSTRAINT "PK_PRESCRIPTIONS" PRIMARY KEY ("Parent_予約_RESERVATION_ID", "MEDICINE_ID"),
    CONSTRAINT "FK_診察記録_PRESCRIPTIONS" FOREIGN KEY ("Parent_予約_RESERVATION_ID") REFERENCES "診察記録" ("予約_RESERVATION_ID") ON DELETE CASCADE
);

CREATE TABLE "STOCK_HISTORY" (
    "Parent_Parent_PRODUCT_ID" TEXT NOT NULL,
    "Parent_保管庫_WAREHOUSE_ID" TEXT NOT NULL,
    "HISTORY_ID" TEXT NOT NULL,
    "CHANGE_DATE" TEXT NULL,
    "PREVIOUS_QUANTITY" INTEGER NULL,
    "CURRENT_QUANTITY" INTEGER NULL,
    "担当者_ID" TEXT NOT NULL,
    "CreatedAt" TEXT NULL,
    "CreateUser" TEXT NULL,
    "UpdatedAt" TEXT NULL,
    "UpdateUser" TEXT NULL,
    CONSTRAINT "PK_STOCK_HISTORY" PRIMARY KEY ("Parent_Parent_PRODUCT_ID", "Parent_保管庫_WAREHOUSE_ID", "HISTORY_ID"),
    CONSTRAINT "FK_EMPLOYEE_STOCK_HISTORY_XB332A41" FOREIGN KEY ("担当者_ID") REFERENCES "EMPLOYEE" ("ID"),
    CONSTRAINT "FK_INVENTORY_STOCK_HISTORY" FOREIGN KEY ("Parent_Parent_PRODUCT_ID", "Parent_保管庫_WAREHOUSE_ID") REFERENCES "INVENTORY" ("Parent_PRODUCT_ID", "保管庫_WAREHOUSE_ID") ON DELETE CASCADE
);

CREATE TABLE "機器点検報告" (
    "対象機器_Parent_PRODUCT_ID" TEXT NOT NULL,
    "対象機器_保管庫_WAREHOUSE_ID" TEXT NOT NULL,
    "SURVEY_DATE" TEXT NOT NULL,
    "点検担当者_ID" TEXT NOT NULL,
    "ACTUAL_COUNT" INTEGER NOT NULL,
    "INVENTORY_DIFF" INTEGER NULL,
    "SURVEY_NOTE" TEXT NULL,
    "PHOTO_URL" TEXT NULL,
    "CreatedAt" TEXT NULL,
    "CreateUser" TEXT NULL,
    "UpdatedAt" TEXT NULL,
    "UpdateUser" TEXT NULL,
    "Version" INTEGER NOT NULL,
    CONSTRAINT "PK_機器点検報告" PRIMARY KEY ("対象機器_Parent_PRODUCT_ID", "対象機器_保管庫_WAREHOUSE_ID"),
    CONSTRAINT "FK_EMPLOYEE_機器点検報告_XC084C68" FOREIGN KEY ("点検担当者_ID") REFERENCES "EMPLOYEE" ("ID"),
    CONSTRAINT "FK_INVENTORY_機器点検報告_X62E8D1C" FOREIGN KEY ("対象機器_Parent_PRODUCT_ID", "対象機器_保管庫_WAREHOUSE_ID") REFERENCES "INVENTORY" ("Parent_PRODUCT_ID", "保管庫_WAREHOUSE_ID")
);

CREATE TABLE "ACCESSORIES" (
    "Parent_Parent_PRODUCT_ID" TEXT NOT NULL,
    "ACCESSORY_ID" TEXT NOT NULL,
    "ACCESSORY_NAME" TEXT NULL,
    "QUANTITY" INTEGER NULL,
    "CreatedAt" TEXT NULL,
    "CreateUser" TEXT NULL,
    "UpdatedAt" TEXT NULL,
    "UpdateUser" TEXT NULL,
    CONSTRAINT "PK_ACCESSORIES" PRIMARY KEY ("Parent_Parent_PRODUCT_ID", "ACCESSORY_ID"),
    CONSTRAINT "FK_PRODUCT_DETAIL_ACCESSORIES" FOREIGN KEY ("Parent_Parent_PRODUCT_ID") REFERENCES "PRODUCT_DETAIL" ("Parent_PRODUCT_ID") ON DELETE CASCADE
);

CREATE TABLE "PRODUCT_SPEC" (
    "Parent_Parent_PRODUCT_ID" TEXT NOT NULL CONSTRAINT "PK_PRODUCT_SPEC" PRIMARY KEY,
    "WEIGHT" INTEGER NULL,
    "CreatedAt" TEXT NULL,
    "CreateUser" TEXT NULL,
    "UpdatedAt" TEXT NULL,
    "UpdateUser" TEXT NULL,
    CONSTRAINT "FK_PRODUCT_DETAIL_PRODUCT_SPEC" FOREIGN KEY ("Parent_Parent_PRODUCT_ID") REFERENCES "PRODUCT_DETAIL" ("Parent_PRODUCT_ID") ON DELETE CASCADE
);

CREATE TABLE "DISCOUNT_INFO" (
    "Parent_Parent_ORDER_ID" TEXT NOT NULL,
    "Parent_医療機器_PRODUCT_ID" TEXT NOT NULL,
    "DISCOUNT_CODE" TEXT NULL,
    "DISCOUNT_RATE" TEXT NULL,
    "DISCOUNT_AMOUNT" INTEGER NULL,
    "CreatedAt" TEXT NULL,
    "CreateUser" TEXT NULL,
    "UpdatedAt" TEXT NULL,
    "UpdateUser" TEXT NULL,
    CONSTRAINT "PK_DISCOUNT_INFO" PRIMARY KEY ("Parent_Parent_ORDER_ID", "Parent_医療機器_PRODUCT_ID"),
    CONSTRAINT "FK_ORDER_DETAILS_DISCOUNT_INFO" FOREIGN KEY ("Parent_Parent_ORDER_ID", "Parent_医療機器_PRODUCT_ID") REFERENCES "ORDER_DETAILS" ("Parent_ORDER_ID", "医療機器_PRODUCT_ID") ON DELETE CASCADE
);

CREATE TABLE "CARD_INFO" (
    "Parent_Parent_ORDER_ID" TEXT NOT NULL CONSTRAINT "PK_CARD_INFO" PRIMARY KEY,
    "CARD_TYPE" INTEGER NULL,
    "LAST_FOUR_DIGITS" TEXT NULL,
    "EXPIRY_DATE" TEXT NULL,
    "CreatedAt" TEXT NULL,
    "CreateUser" TEXT NULL,
    "UpdatedAt" TEXT NULL,
    "UpdateUser" TEXT NULL,
    CONSTRAINT "FK_PAYMENT_INFO_CARD_INFO" FOREIGN KEY ("Parent_Parent_ORDER_ID") REFERENCES "PAYMENT_INFO" ("Parent_ORDER_ID") ON DELETE CASCADE
);

CREATE TABLE "SHIPPING_ADDRESS" (
    "Parent_Parent_ORDER_ID" TEXT NOT NULL CONSTRAINT "PK_SHIPPING_ADDRESS" PRIMARY KEY,
    "POSTAL_CODE" TEXT NULL,
    "PREFECTURE" TEXT NULL,
    "CITY" TEXT NULL,
    "ADDRESS_LINE" TEXT NULL,
    "CreatedAt" TEXT NULL,
    "CreateUser" TEXT NULL,
    "UpdatedAt" TEXT NULL,
    "UpdateUser" TEXT NULL,
    CONSTRAINT "FK_SHIPPING_INFO_SHIPPING_ADDRESS" FOREIGN KEY ("Parent_Parent_ORDER_ID") REFERENCES "SHIPPING_INFO" ("Parent_ORDER_ID") ON DELETE CASCADE
);

CREATE TABLE "SHIPPING_STATUS" (
    "Parent_Parent_ORDER_ID" TEXT NOT NULL,
    "STATUS" INTEGER NOT NULL,
    "UPDATE_DATE" TEXT NULL,
    "REMARKS" TEXT NULL,
    "CreatedAt" TEXT NULL,
    "CreateUser" TEXT NULL,
    "UpdatedAt" TEXT NULL,
    "UpdateUser" TEXT NULL,
    CONSTRAINT "PK_SHIPPING_STATUS" PRIMARY KEY ("Parent_Parent_ORDER_ID", "STATUS"),
    CONSTRAINT "FK_SHIPPING_INFO_SHIPPING_STATUS" FOREIGN KEY ("Parent_Parent_ORDER_ID") REFERENCES "SHIPPING_INFO" ("Parent_ORDER_ID") ON DELETE CASCADE
);

CREATE TABLE "ACTIONS" (
    "Parent_対象機器_Parent_PRODUCT_ID" TEXT NOT NULL,
    "Parent_対象機器_保管庫_WAREHOUSE_ID" TEXT NOT NULL,
    "ACTION_ID" TEXT NOT NULL,
    "ACTION_TYPE" INTEGER NULL,
    "STATUS" INTEGER NULL,
    "ACTION_DATE" TEXT NULL,
    "実施担当者_ID" TEXT NOT NULL,
    "ACTION_DETAIL" TEXT NULL,
    "CreatedAt" TEXT NULL,
    "CreateUser" TEXT NULL,
    "UpdatedAt" TEXT NULL,
    "UpdateUser" TEXT NULL,
    CONSTRAINT "PK_ACTIONS" PRIMARY KEY ("Parent_対象機器_Parent_PRODUCT_ID", "Parent_対象機器_保管庫_WAREHOUSE_ID", "ACTION_ID"),
    CONSTRAINT "FK_EMPLOYEE_ACTIONS_X4FD1CEF" FOREIGN KEY ("実施担当者_ID") REFERENCES "EMPLOYEE" ("ID"),
    CONSTRAINT "FK_機器点検報告_ACTIONS" FOREIGN KEY ("Parent_対象機器_Parent_PRODUCT_ID", "Parent_対象機器_保管庫_WAREHOUSE_ID") REFERENCES "機器点検報告" ("対象機器_Parent_PRODUCT_ID", "対象機器_保管庫_WAREHOUSE_ID") ON DELETE CASCADE
);

CREATE TABLE "SIZE" (
    "Parent_Parent_Parent_PRODUCT_ID" TEXT NOT NULL CONSTRAINT "PK_SIZE" PRIMARY KEY,
    "WIDTH" INTEGER NULL,
    "HEIGHT" INTEGER NULL,
    "DEPTH" INTEGER NULL,
    "CreatedAt" TEXT NULL,
    "CreateUser" TEXT NULL,
    "UpdatedAt" TEXT NULL,
    "UpdateUser" TEXT NULL,
    CONSTRAINT "FK_PRODUCT_SPEC_SIZE" FOREIGN KEY ("Parent_Parent_Parent_PRODUCT_ID") REFERENCES "PRODUCT_SPEC" ("Parent_Parent_PRODUCT_ID") ON DELETE CASCADE
);

CREATE TABLE "措置結果" (
    "対象措置_Parent_対象機器_Parent_PRODUCT_ID" TEXT NOT NULL,
    "対象措置_Parent_対象機器_保管庫_WAREHOUSE_ID" TEXT NOT NULL,
    "対象措置_ACTION_ID" TEXT NOT NULL,
    "RESULT_DATETIME" TEXT NOT NULL,
    "結果担当者_ID" TEXT NOT NULL,
    "ACHIEVEMENT" INTEGER NULL,
    "RESULT_STATUS" INTEGER NOT NULL,
    "FEEDBACK" TEXT NULL,
    "CreatedAt" TEXT NULL,
    "CreateUser" TEXT NULL,
    "UpdatedAt" TEXT NULL,
    "UpdateUser" TEXT NULL,
    "Version" INTEGER NOT NULL,
    CONSTRAINT "PK_措置結果" PRIMARY KEY ("対象措置_Parent_対象機器_Parent_PRODUCT_ID", "対象措置_Parent_対象機器_保管庫_WAREHOUSE_ID", "対象措置_ACTION_ID"),
    CONSTRAINT "FK_ACTIONS_措置結果_XFDF1611" FOREIGN KEY ("対象措置_Parent_対象機器_Parent_PRODUCT_ID", "対象措置_Parent_対象機器_保管庫_WAREHOUSE_ID", "対象措置_ACTION_ID") REFERENCES "ACTIONS" ("Parent_対象機器_Parent_PRODUCT_ID", "Parent_対象機器_保管庫_WAREHOUSE_ID", "ACTION_ID"),
    CONSTRAINT "FK_EMPLOYEE_措置結果_XD70B07D" FOREIGN KEY ("結果担当者_ID") REFERENCES "EMPLOYEE" ("ID")
);

CREATE TABLE "ATTACHMENTS" (
    "Parent_対象措置_Parent_対象機器_Parent_PRODUCT_ID" TEXT NOT NULL,
    "Parent_対象措置_Parent_対象機器_保管庫_WAREHOUSE_ID" TEXT NOT NULL,
    "Parent_対象措置_ACTION_ID" TEXT NOT NULL,
    "DOCUMENT_ID" TEXT NOT NULL,
    "DOCUMENT_NAME" TEXT NOT NULL,
    "DOCUMENT_TYPE" INTEGER NULL,
    "FILE_PATH" TEXT NULL,
    "REGISTER_DATETIME" TEXT NULL,
    "CreatedAt" TEXT NULL,
    "CreateUser" TEXT NULL,
    "UpdatedAt" TEXT NULL,
    "UpdateUser" TEXT NULL,
    CONSTRAINT "PK_ATTACHMENTS" PRIMARY KEY ("Parent_対象措置_Parent_対象機器_Parent_PRODUCT_ID", "Parent_対象措置_Parent_対象機器_保管庫_WAREHOUSE_ID", "Parent_対象措置_ACTION_ID", "DOCUMENT_ID"),
    CONSTRAINT "FK_措置結果_ATTACHMENTS" FOREIGN KEY ("Parent_対象措置_Parent_対象機器_Parent_PRODUCT_ID", "Parent_対象措置_Parent_対象機器_保管庫_WAREHOUSE_ID", "Parent_対象措置_ACTION_ID") REFERENCES "措置結果" ("対象措置_Parent_対象機器_Parent_PRODUCT_ID", "対象措置_Parent_対象機器_保管庫_WAREHOUSE_ID", "対象措置_ACTION_ID") ON DELETE CASCADE
);

CREATE TABLE "NEXT_ACTION" (
    "Parent_対象措置_Parent_対象機器_Parent_PRODUCT_ID" TEXT NOT NULL,
    "Parent_対象措置_Parent_対象機器_保管庫_WAREHOUSE_ID" TEXT NOT NULL,
    "Parent_対象措置_ACTION_ID" TEXT NOT NULL,
    "NEXT_ACTION_TYPE" INTEGER NULL,
    "PLANNED_DATE" TEXT NULL,
    "担当者_ID" TEXT NOT NULL,
    "NEXT_CONTENT" TEXT NULL,
    "CreatedAt" TEXT NULL,
    "CreateUser" TEXT NULL,
    "UpdatedAt" TEXT NULL,
    "UpdateUser" TEXT NULL,
    CONSTRAINT "PK_NEXT_ACTION" PRIMARY KEY ("Parent_対象措置_Parent_対象機器_Parent_PRODUCT_ID", "Parent_対象措置_Parent_対象機器_保管庫_WAREHOUSE_ID", "Parent_対象措置_ACTION_ID"),
    CONSTRAINT "FK_EMPLOYEE_NEXT_ACTION_XB332A41" FOREIGN KEY ("担当者_ID") REFERENCES "EMPLOYEE" ("ID"),
    CONSTRAINT "FK_措置結果_NEXT_ACTION" FOREIGN KEY ("Parent_対象措置_Parent_対象機器_Parent_PRODUCT_ID", "Parent_対象措置_Parent_対象機器_保管庫_WAREHOUSE_ID", "Parent_対象措置_ACTION_ID") REFERENCES "措置結果" ("対象措置_Parent_対象機器_Parent_PRODUCT_ID", "対象措置_Parent_対象機器_保管庫_WAREHOUSE_ID", "対象措置_ACTION_ID") ON DELETE CASCADE
);

CREATE INDEX "IX_ACTIONS_実施担当者_ID" ON "ACTIONS" ("実施担当者_ID");

CREATE INDEX "IX_INVENTORY_保管庫_WAREHOUSE_ID" ON "INVENTORY" ("保管庫_WAREHOUSE_ID");

CREATE INDEX "IX_NEXT_ACTION_担当者_ID" ON "NEXT_ACTION" ("担当者_ID");

CREATE INDEX "IX_ORDER_DETAILS_医療機器_PRODUCT_ID" ON "ORDER_DETAILS" ("医療機器_PRODUCT_ID");

CREATE INDEX "IX_SHOZOKU_診療科_BUSHO_CD" ON "SHOZOKU" ("診療科_BUSHO_CD");

CREATE INDEX "IX_STOCK_HISTORY_担当者_ID" ON "STOCK_HISTORY" ("担当者_ID");

CREATE INDEX "IX_医療機器マスタ_機器分類_CATEGORY_ID" ON "医療機器マスタ" ("機器分類_CATEGORY_ID");

CREATE INDEX "IX_医療機器マスタ_供給業者_SUPPLIER_ID" ON "医療機器マスタ" ("供給業者_SUPPLIER_ID");

CREATE INDEX "IX_機器点検報告_点検担当者_ID" ON "機器点検報告" ("点検担当者_ID");

CREATE INDEX "IX_勤務スケジュール_診療科_STORE_ID" ON "勤務スケジュール" ("診療科_STORE_ID");

CREATE INDEX "IX_診療科マスタ_科長_ID" ON "診療科マスタ" ("科長_ID");

CREATE INDEX "IX_診療履歴_患者_CUSTOMER_ID" ON "診療履歴" ("患者_CUSTOMER_ID");

CREATE INDEX "IX_診療履歴_診療科_STORE_ID" ON "診療履歴" ("診療科_STORE_ID");

CREATE INDEX "IX_診療履歴_担当医_ID" ON "診療履歴" ("担当医_ID");

CREATE INDEX "IX_措置結果_結果担当者_ID" ON "措置結果" ("結果担当者_ID");

CREATE INDEX "IX_保管庫マスタ_管理責任者_ID" ON "保管庫マスタ" ("管理責任者_ID");

CREATE INDEX "IX_予約_患者_CUSTOMER_ID" ON "予約" ("患者_CUSTOMER_ID");

CREATE INDEX "IX_予約_担当医_ID" ON "予約" ("担当医_ID");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251004003325_00001_Init2', '9.0.3');

COMMIT;

