-- 機器分類別在庫集計ビュー
CREATE VIEW V_INVENTORY_BY_CATEGORY AS
SELECT
    MC.CATEGORY_ID AS CATEGORY_CATEGORY_ID,
    MC.CATEGORY_NAME AS CATEGORY_CATEGORY_NAME,
    SUM(COALESCE(I.STOCK_QUANTITY, 0)) AS TOTAL_STOCK,
    COUNT(DISTINCT PM.PRODUCT_ID) AS PRODUCT_COUNT,
    MAX(PM.UpdatedAt) AS LAST_UPDATED
FROM
    "機器分類マスタ" AS MC
    LEFT JOIN "医療機器マスタ" AS PM ON MC.CATEGORY_ID = PM."機器分類_CATEGORY_ID"
    LEFT JOIN INVENTORY AS I ON PM.PRODUCT_ID = I.Parent_PRODUCT_ID
GROUP BY
    MC.CATEGORY_ID,
    MC.CATEGORY_NAME;
