-- 診療科別患者統計ビュー
CREATE VIEW V_PATIENT_STATS_BY_DEPT AS
SELECT
    D.BUSHO_CD AS DEPT_CODE,
    D.BUSHO_NAME AS DEPT_NAME,
    COUNT(DISTINCT OH.患者_CUSTOMER_ID) AS TOTAL_PATIENTS,
    COUNT(DISTINCT CASE 
        WHEN DATE(OH.ORDER_DATE, 'start of month') = DATE('now', 'start of month') 
        THEN OH.患者_CUSTOMER_ID 
    END) AS NEW_PATIENTS_THIS_MONTH,
    AVG(CAST((JULIANDAY('now') - JULIANDAY(PM.BIRTH_DATE)) / 365.25 AS DECIMAL)) AS AVG_AGE,
    DATETIME('now') AS STATS_DATETIME
FROM
    BUSHO AS D
    LEFT JOIN SHOZOKU AS SZ ON D.BUSHO_CD = SZ."診療科_BUSHO_CD"
    LEFT JOIN EMPLOYEE AS E ON SZ.Parent_ID = E.ID
    LEFT JOIN "診療履歴" AS OH ON E.ID = OH."担当医_ID"
    LEFT JOIN "患者マスタ" AS PM ON OH."患者_CUSTOMER_ID" = PM.CUSTOMER_ID
GROUP BY
    D.BUSHO_CD,
    D.BUSHO_NAME;
