-- 保管庫別在庫 (機器分類別在庫集計ビューの子集約)
CREATE VIEW WAREHOUSE_INVENTORY AS
SELECT
    MC.CATEGORY_ID AS CATEGORY_CATEGORY_ID,
    WM.WAREHOUSE_ID AS WAREHOUSE_WAREHOUSE_ID,
    WM.WAREHOUSE_NAME AS WAREHOUSE_WAREHOUSE_NAME,
    WA.POSTAL_CODE AS "WAREHOUSE_住所_POSTAL_CODE",
    WA.PREFECTURE AS "WAREHOUSE_住所_PREFECTURE",
    WA.CITY AS "WAREHOUSE_住所_CITY",
    WA.ADDRESS_LINE AS "WAREHOUSE_住所_ADDRESS_LINE",
    E.ID AS WAREHOUSE_MANAGER_ID_ID,
    E.NAME AS WAREHOUSE_MANAGER_ID_NAME,
    E.NAME_KANA AS WAREHOUSE_MANAGER_ID_NAME_KANA,
    E.TAISHOKU AS WAREHOUSE_MANAGER_ID_TAISHOKU,
    SUM(COALESCE(I.STOCK_QUANTITY, 0)) AS STOCK_QUANTITY,
    COUNT(DISTINCT PM.PRODUCT_ID) AS EQUIPMENT_COUNT
FROM
    "機器分類マスタ" AS MC
    CROSS JOIN "保管庫マスタ" AS WM
    LEFT JOIN WAREHOUSE_ADDRESS AS WA ON WM.WAREHOUSE_ID = WA.Parent_WAREHOUSE_ID
    LEFT JOIN EMPLOYEE AS E ON WM."管理責任者_ID" = E.ID
    LEFT JOIN "医療機器マスタ" AS PM ON MC.CATEGORY_ID = PM."機器分類_CATEGORY_ID"
    LEFT JOIN INVENTORY AS I ON PM.PRODUCT_ID = I.Parent_PRODUCT_ID AND WM.WAREHOUSE_ID = I."保管庫_WAREHOUSE_ID"
GROUP BY
    MC.CATEGORY_ID,
    WM.WAREHOUSE_ID,
    WM.WAREHOUSE_NAME,
    WA.POSTAL_CODE,
    WA.PREFECTURE,
    WA.CITY,
    WA.ADDRESS_LINE,
    E.ID,
    E.NAME,
    E.NAME_KANA,
    E.TAISHOKU;
