import * as RHF from "react-hook-form"
import type { AggregateMetadata } from "../__autoGenerated"
import type { PresentationContextDetail } from "../app/DetailMessageContext"
import type { BoundInputs } from "./input/bindInputs"
import type { FieldLabelProps } from "./FieldLabel"
import type { RootErrorsProps } from "./RootErrors"
import type { BoundUseEditableGrid } from "./useEditableGrid"

/**
 * useDisplayDataForm に渡す、自動生成されたモジュールのうちこのフックが使う部分。
 * 自動生成された集約のモジュールを `import * as` したものをそのまま渡せる。
 * メタデータの表は具体的な型のまま受け取る。外部参照の入力欄で、項目のパスから検索ダイアログを決めるのに使うため。
 */
export type DisplayDataModule<
  TDisplayData extends DisplayDataBase,
  TTable extends AggregateMetadata.Table = AggregateMetadata.Table,
> = {
  /** 集約のメタデータ */
  metadata: { displayData: TTable }
  /** 画面表示用データの新しいインスタンスを作成する関数 */
  createNewDisplayData: () => TDisplayData
}

/** 画面表示用データが必ず持つプロパティ */
export type DisplayDataBase = RHF.FieldValues & {
  instanceId: string
}

export type UseDisplayDataFormOptions<TDisplayData extends DisplayDataBase> = {
  /**
   * フォームの初期値。
   * 既存のデータを編集する場合は、読み込み処理を、Promise を返す関数で渡す。
   * 未指定の場合は createNewDisplayData の戻り値。
   *
   * 読み込み中の表示と、読み込みに失敗したときの処理はこのフックでは行わない。利用側の責務とする。
   * 読み込み中かどうかは formMethods.formState.isLoading で判定できる。
   * 読み込みの失敗は、渡す関数の中で処理すること。
   */
  defaultValues?: TDisplayData | (() => Promise<TDisplayData>)
}

export type UseDisplayDataFormReturn<
  TDisplayData extends DisplayDataBase,
  TTable extends AggregateMetadata.Table = AggregateMetadata.Table,
> = {
  /** react-hook-form の useForm の戻り値 */
  formMethods: RHF.UseFormReturn<TDisplayData>
  /** このフォームと結びついた入力コンポーネント */
  Input: BoundInputs<TDisplayData, TTable>
  /** このフォームの項目のラベル。クライアント側エラーとサーバー側メッセージの両方を表示する */
  FieldLabel: (props: FieldLabelProps<TDisplayData>) => React.ReactNode
  /** このフォームの、どの項目とも紐づかないメッセージ。クライアント側エラーとサーバー側メッセージの両方を表示する */
  RootErrors: (props: RootErrorsProps) => React.ReactNode
  /** EditableGrid を使うときはこれで列定義等を行う */
  useEditableGrid: BoundUseEditableGrid<TDisplayData, TTable>
  /**
   * サーバーから返されたメッセージを画面に表示する。それまでに表示していたサーバーのメッセージは置き換えられる。
   * 保存や更新を実行した後のサーバーから返されたエラーをこれに渡すこと。
   * サーバーに送信したときのフォームの値の instanceId を手掛かりに各項目と紐づける。
   * サーバー側メッセージは、次に setServerMessages か clearServerMessages を呼ぶまで表示され続ける。項目を編集しても消えない。
   * react-hook-form のクライアント側エラーには影響しない。
   */
  setServerMessages: (detail: PresentationContextDetail | null | undefined) => void
  /** サーバーから返されたメッセージをすべて消す。react-hook-form のクライアント側エラーには影響しない */
  clearServerMessages: () => void
}

/**
 * 画面表示用データを編集するフォームを作るフック。
 * 入力コンポーネント・ラベル・メッセージ表示・グリッドを、自動生成されたメタデータと結びつけた状態で返す。
 * 画面側は項目のパスを指定するだけで、表示名や入力制約を個別に指定せずに画面を組み立てられる。
 *
 * このフックはフォームの状態とメッセージの管理だけを行う。データの読み込み・保存の呼び出しは行わない。
 * 読み取り専用はフォーム全体では指定できない。入力コンポーネントやグリッドごとに指定する。
 *
 * ## メッセージ
 * 画面に表示するメッセージには出どころが2種類あり、表示の仕組みは共通だが、出し方と消え方が異なる。
 *
 * - クライアント側エラー: react-hook-form の検証エラー。入力コンポーネントがメタデータから組み立てる検証ルール、
 *   入力コンポーネントの rules で追加した検証ルール、画面側が formMethods.setError で設定したものが該当する。
 *   消えるタイミングは react-hook-form の検証の仕組みに従う。
 * - サーバー側メッセージ: setServerMessages で渡したもの。エラー・警告・情報がある。clearServerMessages を呼ぶか、次の setServerMessages で置き換わるまで消えない。
 *
 * どちらも、項目ごとの表示は FieldLabel とグリッドのセル、どこにも表示されないものは RootErrors が受け持つ。
 *
 * ## 外部参照の照合と送信
 * 外部参照の入力欄は、手入力されたコードの照合を非同期の検証ルールとして登録する。
 * formMethods.handleSubmit は照合の完了を待ってから送信処理を呼ぶので、利用側は照合中かどうかを意識しなくてよい。
 */
export function useDisplayDataForm<
  TDisplayData extends DisplayDataBase,
  TTable extends AggregateMetadata.Table,
>(
  autoGenerated: DisplayDataModule<TDisplayData, TTable>,
  options?: UseDisplayDataFormOptions<TDisplayData>,
): UseDisplayDataFormReturn<TDisplayData, TTable> {
  // 実装時の注意: ui フォルダと、ui フォルダに依存するモジュールには依存せず、ui2 単独で実装すること。
  // ui フォルダは ui2 の動作が安定したら削除するので、依存していると削除時に巻き込まれるため。
  throw new Error('not implemented')
}
