import * as RHF from "react-hook-form"
import type { AggregateMetadata } from "../__autoGenerated"
import type { PresentationContextDetail } from "../app/DetailMessageContext"
import type { BoundInputs } from "./input/bindInputs"
import type { FieldLabelProps } from "./FieldLabel"
import type { RootErrorsProps } from "./RootErrors"

/**
 * useSearchConditionForm に渡す、自動生成されたモジュールのうちこのフックが使う部分。
 * 自動生成されたクエリモデルのモジュールを `import * as` したものをそのまま渡せる。
 * メタデータの表は具体的な型のまま受け取る。外部参照の入力欄で、項目のパスから検索ダイアログを決めるのに使うため。
 */
export type SearchConditionModule<
  TSearchCondition extends SearchConditionBase,
  TTable extends AggregateMetadata.Table = AggregateMetadata.Table,
> = {
  /** 集約のメタデータ */
  metadata: { searchCondition: TTable }
  /** 検索条件の新しいインスタンスを作成する関数 */
  createNewSearchCondition: () => TSearchCondition
}

/** 検索条件が必ず持つプロパティ */
export type SearchConditionBase = RHF.FieldValues & {
  filter: RHF.FieldValues
}

/** 検索条件の絞り込み条件の型 */
export type FilterOf<TSearchCondition extends SearchConditionBase> = TSearchCondition['filter']

export type UseSearchConditionFormOptions<TSearchCondition extends SearchConditionBase> = {
  /**
   * フォームの初期値。URL のクエリパラメータから復元した検索条件などを渡す。
   * 未指定の場合は createNewSearchCondition の戻り値。
   */
  defaultValues?: TSearchCondition
}

export type UseSearchConditionFormReturn<
  TSearchCondition extends SearchConditionBase,
  TTable extends AggregateMetadata.Table = AggregateMetadata.Table,
> = {
  /**
   * react-hook-form の useForm の戻り値。
   * 並び順やページングなど、絞り込み条件以外の値もこのフォームで管理する。
   */
  formMethods: RHF.UseFormReturn<TSearchCondition>
  /**
   * このフォームと結びついた入力コンポーネント。
   * name は絞り込み条件のオブジェクトから見たパス。
   * 数値・日付は範囲指定、真偽値と列挙体は複数選択になるなど、検索条件用の外観になる。
   */
  Input: BoundInputs<FilterOf<TSearchCondition>, TTable>
  /**
   * このフォームの項目のラベル。name は絞り込み条件のオブジェクトから見たパス。
   * クライアント側エラーとサーバー側メッセージの両方を表示する。
   */
  FieldLabel: (props: FieldLabelProps<FilterOf<TSearchCondition>>) => React.ReactNode
  /** このフォームの、どの項目とも紐づかないメッセージ。クライアント側エラーとサーバー側メッセージの両方を表示する */
  RootErrors: (props: RootErrorsProps) => React.ReactNode
  /**
   * 検索処理がサーバーから返したメッセージを画面に表示する。それまでに表示していたサーバーのメッセージは置き換えられる。
   * 次に setServerMessages か clearServerMessages を呼ぶまで表示され続ける。項目を編集しても消えない。
   * react-hook-form のクライアント側エラーには影響しない。
   */
  setServerMessages: (detail: PresentationContextDetail | null | undefined) => void
  /** サーバーから返されたメッセージをすべて消す。react-hook-form のクライアント側エラーには影響しない */
  clearServerMessages: () => void
}

/**
 * 検索条件を入力するフォームを作るフック。
 * 入力コンポーネント・ラベル・メッセージ表示を、自動生成されたメタデータと結びつけた状態で返す。
 * 画面側は項目のパスを指定するだけで、表示名や入力制約を個別に指定せずに画面を組み立てられる。
 *
 * このフックはフォームの状態とメッセージの管理だけを行う。検索処理の呼び出しは行わない。
 * 読み取り専用はフォーム全体では指定できない。入力コンポーネントごとに指定する。
 *
 * ## メッセージ
 * 出どころの区別と消え方は useDisplayDataForm と同じ。
 *
 * - クライアント側エラー: react-hook-form の検証エラー。範囲指定の下限が上限より大きい場合など。
 * - サーバー側メッセージ: setServerMessages で渡したもの。検索処理が返したエラーなど。
 */
export function useSearchConditionForm<
  TSearchCondition extends SearchConditionBase,
  TTable extends AggregateMetadata.Table,
>(
  autoGenerated: SearchConditionModule<TSearchCondition, TTable>,
  options?: UseSearchConditionFormOptions<TSearchCondition>,
): UseSearchConditionFormReturn<TSearchCondition, TTable> {
  // 実装時の注意: ui フォルダと、ui フォルダに依存するモジュールには依存せず、ui2 単独で実装すること。
  // ui フォルダは ui2 の動作が安定したら削除するので、依存していると削除時に巻き込まれるため。
  throw new Error('not implemented')
}
