import React from "react"
import * as ReactHookForm from "react-hook-form"
import { LoadReturnType } from "../../__autoGenerated/util"
import { DataTableColumn } from "../../layout/DataTable"
import { DataTableColumnDefinitionHelper } from "../Field"
import { ComplexPostResult } from "../../example/callComplexPostEndpointAsync"

/**
 * 検索ダイアログ自体ではなくダイアログ定義関数の引数の型
 */
export type DefineSearchDialogProps<
  TSearchCondition extends ReactHookForm.FieldValues,
  TSearchResultRefTarget,
  TSearchResultFilter,
  TDialogProps,
> = {
  /** ダイアログのタイトル */
  title: string
  /** 編集画面用のオブジェクトからコード値までのパス */
  codePathFromRefTarget: ReactHookForm.Path<TSearchResultRefTarget>
  /** 検索条件欄用のオブジェクトから名称までのパス */
  namePathFromRefTarget: ReactHookForm.Path<TSearchResultRefTarget>
  /** 検索条件欄用のオブジェクトからコード値までのパス */
  codePathFromSearchCondition: ReactHookForm.Path<TSearchResultFilter>
  /** 検索条件欄用のオブジェクトから名称までのパス */
  namePathFromSearchCondition: ReactHookForm.Path<TSearchResultFilter>
  /** コード値のテキストボックスの横幅（CSSの「rem」単位） */
  codeWidthRem: number

  /**
   * ダイアログ表示時の初期検索条件を取得します。
   * なお、 skip, take は既定値が設定されるため、ここで設定する必要はありません。
   */
  getDefaultSearchCondition: (dialogProps: TDialogProps) => TSearchCondition
  /**
   * 検索条件欄のレンダリング。
   * form タグの内側にレンダリングされます。
   */
  renderSearchCondition: (props: SearchDialogConditionProops<TSearchCondition, TDialogProps>) => React.ReactNode
  /**
   * 検索結果欄のグリッドの列定義を取得します。
   * なお、グリッド左端の選択ボタンは自動で追加されるため、ここで定義する必要はありません。
   */
  getSearchResultGridColumns: (
    columnFor: DataTableColumnDefinitionHelper<TSearchResultRefTarget>,
    dialogProps: TDialogProps,
  ) => DataTableColumn<TSearchResultRefTarget>[]
  /**
   * 検索処理関数
   */
  onSearch: (
    formValues: TSearchCondition,
    signal: AbortSignal | undefined,
  ) => Promise<ComplexPostResult<LoadReturnType<TSearchResultRefTarget>>>
  /**
   * コード値から検索条件を作成します。
   * 詳細画面でフォーカスアウトした際の自動検索に使用します。
   */
  convertCodeToSearchCondition: (code: string) => TSearchCondition
  /**
   * ダイアログ内部の検索結果はRefTarget型だが、
   * 検索画面の検索条件欄で使用する場合はその画面のSearchConditionのFilter型になるため、
   * 前者から後者への変換関数。
   */
  convertRefTargetToFilter: (refTarget: TSearchResultRefTarget) => TSearchResultFilter
}

export type SearchDialogConditionProops<
  TSearchCondition extends ReactHookForm.FieldValues,
  TDialogProps,
> = {
  formMethods: ReactHookForm.UseFormReturn<TSearchCondition>
  /** ダイアログ呼び出し元で指定されたオプション */
  dialogProps: TDialogProps
}

/**
 * 検索ダイアログコンポーネントの props の型
 */
export type SearchDialogComponentProps<
  TFormRoot extends ReactHookForm.FieldValues,
  TSearchResultItem,
  TPath extends ReactHookForm.FieldPathByValue<TFormRoot, TSearchResultItem>,
  TDialogProps,
> = TDialogProps & {
  name: TPath
  control: ReactHookForm.Control<TFormRoot>
  readOnly?: boolean
  className?: string
}

/**
 * 検索ダイアログコンポーネントを定義します。
 * 参照先のデータが、１個のコードと１個の名称を持っているという前提で実装されています。
 *
 * ## このベースの責務
 *
 * - 呼び出し元コンポーネントの定義
 *   - コード値
 *     - readOnly 時のコード値入力不可対応
 *     - 詳細画面ではフォーカスアウト時に検索処理を自動的に実行する
 *     - 検索条件欄では手入力された値をそのまま検索条件として使用する
 *   - 名称値
 *     - 詳細画面では手入力不可。検索条件欄では手入力可能
 *     - もし検索条件欄でコードと名称で不一致がある場合、検索結果としては何もヒットしないので注意
 * - ダイアログの表示/非表示管理
 * - 検索結果欄のレンダリング、選択ボタン、ページング
 * - 検索ボタン、クリアボタン、ダイアログを閉じるUI
 * - 検索条件欄の useForm 状態管理
 *
 * ## カスタマイズポイント
 *
 * - 呼び出し元コンポーネント
 *   - このベースが呼び出し元画面から name, control, readOnly, className を受け取って
 *     呼び出し元のコンポーネントをレンダリングするために必要な情報
 * - 検索ダイアログ
 *   - 検索条件欄のレンダリング
 *   - 検索条件の初期値の定義
 *   - 検索処理の実装
 *   - 検索結欄のグリッドの列定義
 */
export function defineSearchDialog<
  TSearchCondition extends ReactHookForm.FieldValues,
  TSearchResultRefTarget,
  TSearchResultFilter,
  TDialogProps,
>(def: DefineSearchDialogProps<TSearchCondition, TSearchResultRefTarget, TSearchResultFilter, TDialogProps>) {

  // 詳細画面用のダイアログ
  function SearchDialogComponentForEditPage<
    TFormRoot extends ReactHookForm.FieldValues,
    TPath extends ReactHookForm.FieldPathByValue<TFormRoot, TSearchResultRefTarget>,
  >(props: SearchDialogComponentProps<TFormRoot, TSearchResultRefTarget, TPath, TDialogProps>): React.ReactNode {
    return (
      <div>未実装</div>
    )
  }

  // 検索条件欄用のダイアログ
  function SearchDialogComponentForSearchCondition<
    TFormRoot extends ReactHookForm.FieldValues,
    TPath extends ReactHookForm.FieldPathByValue<TFormRoot, TSearchResultFilter>,
  >(props: SearchDialogComponentProps<TFormRoot, TSearchResultFilter, TPath, TDialogProps>): React.ReactNode {
    return (
      <div>未実装</div>
    )
  }

  return [
    SearchDialogComponentForEditPage,
    SearchDialogComponentForSearchCondition,
  ] as const
}
