chcp 65001 
setlocal enabledelayedexpansion 
@echo off 
 
set "SOURCE_ROOT=%~dp0..\Nijo.NewProjectTemplate" 
set "NIJO_EXE_PATH=%~dp0\..\Nijo\bin\Debug\net9.0\nijo.exe" 
 
@rem nijo.exe リビルド 
dotnet build "%~dp0\..\Nijo" -c Debug 
 
if %errorlevel% neq 0 ( 
    echo エラーが発生しました 
    pause 
    exit /b 1 
) 
 
@rem テンプレートプロジェクトのソースコード自動生成かけなおし 
%NIJO_EXE_PATH% generate "%SOURCE_ROOT%"  
 
@rem デモフォルダをループし全デモフォルダに対して処理を行う 
for /d %%d in ("%~dp0\..\demo\*") do ( 
 
    set "TARGET_ROOT=%%d" 
 
    @rem ソースコード自動生成かけなおし 
    %NIJO_EXE_PATH% generate !TARGET_ROOT! 
 
    @rem 新規プロジェクトテンプレートのソースをコピー 
    if !errorlevel!==0 ( 
        call :COPY_REACT 
        call :COPY_CORE 
        call :COPY_CORE_AUTOGENERATED 
        call :COPY_WEBAPI 
        call :COPY_UNIT_TEST 
        call :COPY_TASK 
    ) 
) 
@echo コピー完了しました 
exit /b 0 
 
@rem **************************************** 
@rem コピー実行 
@rem コピー元のファイルでコピー先のフォルダ構造ごと完全に洗い替える 
@rem コピー先に同じ名前のファイルがある場合は上書きする 
@rem コピー先に同じ名前のファイルが無い場合はコピー先の当該ファイルを削除する 
 
:COPY_REACT 
@rem React 
@rem copy "%SOURCE_ROOT%\client\src\callAspNetCoreApiAsync.ts" "%TARGET_ROOT%\client\src\callAspNetCoreApiAsync.ts" 
copy "%SOURCE_ROOT%\client\src\callComplexPostEndpointAsync.ts" "%TARGET_ROOT%\client\src\callComplexPostEndpointAsync.ts" 
exit /b 
 
:COPY_CORE 
@rem Core 
robocopy "%SOURCE_ROOT%\Core\Debugging" "%TARGET_ROOT%\Core\Debugging" /MIR /XA:SH 
copy "%SOURCE_ROOT%\Core\OverridedApplicationConfigure.cs" "%TARGET_ROOT%\Core\OverridedApplicationConfigure.cs" 
copy "%SOURCE_ROOT%\Core\OverridedApplicationService.cs" "%TARGET_ROOT%\Core\OverridedApplicationService.cs" 
copy "%SOURCE_ROOT%\Core\MigrationEntryPoint.cs" "%TARGET_ROOT%\Core\MigrationEntryPoint.cs" 
exit /b 
 
:COPY_CORE_AUTOGENERATED 
@rem Core.AutoGenerated 特になし 
exit /b 
 
:COPY_WEBAPI 
@rem WebApi 
robocopy "%SOURCE_ROOT%\WebApi\Base" "%TARGET_ROOT%\WebApi\Base" /MIR /XA:SH 
@rem copy "%SOURCE_ROOT%\WebApi\Program.cs" "%TARGET_ROOT%\WebApi\Program.cs" 
copy "%SOURCE_ROOT%\WebApi\Properties\launchSettings.json" "%TARGET_ROOT%\WebApi\Properties\launchSettings.json" 
copy "%SOURCE_ROOT%\WebApi\Properties\PublishProfiles\本番用ビルド.xml" "%TARGET_ROOT%\WebApi\Properties\PublishProfiles\本番用ビルド.xml" 
exit /b 
 
:COPY_UNIT_TEST 
@rem UnitTest 
copy "%SOURCE_ROOT%\UnitTest\PresentationContextInUnitTest.cs" "%TARGET_ROOT%\UnitTest\PresentationContextInUnitTest.cs" 
copy "%SOURCE_ROOT%\UnitTest\TestUtilImpl.cs" "%TARGET_ROOT%\UnitTest\TestUtilImpl.cs" 
robocopy "%SOURCE_ROOT%\UnitTest\Tests" "%TARGET_ROOT%\UnitTest\Tests" /E /XA:SH
exit /b 
 
:COPY_TASK 
@rem Task 
set "SOURCE_DIR=%SOURCE_ROOT%\Task" 
set "TARGET_DIR=%TARGET_ROOT%\Task" 
set "EXCLUDE_DIRS=" 
set "EXCLUDE_FILES=" 
robocopy "%SOURCE_DIR%" "%TARGET_DIR%" /MIR /XA:SH /XD %EXCLUDE_DIRS% /XF %EXCLUDE_FILES% 
exit /b 
