import { defineSearchDialog, FieldColumn, FieldGroup, type SearchResult, ReadOnlyColumn } from "../../../ui"
import * as サンプル従業員 from "./サンプル従業員"

/** 従業員検索ダイアログを開くときのパラメータ */
type OpenParams = {
  /** 退職済みの従業員も最初から検索結果に含めるかどうか */
  退職者を含む: boolean
}

/**
 * サンプル従業員の検索ダイアログ。
 * 検索ダイアログごとに異なる部分（検索条件欄・検索結果欄・初期条件・検索処理）だけをここに書く。
 */
export const 従業員検索ダイアログ = defineSearchDialog<サンプル従業員.SearchCondition, サンプル従業員.RefTarget, OpenParams>({
  title: '従業員',
  autoGenerated: サンプル従業員,

  // 初期の検索条件。パラメータによって退職者を除外する
  getDefaultSearchCondition: params => {
    const condition = サンプル従業員.createNewSearchCondition()
    condition.filter.退職済み = { falseのみ: !params.退職者を含む }
    condition.sort = ['サンプル従業員.従業員番号（昇順）']
    return condition
  },

  // 検索条件欄
  SearchCondition: ({ Input, FieldLabel }) => (
    <FieldGroup>
      <FieldColumn>
        <FieldLabel name="従業員番号">
          <Input.TextBox name="従業員番号" className="w-28" />
        </FieldLabel>
        <FieldLabel name="氏名">
          <Input.TextBox name="氏名" />
        </FieldLabel>
      </FieldColumn>
      <FieldColumn>
        <FieldLabel name="退職済み">
          <Input.CheckBox name="退職済み" />
        </FieldLabel>
      </FieldColumn>
    </FieldGroup>
  ),

  // 検索結果欄
  getResultColumns: () => [
    ReadOnlyColumn.text<サンプル従業員.RefTarget>('従業員番号', row => row.従業員番号, { columnId: '従業員番号', defaultWidth: 120 }),
    ReadOnlyColumn.text<サンプル従業員.RefTarget>('氏名', row => row.氏名, { columnId: '氏名', defaultWidth: 200 }),
  ],

  // 検索処理。実際のアプリケーションではここでサーバー側の検索処理を呼ぶ
  search: searchOnMockServer,
  getItemKey: item => item.従業員番号 ?? '',

  // 外部参照の入力欄から使うときの情報
  refField: {
    codePath: '従業員番号',
    namePath: '氏名',
    createConditionFromCode: code => {
      const condition = サンプル従業員.createNewSearchCondition()
      condition.filter.従業員番号 = code
      return condition
    },
    toFilter: item => ({
      従業員番号: item.従業員番号,
      氏名: item.氏名,
    }),
  },
})

//#region サーバー側の検索処理の模擬

/** サーバー側の検索処理を模擬する。少し待ってから、絞り込みとページングをした結果を返す */
async function searchOnMockServer(
  condition: サンプル従業員.SearchCondition,
  signal: AbortSignal,
): Promise<SearchResult<サンプル従業員.RefTarget>> {
  await new Promise(resolve => setTimeout(resolve, 300))
  if (signal.aborted) return { type: 'canceled' }

  const { 従業員番号, 氏名, 退職済み } = condition.filter
  const hits = MOCK_EMPLOYEES.filter(employee => {
    if (従業員番号 && employee.従業員番号 !== 従業員番号) return false
    if (氏名 && !employee.氏名.includes(氏名)) return false
    if (退職済み?.trueのみ && !退職済み?.falseのみ && !employee.退職済み) return false
    if (退職済み?.falseのみ && !退職済み?.trueのみ && employee.退職済み) return false
    return true
  })

  const skip = Number(condition.skip || 0)
  const take = Number(condition.take || hits.length)
  return {
    type: 'ok',
    returnValue: {
      currentPageItems: hits
        .slice(skip, skip + take)
        .map(({ 従業員番号, 氏名 }) => ({ 従業員番号, 氏名 })),
      totalCount: hits.length,
    },
    detail: {},
  }
}

/** 模擬サーバーのデータ。ページングを確認できるよう、1ページに収まらない件数にしている */
const MOCK_EMPLOYEES = Array.from({ length: 45 }, (_, i) => ({
  従業員番号: `E${(i + 1).toString().padStart(4, '0')}`,
  氏名: `${['山田', '佐藤', '鈴木', '高橋', '田中'][i % 5]} ${['太郎', '花子', '一郎', '次郎', '三郎', '桜', '健'][i % 7]}`,
  退職済み: i % 6 === 5,
}))

//#endregion サーバー側の検索処理の模擬
