import React from "react"
import * as RHF from "react-hook-form"
import * as EG2 from "@halllky/editable-grid"
import type { AggregateMetadata } from "../../__autoGenerated"
import { EnumValueMap } from "../../__autoGenerated/enum-defs"
import { findMemberMetadata, type GridBinding } from "../FormBinding"
import { assertValueMember, inputFrameClassName, toRegisterRules, type ColumnOptionsBase, type InputPropsBase, type WithFormBinding } from "./InputProps"
import { defineCellColumn, findCellMemberMetadata } from "./GridCell"

/*
 * 列挙体の選択欄。
 * フォーム用とグリッド用で以下の仕様を共有する。
 *
 * - 選択肢はメタデータの列挙体の型名から決める。並び順は列挙体の定義順。
 * - 先頭に未選択を表す空の選択肢を置く。
 * - コピー&ペーストの文字列表現は選択肢の値そのもの。選択肢に無い文字列の貼り付けは無視する。
 * - 検索条件のフォームでは、選択肢ごとのチェックボックスを並べた複数選択になる。
 *   選ばれた値のいずれかに一致するものに絞り込み、何も選ばなければ絞り込まない。
 */

//#region フォーム用

export type EnumSelectionProps<TValues extends RHF.FieldValues> = InputPropsBase<TValues>

/** 列挙体の選択欄（フォーム用）。ドロップダウンで1つ選ぶ */
export function EnumSelection<TValues extends RHF.FieldValues>(props: WithFormBinding<EnumSelectionProps<TValues>, TValues>): React.ReactNode {
  const { binding, name, isReadOnly, rules, className } = props
  const formPath = binding.toFormPath(name)
  const options = enumOptionsOf(findMemberMetadata(binding.metadata, name), name)

  // 画面表示用データではドロップダウン
  if (binding.kind === 'display-data') {
    return (
      <EnumDropDown
        formPath={formPath}
        control={binding.formMethods.control}
        rules={toRegisterRules({ rules })}
        options={options}
        isReadOnly={isReadOnly}
        className={className}
      />
    )
  }

  // 検索条件では選択肢ごとのチェックボックス。項目全体に対する検証は1つ目に付ける
  return (
    <div className={`flex flex-wrap items-center gap-x-3 min-h-6 ${className ?? ''}`}>
      {options.map((option, index) => (
        <EnumOptionCheckBox
          key={option}
          formPath={`${formPath}.${option}`}
          control={binding.formMethods.control}
          rules={index === 0
            ? toRegisterRules({ rules, itemValueOf: (_, formValues) => RHF.get(formValues, formPath) })
            : toRegisterRules({ rules: undefined })}
          isReadOnly={isReadOnly}
        >
          {option}
        </EnumOptionCheckBox>
      ))}
    </div>
  )
}

/** ドロップダウン */
function EnumDropDown({ formPath, control, rules, options, isReadOnly, className }: {
  formPath: string
  control: RHF.Control<RHF.FieldValues>
  rules: Pick<RHF.RegisterOptions, 'validate'>
  options: readonly string[]
  isReadOnly: boolean | undefined
  className?: string
}) {
  const { field } = RHF.useController({ name: formPath, control, rules })
  const value = typeof field.value === 'string' ? field.value : ''

  // select 要素には readOnly 属性が効かないので、読み取り専用のときは値だけを表示する
  if (isReadOnly) {
    return (
      <span className={`block px-1 py-px min-h-6 ${inputFrameClassName(true)} ${className ?? ''}`}>
        {value}
      </span>
    )
  }
  return (
    <select
      ref={field.ref}
      name={field.name}
      value={value}
      onChange={e => field.onChange(e.target.value)}
      onBlur={field.onBlur}
      className={`block px-1 py-px ${inputFrameClassName(false)} ${className ?? ''}`}
    >
      {/* 未選択 */}
      <option value=""></option>
      {/* 選択肢 */}
      {options.map(option => (
        <option key={option} value={option}>{option}</option>
      ))}
    </select>
  )
}

/** 検索条件の、選択肢1つ分のチェックボックス */
function EnumOptionCheckBox({ formPath, control, rules, isReadOnly, children }: {
  formPath: string
  control: RHF.Control<RHF.FieldValues>
  rules: Pick<RHF.RegisterOptions, 'validate'>
  isReadOnly: boolean | undefined
  children?: React.ReactNode
}) {
  const { field } = RHF.useController({ name: formPath, control, rules })

  return (
    <label className={`inline-flex items-center gap-1 select-none ${isReadOnly ? '' : 'cursor-pointer'}`}>
      <input
        type="checkbox"
        ref={field.ref}
        name={field.name}
        checked={field.value === true}
        // チェックボックスには readOnly 属性が効かないので、読み取り専用のときは値を変えないようにする
        onChange={e => { if (!isReadOnly) field.onChange(e.target.checked) }}
        onBlur={field.onBlur}
        aria-readonly={isReadOnly}
        className={isReadOnly ? 'pointer-events-none' : 'cursor-pointer'}
      />
      {children}
    </label>
  )
}

//#endregion フォーム用

//#region グリッド用

export type EnumColumnOptions<TRow> = ColumnOptionsBase<TRow>

/** 列挙体の列（グリッド用）。セルの編集開始でドロップダウンを開く */
export function enumColumn<TRow>(
  binding: GridBinding,
  path: RHF.Path<TRow>,
  options?: EnumColumnOptions<TRow>,
): EG2.EditableGridLeafColumn<TRow> {
  const member = findCellMemberMetadata(binding, path)
  const enumOptions = enumOptionsOf(member, path)

  return defineCellColumn(binding, path, options, {
    render: ({ value }) => typeof value === 'string' ? value : '',
    editor: getEnumCellEditor((member as AggregateMetadata.Value).enumType!, enumOptions),
    toText: value => typeof value === 'string' ? value : '',
    fromText: text => {
      const trimmed = text.trim()
      return trimmed === '' || enumOptions.includes(trimmed) ? { value: trimmed } : undefined
    },
    onCellKeyDown: ({ event, requestEditStart }) => {
      // Alt+↑↓ はドロップダウンを開くキー操作。編集中でないエディタのドロップダウンが開くと、選んでも確定できないので、
      // ブラウザの既定の動作を止めて、編集を開始してから開く。読み取り専用のセルでは編集が始まらないので何も開かない
      if (event.altKey && (event.key === 'ArrowUp' || event.key === 'ArrowDown')) {
        event.preventDefault()
        requestEditStart()
      }
    },
  })
}

/**
 * 列挙体のセルエディタを返す。
 * エディタの参照を使い回すため、列挙体の型名ごとにモジュールのトップレベルに保持する。
 */
function getEnumCellEditor(enumType: string, options: readonly string[]): EG2.EditableGridCellEditor {
  const cached = enumCellEditors.get(enumType)
  if (cached) return cached

  const Editor: EG2.EditableGridCellEditor = React.forwardRef(function EnumCellEditor({ style, isEditing, requestCommit, requestCancel }, ref) {
    const selectRef = React.useRef<HTMLSelectElement>(null)
    const [value, setValue] = React.useState('')

    React.useImperativeHandle(ref, () => ({
      getCurrentValue: () => selectRef.current?.value ?? '',
      setValueAndSelectAll: (nextValue, timing) => {
        // キー入力による編集開始では入力された文字が渡されるので、選択肢に無ければ元の値のままにする
        if (timing !== 'edit-start' || nextValue === '' || options.includes(nextValue)) setValue(nextValue)
        // グリッドはアクティブな間エディタがフォーカスを持つ前提で、フォーカスを持たせるのはエディタの役目。
        // 他の列からこの列へ選択が移るとエディタがマウントし直されてフォーカスが外れるので、編集開始時に限らずフォーカスする。
        // 編集中の表示に切り替わってからでないとドロップダウンを開けないため、少し待つ
        setTimeout(() => {
          selectRef.current?.focus()
          if (timing !== 'edit-start') return
          try { selectRef.current?.showPicker() } catch { /* ユーザー操作の直後でない場合は開けないので、選択欄の表示だけにする */ }
        }, 0)
      },
      getDomElement: () => selectRef.current,
    }), [])

    return (
      <div style={style}>
        <select
          ref={selectRef}
          value={value}
          onChange={e => {
            setValue(e.target.value)
            if (isEditing) requestCommit(e.target.value)
          }}
          onKeyDown={e => {
            if (!isEditing) return
            if (e.key === 'Escape') {
              requestCancel()
              e.preventDefault()
            } else if (e.key === 'Tab') {
              // フォーカスが次の要素へ移ってもセルが編集中のまま残らないよう、確定する
              requestCommit(e.currentTarget.value)
            }
          }}
          className="w-full h-full text-sm outline-none border border-black bg-white"
        >
          {/* 未選択 */}
          <option value=""></option>
          {/* 選択肢 */}
          {options.map(option => (
            <option key={option} value={option}>{option}</option>
          ))}
        </select>
      </div>
    )
  })

  enumCellEditors.set(enumType, Editor)
  return Editor
}

const enumCellEditors = new Map<string, EG2.EditableGridCellEditor>()

//#endregion グリッド用

//#region フォームとグリッドで共有する仕様

/** メタデータから選択肢を求める。列挙体でない場合は例外を投げる */
function enumOptionsOf(member: AggregateMetadata.Member, path?: string): readonly string[] {
  const value = assertValueMember(member, path ?? '', 'EnumSelection', m => m.enumType !== undefined)
  return EnumValueMap[value.enumType!]()
}

//#endregion フォームとグリッドで共有する仕様
