import * as RHF from "react-hook-form"
import * as EG2 from "@halllky/editable-grid"
import type { AggregateMetadata } from "../../__autoGenerated"
import type { GridBinding } from "../FormBinding"
import type { ColumnOptionsBase, InputPropsBase, WithFormBinding } from "./InputProps"

/*
 * 列挙体の選択欄。
 * フォーム用とグリッド用で以下の仕様を共有する。
 *
 * - 選択肢はメタデータの列挙体の型名から決める。並び順は列挙体の定義順。
 * - 先頭に未選択を表す空の選択肢を置く。
 * - コピー&ペーストの文字列表現は選択肢の値そのもの。選択肢に無い文字列の貼り付けは無視する。
 * - 検索条件のフォームでは、選択肢ごとのチェックボックスを並べた複数選択になる。
 *   選ばれた値のいずれかに一致するものに絞り込み、何も選ばなければ絞り込まない。
 */

//#region フォーム用

export type EnumSelectionProps<TValues extends RHF.FieldValues> = InputPropsBase<TValues>

/** 列挙体の選択欄（フォーム用）。ドロップダウンで1つ選ぶ */
export function EnumSelection<TValues extends RHF.FieldValues>(props: WithFormBinding<EnumSelectionProps<TValues>, TValues>): React.ReactNode {
  throw new Error('not implemented')
}

//#endregion フォーム用

//#region グリッド用

export type EnumColumnOptions<TRow> = ColumnOptionsBase<TRow>

/** 列挙体の列（グリッド用）。セルの編集開始でドロップダウンを開く */
export function enumColumn<TRow>(
  binding: GridBinding,
  path: RHF.Path<TRow>,
  options?: EnumColumnOptions<TRow>,
): EG2.EditableGridLeafColumn<TRow> {
  throw new Error('not implemented')
}

//#endregion グリッド用

//#region フォームとグリッドで共有する仕様

/** メタデータから選択肢を求める。列挙体でない場合は例外を投げる */
function enumOptionsOf(member: AggregateMetadata.Member): readonly string[] {
  throw new Error('not implemented')
}

//#endregion フォームとグリッドで共有する仕様
