import React from "react"
import * as RHF from "react-hook-form"
import * as EG2 from "@halllky/editable-grid"
import type { AggregateMetadata } from "../../__autoGenerated"
import { findMemberMetadata, type GridBinding } from "../FormBinding"
import { assertValueMember, attachColumnRules, inputFrameClassName, toRegisterRules, useSelectAllOnFocus, type ColumnOptionsBase, type InputPropsBase, type WithFormBinding } from "./InputProps"
import { createTextCellEditor, defineCellColumn, findCellMemberMetadata, type TextInputFilter } from "./GridCell"

/*
 * 数値の入力欄。
 * フォーム用とグリッド用で以下の仕様を共有する。
 *
 * - 右寄せで表示する。
 * - 整数部・小数部の桁数はメタデータから決める。
 *   総合桁数・小数部桁数の指定が無い場合は値の型から決める（整数・シーケンスは小数部なし、年は整数部4桁など）。
 * - 金額項目は接尾辞「円」、数量項目は接尾辞「個」を付け、いずれも3桁カンマ区切りで表示する。どちらでもない項目には付けない。
 * - 数値として解釈できない文字の入力は受け付けない。全角数字・全角記号は半角に読み替える。
 * - 桁数を超える値は切り捨てず、そのまま保持してクライアント側エラーにする。貼り付けの場合も同じ。
 *   整数部の切り捨ては値そのものを変えてしまい、ユーザーが気付かないまま誤った値が保存されるおそれがあるため。
 * - 3桁カンマ区切りは表示上だけのもので、フォームの値にはカンマを含めない。
 * - 検索条件のフォームでは、範囲指定（下限〜上限）の2つの入力欄になる。
 */

//#region フォーム用

export type NumericTextBoxProps<TValues extends RHF.FieldValues> = InputPropsBase<TValues> & {
  /** 未入力のときに表示する文字列。検索条件のフォームでは下限と上限の両方に表示される */
  placeholder?: string
}

/** 数値の入力欄（フォーム用） */
export function NumericTextBox<TValues extends RHF.FieldValues>(props: WithFormBinding<NumericTextBoxProps<TValues>, TValues>): React.ReactNode {
  const { binding, name, isReadOnly, rules, className, placeholder } = props
  const formPath = binding.toFormPath(name)
  const member = assertValueMember(findMemberMetadata(binding.metadata, name), name, 'NumericTextBox', isNumericMember)
  const format = numericFormatOf(member)
  const validateDigits = (value: unknown) => validateNumericDigits(toNumericText(value), format)

  // 画面表示用データでは1つの入力欄
  if (binding.kind === 'display-data') {
    return (
      <NumericInput
        id={binding.toElementId(formPath)}
        formPath={formPath}
        control={binding.formMethods.control}
        rules={toRegisterRules({ rules, validators: [validateDigits] })}
        format={format}
        isReadOnly={isReadOnly}
        placeholder={placeholder}
        className={className}
      />
    )
  }

  // 検索条件では範囲指定。範囲全体に対する検証は下限の入力欄に付ける
  const rangeOf = (_: unknown, formValues: RHF.FieldValues) => RHF.get(formValues, formPath) as NumericRange | undefined
  return (
    <div className={`flex items-center gap-1 ${className ?? ''}`}>
      {/* 下限 */}
      <NumericInput
        id={binding.toElementId(formPath)}
        formPath={`${formPath}.from`}
        control={binding.formMethods.control}
        rules={toRegisterRules({
          rules,
          itemValueOf: rangeOf,
          validators: [
            range => validateDigits((range as NumericRange | undefined)?.from),
            range => validateNumericRange(range as NumericRange | undefined),
          ],
        })}
        format={format}
        isReadOnly={isReadOnly}
        placeholder={placeholder}
        className="flex-1 min-w-0"
      />
      <span className="select-none">～</span>
      {/* 上限 */}
      <NumericInput
        formPath={`${formPath}.to`}
        control={binding.formMethods.control}
        rules={toRegisterRules({ rules: undefined, validators: [validateDigits] })}
        format={format}
        isReadOnly={isReadOnly}
        placeholder={placeholder}
        className="flex-1 min-w-0"
      />
    </div>
  )
}

/**
 * 1つの数値の入力欄。
 * 入力中は書式を外した文字列を、入力中でなければカンマ区切りの文字列を表示する。
 * 入力中の文字列はフォームの値とは別に持ち、フォーカスアウト時と Enter キーでフォームの値に反映する。
 * IME で変換中の全角文字を半角に読み替えると変換が壊れるため、入力中の文字列はフォームの値と別にしている。
 * Enter キーでも反映するのは、Enter キーによるフォームの送信で入力中の値が送信されるようにするため。
 */
function NumericInput({ id, formPath, control, rules, format, isReadOnly, placeholder, className }: {
  id?: string
  formPath: string
  control: RHF.Control<RHF.FieldValues>
  rules: Pick<RHF.RegisterOptions, 'validate'>
  format: NumericFormat
  isReadOnly: boolean | undefined
  placeholder: string | undefined
  className?: string
}) {
  const { field } = RHF.useController({ name: formPath, control, rules })
  const value = toNumericText(field.value)

  /** 入力中の文字列。入力中でなければ undefined */
  const [draft, setDraft] = React.useState<string>()
  const selectAllOnFocus = useSelectAllOnFocus()

  const handleFocus: React.FocusEventHandler<HTMLInputElement> = e => {
    if (!isReadOnly) setDraft(value)
    selectAllOnFocus.onFocus(e)
  }
  const handleChange: React.ChangeEventHandler<HTMLInputElement> = e => {
    if ((e.nativeEvent as InputEvent).isComposing) {
      setDraft(e.target.value)
      return
    }
    const accepted = NUMERIC_INPUT_FILTER.accept(e.target.value)
    if (accepted !== undefined) setDraft(accepted)
  }
  /** 入力中の文字列をフォームの値に反映し、反映した文字列を返す。入力中でなければ undefined */
  const commitDraft = () => {
    if (draft === undefined) return undefined
    const committed = commitNumericText(draft)
    if (committed !== value) field.onChange(committed)
    return committed
  }
  const handleKeyDown: React.KeyboardEventHandler<HTMLInputElement> = e => {
    if (e.key !== 'Enter' || e.nativeEvent.isComposing) return
    const committed = commitDraft()
    if (committed !== undefined) setDraft(committed)
  }
  const handleBlur = () => {
    commitDraft()
    setDraft(undefined)
    field.onBlur()
  }

  return (
    <div className={`inline-flex items-center px-1 py-px ${inputFrameClassName(isReadOnly)} ${className ?? ''}`}>
      <input
        type="text"
        id={id}
        ref={field.ref}
        name={field.name}
        inputMode={format.decimalDigit > 0 ? 'decimal' : 'numeric'}
        value={draft ?? formatNumeric(value, { ...format, suffix: undefined })}
        onFocus={handleFocus}
        onMouseDown={selectAllOnFocus.onMouseDown}
        onMouseUp={selectAllOnFocus.onMouseUp}
        onChange={handleChange}
        onCompositionEnd={e => setDraft(NUMERIC_INPUT_FILTER.sanitize(e.currentTarget.value))}
        onKeyDown={handleKeyDown}
        onBlur={handleBlur}
        readOnly={isReadOnly}
        placeholder={isReadOnly ? undefined : placeholder}
        spellCheck={false}
        autoComplete="off"
        className="flex-1 min-w-0 w-full text-right bg-transparent outline-none"
      />
      {/* 接尾辞（単位） */}
      {format.suffix && (
        <span className="pl-1 select-none whitespace-nowrap">{format.suffix}</span>
      )}
    </div>
  )
}

//#endregion フォーム用

//#region グリッド用

export type NumericColumnOptions<TRow> = ColumnOptionsBase<TRow>

/** 数値の列（グリッド用） */
export function numericColumn<TRow>(
  binding: GridBinding,
  path: RHF.Path<TRow>,
  options?: NumericColumnOptions<TRow>,
): EG2.EditableGridLeafColumn<TRow> {
  const member = assertValueMember(findCellMemberMetadata(binding, path), path, 'numeric 列', isNumericMember)
  const format = numericFormatOf(member)

  const column = defineCellColumn(binding, path, options, {
    render: ({ value }) => formatNumeric(toNumericText(value), format),
    editor: NUMERIC_CELL_EDITOR,
    toText: toNumericText,
    fromText: text => {
      const committed = commitNumericText(normalizeNumeric(text))
      return isNumericText(committed) ? { value: committed } : undefined
    },
    alignRight: true,
  })
  // 桁数の超過は切り捨てずにクライアント側エラーにする
  return attachColumnRules(column, {
    path,
    validate: value => validateNumericDigits(toNumericText(value), format),
  })
}

/**
 * 数値のセルエディタ。参照を使い回すためモジュールのトップレベルで作る。
 * 入力できる文字の制限はフォームの入力欄と同じものを使う。制限はこのファイルの後ろで定義しているので、呼び出し時に参照する
 */
const NUMERIC_CELL_EDITOR = createTextCellEditor({
  multiline: false,
  inputFilter: {
    accept: text => NUMERIC_INPUT_FILTER.accept(text),
    sanitize: text => NUMERIC_INPUT_FILTER.sanitize(text),
  },
  alignRight: true,
})

//#endregion グリッド用

//#region フォームとグリッドで共有する仕様

/** 数値の書式 */
type NumericFormat = {
  /** 整数部の最大桁数 */
  integerDigit: number
  /** 小数部の最大桁数。0 の場合は小数を入力できない */
  decimalDigit: number
  /** 3桁カンマ区切りで表示するかどうか */
  commaSeparated: boolean
  /** 接尾辞（単位）。無い場合は undefined */
  suffix: string | undefined
}

/** 検索条件の範囲指定の値 */
type NumericRange = { from?: string | null, to?: string | null }

function isNumericMember(member: AggregateMetadata.Value): boolean {
  return member.type === 'int' || member.type === 'decimal' || member.type === 'sequence' || member.type === 'year'
}

/** メタデータから数値の書式を求める */
function numericFormatOf(member: AggregateMetadata.Member): NumericFormat {
  let integerDigit: number
  let decimalDigit: number
  if (member.kind === 'value' && member.type === 'year') {
    integerDigit = 4
    decimalDigit = 0
  } else if (member.kind === 'value' && member.type === 'decimal') {
    // 桁数の指定が無い場合はデータベースの既定の精度（総合18桁・小数部2桁）に合わせる
    const totalDigit = member.totalDigit ?? 18
    decimalDigit = member.decimalPlace ?? (member.totalDigit === undefined ? 2 : 0)
    integerDigit = Math.max(totalDigit - decimalDigit, 0)
  } else {
    // 整数・シーケンス。桁数の指定が無い場合は32ビット整数に収まる桁数
    integerDigit = member.totalDigit ?? 10
    decimalDigit = 0
  }

  const suffix = member.isCurrency ? '円' : member.isQuantity ? '個' : undefined
  return {
    integerDigit,
    decimalDigit,
    commaSeparated: suffix !== undefined,
    suffix,
  }
}

/** 値の確定時の正規化。全角を半角に読み替え、カンマを除く。桁数の超過はここでは扱わない */
function normalizeNumeric(value: string): string {
  return value
    .replace(/[０-９]/g, char => String.fromCharCode(char.charCodeAt(0) - 0xFEE0))
    .replace(/[．。]/g, '.')
    .replace(/[−－ー‐–—―]/g, '-')
    .replace(/[,，\s]/g, '')
}

/** 桁数の検証。整数部か小数部が桁数を超えていればエラーメッセージを、超えていなければ undefined を返す */
function validateNumericDigits(value: string, format: NumericFormat): string | undefined {
  if (value === '') return undefined
  if (!isNumericText(value)) return '数値を入力してください。'

  const [integerPart, decimalPart = ''] = value.replace('-', '').split('.')
  if (integerPart.replace(/^0+/, '').length > format.integerDigit) {
    return `整数部は${format.integerDigit}桁以内で入力してください。`
  }
  if (decimalPart.length > format.decimalDigit) {
    return format.decimalDigit === 0
      ? '小数は入力できません。'
      : `小数部は${format.decimalDigit}桁以内で入力してください。`
  }
  return undefined
}

/** 表示用の文字列にする。カンマ区切りと接尾辞を付ける */
function formatNumeric(value: string | null | undefined, format: NumericFormat): string {
  if (value === null || value === undefined || value === '') return ''
  let text = value
  if (format.commaSeparated && isNumericText(value)) {
    const [integerPart, decimalPart] = value.split('.')
    const sign = integerPart.startsWith('-') ? '-' : ''
    const digits = integerPart.replace('-', '').replace(/\B(?=(\d{3})+(?!\d))/g, ',')
    text = `${sign}${digits}${decimalPart === undefined ? '' : `.${decimalPart}`}`
  }
  return format.suffix ? `${text}${format.suffix}` : text
}

/**
 * 数値の入力欄とセルエディタで入力できる文字の制限。
 * 全角は半角に読み替え、数値として解釈できない文字の入力は受け付けない。
 */
const NUMERIC_INPUT_FILTER: TextInputFilter = {
  accept: text => {
    const normalized = normalizeNumeric(text)
    return isNumericText(normalized) ? normalized : undefined
  },
  sanitize: text => sanitizeNumericText(text),
}

/** 数値として解釈できる途中までの文字列か（符号・小数点だけの入力途中も含む） */
function isNumericText(value: string): boolean {
  return /^-?\d*\.?\d*$/.test(value)
}

/** 数値として解釈できない文字を取り除く。符号は先頭のものだけ、小数点は最初のものだけを残す */
function sanitizeNumericText(value: string): string {
  const normalized = normalizeNumeric(value).replace(/[^0-9.-]/g, '')
  const sign = normalized.startsWith('-') ? '-' : ''
  const [integerPart, ...decimalParts] = normalized.replace(/-/g, '').split('.')
  return decimalParts.length === 0
    ? `${sign}${integerPart}`
    : `${sign}${integerPart}.${decimalParts.join('')}`
}

/**
 * 入力を確定するときの文字列。末尾の小数点や、符号・小数点だけの入力を取り除く。
 * 整数部を省略した入力（「.5」など）は整数部に 0 を補う。
 */
function commitNumericText(value: string): string {
  const normalized = normalizeNumeric(value)
    .replace(/\.$/, '')
    .replace(/^(-?)\./, (_, sign: string) => `${sign}0.`)
  return normalized === '-' ? '' : normalized
}

/** フォームの値を数値の文字列として読む */
function toNumericText(value: unknown): string {
  if (value === null || value === undefined) return ''
  return typeof value === 'string' ? value : String(value)
}

/** 範囲指定の下限が上限を超えていればエラーメッセージを返す */
function validateNumericRange(range: NumericRange | undefined): string | undefined {
  const from = range?.from ?? ''
  const to = range?.to ?? ''
  if (from === '' || to === '' || !isNumericText(from) || !isNumericText(to)) return undefined
  return Number(from) > Number(to) ? '下限が上限を超えています。' : undefined
}

//#endregion フォームとグリッドで共有する仕様
