import * as RHF from "react-hook-form"
import * as EG2 from "@halllky/editable-grid"
import type { AggregateMetadata } from "../../__autoGenerated"
import type { GridBinding } from "../FormBinding"
import type { ColumnOptionsBase, InputPropsBase, WithFormBinding } from "./InputProps"

/*
 * 文章（複数行の文字列）の入力欄。
 * フォーム用とグリッド用で以下の仕様を共有する。
 *
 * - 改行を入力できる。グリッドでは Shift+Enter で改行し、Enter で編集を確定する。
 * - 最大長はメタデータから決める。
 * - 値の確定時に前後の空白を削除し、Unicode正規化（NFKC）を行う。最大長を超える部分は切り捨てる。
 * - スペルチェックとオートコンプリートは無効。
 * - 検索条件のフォームでは、改行を入力できない1行の入力欄になる。
 */

//#region フォーム用

export type TextAreaProps<TValues extends RHF.FieldValues> = InputPropsBase<TValues> & {
  /** 未入力のときに表示する文字列 */
  placeholder?: string
}

/** 文章の入力欄（フォーム用）。内容の行数に合わせて高さが伸びる。上限は className の max-height で指定する */
export function TextArea<TValues extends RHF.FieldValues>(props: WithFormBinding<TextAreaProps<TValues>, TValues>): React.ReactNode {
  throw new Error('not implemented')
}

//#endregion フォーム用

//#region グリッド用

export type TextAreaColumnOptions<TRow> = ColumnOptionsBase<TRow> & {
  /** セルの中で折り返して全文を表示するかどうか。未指定の場合は折り返さず、1行に収まらない部分は省略する */
  wrap?: boolean
}

/** 文章の列（グリッド用） */
export function textAreaColumn<TRow>(
  binding: GridBinding,
  path: RHF.Path<TRow>,
  options?: TextAreaColumnOptions<TRow>,
): EG2.EditableGridLeafColumn<TRow> {
  throw new Error('not implemented')
}

//#endregion グリッド用

//#region フォームとグリッドで共有する仕様

/** メタデータから最大長を求める。制限が無い場合は undefined */
function maxLengthOf(member: AggregateMetadata.Member): number | undefined {
  throw new Error('not implemented')
}

/** 値の確定時の正規化 */
function normalizeDescription(value: string, maxLength: number | undefined): string {
  throw new Error('not implemented')
}

//#endregion フォームとグリッドで共有する仕様
