import * as RHF from "react-hook-form"
import * as EG2 from "@halllky/editable-grid"
import type { AggregateMetadata } from "../../__autoGenerated"
import type { GridBinding } from "../FormBinding"
import type { ColumnOptionsBase, InputPropsBase, WithFormBinding } from "./InputProps"

/*
 * 単語（1行の文字列）の入力欄。
 * フォーム用とグリッド用で以下の仕様を共有する。
 *
 * - 最大長はメタデータから決める。
 * - 値の確定時（フォームはフォーカスアウト、グリッドはセル編集の確定と貼り付け）に、
 *   前後の空白を削除し、Unicode正規化（NFKC）を行う。最大長を超える部分は切り捨てる。
 * - スペルチェックとオートコンプリートは無効。
 * - 検索条件のフォームでも外観と挙動は変わらない。一致方法（部分一致など）はサーバー側が決める。
 */

//#region フォーム用

export type TextBoxProps<TValues extends RHF.FieldValues> = InputPropsBase<TValues> & {
  /** 未入力のときに表示する文字列 */
  placeholder?: string
}

/** 単語の入力欄（フォーム用） */
export function TextBox<TValues extends RHF.FieldValues>(props: WithFormBinding<TextBoxProps<TValues>, TValues>): React.ReactNode {
  // 実装時の注意: ui フォルダと、ui フォルダに依存するモジュールには依存せず、ui2 単独で実装すること。
  // ui フォルダは ui2 の動作が安定したら削除するので、依存していると削除時に巻き込まれるため。
  throw new Error('not implemented')
}

//#endregion フォーム用

//#region グリッド用

export type TextColumnOptions<TRow> = ColumnOptionsBase<TRow>

/** 単語の列（グリッド用） */
export function textColumn<TRow>(
  binding: GridBinding,
  path: RHF.Path<TRow>,
  options?: TextColumnOptions<TRow>,
): EG2.EditableGridLeafColumn<TRow> {
  // 実装時の注意: ui フォルダと、ui フォルダに依存するモジュールには依存せず、ui2 単独で実装すること。
  // ui フォルダは ui2 の動作が安定したら削除するので、依存していると削除時に巻き込まれるため。
  throw new Error('not implemented')
}

//#endregion グリッド用

//#region フォームとグリッドで共有する仕様

/**
 * メタデータから最大長を求める。制限が無い場合は undefined。
 * ノードオプションの最大長はデータベースの桁数の定義に使うものなので見ず、画面制御用のカスタム属性の最大長を使う。
 */
function maxLengthOf(member: AggregateMetadata.Member): number | undefined {
  // 実装時の注意: ui フォルダと、ui フォルダに依存するモジュールには依存せず、ui2 単独で実装すること。
  // ui フォルダは ui2 の動作が安定したら削除するので、依存していると削除時に巻き込まれるため。
  throw new Error('not implemented')
}

/** 値の確定時の正規化 */
function normalizeWord(value: string, maxLength: number | undefined): string {
  // 実装時の注意: ui フォルダと、ui フォルダに依存するモジュールには依存せず、ui2 単独で実装すること。
  // ui フォルダは ui2 の動作が安定したら削除するので、依存していると削除時に巻き込まれるため。
  throw new Error('not implemented')
}

//#endregion フォームとグリッドで共有する仕様
