import * as RHF from "react-hook-form"
import * as EG2 from "@halllky/editable-grid"
import type { AggregateMetadata } from "../../__autoGenerated"
import { findMemberMetadata, type GridBinding } from "../FormBinding"
import { assertValueMember, inputFrameClassName, toRegisterRules, type ColumnOptionsBase, type InputPropsBase, type WithFormBinding, useSelectAllOnFocus } from "./InputProps"
import { createTextCellEditor, defineCellColumn, findCellMemberMetadata } from "./GridCell"

/*
 * 単語（1行の文字列）の入力欄。
 * フォーム用とグリッド用で以下の仕様を共有する。
 *
 * - 最大長はメタデータから決める。
 * - 値の確定時（フォームはフォーカスアウト、グリッドはセル編集の確定と貼り付け）に、
 *   前後の空白を削除し、Unicode正規化（NFKC）を行う。最大長を超える部分は切り捨てる。
 * - スペルチェックとオートコンプリートは無効。
 * - 検索条件のフォームでも外観と挙動は変わらない。一致方法（部分一致など）はサーバー側が決める。
 */

//#region フォーム用

export type TextBoxProps<TValues extends RHF.FieldValues> = InputPropsBase<TValues> & {
  /** 未入力のときに表示する文字列 */
  placeholder?: string
}

/** 単語の入力欄（フォーム用） */
export function TextBox<TValues extends RHF.FieldValues>(props: WithFormBinding<TextBoxProps<TValues>, TValues>): React.ReactNode {
  const { binding, name, isReadOnly, rules, className, placeholder } = props
  const formPath = binding.toFormPath(name)
  const member = assertValueMember(findMemberMetadata(binding.metadata, name), name, 'TextBox', isWordMember)
  const maxLength = maxLengthOf(member)

  const { field } = RHF.useController({
    name: formPath,
    control: binding.formMethods.control,
    rules: toRegisterRules({ rules }),
  })
  const selectAllOnFocus = useSelectAllOnFocus()

  const handleBlur: React.FocusEventHandler<HTMLInputElement> = e => {
    const normalized = normalizeWord(e.target.value, maxLength)
    if (normalized !== (field.value ?? '')) field.onChange(normalized)
    field.onBlur()
  }

  return (
    <input
      type="text"
      ref={field.ref}
      name={field.name}
      value={field.value ?? ''}
      onChange={e => field.onChange(e.target.value)}
      onBlur={handleBlur}
      {...selectAllOnFocus}
      readOnly={isReadOnly}
      maxLength={maxLength}
      placeholder={isReadOnly ? undefined : placeholder}
      spellCheck={false}
      autoComplete="off"
      className={`block px-1 py-px outline-none ${inputFrameClassName(isReadOnly)} ${className ?? ''}`}
    />
  )
}

//#endregion フォーム用

//#region グリッド用

export type TextColumnOptions<TRow> = ColumnOptionsBase<TRow>

/** 単語の列（グリッド用） */
export function textColumn<TRow>(
  binding: GridBinding,
  path: RHF.Path<TRow>,
  options?: TextColumnOptions<TRow>,
): EG2.EditableGridLeafColumn<TRow> {
  const member = assertValueMember(findCellMemberMetadata(binding, path), path, 'text 列', isWordMember)
  const maxLength = maxLengthOf(member)

  return defineCellColumn(binding, path, options, {
    render: ({ value }) => typeof value === 'string' ? value : '',
    editor: WORD_CELL_EDITOR,
    toText: value => typeof value === 'string' ? value : '',
    fromText: text => ({ value: normalizeWord(text, maxLength) }),
  })
}

/** 単語のセルエディタ。参照を使い回すためモジュールのトップレベルで作る */
const WORD_CELL_EDITOR = createTextCellEditor({ multiline: false })

//#endregion グリッド用

//#region フォームとグリッドで共有する仕様

function isWordMember(member: AggregateMetadata.Value): boolean {
  return member.type === 'word'
}

/**
 * メタデータから最大長を求める。制限が無い場合は undefined。
 * ノードオプションの最大長はデータベースの桁数の定義に使うものなので見ず、画面制御用のカスタム属性の最大長を使う。
 */
function maxLengthOf(member: AggregateMetadata.Member): number | undefined {
  return member.customMaxLength !== undefined && member.customMaxLength > 0
    ? member.customMaxLength
    : undefined
}

/** 値の確定時の正規化 */
function normalizeWord(value: string, maxLength: number | undefined): string {
  const normalized = value.trim().normalize('NFKC')
  return maxLength === undefined ? normalized : normalized.slice(0, maxLength)
}

//#endregion フォームとグリッドで共有する仕様
