import * as ReactHookForm from "react-hook-form"
import * as Icon from "@heroicons/react/24/solid"
import { MetadataForPage } from "../__autoGenerated/util"
import * as DynamicForm from "@nijo/ui-components/layout/DynamicForm"
import * as Input from "@nijo/ui-components/input"
import * as EnumDefs from "../__autoGenerated/enum-defs"
import { asDecimalSafety } from "@nijo/ui-components/util"
import { MetadataContextType, MetadataModelType } from "./MetadataContext"

/**
 * 自動生成されたメタデータをもとに、 DynamicForm の入力フォーム定義を生成する。
 */
export default function (
  /** ルート集約のメタデータ */
  metadata: MetadataForPage.StructureMetadata,
  /** ルート集約のモデルの種類 */
  model: MetadataModelType,
  /** 検索条件の場合はフォームの構築ルールが大きく変わるので */
  isSearchCondition: boolean,
  /** `MetadataContext` のインスタンス */
  helper: MetadataContextType,
): DynamicForm.MemberOwner {
  return {
    members: convertMembersToDynamicFormMembers(metadata.members, model, isSearchCondition, helper, [])
  }
}

/**
 * メタデータのメンバーをDynamicFormのメンバーに変換する
 */
function convertMembersToDynamicFormMembers(
  members: { [key: string]: MetadataForPage.StructureMetadataMember },
  /** エントリーではなくmembersのオーナーのモデルの種類 */
  ownerModel: MetadataModelType,
  isSearchCondition: boolean,
  helper: MetadataContextType,
  /** 処理中では使われない */
  ancestorsPathForDebug: string[],
): DynamicForm.Member[] {
  const result: DynamicForm.Member[] = []

  for (const [memberName, member] of Object.entries(members)) {

    if (member.type === 'RootAggregate') {
      // RootAggregateは再帰的に処理
      result.push(...convertMembersToDynamicFormMembers(member.members, ownerModel, isSearchCondition, helper, [...ancestorsPathForDebug, memberName]))

    } else if (member.type === 'ChildAggregate') {
      // ChildAggregateはセクションとして処理
      result.push({
        type: 'section',
        physicalName: memberName,
        label: member.displayName,
        members: convertMembersToDynamicFormMembers(member.members, ownerModel, isSearchCondition, helper, [...ancestorsPathForDebug, memberName])
      })

    } else if (member.type === 'ChildrenAggregate') {
      // ChildrenAggregateは、検索条件の場合はChildと同様、そうでない場合は配列として処理
      if (isSearchCondition) {
        result.push({
          type: 'section',
          physicalName: memberName,
          label: member.displayName,
          members: convertMembersToDynamicFormMembers(member.members, ownerModel, isSearchCondition, helper, [...ancestorsPathForDebug, memberName])
        })

      } else {
        result.push({
          type: 'array',
          physicalName: memberName,
          arrayLabel: member.displayName,
          itemLabel: member.displayName,
          members: convertMembersToDynamicFormMembers(member.members, ownerModel, isSearchCondition, helper, [...ancestorsPathForDebug, memberName]),
          onCreateNewItem: () => createDefaultItem(member.members)
        })
      }

    } else if (member.type === 'ref-to') {

      // 検索ダイアログで対象データを選択するのではなくここで参照先の属性を直に入力する
      if (ownerModel === 'command-model' || isSearchCondition) {
        const refTo = helper.getRefTo(member)
        if (!refTo) throw new Error(`${member.refToObject} の参照先が見つかりません`)

        const refToIsSearchCondition = member.refToObject === 'SearchCondition' || isSearchCondition
        const isRefEntry = ownerModel === 'command-model' && member.refToObject === 'SearchCondition'

        result.push({
          type: 'section',
          // Refエントリーの場合はfilterオブジェクトに包む
          physicalName: isRefEntry ? `${memberName}.filter` : memberName,
          label: member.displayName,
          members: convertMembersToDynamicFormMembers(
            // 参照先のオブジェクトの型
            refToIsSearchCondition
              ? refTo.refToRootMetadata.members
              : refTo.refToMetadata.members,
            refTo.refToRootMetadata.model,
            refToIsSearchCondition || isSearchCondition,
            helper,
            // デバッグ用
            isRefEntry
              ? [...ancestorsPathForDebug, memberName, 'filter']
              : [...ancestorsPathForDebug, memberName],
          ),
        })
        continue
      }

      // 検索ダイアログで対象を選択

      result.push({
        physicalName: memberName,
        label: member.displayName,
        contents: ({ useFormReturn, name }) => (
          // TODO: 検索ダイアログを表示する
          <Input.IconButton icon={Icon.MagnifyingGlassIcon} hideText outline>
            検索
          </Input.IconButton>
        ),
        getGridColumnDef: ({ member }) => ({
          fieldPath: member.physicalName,
          header: typeof member.label === 'string' ? member.label : undefined,
          onStartEditing: ctx => {
            ctx.setEditorInitialValue(ReactHookForm.get(ctx.row, member.physicalName!))
          },
          onEndEditing: ctx => {
            const clone = window.structuredClone(ctx.row)
            ReactHookForm.set(clone, member.physicalName!, ctx.value)
            ctx.setEditedRow(clone)
          },
          renderCell: ctx => (
            // TODO: 検索ダイアログを表示する
            <Input.IconButton icon={Icon.MagnifyingGlassIcon} hideText outline>
              検索
            </Input.IconButton>
          ),
        }),
      })

    } else {
      // ValueMetadataの場合
      const valueMember = member as MetadataForPage.ValueMetadata
      result.push(convertValueMetadataToValueMember(valueMember, memberName, isSearchCondition))
    }
  }

  return result
}

/**
 * ValueMetadataをDynamicFormのValueMemberに変換する
 */
function convertValueMetadataToValueMember(
  member: MetadataForPage.ValueMetadata,
  memberName: string,
  isSearchCondition: boolean,
): DynamicForm.ValueMember {
  const baseMember: DynamicForm.ValueMember = {
    physicalName: memberName,
    label: member.displayName,
    fullWidth: false
  }

  // 通常の値メンバー。単語、実数、日付など
  if (member.type) {
    return {
      ...baseMember,
      ...VALUE_MEMBER_INPUT(member.type, isSearchCondition)
    }
  }

  // 列挙体
  if (member.enumType !== undefined) {
    const enumValues = EnumDefs.EnumValueMap[member.enumType!]()

    return {
      ...baseMember,
      contents: isSearchCondition
        ? ({ useFormReturn, name }) => (
          <div className="flex flex-wrap gap-y-1 gap-x-2">
            {enumValues.map(val => (
              <Input.CheckBox key={val} control={useFormReturn.control} name={`${name}.${val}`}>
                {val}
              </Input.CheckBox>
            ))}
          </div>
        )
        : ({ useFormReturn, name }) => (
          <Input.EnumSelect
            enumValues={enumValues}
            control={useFormReturn.control}
            name={name}
          />
        ),
    }
  }

  // 値オブジェクト
  if (member.valueObjectType !== undefined) {
    return {
      ...baseMember,
      ...VALUE_MEMBER_INPUT('word', isSearchCondition)
    }
  }

  // デフォルトは単語型
  return {
    ...baseMember,
    ...VALUE_MEMBER_INPUT('word', isSearchCondition)
  }
}

/**
 * 値メンバーの入力コンポーネントを取得する
 */
const VALUE_MEMBER_INPUT = (
  type: MetadataForPage.ValueMetadata['type'],
  isSearchCondition: boolean,
): Required<Pick<DynamicForm.ValueMember, 'contents' | 'getGridColumnDef'>> => {
  switch (type) {
    case 'word':
      return {
        contents: ({ useFormReturn, name, isReadOnly }) => (
          <Input.Word
            control={useFormReturn.control}
            name={name}
            readOnly={isReadOnly}
          />
        ),
        getGridColumnDef: ({ member, cellType, pathFromRow, isReadOnly }) => {
          return cellType.text(pathFromRow, typeof member.label === 'string' ? member.label : member.physicalName || '', {
            defaultWidth: 150,
            isReadOnly,
          })
        }
      }
    case 'description':
      return {
        contents: ({ useFormReturn, name, isReadOnly }) => (
          <Input.Description
            control={useFormReturn.control}
            name={name}
            readOnly={isReadOnly}
          />
        ),
        getGridColumnDef: ({ member, cellType, pathFromRow, isReadOnly }) => {
          return cellType.text(pathFromRow, typeof member.label === 'string' ? member.label : member.physicalName || '', {
            defaultWidth: 200,
            editorOverflow: 'vertical',
            isReadOnly,
          })
        }
      }
    case 'int':
    case 'decimal':
      return {
        contents: isSearchCondition
          ? ({ useFormReturn, name, isReadOnly }) => (
            <div className="flex flex-wrap gap-1">
              <Input.NumberInput
                control={useFormReturn.control}
                name={`${name}.from`}
                readOnly={isReadOnly}
              />
              <span>～</span>
              <Input.NumberInput
                control={useFormReturn.control}
                name={`${name}.to`}
                readOnly={isReadOnly}
              />
            </div>
          )
          : ({ useFormReturn, name, isReadOnly }) => (
            <Input.NumberInput
              control={useFormReturn.control}
              name={name}
              readOnly={isReadOnly}
            />
          ),
        getGridColumnDef: ({ member, pathFromRow, isReadOnly }) => ({
          fieldPath: pathFromRow,
          header: typeof member.label === 'string' ? member.label : undefined,
          isReadOnly,
          onStartEditing: ctx => {
            const value: string | number | null | undefined = ReactHookForm.get(ctx.row, member.physicalName!)
            ctx.setEditorInitialValue(asDecimalSafety(value)?.toFixed() ?? '')
          },
          onEndEditing: ctx => {
            const clone = window.structuredClone(ctx.row)
            const value = asDecimalSafety(ctx.value)?.toNumber() ?? null
            ReactHookForm.set(clone, member.physicalName!, value)
            ctx.setEditedRow(clone)
          },
          renderCell: ctx => (
            <div className="w-full px-1 truncate text-right">
              {ReactHookForm.get(ctx.row.original, member.physicalName!)}
            </div>
          ),
        })
      }
    case 'date':
    case 'yearmonth':
    case 'datetime':
      return {
        contents: isSearchCondition
          ? ({ useFormReturn, name, isReadOnly }) => (
            <div className="flex flex-wrap gap-1">
              <Input.DateInput
                control={useFormReturn.control}
                name={`${name}.from`}
                yearMonth={type === 'yearmonth'}
                readOnly={isReadOnly}
              />
              <span>～</span>
              <Input.DateInput
                control={useFormReturn.control}
                name={`${name}.to`}
                yearMonth={type === 'yearmonth'}
                readOnly={isReadOnly}
              />
            </div>
          )
          : ({ useFormReturn, name, isReadOnly }) => (
            <Input.DateInput
              control={useFormReturn.control}
              name={name}
              yearMonth={type === 'yearmonth'}
              readOnly={isReadOnly}
            />
          ),
        getGridColumnDef: ({ member, cellType, pathFromRow, isReadOnly }) => {
          return cellType.date(pathFromRow, typeof member.label === 'string' ? member.label : member.physicalName || '', {
            isReadOnly,
            defaultWidth: 140,
          })
        }
      }
    case 'bool':
      return {
        contents: ({ useFormReturn, name, isReadOnly }) => (
          <Input.CheckBox
            control={useFormReturn.control}
            name={name}
            readOnly={isReadOnly}
          />
        ),
        getGridColumnDef: ({ member, cellType, pathFromRow, isReadOnly }) => {
          return cellType.boolean(pathFromRow, typeof member.label === 'string' ? member.label : member.physicalName || '', {
            isReadOnly,
            defaultWidth: 80,
          })
        }
      }
    default:
      return {
        contents: ({ useFormReturn, name, isReadOnly }) => (
          <Input.Word
            control={useFormReturn.control}
            name={name}
            readOnly={isReadOnly}
          />
        ),
        getGridColumnDef: ({ member, cellType, pathFromRow, isReadOnly }) => {
          return cellType.text(pathFromRow, typeof member.label === 'string' ? member.label : member.physicalName || '', {
            defaultWidth: 150,
            isReadOnly,
          })
        }
      }
  }
}

/**
 * デフォルトのアイテムを作成する
 */
function createDefaultItem(members: { [key: string]: MetadataForPage.StructureMetadataMember }): any {
  const result: any = {}

  for (const [memberName, member] of Object.entries(members)) {
    if (member.type === 'RootAggregate' || member.type === 'ChildAggregate' || member.type === 'ChildrenAggregate') {
      // 集約型は再帰的に処理
      result[memberName] = createDefaultItem(member.members)
    } else if (member.type === 'ref-to') {
      // 外部参照は空文字
      result[memberName] = ''
    } else {
      // ValueMetadataの場合
      const valueMember = member as MetadataForPage.ValueMetadata
      result[memberName] = getDefaultValue(valueMember)
    }
  }

  return result
}

/**
 * 値メンバーのデフォルト値を取得する
 */
function getDefaultValue(member: MetadataForPage.ValueMetadata): any {
  if (member.type === 'bool') {
    return false
  }
  if (member.type === 'int' || member.type === 'decimal') {
    return 0
  }
  if (member.type === 'date' || member.type === 'yearmonth' || member.type === 'datetime') {
    return ''
  }
  if (member.enumType !== undefined) {
    const enumValues = EnumDefs.EnumValueMap[member.enumType]()
    return enumValues.length > 0 ? enumValues[0] : ''
  }
  // その他は空文字
  return ''
}
