import React from "react"
import { Allotment, LayoutPriority } from "allotment"
import * as Icon from "@heroicons/react/24/solid"
import { DynamicForm, MemberOwner, DynamicFormRef } from "@nijo/ui-components/layout"
import * as Input from "@nijo/ui-components/input"
import { UUID } from "uuidjs"
import { toFlattenStringList, useHttpRequest, useUnhandledMessage } from "../util"
import dayjs from "dayjs"
import useEvent from "react-use-event-hook"
import { callComplexPostEndpointAsync } from "../example/callComplexPostEndpointAsync"
import * as AutoGenerated from "../__autoGenerated"

/**
 * Command Model のコマンド実行と Query Model の検索処理の両方で用いられる
 */
export default function ({
  title,
  localStorageUniqueKey,
  rootAggregateType,
  parameterFormSchema,
  onSelectedHistoryChanged,
  className,
  children,
}: {
  title: string
  parameterFormSchema: MemberOwner
  onSelectedHistoryChanged: (history: ExecutionHistory | null) => void
  localStorageUniqueKey: string
  rootAggregateType: string
  className?: string
  /** 実行履歴表示欄 */
  children: React.ReactNode
}) {

  const { commandHistory, executeCommand, clearCommandHistory } = useCommandExecutor(localStorageUniqueKey, rootAggregateType)
  const parameterFormRef = React.useRef<DynamicFormRef>(null)

  // 表示中の履歴
  const [selectedHistoryId, setSelectedHistoryId] = React.useState<string | null>(null)
  const handleSelectHistory = useEvent((history: ExecutionHistory | null) => {
    setSelectedHistoryId(history?.id ?? null)
    onSelectedHistoryChanged(history)
  })
  const handleClearHistory = useEvent(() => {
    handleSelectHistory(null)
    clearCommandHistory()
  })

  // コマンド実行
  const [nowExecuting, setNowExecuting] = React.useState(false)
  const handleExecuteCommand = useEvent(async () => {
    if (nowExecuting) return
    setNowExecuting(true)
    try {
      const parameter = parameterFormRef.current?.useFormReturn.getValues()
      if (!parameter) return
      const newHistory = await executeCommand(parameter)
      if (!newHistory) return // キャンセルされた場合はundefinedが返る

      handleSelectHistory(newHistory)
    } finally {
      setNowExecuting(false)
    }
  })

  // コマンド欄折りたたみ
  const [parameterOpened, setParameterOpened] = React.useState(true)
  const handleButtonClick = () => {
    setParameterOpened(prev => !prev)
  }
  const handleVisibleChange = (index: number, visible: boolean) => {
    if (index === 0) setParameterOpened(visible)
  }

  return (
    <div className={`flex flex-col ${className}`}>
      <button type="button" className="flex items-center gap-1 font-bold select-none cursor-pointer" onClick={handleButtonClick}>
        {parameterOpened
          ? <Icon.ChevronDownIcon className="w-4 h-4" />
          : <Icon.ChevronRightIcon className="w-4 h-4" />}
        {title}
      </button>

      <Allotment
        vertical
        separator={false}
        proportionalLayout={false}
        className="flex-1"
        onVisibleChange={handleVisibleChange}
      >
        {/* パラメータ */}
        <Allotment.Pane
          visible={parameterOpened}
          snap
          priority={LayoutPriority.Low}
          className="h-full w-full flex flex-col gap-1"
        >
          <div className="flex-1 overflow-y-auto bg-gray-100 p-1 border border-gray-300">
            <DynamicForm
              ref={parameterFormRef}
              root={parameterFormSchema}
            />
          </div>
        </Allotment.Pane>

        {/* 実行結果 */}
        <Allotment.Pane
          className="flex flex-col gap-1 pt-2"
        >
          <Allotment
            className="w-full h-full"
            separator={false}
            proportionalLayout={false}
          >
            {/* 実行履歴 */}
            <Allotment.Pane
              priority={LayoutPriority.Low}
              preferredSize={124}
              className="flex flex-col gap-1"
            >
              <div className="flex flex-wrap gap-1">
                <Input.IconButton fill icon={Icon.ArrowRightIcon} onClick={handleExecuteCommand} loading={nowExecuting}>
                  実行
                </Input.IconButton>
                <Input.IconButton outline onClick={handleClearHistory}>
                  クリア
                </Input.IconButton>
              </div>
              <ul className="flex-1 overflow-y-auto">
                {commandHistory.length >= 1 && (
                  <li className="px-1 text-xs select-none truncate">
                    実行履歴
                  </li>
                )}
                {commandHistory.map((history) => (
                  <li
                    key={history.id}
                    className={`p-1 truncate select-none text-xs cursor-pointer hover:bg-gray-200 ${selectedHistoryId === history.id ? 'bg-gray-200' : ''}`}
                    onClick={() => handleSelectHistory(history)}
                  >
                    {history.createdAt}
                  </li>
                ))}
              </ul>
            </Allotment.Pane>

            {/* 実行結果（戻り値） */}
            <Allotment.Pane className="bg-gray-100 border border-gray-300">
              {children}
            </Allotment.Pane>

          </Allotment>
        </Allotment.Pane>
      </Allotment>
    </div>
  )
}

// ---------------------------------

/**
 * コマンド実行と履歴の管理。
 * コマンド実行履歴はlocalStorage に保存される。
 */
const useCommandExecutor = (
  localStorageUniqueKey: string,
  rootAggregateType: string,
) => {
  const localStorageKey = `EXECUTE_HISTORY::${localStorageUniqueKey}`
  const [commandHistory, setCommandHistory] = React.useState<ExecutionHistory[]>([])

  // 履歴をlocalStorage から読み込む
  React.useEffect(() => {
    const history = localStorage.getItem(localStorageKey)
    if (history) {
      setCommandHistory(JSON.parse(history))
    }
  }, [])

  // コマンド実行
  const executeCommand = React.useCallback(async (parameter: object): Promise<ExecutionHistory | undefined> => {
    let newHistory: ExecutionHistory
    const newHistoryId = UUID.generate()
    const createdAt = dayjs().format('YYYY-MM-DD HH:mm:ss')


    // コマンド実行
    const result = await callComplexPostEndpointAsync(
      rootAggregateType as AutoGenerated.QueryModelType, // 型をごまかす。なんでもよい
      parameter as AutoGenerated.LoadFeature.ParamType[AutoGenerated.QueryModelType], // 型をごまかす。なんでもよい
    )
    if (result.type === 'canceled') {
      // キャンセルされた場合は履歴に追加しない
      return undefined

    } else if (result.type === 'error') {
      // パラメータエラー
      newHistory = {
        id: newHistoryId,
        parameter,
        errors: toFlattenStringList(result.detail),
        createdAt,
        ok: false,
      }

    } else {
      // 正常終了
      newHistory = {
        id: newHistoryId,
        createdAt,
        ok: true,
        returnValue: result.returnValue,
        parameter,
      }
    }

    // 履歴をstateに追加
    setCommandHistory(prev => [newHistory, ...prev])

    // 履歴をlocalStorage に保存
    let currentHistory: ExecutionHistory[]
    try {
      currentHistory = JSON.parse(localStorage.getItem(localStorageKey) ?? '[]')
    } catch {
      currentHistory = []
    }
    localStorage.setItem(localStorageKey, JSON.stringify([newHistory, ...currentHistory]))

    return newHistory
  }, [rootAggregateType, localStorageKey])

  // 履歴をクリア
  const clearCommandHistory = React.useCallback(() => {
    localStorage.removeItem(localStorageKey)
    setCommandHistory([])
  }, [localStorageKey])

  return {
    /** コマンド実行履歴 */
    commandHistory,
    /** コマンド実行 */
    executeCommand,
    /** コマンド実行履歴をクリア */
    clearCommandHistory,
  }
}

/** コマンド実行履歴 */
export type ExecutionHistory = {
  id: string
  parameter: object
  createdAt: string
} & ({
  ok: true
  returnValue: object
} | {
  ok: false
  errors: string[]
})
