import { Allotment, LayoutPriority } from 'allotment';
export { QueryModelLoadView } from './QueryModelLoadView';
import SchemaGraph from './SchemaGraph';
import React from 'react';
import { MetadataForPage } from '../__autoGenerated/util';
import RootAggregateView, { RootAggregateViewProps } from './RootAggregateView';

/**
 * スキーマ定義をもとにしたデバッグビュー
 */
export default function ({ className }: {
  className?: string
}) {

  // スキーマ全体のメタデータ
  const autoGenerated = React.useMemo(() => {
    const metadata: { [physicalName: string]: MetadataForPage.StructureMetadata } = MetadataForPage.getAll()

    // ユニークIDによるルート集約のマッピング
    const rootAggregates = new Map<string, MetadataForPage.StructureMetadata>()
    for (const element of Object.values(metadata)) {
      if (element.type === 'RootAggregate') {
        rootAggregates.set(element.uniqueId, element)
      }
    }
    return { metadata, rootAggregates }
  }, [])

  // 選択されているルート集約のID
  const [selectedRootAggregateId, setSelectedRootAggregateId] = React.useState<string | null>(null)

  // 右側ペインに表示するビュー
  const detailPaneProps = React.useMemo((): RootAggregateViewProps => ({
    autoGenerated,
    selectedRootAggregateId,
  }), [autoGenerated, selectedRootAggregateId])

  return (
    <Allotment
      proportionalLayout={false}
      className={`relative flex flex-col ${className ?? ''}`}
    >
      <Allotment.Pane
        minSize={40}
        priority={LayoutPriority.High}
      >
        <SchemaGraph
          onSelectedRootAggregateChange={setSelectedRootAggregateId}
          className="h-full w-full"
        />
      </Allotment.Pane>

      <Allotment.Pane minSize={40}>
        <RootAggregateView {...detailPaneProps} />
      </Allotment.Pane>
    </Allotment>
  )
}
