import React from "react"
import { CommandModelType } from "../__autoGenerated"
import { MetadataContext } from "./MetadataContext"
import CommandModelView from "./RootAggregateView.Command"

export type RootAggregateViewProps = {
  selectedRootAggregateId: string | null
}

/**
 * ルート集約のビュー
 */
export default function (props: RootAggregateViewProps) {

  const { rootAggregatesByUniqueId } = React.useContext(MetadataContext)

  // ルート集約が選択されていない
  if (!props.selectedRootAggregateId) return null
  const [rootAggregatePhysicalName, rootAggregate] = rootAggregatesByUniqueId.get(props.selectedRootAggregateId) ?? []
  if (!rootAggregate) return null

  // Data Model
  if (rootAggregate.model === 'data-model') {
    return (
      <div>
        TODO: ここに {rootAggregate.displayName} のダミーデータ編集機能を表示
      </div>
    )
  }

  // Query Model
  if (rootAggregate.model === 'query-model') {
    return (
      <div>
        TODO: ここに {rootAggregate.displayName} の検索機能を表示
      </div>
    )
  }

  // Command Model
  if (rootAggregate.model === 'command-model') {
    return (
      <CommandModelView
        rootAggregateType={rootAggregatePhysicalName as CommandModelType}
      />
    )
  }

  // Structure Model
  if (rootAggregate.model === 'structure-model') {
    return (
      <div>
        {rootAggregate.displayName}
      </div>
    )
  }

  // 上記以外はグラフに表示されない
  return null
}