import React from "react"
import { Allotment, LayoutPriority } from "allotment"
import { QueryModelType, SearchCondition, DisplayData, LoadFeature } from "../__autoGenerated"
import { DynamicForm, DynamicFormRef } from "@nijo/ui-components/layout"
import buildDynamicFormSchema from "./buildDynamicFormSchema"
import { MetadataContext } from "./MetadataContext"
import { MetadataForPage } from "../__autoGenerated/util"
import { useHttpRequest } from "../util"

/**
 * Query Model のWeb側エンドポイントの呼び出しと結果の閲覧を行なうデバッグ用コンポーネント。
 */
export default function ({ rootAggregateType, className }: {
  rootAggregateType: QueryModelType
  className?: string
}) {

  const helper = React.useContext(MetadataContext)
  const { complexPost } = useHttpRequest()
  const searchConditionFormRef = React.useRef<DynamicFormRef>(null)

  // 検索結果の状態
  type TDisplayData = DisplayData.TypeMap[typeof rootAggregateType]
  const [searchResults, setSearchResults] = React.useState<TDisplayData[]>([])
  const [isLoading, setIsLoading] = React.useState(false)
  const [error, setError] = React.useState<string | null>(null)

  // 自動生成されたメタデータをもとにした検索条件の入力フォーム定義
  const searchConditionFormSchema = React.useMemo(() => {
    const searchConditionMetadata = helper.metadata[rootAggregateType]
    if (!searchConditionMetadata) throw new Error(`${rootAggregateType}SearchCondition が見つかりません`)
    return buildDynamicFormSchema(searchConditionMetadata, 'query-model', true, helper)
  }, [rootAggregateType, helper])

  // 自動生成されたメタデータをもとにした検索結果の表示フォーム定義
  const displayDataFormSchema = React.useMemo(() => {
    const displayDataMetadata = helper.metadata[rootAggregateType]
    if (!displayDataMetadata) throw new Error(`${rootAggregateType}DisplayData が見つかりません`)
    return buildDynamicFormSchema(displayDataMetadata, 'query-model', false, helper)
  }, [rootAggregateType, helper])

  // 検索実行
  const executeSearch = React.useCallback(async () => {
    setIsLoading(true)
    setError(null)
    try {
      const searchCondition = searchConditionFormRef.current?.useFormReturn?.getValues()
      if (!searchCondition) {
        console.error("検索条件が取得できませんでした")
        setSearchResults([])
        return
      }
      const response = await complexPost<LoadFeature.ReturnType[typeof rootAggregateType]>(
        LoadFeature.Endpoint[rootAggregateType],
        searchCondition,
      )
      if (response) {
        setSearchResults(response.currentPageItems)
      } else {
        console.error("検索結果が取得できませんでした")
        setSearchResults([])
      }
    } catch (err) {
      console.error("検索でエラーが発生しました:", err)
      setError("検索でエラーが発生しました")
      setSearchResults([])
    } finally {
      setIsLoading(false)
    }
  }, [rootAggregateType, complexPost])

  return (
    <Allotment
      vertical
      separator={false}
      proportionalLayout={false}
      className={className}
    >

      {/* 検索条件 */}
      <Allotment.Pane priority={LayoutPriority.Low}>
        <div className="h-full w-full flex flex-col gap-1">
          <h2 className="font-bold select-none">
            {rootAggregateType} - 検索条件
          </h2>
          <div className="flex-1 overflow-y-auto bg-gray-100 p-1 border border-gray-300">
            <DynamicForm
              ref={searchConditionFormRef}
              root={searchConditionFormSchema}
            />
          </div>
        </div>
      </Allotment.Pane>

      {/* 検索結果 */}
      <Allotment.Pane className="pt-4">
        <div className="h-full w-full flex flex-col gap-1">
          <h2 className="font-bold select-none">
            <div className="flex items-center justify-between">
              <div className="flex gap-2">
                <button
                  type="button"
                  onClick={executeSearch}
                  disabled={isLoading}
                  className="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600 disabled:opacity-50"
                >
                  {isLoading ? "検索中..." : "検索実行"}
                </button>
                <button
                  type="button"
                  onClick={() => {
                    setSearchResults([])
                    setError(null)
                  }}
                  className="px-4 py-2 bg-gray-500 text-white rounded hover:bg-gray-600"
                >
                  リセット
                </button>
              </div>
              <div>
                {searchResults.length > 0 && `(${searchResults.length}件)`}
              </div>
            </div>
          </h2>
          <div className="flex-1 overflow-y-auto bg-gray-100 p-1 border border-gray-300">
            {error && (
              <div className="text-red-500 bg-red-50 p-2 rounded mb-4">
                {error}
              </div>
            )}
            {searchResults.length === 0 ? (
              <div className="text-gray-500 text-center py-8">
                {isLoading ? "検索中..." : "検索結果がありません"}
              </div>
            ) : (
              <div className="space-y-4">
                {searchResults.map((result, index) => (
                  <div key={index} className="bg-white p-2 rounded border">
                    <h3 className="font-semibold mb-2">検索結果 {index + 1}</h3>
                    <DynamicForm
                      root={displayDataFormSchema}
                      defaultValues={result}
                    />
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      </Allotment.Pane>
    </Allotment>
  )
}
