import { MetadataForPage } from "../../__autoGenerated/util"
import { ValueMember } from "@nijo/ui-components/layout/DynamicForm"
import { AutoFormatTextBox } from "./AutoFormatTextBox"
import { AutoResizeTextarea } from "./AutoResizeTextarea"

/** nijo.xml で指定可能な値メンバーの型の一覧 */
export type AllValueMemberType = Exclude<MetadataForPage.ValueMetadata['type'], undefined>

/** 既定のUIモジュールの型 */
export type DefaultUiModule = Pick<ValueMember, 'contents' | 'getGridColumnDef'>

/** デフォルトの値メンバーのレンダリングコンポーネント */
export default {

  // 単語型
  word: {
    contents: ({ useFormReturn: { register }, name }) => (
      <AutoFormatTextBox
        {...register(name)}
      />
    ),
    getGridColumnDef: ({ member, cellType }) => cellType.text(
      member.physicalName ?? '',
      typeof member.label === 'string' ? member.label : '', {
      defaultWidth: 150,
    }),
  },

  // 整数型
  int: {
    contents: ({ useFormReturn: { register }, name }) => (
      <input
        type="number"
        {...register(name, { valueAsNumber: true })}
        className="border border-gray-300 px-2 py-1 rounded"
        placeholder="数値を入力してください"
      />
    ),
    getGridColumnDef: ({ member, cellType }) => cellType.number(
      member.physicalName ?? '',
      typeof member.label === 'string' ? member.label : '', {
      defaultWidth: 120,
    }),
  },

  // 日時型
  datetime: {
    contents: ({ useFormReturn: { register }, name }) => (
      <input
        type="datetime-local"
        {...register(name)}
        className="border border-gray-300 px-2 py-1 rounded"
      />
    ),
    getGridColumnDef: ({ member, cellType }) => cellType.date(
      member.physicalName ?? '',
      typeof member.label === 'string' ? member.label : '', {
      defaultWidth: 180,
    }),
  },

  // 日付型
  date: {
    contents: ({ useFormReturn: { register }, name }) => (
      <input
        type="date"
        {...register(name)}
        className="border border-gray-300 px-2 py-1 rounded"
      />
    ),
    getGridColumnDef: ({ member, cellType }) => cellType.date(
      member.physicalName ?? '',
      typeof member.label === 'string' ? member.label : '', {
      defaultWidth: 140,
    }),
  },

  // 年月型
  yearmonth: {
    contents: ({ useFormReturn: { register }, name }) => (
      <input
        type="month"
        {...register(name)}
        className="border border-gray-300 px-2 py-1 rounded"
      />
    ),
    getGridColumnDef: ({ member, cellType }) => cellType.text(
      member.physicalName ?? '',
      typeof member.label === 'string' ? member.label : '', {
      defaultWidth: 120,
    }),
  },

  // 年型
  year: {
    contents: ({ useFormReturn: { register }, name }) => (
      <input
        type="number"
        {...register(name, { valueAsNumber: true })}
        className="border border-gray-300 px-2 py-1 rounded"
        placeholder="年を入力してください"
        min="1900"
        max="2100"
      />
    ),
    getGridColumnDef: ({ member, cellType }) => cellType.number(
      member.physicalName ?? '',
      typeof member.label === 'string' ? member.label : '', {
      defaultWidth: 100,
    }),
  },

  // 説明文型
  description: {
    contents: ({ useFormReturn: { register }, name }) => (
      <AutoResizeTextarea
        {...register(name)}
        placeholder="説明を入力してください"
        className="w-full"
      />
    ),
    getGridColumnDef: ({ member, cellType }) => cellType.text(
      member.physicalName ?? '',
      typeof member.label === 'string' ? member.label : '', {
      defaultWidth: 200,
      editorOverflow: 'vertical',
    }),
  },

  // 小数型
  decimal: {
    contents: ({ useFormReturn: { register }, name }) => (
      <input
        type="number"
        step="0.01"
        {...register(name, { valueAsNumber: true })}
        className="border border-gray-300 px-2 py-1 rounded"
        placeholder="小数を入力してください"
      />
    ),
    getGridColumnDef: ({ member, cellType }) => cellType.number(
      member.physicalName ?? '',
      typeof member.label === 'string' ? member.label : '', {
      defaultWidth: 120,
    }),
  },

  // 真偽値型
  bool: {
    contents: ({ useFormReturn: { register }, name }) => (
      <label className="flex items-center gap-2">
        <input
          type="checkbox"
          {...register(name)}
          className="rounded"
        />
        <span>はい</span>
      </label>
    ),
    getGridColumnDef: ({ member, cellType }) => cellType.boolean(
      member.physicalName ?? '',
      typeof member.label === 'string' ? member.label : '', {
      defaultWidth: 80,
    }),
  },

  // バイト配列型
  bytearray: {
    contents: ({ useFormReturn: { register }, name }) => (
      <input
        type="file"
        {...register(name)}
        className="border border-gray-300 px-2 py-1 rounded"
      />
    ),
    getGridColumnDef: ({ member, cellType }) => cellType.other(
      typeof member.label === 'string' ? member.label : '', {
      defaultWidth: 150,
      renderCell: (context) => {
        const value = context.cell.getValue()
        return (
          <span className="text-sm text-gray-600">
            {value ? 'ファイルが選択されています' : 'ファイルなし'}
          </span>
        )
      },
    }),
  },

} satisfies {
  [key in AllValueMemberType]: DefaultUiModule
}
