using Nijo.CodeGenerating;
using Nijo.ImmutableSchema;
using Nijo.Models.QueryModelModules;
using Nijo.Parts.CSharp;
using Nijo.SchemaParsing;
using Nijo.Util.DotnetEx;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Nijo.Models.QueryModelModules {
    /// <summary>
    /// QueryModelの検索結果型。
    /// SQLのSELECT句の形と対応する。
    /// EFCoreによるWhere句の付加が可能。
    /// <see cref="DisplayData"/> が持つ項目は全て検索結果型にも存在する。
    ///
    /// <para>
    /// 検索条件のプロパティはChildやRefといった親と1対1のリレーションについては
    /// DisplayData等のネストされたオブジェクトではなく"_"で接続されたフラットな構造になる（以下例）。
    /// こうなっている理由は、もしパフォーマンスに問題が出た場合に、EFCoreのLINQ to Entity からSQLへ実装を変更しやすい余地を残すため。
    /// <code>
    /// // DisplayDataなどのネストされたオブジェクトにおける親と1対1対応のオブジェクトの構造
    /// var displayData = new なんらかのDisplayData {
    ///     親のID = "xxx",
    ///     子 = new() {
    ///         子のID = "xxx",
    ///     },
    /// };
    ///
    /// // SearchResultにおける親と1対1対応のオブジェクトの構造
    /// var searchResult = new なんらかのSearchResult {
    ///     親のID = "xxx",
    ///     子_子のID = "xxx",
    /// };
    /// </code>
    ///
    /// 各構造ごとの詳細なルールは以下。
    ///
    /// * ValueMember: 親集約のプロパティとして定義される。
    /// * Child: 親と別のクラスとしてではなく、 `(親のインスタンス).(Childの物理名)_(ValueMemberの物理名)` という風にアンダースコアつながりで親の直下のメンバーとして生成される。
    /// * Children: 親と別のクラスとして定義される。プロパティのパスは、Childrenが起点となる。
    /// * Ref:
    ///   * 参照先のSearchConditionのすべてのメンバーは、参照元のSearchConditionクラスのメンバーとして現れる。
    ///   * Childと同様に、参照元集約直下のプロパティとして定義される。
    ///   * 参照先がルート集約ではなく子孫集約の場合、参照元の親集約のメンバーも参照元クラスに定義される。
    ///   * 参照先がChildrenを持つ場合、参照元にChildrenがある場合と同様に、別のクラスとして定義される。アンダースコアのパスは当該参照先のChildrenが起点となる。
    ///   * 参照先が子孫集約の場合、親への参照がParentという名前で表れる。
    /// </para>
    /// </summary>
    internal class SearchResult : IInstancePropertyOwnerMetadata, IEFCoreEntity {

        // Childは親の一部としてレンダリングされるので定義できない
        internal SearchResult(RootAggregate aggregate) {
            Aggregate = aggregate;
        }
        protected SearchResult(ChildrenAggregate children) {
            Aggregate = children;
        }
        public AggregateBase Aggregate { get; }

        /// <summary>この検索結果クラスと対応するEFCoreのエンティティが存在するかどうか</summary>
        internal bool MapToEFCoreEntity => Aggregate.GetRoot().IsView;

        /// <summary>楽観排他制御用のバージョン</summary>
        internal const string VERSION = "Version";

        /// <summary>
        /// 楽観排他用のバージョンを持つかどうか。
        /// ビューの場合はスキーマ定義で定義された属性がすべてのため暗黙的なバージョニング列は持たない
        /// </summary>
        public bool HasVersionColumn => !Aggregate.GetRoot().IsView && Aggregate is RootAggregate;
        public bool HasTimestampColumns => false;

        public string CsClassName => $"{Aggregate.PhysicalName}SearchResult";

        public string DbSetName => MapToEFCoreEntity
            ? $"{Aggregate.PhysicalName}DbSet"
            : throw new InvalidOperationException("ビューにマッピングされないSearchResultにDbSetは存在しない");

        public string OnModelCreatingAutoGenerated => MapToEFCoreEntity
            ? $"AutoGeneratedFluentApi{Aggregate.PhysicalName}"
            : throw new InvalidOperationException("ビューにマッピングされないSearchResultにOnModelCreatingは存在しない");


        public IEnumerable<EFCoreEntity.EFCoreEntityColumn> GetColumns() {
            if (!MapToEFCoreEntity) throw new InvalidOperationException("ビューにマッピングされないのにこのメソッドが呼ばれるのはおかしい");

            return GetMembers()
                .OfType<SearchResultValueMember>()
                .Select(vm => vm.ToEFCoreEntityColumn());
        }

        public IEnumerable<NavigationProperty> GetNavigationProperties() {
            return GetMembers()
                .Select(m => m.NavigationProperty)
                .Where(nav => nav != null)
                .Cast<NavigationProperty>();
        }

        /// <summary>
        /// この検索結果型が持つメンバーを列挙。
        /// ビューにマッピングされないDTOの場合の子配列、およびナビゲーションプロパティを含む。
        /// </summary>
        internal IEnumerable<ISearchResultMember> GetMembers() {
            var entryIsView = Aggregate.GetRoot().IsView;
            return GetMembersRecursively(Aggregate, false, null);

            IEnumerable<ISearchResultMember> GetMembersRecursively(AggregateBase aggregate, bool isOutOfEntryTree, RefToMember? refToMember) {
                // ビューにマッピングされる場合、親のキーを列挙する(JOIN用)
                if (!isOutOfEntryTree && aggregate.GetRoot().IsView) {
                    var parent = aggregate.GetParent();
                    if (parent != null) {
                        // 親のキー（祖先のキーも含む）を列挙
                        // parent.GetKeyVMs() は既に祖先のキーも含んでいるため、再帰的に辿る必要はない
                        foreach (var vm in parent.GetKeyVMs()) {
                            yield return new SearchResultValueMember(vm, false, parentKeyPath: ["Parent"]);
                        }

                        // 子から親へのナビゲーションプロパティ
                        var navOfParentChild = new NavigationProperty.NavigationOfParentChild(parent, aggregate);
                        // aggregateは必ずChildAggregateまたはChildrenAggregateのいずれか(RootAggregateには親がないため)
                        var aggregateAsMember = (IAggregateMember)aggregate;
                        yield return new SearchResultParentOrRefMember(navOfParentChild, aggregateAsMember);
                    }
                }

                // aggregateが参照先の場合は親のメンバーも列挙
                if (isOutOfEntryTree) {
                    var parent = aggregate.GetParent();
                    if (parent != null && aggregate.PreviousNode != (ISchemaPathNode)parent) {
                        foreach (var srm in GetMembersRecursively(parent, true, refToMember)) {
                            yield return srm;
                        }
                    }
                }

                // 自身のメンバーを列挙
                foreach (var member in aggregate.GetMembers()) {
                    if (member is ValueMember vm) {
                        // 検索条件にのみ定義されるメンバーは除外
                        if (vm.OnlySearchCondition) continue;

                        // 参照先の直接のキーメンバーの場合のみrefToMemberを渡す
                        // （参照先の子要素やRefToMemberのキーは、外部キーではなく単なる属性として展開されるだけ）
                        var refToForThisMember = (refToMember != null && vm.IsKey && vm.Owner == refToMember.RefTo) ? refToMember : null;
                        yield return new SearchResultValueMember(vm, isOutOfEntryTree, refToMember: refToForThisMember);

                    } else if (member is ChildrenAggregate children) {
                        // aggregateが参照先の場合、かつ子から親へ辿られたとき、循環参照を防ぐ
                        if (aggregate.PreviousNode == (ISchemaPathNode)children) continue;

                        // 参照先のChildrenは、コンフィグで明示的に指定されていない場合は生成しない
                        if (isOutOfEntryTree && !CodeRenderingContext.CurrentContext.Config.GenerateRefToChildrenDisplayData) continue;

                        yield return new SearchResultChildrenMember(children, isOutOfEntryTree);

                    } else if (member is ChildAggregate child) {
                        // aggregateが参照先の場合、かつ子から親へ辿られたとき、循環参照を防ぐ
                        if (aggregate.PreviousNode == (ISchemaPathNode)child) continue;

                        foreach (var srm in GetMembersRecursively(child, isOutOfEntryTree, refToMember)) {
                            yield return srm;
                        }

                    } else if (member is RefToMember refTo) {
                        // aggregateが参照先の場合、かつ子から親へ辿られたとき、循環参照を防ぐ
                        if (aggregate.PreviousNode == (ISchemaPathNode)refTo) continue;

                        // RefToMemberに対するナビゲーションプロパティ(ビューにマッピングされる場合のみ)
                        if (!isOutOfEntryTree && aggregate.GetRoot().IsView) {
                            var navOfRef = new NavigationProperty.NavigationOfRef(refTo);
                            yield return new SearchResultParentOrRefMember(navOfRef, refTo);
                        }

                        // 参照先を再帰的に辿る。
                        // SearchResultからの直接の参照の場合（refToMemberがnull）は、このrefToを渡す。
                        // 参照先のさらに参照先の場合（refToMemberが設定済み）は、さらに先の参照にはnullを渡す。
                        var refToMemberForRecursion = refToMember == null ? refTo : null;
                        foreach (var srm in GetMembersRecursively(refTo.RefTo, true, refToMember: refToMemberForRecursion)) {
                            yield return srm;
                        }

                    } else {
                        throw new InvalidOperationException($"予期しないメンバー: {member}");
                    }
                }

                // ビューにマッピングされる場合、被参照（RefFrom）のナビゲーションプロパティを列挙
                if (entryIsView) {
                    foreach (var refFrom in Aggregate.GetRefFroms()) {
                        // DBの実体をもたないクエリモデルやコマンドモデルから参照された場合はナビゲーションプロパティを張らない
                        var refFromRoot = refFrom.Owner.GetRoot();
                        var hasDbEntity = refFromRoot.Model is DataModel
                                       || refFromRoot.Model is QueryModel
                                       && refFromRoot.IsView;

                        if (hasDbEntity) {
                            yield return new SearchResultRefFromMember(refFrom);
                        }
                    }
                }
            }
        }

        /// <summary>
        /// このツリーに含まれるルートと子配列を列挙
        /// </summary>
        internal IEnumerable<SearchResult> EnumerateThisAndChildren() {
            if (Aggregate is not RootAggregate) throw new InvalidOperationException("このメソッドはルート集約でのみ呼び出せます");

            var searchResultTree = Aggregate
                .EnumerateThisAndDescendants()
                .Where(agg => agg is RootAggregate || agg is ChildrenAggregate)
                .Select(agg => agg switch {
                    RootAggregate root => new SearchResult(root),
                    ChildrenAggregate children => new SearchResultChildrenMember(children, false),
                    _ => throw new InvalidOperationException(),
                });
            return searchResultTree;
        }

        IEnumerable<IInstancePropertyMetadata> IInstancePropertyOwnerMetadata.GetMembers() {
            foreach (var m in GetMembers()) {
                if (m is SearchResultParentOrRefMember) {
                    // 親や参照先のナビゲーションプロパティは OnModelCreating で明示的に参照する場合だけ使うので列挙しない
                    // ※ ここでナビゲーションプロパティを返すと StackOverflow が発生したがそれを解決する理由が無い
                } else {
                    yield return m;
                }
            }
        }

        internal string RenderTree(CodeRenderingContext ctx) {
            if (Aggregate is not RootAggregate root) {
                throw new InvalidOperationException("このメソッドはルート集約でのみ呼び出せます");
            }

            var tree = EnumerateThisAndChildren().ToArray();

            return $$"""
                #region 検索クエリ型
                {{tree.SelectTextTemplate(sr => $$"""
                {{RenderAggregate(sr)}}
                """)}}
                #endregion 検索クエリ型
                {{If(root.IsView, () => $$"""


                #region Entity Framework Core エンティティ定義
                partial class {{ApplicationConfigure.ABSTRACT_CLASS_CORE}} {
                {{tree.SelectTextTemplate(sr => $$"""
                    {{WithIndent(EFCoreOnModelCreating.RenderOnModelCreating(sr, ctx), "    ")}}
                """)}}
                {{tree.SelectTextTemplate(sr => $$"""
                    {{WithIndent(EFCoreOnModelCreating.RenderConfigureAbstractMethod(sr), "    ")}}
                """)}}
                }
                #endregion Entity Framework Core エンティティ定義
                """)}}
                """;

            static string RenderAggregate(SearchResult sr) {
                // 視認性のために親と参照先のナビゲーションプロパティを後ろに持っていく
                var orderedMembers = sr
                    .GetMembers()
                    .Select((m, i) => new { Member = m, Index = i })
                    .OrderBy(x => x.Member is not SearchResultParentOrRefMember ? 0 : 1)
                    .ThenBy(x => x.Index)
                    .Select(x => x.Member);

                return $$"""
                    /// <summary>
                    /// {{sr.Aggregate.DisplayName}}の検索結果型。
                    /// SQLのSELECT句の形と対応する。
                    /// </summary>
                    public partial class {{sr.CsClassName}} {
                    {{orderedMembers.SelectTextTemplate(srm => $$"""
                        {{WithIndent(srm.RenderDeclaration(), "    ")}}
                    """)}}
                    {{If(sr.HasVersionColumn, () => $$"""
                        /// <summary>
                        /// 楽観排他制御用のバージョン。
                        /// null許容でないのは、データベース上に存在する時点で必ずバージョンも存在するため。
                        /// </summary>
                        public int {{VERSION}} { get; set; }
                    """)}}
                    }
                    """;
            }
        }


        /// <summary>
        /// 子孫要素をIncludeする式をレンダリングします。
        /// また、 1:N のリレーションが複数登場する場合、パフォーマンスに問題が出るのを防ぐため
        /// AsSplitQuery() を呼び出すようにします。
        /// </summary>
        internal IEnumerable<string> RenderInclude() {
            var descendants = Aggregate.EnumerateDescendants().ToArray();

            // 1:N のリレーションが2個以上存在する場合は AsSplitQuery() を追加
            if (descendants.Count(agg => agg is ChildrenAggregate) >= 2) {
                yield return ".AsSplitQuery() // パフォーマンスの問題を防ぐため、テーブル毎に個別にSQLを発行して取得する";
            }

            foreach (var agg in descendants) {
                var fullPath = agg.GetPathFromEntry().Skip(1).ToArray();

                for (int i = 0; i < fullPath.Length; i++) {
                    var parent = (AggregateBase?)fullPath[i].PreviousNode ?? throw new InvalidOperationException("ありえない");
                    var child = (AggregateBase?)fullPath[i] ?? throw new InvalidOperationException("ありえない");
                    var nav = new NavigationProperty.NavigationOfParentChild(parent, child);

                    yield return i == 0
                        ? $".Include(e => e!.{nav.Principal.OtherSidePhysicalName})"      // クエリのエンティティ直下の場合はInclude
                        : $".ThenInclude(e => e!.{nav.Principal.OtherSidePhysicalName})"; // クエリのエンティティ直下でない場合はThenInclude
                }
            }
        }


        #region メンバー
        internal interface ISearchResultMember : IInstancePropertyMetadata {
            bool IsOutOfEntryTree { get; }
            IAggregateMember Member { get; }
            string RenderDeclaration();
            NavigationProperty? NavigationProperty { get; }
            ISchemaPathNode IInstancePropertyMetadata.SchemaPathNode => Member;

            /// <summary>
            /// プロパティ名の計算。
            /// 詳細なルールはこのクラスのXMLコメントを参照。
            /// </summary>
            internal string GetPhysicalName(bool forDbName = false) {
                var list = new List<string>();
                var previousOfPrevious = (ISchemaPathNode?)null;
                var isLastNode = false;
                var nodes = Member.GetPathFromEntry().ToArray();

                for (int i = 0; i < nodes.Length; i++) {
                    var node = nodes[i];
                    isLastNode = (i == nodes.Length - 1);

                    // エントリーを除外
                    if (node.PreviousNode == null) {
                        previousOfPrevious = node.PreviousNode;
                        continue;
                    }

                    // Childrenはその親とは別のクラスのためアンダースコアによるパス結合をクリア
                    if (node.PreviousNode is ChildrenAggregate
                        // 親から子に向かって辿った場合のみクリア（参照先の場合は子から親に辿ることがある）
                        && previousOfPrevious?.XElement == node.PreviousNode.XElement.GetParentWithoutMemo()) {
                        list.Clear();
                    }

                    // Refの名前はこの1つ前で列挙済みのためスキップ
                    if (node.PreviousNode is RefToMember) {
                        previousOfPrevious = node.PreviousNode;
                        continue;
                    }

                    // 参照先のメンバーで子から親に辿る場合は "Parent" という名前になる
                    if (node.XElement == node.PreviousNode.XElement.GetParentWithoutMemo()) {
                        list.Add("Parent");
                    } else {
                        if (forDbName && isLastNode && node is ValueMember vm) {
                            // 最後のノード（ValueMember自身）かつDbName計算の場合は、スキーマ定義のDbNameを使用
                            list.Add(vm.DbName);
                        } else if (forDbName && node is RefToMember refto) {
                            // 物理名の途中経路に付されるRefToMemberの場合もDbNameを使用
                            list.Add(refto.DbName);
                        } else {
                            list.Add(node.XElement.Name.LocalName);
                        }
                    }

                    previousOfPrevious = node.PreviousNode;
                }
                return list.Join("_");
            }
        }

        internal class SearchResultValueMember : ISearchResultMember, IInstanceValuePropertyMetadata {
            internal SearchResultValueMember(ValueMember valueMember, bool isOutOfEntryTree, string[]? parentKeyPath = null, RefToMember? refToMember = null) {
                ValueMember = valueMember;
                IsOutOfEntryTree = isOutOfEntryTree;
                ParentKeyPath = parentKeyPath;
                RefToMember = refToMember;
            }
            internal ValueMember ValueMember { get; }
            private string? _physicalName;

            public bool IsOutOfEntryTree { get; }

            /// <summary>親のキーである場合のパス。例: ["Parent"] または ["Parent", "Parent"]</summary>
            internal string[]? ParentKeyPath { get; }

            /// <summary>
            /// 参照先のキーである場合の RefToMember。
            /// 参照自体がキーである場合のみ設定される（参照先の参照先のキーなどには設定されない）。
            /// </summary>
            internal RefToMember? RefToMember { get; }

            NavigationProperty? ISearchResultMember.NavigationProperty => null;

            public string GetPropertyName(E_CsTs csts) => _physicalName ??= ((ISearchResultMember)this).GetPhysicalName();
            IValueMemberType IInstanceValuePropertyMetadata.Type => ValueMember.Type;
            IAggregateMember ISearchResultMember.Member => ValueMember;

            string ISearchResultMember.RenderDeclaration() {
                var type = ValueMember.Type.CsPrimitiveTypeName;

                return $$"""
                    /// <summary>{{ValueMember.DisplayName}}</summary>
                    public {{type}}? {{GetPropertyName(E_CsTs.CSharp)}} { get; set; }
                    """;
            }

            /// <summary>
            /// EFCoreのカラム定義に変換。ビューにマッピングされる場合のみ有効。
            /// </summary>
            internal EFCoreEntity.EFCoreEntityColumn ToEFCoreEntityColumn() {
                var physicalName = GetPropertyName(E_CsTs.CSharp);
                var dbName = ((ISearchResultMember)this).GetPhysicalName(true);

                // 親のキーの場合
                if (ParentKeyPath != null) {
                    return new EFCoreEntity.ParentKeyMember(ValueMember, physicalName, dbName);
                }
                // 参照先のキーの場合（参照自体がキーである場合のみ外部キーとして扱う）
                else if (RefToMember != null) {
                    return new EFCoreEntity.RefKeyMember(
                        RefToMember,
                        ValueMember,
                        physicalName,
                        dbName,
                        isParentKey: false);
                }
                // 通常のメンバー（参照先から展開された属性を含む）
                else {
                    // 参照先から展開された属性（RefToMemberがnullだが、isOutOfEntryTreeがtrue）の場合、
                    // その属性が元々キーであってもこのビューではキーにしない
                    var isKey = IsOutOfEntryTree ? false : (bool?)null;
                    return new EFCoreEntity.OwnColumnMember(
                        ValueMember,
                        physicalName: physicalName,
                        dbName: dbName,
                        isKey: isKey);
                }
            }
        }

        internal class SearchResultChildrenMember : SearchResult, ISearchResultMember, IInstanceStructurePropertyMetadata {
            internal SearchResultChildrenMember(ChildrenAggregate children, bool isOutOfEntryTree) : base(children) {
                Aggregate = children;
                IsOutOfEntryTree = isOutOfEntryTree;
            }
            internal new ChildrenAggregate Aggregate { get; }
            private string? _physicalName;

            public bool IsOutOfEntryTree { get; }

            NavigationProperty? ISearchResultMember.NavigationProperty => MapToEFCoreEntity
                ? new NavigationProperty.NavigationOfParentChild(Aggregate.GetParent() ?? throw new InvalidOperationException($"{Aggregate.DisplayName}の親が無い"), Aggregate)
                : null;

            public string GetPropertyName(E_CsTs csts) => _physicalName ??= ((ISearchResultMember)this).GetPhysicalName();
            bool IInstanceStructurePropertyMetadata.IsArray => true;
            string IInstanceStructurePropertyMetadata.GetTypeName(E_CsTs csts) => CsClassName;
            IAggregateMember ISearchResultMember.Member => Aggregate;

            string ISearchResultMember.RenderDeclaration() {
                // ビューにマッピングされない場合はただのリスト、
                // ビューにマッピングされる場合はナビゲーションプロパティ
                if (MapToEFCoreEntity) {
                    var parent = Aggregate.GetParent() ?? throw new InvalidOperationException($"{Aggregate.DisplayName}の親が無い");
                    var nav = new NavigationProperty.NavigationOfParentChild(parent, Aggregate);
                    var p = nav.Principal;

                    return $$"""
                        /// <summary>{{Aggregate.DisplayName}}</summary>
                        public virtual {{p.GetOtherSideCsTypeName(true)}} {{p.OtherSidePhysicalName}} { get; set; }{{p.GetInitializerStatement()}}
                        """;

                } else {
                    return $$"""
                        /// <summary>{{Aggregate.DisplayName}}</summary>
                        public List<{{CsClassName}}> {{GetPropertyName(E_CsTs.CSharp)}} { get; set; } = new();
                        """;
                }
            }
        }

        /// <summary>
        /// この検索結果型を参照するほかの集約からのナビゲーションプロパティを表すメンバー。
        /// ビューにマッピングされる場合のみ存在する。
        /// </summary>
        internal class SearchResultRefFromMember : ISearchResultMember, IInstanceStructurePropertyMetadata {
            internal SearchResultRefFromMember(RefToMember refFrom) {
                RefFrom = refFrom;
                NavigationProperty = new NavigationProperty.NavigationOfRef(refFrom);
            }

            internal RefToMember RefFrom { get; }

            private string RefFromItemTypeName => NavigationProperty.Principal.GetOtherSideCsTypeName(true);

            public bool IsOutOfEntryTree => false;

            public NavigationProperty NavigationProperty { get; }

            IAggregateMember ISearchResultMember.Member => RefFrom;

            string IInstancePropertyMetadata.GetPropertyName(E_CsTs csts) {
                return NavigationProperty.Principal.OtherSidePhysicalName;
            }

            string ISearchResultMember.RenderDeclaration() {
                var side = NavigationProperty.Principal;
                var propName = side.OtherSidePhysicalName;
                var initializer = side.GetInitializerStatement();

                return $$"""
                    /// <summary>{{RefFrom.Owner.DisplayName}}</summary>
                    public virtual {{RefFromItemTypeName}} {{propName}} { get; set; }{{initializer}}
                    """;
            }


            bool IInstanceStructurePropertyMetadata.IsArray => true;
            string IInstanceStructurePropertyMetadata.GetTypeName(E_CsTs csts) => RefFromItemTypeName;
            IEnumerable<IInstancePropertyMetadata> IInstancePropertyOwnerMetadata.GetMembers() { yield break; }
        }

        /// <summary>
        /// 親またはRef先へのナビゲーションプロパティを表すメンバー。
        /// ビューにマッピングされる場合のみ存在する。
        /// </summary>
        internal class SearchResultParentOrRefMember : ISearchResultMember {
            internal SearchResultParentOrRefMember(NavigationProperty navigationProperty, IAggregateMember memberForSchemaPath) {
                NavigationProperty = navigationProperty;
                MemberForSchemaPath = memberForSchemaPath;
            }

            public bool IsOutOfEntryTree => false;

            NavigationProperty? ISearchResultMember.NavigationProperty => NavigationProperty;

            internal NavigationProperty NavigationProperty { get; }

            /// <summary>
            /// SchemaPathNodeとして機能するためのメンバー。
            /// 親へのナビゲーションの場合は子の集約自体、RefToMemberへのナビゲーションの場合はRefToMember自体。
            /// </summary>
            internal IAggregateMember MemberForSchemaPath { get; }

            IAggregateMember ISearchResultMember.Member => MemberForSchemaPath;

            string IInstancePropertyMetadata.GetPropertyName(E_CsTs csts) => NavigationProperty switch {
                NavigationProperty.NavigationOfParentChild parentChild => parentChild.Relevant.OtherSidePhysicalName,
                NavigationProperty.NavigationOfRef refNav => refNav.Relevant.OtherSidePhysicalName,
                _ => throw new InvalidOperationException(),
            };

            string ISearchResultMember.RenderDeclaration() {
                // ナビゲーションプロパティとしてレンダリング
                var side = NavigationProperty switch {
                    NavigationProperty.NavigationOfParentChild parentChild => parentChild.Relevant,
                    NavigationProperty.NavigationOfRef refNav => refNav.Relevant,
                    _ => throw new InvalidOperationException(),
                };

                var typeName = side.GetOtherSideCsTypeName(true);
                var propName = side.OtherSidePhysicalName;
                var initializer = side.GetInitializerStatement();

                return $$"""
                    /// <summary>{{MemberForSchemaPath.DisplayName}}</summary>
                    public virtual {{typeName}} {{propName}} { get; set; }{{initializer}}
                    """;
            }
        }
        #endregion メンバー
    }
}
