@echo off

set "PROJECT_ROOT=%~dp0..\..\demo\100_チャットアプリ"
set /p "OUT_DIR=出力先フォルダ名: "

if "%OUT_DIR%"=="" (
  exit /b
)

mkdir %OUT_DIR%

xcopy /I /S /E /Y "%PROJECT_ROOT%\Core.AutoGenerated\__AutoGenerated" %OUT_DIR%\CORE    >nul 
xcopy /I /S /E /Y "%PROJECT_ROOT%\client\src\__autoGenerated" %OUT_DIR%\CLIENT   >nul 
xcopy /I /S /E /Y "%PROJECT_ROOT%\UnitTest\__AutoGenerated"               %OUT_DIR%\TEST    >nul 
xcopy /I /S /E /Y "%PROJECT_ROOT%\WebApi\__AutoGenerated"             %OUT_DIR%\WEBAPI  >nul 
