@echo off

set "PROJECT_ROOT=%~dp0.."
set /p "OUT_DIR=�o�͐�t�H���_�����w�肵�Ă�������: "

if "%OUT_DIR%"=="" (
  exit /b
)

mkdir %OUT_DIR%

xcopy /I /S /E /Y "%PROJECT_ROOT%\Core.AutoGenerated\__AutoGenerated" %OUT_DIR%\CORE    >nul 
xcopy /I /S /E /Y "%PROJECT_ROOT%\react\package_nijo-client-sample\src\__autoGenerated" %OUT_DIR%\REACT   >nul 
xcopy /I /S /E /Y "%PROJECT_ROOT%\Test\__AutoGenerated"               %OUT_DIR%\TEST    >nul 
xcopy /I /S /E /Y "%PROJECT_ROOT%\WebApi\__AutoGenerated"             %OUT_DIR%\WEBAPI  >nul 
