using System;
using System.Linq;

namespace MyApp.UnitTest;

public class カテゴリ付き汎用参照の回帰テスト {

    [Test]
    public void 社員と係のコマンドはカテゴリ専用キー型を使う() {
        Assert.That(typeof(社員CreateCommand).GetProperty("契約種別")?.PropertyType, Is.EqualTo(typeof(汎用マスタ_契約種別Key)));
        Assert.That(typeof(社員UpdateCommand).GetProperty("契約種別")?.PropertyType, Is.EqualTo(typeof(汎用マスタ_契約種別Key)));

        Assert.That(typeof(係CreateCommand).GetProperty("勤怠管理区分")?.PropertyType, Is.EqualTo(typeof(汎用マスタ_勤怠管理区分Key)));
        Assert.That(typeof(係UpdateCommand).GetProperty("勤怠管理区分")?.PropertyType, Is.EqualTo(typeof(汎用マスタ_勤怠管理区分Key)));
    }

    [Test]
    public void カテゴリ専用キー型は非ハードコード主キーだけを持つ() {
        AssertCategoryKey(typeof(汎用マスタ_契約種別Key));
        AssertCategoryKey(typeof(汎用マスタ_勤怠管理区分Key));

        Assert.That(typeof(汎用マスタKey).GetProperty("汎用種別"), Is.Not.Null, "元の汎用マスタKey からはハードコード主キーを消してはいけません。");
        Assert.That(typeof(汎用マスタKey).GetProperty("区分値"), Is.Not.Null);
    }

    [Test]
    public void 参照元DbEntityはハードコード主キー列を持たない() {
        AssertRefColumns(typeof(社員DbEntity), valueColumnName: "契約種別_区分値", hardCodedColumnName: "契約種別_汎用種別");
        AssertRefColumns(typeof(係DbEntity), valueColumnName: "勤怠管理区分_区分値", hardCodedColumnName: "勤怠管理区分_汎用種別");
    }

    [Test]
    public void カテゴリビューとユーティリティは生成され続ける() {
        var utilType = typeof(汎用マスタUtil);

        Assert.That(utilType.GetProperty("契約区分")?.PropertyType, Is.EqualTo(typeof(汎用マスタUtilCategory<汎用マスタ_契約区分DbEntity>)));
        Assert.That(utilType.GetProperty("勤怠管理区分")?.PropertyType, Is.EqualTo(typeof(汎用マスタUtilCategory<汎用マスタ_勤怠管理区分DbEntity>)));

        Assert.That(typeof(AutoGeneratedDbContext).GetProperty("汎用マスタ_契約区分DbSet"), Is.Not.Null);
        Assert.That(typeof(AutoGeneratedDbContext).GetProperty("汎用マスタ_勤怠管理区分DbSet"), Is.Not.Null);
        Assert.That(typeof(汎用マスタ_契約区分DbEntity), Is.Not.Null);
        Assert.That(typeof(汎用マスタ_勤怠管理区分DbEntity), Is.Not.Null);
    }

    private static void AssertCategoryKey(Type type) {
        var publicInstanceProperties = type
            .GetProperties()
            .Where(property => property.GetMethod?.IsPublic == true)
            .Select(property => property.Name)
            .OrderBy(name => name)
            .ToArray();

        Assert.That(publicInstanceProperties, Is.EqualTo(new[] { "区分値" }), $"{type.Name} は区分値 だけを持つ想定です。");
        Assert.That(type.GetProperty("汎用種別"), Is.Null, $"{type.Name} にハードコード主キーが残っています。");
    }

    private static void AssertRefColumns(Type type, string valueColumnName, string hardCodedColumnName) {
        Assert.That(type.GetProperty(valueColumnName), Is.Not.Null, $"{type.Name} に {valueColumnName} がありません。");
        Assert.That(type.GetProperty(hardCodedColumnName), Is.Null, $"{type.Name} に {hardCodedColumnName} が残っています。");
    }
}
