-- Auto-generated by Management generate-general-lookup-views-sql
-- 汎用参照テーブルビュー再作成用SQL

DROP VIEW IF EXISTS [汎用マスタ_契約区分];

CREATE VIEW [汎用マスタ_契約区分] AS
SELECT t1.[区分値], t1.[表示名称]
FROM [汎用マスタ] t1
WHERE t1.[汎用種別] = '010';

DROP VIEW IF EXISTS [汎用マスタ_勤怠管理区分];

CREATE VIEW [汎用マスタ_勤怠管理区分] AS
SELECT t1.[区分値], t1.[表示名称]
FROM [汎用マスタ] t1
WHERE t1.[汎用種別] = '020';

