using Nijo.Core;
using Nijo.Util.DotnetEx;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Nijo.Util.CodeGenerating;

namespace Nijo.Parts.WebServer {
    internal class DbContextClass : ISummarizedFile {

        /// <summary>DbSet追加</summary>
        internal void AddDbSet(string className, string propName) {
            _dbSet.Add((className, propName));
        }
        private readonly List<(string ClassName, string PropName)> _dbSet = new();

        /// <summary>OnModelCreatingメソッドに生のソースを追加する。関数の引数はmodelBuilderの変数名。</summary>
        internal void AddOnModelCreating(Func<string, string> render) {
            _onModelCreating.Add(render);
        }
        private readonly List<Func<string, string>> _onModelCreating = new();

        /// <summary>
        /// プロパティの型のコンバータを登録する。
        /// 二重ループの処理をレンダリングことによるパフォーマンスの都合上、
        /// <see cref="AddOnModelCreating"/> とは別のメソッドになっている。
        /// </summary>
        /// <param name="className">変換対象の型の名前</param>
        /// <param name="configureClassMethodName">コンフィグクラスのメソッドの名前</param>
        internal void AddOnModelCreatingPropConverter(string className, string configureClassMethodName) {
            _onModelCreatingPropValueConverter.Add(className, configureClassMethodName);
        }
        private readonly Dictionary<string, string> _onModelCreatingPropValueConverter = new();

        void ISummarizedFile.OnEndGenerating(CodeRenderingContext context) {

            context.UseSummarizedFile<Configure>().AddMethod($$"""
                /// <summary>
                /// Entity Framework Core の定義にカスタマイズを加えます。
                /// 既定のモデル定義処理の一番最後に呼ばれます。
                /// データベース全体に対する設定を行うことを想定しています。（例えば、全テーブルの列挙体のDB保存される型を数値ではなく文字列にする、など）
                /// </summary>
                /// <param name="modelBuilder">モデルビルダー。Entity Framework Core 公式の解説を参照のこと。</param>
                public virtual void {{ON_DBCONTEXT_MODEL_CREATING}}(Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder) {
                }

                /// <summary>
                /// Entity Framework Core の <see cref="DbContext.ConfigureConventions(ModelConfigurationBuilder)"/> メソッドから呼ばれます。
                /// 主にC#の値とDBのカラムの値の変換処理を定義します。
                /// </summary>
                /// <param name="configurationBuilder"></param>
                public virtual void ConfigureConventions(ModelConfigurationBuilder configurationBuilder) {
                }
                """);

            context.CoreLibrary.AutoGeneratedDir(genDir => {
                genDir.Directory("EntityFramework", efDir => {
                    efDir.Generate(RenderDeclaring());
                    //efDir.Generate(RenderFactoryForMigration());
                    efDir.Generate(RenderLogEntity());
                });
            });
        }

        private SourceFile RenderDeclaring() => new SourceFile {
            FileName = $"EFCoreDbContext.cs",
            RenderContent = ctx => {
                var app = new ApplicationService();

                return $$"""
                    using Microsoft.EntityFrameworkCore;
                    using Microsoft.Extensions.Logging;

                    namespace {{ctx.Config.DbContextNamespace}} {

                        /// <summary>
                        /// DBコンテキスト。データベース全体と対応する抽象。
                        /// 詳しくは Entity Framework Core で調べてください。
                        /// </summary>
                        public partial class {{ctx.Config.DbContextName}} : DbContext {
                    #pragma warning disable CS8618 // DbSetはEFCore側で自動的に設定されるため問題なし
                            public {{ctx.Config.DbContextName}}(DbContextOptions<{{ctx.Config.DbContextName}}> options, {{Configure.ABSTRACT_CLASS_NAME}} nijoConfig, NLog.Logger logger) : base(options) {
                                _nijoConfig = nijoConfig;
                                _logger = logger;
                            }
                    #pragma warning restore CS8618 // DbSetはEFCore側で自動的に設定されるため問題なし

                            private readonly {{Configure.ABSTRACT_CLASS_NAME}} _nijoConfig;
                            private readonly NLog.Logger _logger;

                    {{_dbSet.SelectTextTemplate(dbSet => $$"""
                            public virtual DbSet<{{dbSet.ClassName}}> {{dbSet.PropName}} { get; set; }
                    """)}}

                            /// <summary>
                            /// ログテーブル。このDbSetを直に参照する使い方は想定されていない。
                            /// ログ出力はアプリケーションサービスのログプロパティ経由で行う想定
                            /// </summary>
                            public DbSet<LogEntity> LogEntity { get; set; }

                            /// <inheritdoc />
                            protected override void OnModelCreating(ModelBuilder modelBuilder) {
                                try {
                                    // 集約ごとのモデル定義
                    {{_onModelCreating.SelectTextTemplate(fn => $$"""
                                    {{WithIndent(fn("modelBuilder"), "                ")}}
                    """)}}

                                    // モデル定義に変更を加えたい場合は {{Configure.CONCRETE_CLASS_NAME}} クラスでこのメソッドをオーバーライドしてください。
                                    _nijoConfig.{{ON_DBCONTEXT_MODEL_CREATING}}(modelBuilder);

                                } catch (Exception ex) {
                                    _logger.Error(ex);
                                    throw;
                                }
                            }

                            /// <inheritdoc/>
                            protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder) {
                                _nijoConfig.ConfigureConventions(configurationBuilder);
                            }

                            /// <inheritdoc />
                            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) {
                                optionsBuilder.LogTo(sql => {
                                    _logger.Debug(sql);
                                    if (OutSqlToVisualStudio) {
                                        System.Diagnostics.Debug.WriteLine("---------------------");
                                        System.Diagnostics.Debug.WriteLine(sql);
                                    }
                                },
                                LogLevel.Information,
                                Microsoft.EntityFrameworkCore.Diagnostics.DbContextLoggerOptions.SingleLine);
                            }
                            /// <summary>デバッグ用</summary>
                            public static bool OutSqlToVisualStudio { get; set; } = false;
                        }

                    }
                    """;
            },
        };

        private SourceFile RenderFactoryForMigration() => new SourceFile {
            FileName = $"EFCoreDbContextFactoryForMigration.cs",
            RenderContent = ctx => {
                var app = new ApplicationService();

                return $$"""
                    using Microsoft.EntityFrameworkCore.Design;
                    using Microsoft.Extensions.DependencyInjection;
                    using System;
                    using System.Collections.Generic;
                    using System.Linq;
                    using System.Text;
                    using System.Threading.Tasks;
                    using Microsoft.Extensions.Configuration;

                    namespace {{ctx.Config.DbContextNamespace}} {
                        /// <summary>
                        /// DB定義更新スクリプト作成に関するコマンド `dotnet ef migrations add` の際に呼ばれるファクトリークラス
                        /// </summary>
                        internal class {{ctx.Config.DbContextName}}FactoryForMigration : IDesignTimeDbContextFactory<{{ctx.Config.DbContextName}}> {
                            public {{ctx.Config.DbContextName}} CreateDbContext(string[] args) {
                                var serviceCollection = new ServiceCollection();
                                new {{Configure.CONCRETE_CLASS_NAME}}().{{Configure.CONFIGURE_SERVICES}}(serviceCollection);

                                // webapiプロジェクト追加のappsettings.jsonを参照して構成する
                                var builder = new ConfigurationBuilder()
                                    .SetBasePath(Path.Combine(Directory.GetCurrentDirectory(), "..", "webapi"))
                                    .AddJsonFile("appsettings.json", optional: true, reloadOnChange: false)
                                    .AddJsonFile("appsettings.Development.json", optional: true, reloadOnChange: false); // 後にAddされた方が優先される
                                serviceCollection.AddScoped<IConfiguration>(_ => builder.Build());
                                serviceCollection.AddScoped(provider => {
                                    var instance = {{RuntimeSettings.ServerSetiingTypeFullName}}.{{RuntimeSettings.GET_DEFAULT}}();
                                    provider
                                        .GetRequiredService<IConfiguration>()
                                        .GetSection({{RuntimeSettings.ServerSetiingTypeFullName}}.APP_SETTINGS_SECTION_NAME)
                                        .Bind(instance);
                                    return instance;
                                });

                                var services = serviceCollection.BuildServiceProvider();
                                return services.GetRequiredService<{{ctx.Config.DbContextName}}>();
                            }
                        }
                    }
                    """;
            },
        };

        private SourceFile RenderLogEntity() => new SourceFile {
            FileName = $"LogEntity.cs",
            RenderContent = ctx => {
                return $$"""
                    using System.ComponentModel.DataAnnotations;
                    using System.ComponentModel.DataAnnotations.Schema;

                    namespace {{ctx.Config.RootNamespace}} {
                        /// <summary>
                        /// LogEntityのデータモデル
                        /// </summary>
                        [Table("SYS_LOG")]
                        public class LogEntity {
                            [Key, Column("UUID")]
                            public Guid UUID { get; set; } = Guid.NewGuid();
                            [Column("SESSION_KEY"), MaxLength(200)]
                            public string? SessionKey { get; set; }
                            [Column("PROC_ID"), MaxLength(200)]
                            public string? ProcId { get; set; }
                            [Column("LOG_TIMESTAMP", TypeName = "TIMESTAMP(3)")]
                            public DateTime LogTimestamp { get; set; } = DateTime.Now;
                            [Column("USER_ID"), MaxLength(25)]
                            public string? UserID { get; set; }
                            [Column("LOG_LEVEL")]
                            public int LogLevel { get; set; }
                            [Column("LOG_SUMMARY"), MaxLength(2000)]
                            public string? LogSummary { get; set; }
                            [Column("CLIENT_URL"), MaxLength(2000)]
                            public string? ClientUrl { get; set; }
                            [Column("SERVER_URL"), MaxLength(2000)]
                            public string? ServerUrl { get; set; }
                        }
                    }
                    """;
            },
        };

        private const string ON_DBCONTEXT_MODEL_CREATING = "OnModelCreating";
    }
}
