import { ReactNode, useCallback, useState } from "react"
import * as Icon from "@heroicons/react/24/solid"
import { Allotment, LayoutPriority } from "allotment"
import { PageBase } from "./PageBase"
import { PageTitle } from "./PageTitle"
import { Button } from "../input/Button"
import { DataTable, DataTableColumn } from "./DataTable"
import * as DetailMessage from "../util/DetailMessageContext"
import { NowLoading } from "./NowLoading"
import { callComplexPostEndpointAsync } from "../example/callComplexPostEndpointAsync"
import { QueryModelType, LoadFeature, DisplayData, SearchCondition } from "../__autoGenerated"
import * as UI from "../input/Field"
import React from "react"

export type SearchPageBaseProps<
  TQueryModelType extends QueryModelType,
  TItem,
  TCondition extends LoadFeature.ParamType[TQueryModelType]
> = {
  /** このページと対応するクエリモデルの種類 */
  queryModelType: TQueryModelType
  /** ページタイトル。ブラウザのタイトルバーに表示されます。 */
  pageTitle?: string
  /** 検索条件欄のデフォルトサイズ（ピクセル） */
  searchConditionDefaultSize?: number
  /** 検索条件のクリア処理 */
  onClear: () => void
  /** ヘッダー部分のページタイトルの横の部分のレイアウト */
  header?: ReactNode
  /** 検索条件エリア。この欄はformタグの内側に配置されます。 */
  searchCondition: ReactNode
  /** useFormのhandleSubmit */
  onSubmit: (onValid: (data: TCondition) => void) => (e?: React.BaseSyntheticEvent) => Promise<void>
  /** 検索結果エリアのグリッドの列定義 */
  defineSearchResultColumns: [
    (columnFor: UI.DataTableColumnDefinitionHelper<TItem>) => DataTableColumn<TItem>[],
    deps: React.DependencyList
  ]
}

/**
 * 一覧検索画面のベースコンポーネント。
 *
 * ### このコンポーネントの責務
 * - ページの枠のレイアウト（検索条件、結果、ページャ）
 * - 検索処理の呼び出しと結果の保持
 * - ページング管理
 *
 * ### 利用側の責務
 * - 検索条件フォームのレイアウトと状態管理
 * - 検索結果一覧のレイアウト
 * - 実際のAPI呼び出し
 */
export function SearchPageBase<
  TQueryModelType extends QueryModelType,
  TItem extends DisplayData.TypeMap[TQueryModelType],
  TCondition extends SearchCondition.TypeMap[TQueryModelType]
>(props: SearchPageBaseProps<TQueryModelType, TItem, TCondition>) {

  const searchConditionFieldContext = UI.useFieldUiContextProvider(props.queryModelType, 'SearchCondition')
  const searchResultFieldContext = UI.useFieldUiContextProvider(props.queryModelType, 'EditableObject')

  const [items, setItems] = useState<TItem[]>([])
  const [totalCount, setTotalCount] = useState(0)
  const [pageIndex, setPageIndex] = useState(0)
  const [pageSize, setPageSize] = useState(20)
  const [lastCondition, setLastCondition] = useState<TCondition | undefined>(undefined)
  const [loading, setLoading] = useState(false)
  const [searchConditionVisible, setSearchConditionVisible] = useState(true)
  const { clearMessages, replaceMessages } = DetailMessage.useSetter()

  const executeSearch = useCallback(async (condition: TCondition, page: number, size: number) => {
    try {
      setLoading(true)
      condition.skip = (page * size).toString()
      condition.take = size.toString()
      const result = await callComplexPostEndpointAsync(props.queryModelType, condition)
      if (result.type === 'ok') {
        setItems(result.returnValue.currentPageItems as TItem[])
        setTotalCount(result.returnValue.totalCount)
        setPageIndex(page)
        setPageSize(size)
        setLastCondition(condition)
        clearMessages()

      } else if (result.type === 'canceled') {
        // キャンセルされた場合は何もしない

      } else if (result.type === 'error') {
        replaceMessages(result.detail)

      } else {
        replaceMessages({ error: [result.message] })
      }
    } finally {
      setLoading(false)
    }
  }, [props.queryModelType, clearMessages, replaceMessages])

  const handleSearch = useCallback((condition: TCondition) => {
    // 新しい条件で検索するときは1ページ目に戻る
    executeSearch(condition, 0, pageSize)
  }, [executeSearch, pageSize])

  const handlePageChange = useCallback((newPage: number) => {
    if (lastCondition) {
      executeSearch(lastCondition, newPage, pageSize)
    }
  }, [executeSearch, lastCondition, pageSize])

  // 検索結果の列定義
  const columnFor = UI.useGridColumnHelper<TItem>('', searchResultFieldContext)
  const columns: DataTableColumn<TItem>[] = React.useMemo(() => {
    return props.defineSearchResultColumns[0](columnFor)
  }, [...props.defineSearchResultColumns[1], columnFor])

  // ページャーの計算
  const totalPages = Math.ceil(totalCount / pageSize)
  const canPrev = pageIndex > 0
  const canNext = pageIndex < totalPages - 1

  return (
    <UI.FieldUiContext.Provider value={searchConditionFieldContext}>
      <PageBase
        browserTitle={props.pageTitle}
        className="overflow-hidden"
        header={(
          <>
            {/* ページタイトル */}
            <button
              type="button"
              className="flex-1 flex items-center gap-1 cursor-pointer select-none"
              onClick={() => setSearchConditionVisible(prev => !prev)}
            >
              {searchConditionVisible ? (
                <Icon.ChevronDownIcon className="w-4 h-4" />
              ) : (
                <Icon.ChevronRightIcon className="w-4 h-4" />
              )}
              <PageTitle>
                {props.pageTitle}
              </PageTitle>
            </button>

            <Button outline onClick={props.onClear}>
              クリア
            </Button>

            <Button submit fill form="search-form" disabled={loading}>
              検索
            </Button>
          </>
        )}
        contents={(
          <Allotment vertical
            defaultSizes={[props.searchConditionDefaultSize ?? 200, 999]}
            separator={false}
            proportionalLayout={false} // ページサイズ変更時に検索結果欄だけ伸縮するようにするため
            className="pb-1"
          >

            {/* 検索条件欄 */}
            <Allotment.Pane minSize={50} visible={searchConditionVisible} className="pb-1">
              <form
                id="search-form"
                noValidate
                className="h-full overflow-auto"
                onSubmit={props.onSubmit(handleSearch)}
              >
                {props.searchCondition}
              </form>
            </Allotment.Pane>

            {/* 検索結果欄 */}
            <Allotment.Pane
              priority={LayoutPriority.High} // ページサイズ変更時に検索結果欄だけ伸縮する
              className="relative"
            >
              <DataTable
                rows={items}
                columns={columns}
                className="h-full border border-gray-600"
              />

              {loading && (
                <NowLoading opacity={0} />
              )}
            </Allotment.Pane>

          </Allotment>
        )}
        footer={(
          <>
            {/* 件数表示 */}
            <div className="text-sm text-gray-600">
              {totalCount > 0 ? (
                <>
                  全 {totalCount} 件中 {pageIndex * pageSize + 1} - {Math.min((pageIndex + 1) * pageSize, totalCount)} 件を表示
                </>
              ) : (
                <>データなし</>
              )}
            </div>

            {/* ページャー */}
            <div className="flex gap-2 items-center">
              <button
                className="px-3 py-1 border rounded hover:bg-gray-100 disabled:opacity-50"
                onClick={() => handlePageChange(pageIndex - 1)}
                disabled={!canPrev || loading}
              >
                前へ
              </button>
              <span className="px-2 py-1">
                {pageIndex + 1} / {Math.max(1, totalPages)}
              </span>
              <button
                className="px-3 py-1 border rounded hover:bg-gray-100 disabled:opacity-50"
                onClick={() => handlePageChange(pageIndex + 1)}
                disabled={!canNext || loading}
              >
                次へ
              </button>
            </div>
          </>
        )}
      />
    </UI.FieldUiContext.Provider>
  )
}
