using MyApp;
using System.CommandLine;
using System.Text;

namespace MyApp.Management.Commands;

/// <summary>
/// <para>
/// 汎用参照テーブルのビュー定義を再作成するSQLを返す。
/// 汎用参照テーブルを使わないアプリケーションの場合は不要。削除しても構わない。
/// 逆に汎用参照テーブルを使用するアプリケーションの場合、
/// Nijoが生成するソースコードはこのビューの存在を前提としているため、
/// 必ずビューが存在する状態を保つ必要がある。
/// </para>
///
/// <para>
/// このビューの責務は以下。
/// <list type="bullet">
/// <item>大元の汎用参照テーブルから、特定のハードコードされる区分種類による絞り込みを行うこと。</item>
/// <item>ハードコードされる主キー以外のカラムをすべて持つこと。</item>
/// </list>
/// </para>
///
/// <para>
/// nijo.xml スキーマ定義を変更し区分種別が追加削除された場合、このメソッドが返す内容が自動的に変わる。
/// データベースのマイグレーションの際に都度流し直すなどの手順を構築しておけば
/// スキーマ定義をデータベース定義の同期漏れを防ぐことができる。
/// </para>
/// </summary>
internal static class GenerateGeneralLookupViewsSqlCommand {
    internal static Command Create() {
        var outputOption = new Option<FileInfo>("--output") {
            Description = "生成するSQLファイルの出力先パス",
            Required = true,
        };

        var command = new Command("generate-general-lookup-views-sql", "汎用参照テーブルビュー再作成用のSQLファイルを生成します。");
        command.Options.Add(outputOption);

        command.SetAction(parseResult => Execute(parseResult.GetRequiredValue(outputOption)));
        return command;
    }

    private static int Execute(FileInfo output) {
        var outputDirectory = output.Directory;
        if (outputDirectory == null) {
            Console.Error.WriteLine("出力先ディレクトリを判定できませんでした。");
            return 1;
        }

        outputDirectory.Create();

        var builder = new StringBuilder();
        builder.AppendLine("-- Auto-generated by Management generate-general-lookup-views-sql");
        builder.AppendLine("-- 汎用参照テーブルビュー再作成用SQL");
        builder.AppendLine();

        foreach (var sql in GetGeneralLookupViewsSql()) {
            builder.AppendLine(sql.Trim());
            builder.AppendLine();
        }

        File.WriteAllText(output.FullName, builder.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        Console.WriteLine($"Generated: {output.FullName}");
        return 0;
    }

    private static IEnumerable<string> GetGeneralLookupViewsSql() {
        foreach (var viewInfo in AutoGeneratedDbContext.GetGeneralLookupViewsInfo()) {

            // ここではサンプルのため SQLite の文法で記述している。
            // 実際のアプリケーションで使用する RDBMS に応じて修正すること。

            yield return $$"""
                DROP VIEW IF EXISTS [{{viewInfo.ViewName}}];
                """;

            yield return $$"""
                CREATE VIEW [{{viewInfo.ViewName}}] AS
                SELECT {{string.Join(", ", viewInfo.NonHardcodedColumns.Select(c => $"t1.[{c.ColumnName}]"))}}
                FROM [{{viewInfo.SourceTableName}}] t1
                WHERE {{string.Join(" AND ", viewInfo.HardcodedColumns.Select(c => $"t1.[{c.ColumnName}] = '{c.Value}'"))}};
                """;
        }
    }
}
