using Nijo.CodeGenerating;
using Nijo.Util.DotnetEx;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;

namespace Nijo.Models.ReadModel2Modules {
    internal class DisplayDataTypeList : IMultiAggregateSourceFile {
        private sealed record Item(
            DisplayData DisplayData,
            SearchCondition.Entry SearchCondition,
            LoadMethod LoadMethod);

        private readonly Lock _lock = new();
        private readonly List<DisplayData> _displayDataList = [];

        internal DisplayDataTypeList Add(DisplayData displayData) {
            lock (_lock) {
                _displayDataList.Add(displayData);
                return this;
            }
        }

        public void RegisterDependencies(IMultiAggregateSourceFileManager ctx) {
        }

        public void Render(CodeRenderingContext ctx) {
            var items = _displayDataList
                .DistinctBy(displayData => displayData.Aggregate)
                .OrderBy(displayData => displayData.Aggregate.GetRoot().GetIndexOfDataFlow())
                .Select(displayData => new Item(
                        displayData,
                        new SearchCondition.Entry(displayData.Aggregate.GetRoot()),
                        new LoadMethod(displayData.Aggregate.GetRoot())))
                .ToArray();

            ctx.ReactProject(dir => {
                dir.Generate(new SourceFile {
                    FileName = "index.ts",
                    Contents = ctx.IsLegacyCompatibilityMode()
                        ? RenderLegacy(items, ctx)
                        : Render(items, ctx),
                });
            });
        }

        private static string RenderLegacy(Item[] items, CodeRenderingContext ctx) {
            var commandModels = ctx.Schema.GetRootAggregates()
                .Where(root => root.Model is Models.CommandModel || root.Model is Models.CommandModel2)
                .ToArray();
            var hasStaticEnums = ctx.Schema.GetRootAggregates().Any(root => root.Model is Models.StaticEnumModel2);

            return $$"""
                // カスタマイズ側ソースで利用可能なようにまとめてexportする
                {{items.SelectTextTemplate(item => $$"""
                export * from "./{{item.DisplayData.Aggregate.PhysicalName}}"
                """)}}

                {{commandModels.SelectTextTemplate(commandModel => $$"""
                export * from "./{{commandModel.PhysicalName}}"
                """)}}
                {{If(hasStaticEnums, () => $$"""

                export * from "./util"
                export * from "./autogenerated-enum"
                """)}}

                // --------------------------------------------
                import React from "react"
                import ReactRouter from "react-router-dom"
                import { useMsgContext, useHttpRequest, ComplexPostOptions } from "../util2"
                import * as AutoGeneratedUtil from "./util"

                {{items.SelectTextTemplate(item => $$"""
                import * as {{item.DisplayData.Aggregate.PhysicalName}} from "./{{item.DisplayData.Aggregate.PhysicalName}}"
                """)}}


                //#region ReadModel, CommandModel の型名一覧
                /** 自動生成されたReadModelの種類の一覧 */
                export type ReadModelType
                {{If(items.Length == 0, () => $$"""
                  = never
                """)}}
                {{items.SelectTextTemplate((item, i) => $$"""
                  {{(i == 0 ? "=" : "|")}} '{{item.DisplayData.Aggregate.PhysicalName}}'
                """)}}

                /** 自動生成されたReadModelの種類の一覧 */
                export const getReadModelTypeList = (): ReadModelType[] => {
                  return [
                {{items.SelectTextTemplate(item => $$"""
                    '{{item.DisplayData.Aggregate.PhysicalName}}',
                """)}}
                  ]
                }

                /** 自動生成されたCommandModelの種類の一覧 */
                export type CommandModelType
                {{If(commandModels.Length == 0, () => $$"""
                  = never
                """)}}
                {{commandModels.SelectTextTemplate((commandModel, i) => $$"""
                  {{(i == 0 ? "=" : "|")}} '{{commandModel.PhysicalName}}'
                """)}}

                /** 自動生成されたCommandModelの種類の一覧 */
                export const getCommandModelTypeList = (): CommandModelType[] => {
                  return [
                {{commandModels.SelectTextTemplate(commandModel => $$"""
                    '{{commandModel.PhysicalName}}',
                """)}}
                  ]
                }
                //#endregion ReadModel, CommandModel の型名一覧



                //#region DisplayData型一覧
                /** 各ReadModelと画面表示用の型の対応表 */
                export interface DisplayDataTypeMap {
                {{items.SelectTextTemplate(item => $$"""
                  '{{item.DisplayData.Aggregate.PhysicalName}}': {{item.DisplayData.Aggregate.PhysicalName}}.{{item.DisplayData.TsTypeName}}
                """)}}
                }
                //#endregion DisplayData型一覧


                //#region DisplayData新規作成関数
                /** 各ReadModelの画面表示用オブジェクトの新規作成関数 */
                export const CreateNewDisplayData: {
                  [K in ReadModelType]: () => DisplayDataTypeMap[K]
                } = {
                {{items.SelectTextTemplate(item => $$"""
                  '{{item.DisplayData.Aggregate.PhysicalName}}': {{item.DisplayData.Aggregate.PhysicalName}}.{{item.DisplayData.TsNewObjectFunction}},
                """)}}
                }
                //#endregion DisplayData新規作成関数


                //#region SearchCondition型一覧
                /** 各ReadModelと検索条件用の型の対応表 */
                export interface SearchConditionTypeMap {
                {{items.SelectTextTemplate(item => $$"""
                  '{{item.DisplayData.Aggregate.PhysicalName}}': {{item.DisplayData.Aggregate.PhysicalName}}.{{item.SearchCondition.TsTypeName}}
                """)}}
                }
                //#endregion SearchCondition型一覧


                //#region SearchConditionソート可能メンバー
                /** 各ReadModelのSearchConditionのうちソート可能なメンバーの型 */
                export interface SearchConditionSortableMember {
                {{items.SelectTextTemplate(item => $$"""
                  '{{item.DisplayData.Aggregate.PhysicalName}}': {{item.DisplayData.Aggregate.PhysicalName}}.{{item.SearchCondition.TypeScriptSortableMemberType}}
                """)}}
                }

                /** 一覧検索処理のパラメータ指定でメンバー名の後ろにこの文字列をつけるとサーバー側処理でソートしてくれる */
                export type ASC_SUFFIX = '{{SearchCondition.ASC_SUFFIX}}'
                /** 一覧検索処理のパラメータ指定でメンバー名の後ろにこの文字列をつけるとサーバー側処理でソートしてくれる */
                export type DESC_SUFFIX = '{{SearchCondition.DESC_SUFFIX}}'
                //#endregion SearchConditionソート可能メンバー


                //#region SearchCondition新規作成関数
                /** 各ReadModelの検索条件用オブジェクトの新規作成関数 */
                export const CreateNewSearchCondition: {
                  [K in ReadModelType]: () => SearchConditionTypeMap[K]
                } = {
                {{items.SelectTextTemplate(item => $$"""
                  '{{item.DisplayData.Aggregate.PhysicalName}}': {{item.DisplayData.Aggregate.PhysicalName}}.{{item.SearchCondition.TsNewObjectFunction}},
                """)}}
                }
                //#endregion SearchCondition新規作成関数


                //#region 検索用フック（MultiView）
                /** DisplayData読み込み用フック（MultiView）の型 */
                export type LoadHookType<TReadModelType extends ReadModelType> = (disableAutoLoad: true) => {
                  currentPageItems: DisplayDataTypeMap[TReadModelType][]
                  nowLoading: boolean
                  count: (searchConditionFilter: SearchConditionTypeMap[TReadModelType]['filter'], options?: ComplexPostOptions) => Promise<number>
                  load: (searchCondition: SearchConditionTypeMap[TReadModelType], options?: ComplexPostOptions) => Promise<DisplayDataTypeMap[TReadModelType][]>
                }

                /** 各ReadModelとDisplayData読み込み用フックの対応表 */
                export const LoadHookMap: {
                  [K in ReadModelType]: LoadHookType<K>
                }  = {
                {{items.SelectTextTemplate(item => $$"""
                  '{{item.DisplayData.Aggregate.PhysicalName}}': {{item.DisplayData.Aggregate.PhysicalName}}.{{item.LoadMethod.ReactHookName}},
                """)}}
                }
                //#endregion 検索用フック（MultiView）


                //#region 検索用フック（SingleView）
                /** DisplayData読み込み用フック（SingleView）の型 */
                export type SingleViewDataLoader<TReadModelType extends ReadModelType> = (
                  onBeforeInit?: AutoGeneratedUtil.SingleViewDataLoaderOnBeforeInit<DisplayDataTypeMap[TReadModelType]>,
                  onBeforeLoad?: AutoGeneratedUtil.SingleViewDataLoaderOnBeforeLoad<SearchConditionTypeMap[TReadModelType]>,
                ) => {
                  /** 読み込まれたデータ。 */
                  data: DisplayDataTypeMap[TReadModelType] | undefined
                  /** 読み込み状態。loadedなら読み込み完了（ただし読み込み処理の成否を問わない） */
                  loadState: AutoGeneratedUtil.SingleViewLoadState
                  /** 再読み込みを実行する。戻り値は無い。結果はdata変数に代入される。 */
                  reload: (options?: AutoGeneratedUtil.SingleViewNavigationOptions) => void
                }

                /** 各ReadModelと検索用フック（SingleView）の対応 */
                export const SingleViewDataLoaderMap: {
                  [K in ReadModelType]: SingleViewDataLoader<K>
                } = {
                {{items.SelectTextTemplate(item => $$"""
                  '{{item.DisplayData.Aggregate.PhysicalName}}': {{item.DisplayData.Aggregate.PhysicalName}}.{{new SingleView(item.DisplayData.Aggregate.GetRoot()).LoaderHookNameVersion2}},
                """)}}
                }
                //#endregion 検索用フック（SingleView）


                //#region 画面遷移用フックの一覧

                /** 詳細画面への画面遷移用フックの型（新規登録画面ではなく編集閲覧用画面への遷移） */
                export type SingleViewNavigationHook<T> = (
                  data: T,
                  to: 'edit' | 'readonly',
                  options?: AutoGeneratedUtil.SingleViewNavigationOptions
                ) => void

                /** 各ReadModelと詳細画面遷移用フックの対応表（新規登録画面ではなく編集閲覧用画面への遷移） */
                export const SingleViewNavigationHookMap: {
                  [K in ReadModelType]: () => SingleViewNavigationHook<DisplayDataTypeMap[K]>
                } = {
                {{items.SelectTextTemplate(item => $$"""
                  '{{item.DisplayData.Aggregate.PhysicalName}}': {{item.DisplayData.Aggregate.PhysicalName}}.useNavigateTo{{item.DisplayData.Aggregate.PhysicalName}}SingleView,
                """)}}
                }

                /** 各ReadModelと詳細画面遷移用フックの対応表（新規登録画面への遷移） */
                export const CreateViewNavigationHookMap: {
                  [K in ReadModelType]: () => ((options?: AutoGeneratedUtil.SingleViewNavigationOptions) => void)
                } = {
                {{items.SelectTextTemplate(item => $$"""
                  '{{item.DisplayData.Aggregate.PhysicalName}}': {{item.DisplayData.Aggregate.PhysicalName}}.useNavigateTo{{item.DisplayData.Aggregate.PhysicalName}}CreateView,
                """)}}
                }

                /** 各ReadModelと一覧画面遷移用フックの対応表 */
                export const MultiViewNavigationHookMap: {
                  [K in ReadModelType]: () => ((initSearchCondition?: SearchConditionTypeMap[K], options?: ReactRouter.NavigateOptions) => void)
                } = {
                {{items.SelectTextTemplate(item => $$"""
                  '{{item.DisplayData.Aggregate.PhysicalName}}': {{item.DisplayData.Aggregate.PhysicalName}}.{{new MultiView(item.DisplayData.Aggregate.GetRoot()).NavigationHookName}},
                """)}}
                }
                //#endregion 画面遷移用フックの一覧


                //#region URLから検索条件オブジェクトへの変換
                /** 各ReadModelのURLから検索条件オブジェクトへの変換処理 */
                export const UrlToSearchCondition: {
                  [K in ReadModelType]: (urlSearch: string) => SearchConditionTypeMap[K]
                } = {
                {{items.SelectTextTemplate(item => $$"""
                  '{{item.DisplayData.Aggregate.PhysicalName}}': {{item.DisplayData.Aggregate.PhysicalName}}.{{item.SearchCondition.ParseQueryParameter}},
                """)}}
                }
                //#endregion URLから検索条件オブジェクトへの変換


                //#region 検索条件オブジェクトからURLへの変換
                /** 各ReadModelの検索条件オブジェクトからURLへの変換処理 */
                export const SearchConditionToUrl: {
                  [K in ReadModelType]: (searchParams: URLSearchParams, searchCondition: SearchConditionTypeMap[K] | undefined) => void
                } = {
                {{items.SelectTextTemplate(item => $$"""
                  '{{item.DisplayData.Aggregate.PhysicalName}}': {{item.DisplayData.Aggregate.PhysicalName}}.{{new MultiView(item.DisplayData.Aggregate.GetRoot()).AppendToSearchParamsFunction}},
                """)}}
                }
                //#endregion 検索条件オブジェクトからURLへの変換


                //#region 変更チェック関数一覧

                /**
                 * 引数2個の値が変更されているかをディープイコールで確認し、
                 * 変更されている場合はcurrentValuesのwillBeChangedプロパティをtrueにして返す関数の型
                 */
                export type CheckChangesFunction<T> = (args: { defaultValues: T, currentValues: T }) => boolean

                /** 変更チェック関数一覧 */
                export const CheckChangesFunctionMap: {
                  [K in ReadModelType]: CheckChangesFunction<DisplayDataTypeMap[K]>
                } = {
                {{items.SelectTextTemplate(item => $$"""
                  '{{item.DisplayData.Aggregate.PhysicalName}}': {{item.DisplayData.Aggregate.PhysicalName}}.{{item.DisplayData.CheckChangesFunction}},
                """)}}
                }
                //#endregion 変更チェック関数一覧


                //#region UI制約型一覧

                /** UI制約型一覧 */
                export const ReadModelConstraints = {
                {{items.SelectTextTemplate(item => $$"""
                  '{{item.DisplayData.Aggregate.PhysicalName}}': {{item.DisplayData.Aggregate.PhysicalName}}.{{item.DisplayData.UiConstraingValueName}},
                """)}}
                }
                //#endregion UI制約型一覧


                //#region 一括更新フック
                export type UseBatchUpdateReturn<TReadModelType extends ReadModelType> = (
                  items: (DisplayDataTypeMap[TReadModelType])[],
                  handleDetailError: ComplexPostOptions['handleDetailError']
                ) => Promise<{
                  ok: boolean,
                  data?: ((DisplayDataTypeMap[TReadModelType])[]),
                }>

                /** 画面から更新されない集約のための、実際に呼ばれることは無い関数 */
                const useNoopBatchUpdate = (): (() => never) => {
                  return () => {
                    throw new Error('この集約を画面から一括更新することはできません。更新する場合はnijo.xmlでこのReadModelのreadonly指定を外してください。')
                  }
                }

                /** 一括更新処理のフック。 */
                export const BatchUpdateHookMap: {
                  [K in ReadModelType]: () => UseBatchUpdateReturn<K>
                } = {
                {{items.SelectTextTemplate(item => $$"""
                  '{{item.DisplayData.Aggregate.PhysicalName}}': {{item.DisplayData.Aggregate.PhysicalName}}.useBatchUpdate{{item.DisplayData.Aggregate.PhysicalName}},
                """)}}
                }
                //#endregion 一括更新フック


                //#region Excel出力フック

                /** 各ReadModelのExcel出力フック */
                export const UseExcelDownloadHook: {
                  [K in ReadModelType]: () => ((searchCondition: SearchConditionTypeMap[K]) => Promise<void>)
                } = {
                {{items.SelectTextTemplate(item => $$"""
                  '{{item.DisplayData.Aggregate.PhysicalName}}': {{item.DisplayData.Aggregate.PhysicalName}}.{{new MultiView(item.DisplayData.Aggregate.GetRoot()).ExcelDownloadHookName}},
                """)}}
                }
                //#endregion Excel出力フック
                """;
        }

        private static string Render(Item[] items, CodeRenderingContext ctx) {
            var hasStaticEnums = ctx.Schema.GetRootAggregates().Any(root => root.Model is Models.StaticEnumModel2);

            return $$"""
                // カスタマイズ側ソースで利用可能なようにまとめてexportする
                {{items.SelectTextTemplate(item => $$"""
                export * from "./{{item.DisplayData.Aggregate.PhysicalName}}"
                """)}}
                {{If(hasStaticEnums, () => $$"""

                export * from "./util"
                export * from "./autogenerated-enum"
                """)}}

                // --------------------------------------------
                import { ComplexPostOptions } from "../util2"
                {{items.SelectTextTemplate(item => $$"""
                import * as {{item.DisplayData.Aggregate.PhysicalName}} from "./{{item.DisplayData.Aggregate.PhysicalName}}"
                """)}}

                //#region ReadModel の型名一覧
                /** 自動生成されたReadModelの種類の一覧 */
                export type ReadModelType
                {{If(items.Length == 0, () => $$"""
                  = never
                """)}}
                {{items.SelectTextTemplate((item, i) => $$"""
                  {{(i == 0 ? "=" : "|")}} '{{item.DisplayData.Aggregate.PhysicalName}}'
                """)}}

                /** 自動生成されたReadModelの種類の一覧 */
                export const getReadModelTypeList = (): ReadModelType[] => {
                  return [
                {{items.SelectTextTemplate(item => $$"""
                    '{{item.DisplayData.Aggregate.PhysicalName}}',
                """)}}
                  ]
                }
                //#endregion ReadModel の型名一覧

                //#region DisplayData型一覧
                /** 各ReadModelと画面表示用の型の対応表 */
                export interface DisplayDataTypeMap {
                {{items.SelectTextTemplate(item => $$"""
                  '{{item.DisplayData.Aggregate.PhysicalName}}': {{item.DisplayData.Aggregate.PhysicalName}}.{{item.DisplayData.TsTypeName}}
                """)}}
                }

                /** 各ReadModelの画面表示用オブジェクトの新規作成関数 */
                export const CreateNewDisplayData: {
                  [K in ReadModelType]: () => DisplayDataTypeMap[K]
                } = {
                {{items.SelectTextTemplate(item => $$"""
                  '{{item.DisplayData.Aggregate.PhysicalName}}': {{item.DisplayData.Aggregate.PhysicalName}}.{{item.DisplayData.TsNewObjectFunction}},
                """)}}
                }
                //#endregion DisplayData型一覧

                //#region SearchCondition型一覧
                /** 各ReadModelと検索条件用の型の対応表 */
                export interface SearchConditionTypeMap {
                {{items.SelectTextTemplate(item => $$"""
                  '{{item.DisplayData.Aggregate.PhysicalName}}': {{item.DisplayData.Aggregate.PhysicalName}}.{{item.SearchCondition.TsTypeName}}
                """)}}
                }

                /** 各ReadModelのSearchConditionのうちソート可能なメンバーの型 */
                export interface SearchConditionSortableMember {
                {{items.SelectTextTemplate(item => $$"""
                  '{{item.DisplayData.Aggregate.PhysicalName}}': {{item.DisplayData.Aggregate.PhysicalName}}.{{item.SearchCondition.TypeScriptSortableMemberType}}
                """)}}
                }

                /** 一覧検索処理のパラメータ指定でメンバー名の後ろにこの文字列をつけるとサーバー側処理でソートしてくれる */
                export type ASC_SUFFIX = '{{SearchCondition.ASC_SUFFIX}}'
                /** 一覧検索処理のパラメータ指定でメンバー名の後ろにこの文字列をつけるとサーバー側処理でソートしてくれる */
                export type DESC_SUFFIX = '{{SearchCondition.DESC_SUFFIX}}'

                /** 各ReadModelの検索条件用オブジェクトの新規作成関数 */
                export const CreateNewSearchCondition: {
                  [K in ReadModelType]: () => SearchConditionTypeMap[K]
                } = {
                {{items.SelectTextTemplate(item => $$"""
                  '{{item.DisplayData.Aggregate.PhysicalName}}': {{item.DisplayData.Aggregate.PhysicalName}}.{{item.SearchCondition.TsNewObjectFunction}},
                """)}}
                }

                /** 各ReadModelのURLから検索条件オブジェクトへの変換処理 */
                export const UrlToSearchCondition: {
                  [K in ReadModelType]: (urlSearch: string) => SearchConditionTypeMap[K]
                } = {
                {{items.SelectTextTemplate(item => $$"""
                  '{{item.DisplayData.Aggregate.PhysicalName}}': {{item.DisplayData.Aggregate.PhysicalName}}.{{item.SearchCondition.ParseQueryParameter}},
                """)}}
                }
                //#endregion SearchCondition型一覧

                //#region 検索用フック（MultiView）
                /** DisplayData読み込み用フック（MultiView）の型 */
                export type LoadHookType<TReadModelType extends ReadModelType> = (disableAutoLoad: true) => {
                  currentPageItems: DisplayDataTypeMap[TReadModelType][]
                  nowLoading: boolean
                  count: (searchConditionFilter: SearchConditionTypeMap[TReadModelType]['filter'], options?: ComplexPostOptions) => Promise<number>
                  load: (searchCondition: SearchConditionTypeMap[TReadModelType], options?: ComplexPostOptions) => Promise<DisplayDataTypeMap[TReadModelType][]>
                }

                /** 各ReadModelとDisplayData読み込み用フックの対応表 */
                export const LoadHookMap: {
                  [K in ReadModelType]: LoadHookType<K>
                } = {
                {{items.SelectTextTemplate(item => $$"""
                  '{{item.DisplayData.Aggregate.PhysicalName}}': {{item.DisplayData.Aggregate.PhysicalName}}.{{item.LoadMethod.ReactHookName}},
                """)}}
                }
                //#endregion 検索用フック（MultiView）
                """;
        }
    }
}
