using Nijo.CodeGenerating;
using Nijo.Util.DotnetEx;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;

namespace Nijo.Models.ReadModel2Modules {
    internal class DisplayDataTypeList : IMultiAggregateSourceFile {
        private sealed record Item(
            DisplayData DisplayData,
            SearchCondition.Entry SearchCondition,
            LoadMethod LoadMethod);

        private readonly Lock _lock = new();
        private readonly List<DisplayData> _displayDataList = [];

        internal DisplayDataTypeList Add(DisplayData displayData) {
            lock (_lock) {
                _displayDataList.Add(displayData);
                return this;
            }
        }

        public void RegisterDependencies(IMultiAggregateSourceFileManager ctx) {
        }

        public void Render(CodeRenderingContext ctx) {
            var items = _displayDataList
                .DistinctBy(displayData => displayData.Aggregate)
                .OrderBy(displayData => displayData.Aggregate.GetRoot().GetIndexOfDataFlow())
                .Select(displayData => new Item(
                        displayData,
                        new SearchCondition.Entry(displayData.Aggregate.GetRoot()),
                        new LoadMethod(displayData.Aggregate.GetRoot())))
                .ToArray();

            ctx.ReactProject(dir => {
                dir.Generate(new SourceFile {
                    FileName = "index.ts",
                    Contents = Render(items, ctx),
                });
            });
        }

        private static string Render(Item[] items, CodeRenderingContext ctx) {
            var hasStaticEnums = ctx.Schema.GetRootAggregates().Any(root => root.Model is Models.StaticEnumModel2);

            return $$"""
                // カスタマイズ側ソースで利用可能なようにまとめてexportする
                {{items.SelectTextTemplate(item => $$"""
                export * from "./{{item.DisplayData.Aggregate.PhysicalName}}"
                """)}}
                {{If(hasStaticEnums, () => $$"""

                export * from "./util"
                export * from "./autogenerated-enum"
                """)}}

                // --------------------------------------------
                import { ComplexPostOptions } from "../util2"
                {{items.SelectTextTemplate(item => $$"""
                import * as {{item.DisplayData.Aggregate.PhysicalName}} from "./{{item.DisplayData.Aggregate.PhysicalName}}"
                """)}}

                //#region ReadModel の型名一覧
                /** 自動生成されたReadModelの種類の一覧 */
                export type ReadModelType
                {{If(items.Length == 0, () => $$"""
                  = never
                """)}}
                {{items.SelectTextTemplate((item, i) => $$"""
                  {{(i == 0 ? "=" : "|")}} '{{item.DisplayData.Aggregate.PhysicalName}}'
                """)}}

                /** 自動生成されたReadModelの種類の一覧 */
                export const getReadModelTypeList = (): ReadModelType[] => {
                  return [
                {{items.SelectTextTemplate(item => $$"""
                    '{{item.DisplayData.Aggregate.PhysicalName}}',
                """)}}
                  ]
                }
                //#endregion ReadModel の型名一覧

                //#region DisplayData型一覧
                /** 各ReadModelと画面表示用の型の対応表 */
                export interface DisplayDataTypeMap {
                {{items.SelectTextTemplate(item => $$"""
                  '{{item.DisplayData.Aggregate.PhysicalName}}': {{item.DisplayData.Aggregate.PhysicalName}}.{{item.DisplayData.TsTypeName}}
                """)}}
                }

                /** 各ReadModelの画面表示用オブジェクトの新規作成関数 */
                export const CreateNewDisplayData: {
                  [K in ReadModelType]: () => DisplayDataTypeMap[K]
                } = {
                {{items.SelectTextTemplate(item => $$"""
                  '{{item.DisplayData.Aggregate.PhysicalName}}': {{item.DisplayData.Aggregate.PhysicalName}}.{{item.DisplayData.TsNewObjectFunction}},
                """)}}
                }
                //#endregion DisplayData型一覧

                //#region SearchCondition型一覧
                /** 各ReadModelと検索条件用の型の対応表 */
                export interface SearchConditionTypeMap {
                {{items.SelectTextTemplate(item => $$"""
                  '{{item.DisplayData.Aggregate.PhysicalName}}': {{item.DisplayData.Aggregate.PhysicalName}}.{{item.SearchCondition.TsTypeName}}
                """)}}
                }

                /** 各ReadModelのSearchConditionのうちソート可能なメンバーの型 */
                export interface SearchConditionSortableMember {
                {{items.SelectTextTemplate(item => $$"""
                  '{{item.DisplayData.Aggregate.PhysicalName}}': {{item.DisplayData.Aggregate.PhysicalName}}.{{item.SearchCondition.TypeScriptSortableMemberType}}
                """)}}
                }

                /** 一覧検索処理のパラメータ指定でメンバー名の後ろにこの文字列をつけるとサーバー側処理でソートしてくれる */
                export type ASC_SUFFIX = '{{SearchCondition.ASC_SUFFIX}}'
                /** 一覧検索処理のパラメータ指定でメンバー名の後ろにこの文字列をつけるとサーバー側処理でソートしてくれる */
                export type DESC_SUFFIX = '{{SearchCondition.DESC_SUFFIX}}'

                /** 各ReadModelの検索条件用オブジェクトの新規作成関数 */
                export const CreateNewSearchCondition: {
                  [K in ReadModelType]: () => SearchConditionTypeMap[K]
                } = {
                {{items.SelectTextTemplate(item => $$"""
                  '{{item.DisplayData.Aggregate.PhysicalName}}': {{item.DisplayData.Aggregate.PhysicalName}}.{{item.SearchCondition.TsNewObjectFunction}},
                """)}}
                }

                /** 各ReadModelのURLから検索条件オブジェクトへの変換処理 */
                export const UrlToSearchCondition: {
                  [K in ReadModelType]: (urlSearch: string) => SearchConditionTypeMap[K]
                } = {
                {{items.SelectTextTemplate(item => $$"""
                  '{{item.DisplayData.Aggregate.PhysicalName}}': {{item.DisplayData.Aggregate.PhysicalName}}.{{item.SearchCondition.ParseQueryParameter}},
                """)}}
                }
                //#endregion SearchCondition型一覧

                //#region 検索用フック（MultiView）
                /** DisplayData読み込み用フック（MultiView）の型 */
                export type LoadHookType<TReadModelType extends ReadModelType> = (disableAutoLoad: true) => {
                  currentPageItems: DisplayDataTypeMap[TReadModelType][]
                  nowLoading: boolean
                  count: (searchConditionFilter: SearchConditionTypeMap[TReadModelType]['filter'], options?: ComplexPostOptions) => Promise<number>
                  load: (searchCondition: SearchConditionTypeMap[TReadModelType], options?: ComplexPostOptions) => Promise<DisplayDataTypeMap[TReadModelType][]>
                }

                /** 各ReadModelとDisplayData読み込み用フックの対応表 */
                export const LoadHookMap: {
                  [K in ReadModelType]: LoadHookType<K>
                } = {
                {{items.SelectTextTemplate(item => $$"""
                  '{{item.DisplayData.Aggregate.PhysicalName}}': {{item.DisplayData.Aggregate.PhysicalName}}.{{item.LoadMethod.ReactHookName}},
                """)}}
                }
                //#endregion 検索用フック（MultiView）
                """;
        }
    }
}
