using Nijo.CodeGenerating;
using Nijo.ImmutableSchema;
using Nijo.Parts.CSharp;
using System.Collections.Generic;
using System.Linq;

namespace Nijo.Models.ReadModel2Modules {
    internal class SearchResult : IInstancePropertyOwnerMetadata, IEFCoreEntity {
        internal SearchResult(AggregateBase aggregate) {
            Aggregate = aggregate;
        }

        public AggregateBase Aggregate { get; }

        public string CsClassName => $"{Aggregate.PhysicalName}SearchResult";
        public string DbSetName => $"{Aggregate.PhysicalName}DbSet";
        public string OnModelCreatingAutoGenerated => $"OnModelCreating{Aggregate.PhysicalName}";
        public bool HasTimestampColumns => false;
        public bool HasVersionColumn => Aggregate is RootAggregate;

        public IEnumerable<IInstancePropertyMetadata> GetMembers() {
            foreach (var member in Aggregate.GetMembers()) {
                if (member is ValueMember vm) {
                    if (vm.OnlySearchCondition) continue;
                    if (vm.IsHardCodedPrimaryKey) continue;
                    yield return new SearchResultValueMember(vm);
                } else if (member is RefToMember refTo) {
                    yield return new SearchResultStructureMember(refTo.PhysicalName, new SearchResult(refTo.RefTo.AsEntry()), false, refTo);
                } else if (member is ChildAggregate child) {
                    yield return new SearchResultStructureMember(child.PhysicalName, new SearchResult(child), false, child);
                } else if (member is ChildrenAggregate children) {
                    yield return new SearchResultStructureMember(children.PhysicalName, new SearchResult(children), true, children);
                }
            }
        }
        public IEnumerable<EFCoreEntity.EFCoreEntityColumn> GetColumns() => Enumerable.Empty<EFCoreEntity.EFCoreEntityColumn>();
        public IEnumerable<NavigationProperty> GetNavigationProperties() => Enumerable.Empty<NavigationProperty>();

        internal string RenderCSharpDeclaring(CodeRenderingContext ctx) {
            if (ctx.IsLegacyCompatibilityMode()) {
                var createQueryMethodName = $"Create{Aggregate.GetRoot().PhysicalName}QuerySource";

                return $$"""
                    /// <summary>
                    /// <see cref="{{ApplicationService.ABSTRACT_CLASS}}.{{createQueryMethodName}}"/> の戻り値の型。
                    /// </summary>
                    public partial class {{CsClassName}} {
                    {{GetMembers().SelectTextTemplate(member => $$"""
                        {{WithIndent(RenderLegacyMember(member), "    ")}}
                    """)}}
                    {{If(HasVersionColumn, () => $$"""
                        /// <summary>楽観排他制御用のバージョニング用</summary>
                        public required int Version { get; set; }
                    """)}}
                    }
                    """;
            }

            return $$"""
                /// <summary>
                /// {{Aggregate.DisplayName}}の検索結果型。
                /// </summary>
                {{NijoAttr.RenderAttributeValues(ctx, Aggregate)}}
                public partial class {{CsClassName}} {
                {{GetMembers().SelectTextTemplate(member => $$"""
                    {{WithIndent(RenderMember(member), "    ")}}
                """)}}
                {{If(HasVersionColumn, () => $$"""
                    public int Version { get; set; }
                """)}}
                }
                """;

            static string RenderMember(IInstancePropertyMetadata member) {
                return member switch {
                    SearchResultValueMember value => value.RenderDeclaration(),
                    SearchResultStructureMember structure => structure.RenderDeclaration(),
                    _ => string.Empty,
                };
            }

            static string RenderLegacyMember(IInstancePropertyMetadata member) {
                return member switch {
                    SearchResultValueMember value => $$"""
                        /// <summary>{{value.Member.PhysicalName}}</summary>
                        public virtual {{GetLegacyValueTypeName(value)}}? {{value.Member.PhysicalName}} { get; set; }
                        """,
                    SearchResultStructureMember structure => $$"""
                        /// <summary>{{structure.GetPropertyName(E_CsTs.CSharp)}}</summary>
                        public virtual {{GetLegacyTypeName(structure)}}? {{structure.GetPropertyName(E_CsTs.CSharp)}} { get; set; }
                        """,
                    _ => string.Empty,
                };
            }

            static string GetLegacyTypeName(SearchResultStructureMember structure) {
                return structure.IsArray
                    ? $"List<{structure.GetTypeName(E_CsTs.CSharp)}>"
                    : structure.GetTypeName(E_CsTs.CSharp);
            }

            static string GetLegacyValueTypeName(SearchResultValueMember value) {
                return value.Member.Type.CsDomainTypeName.Replace("DateOnly", "Date");
            }
        }
        internal string RenderCSharpRecursively(CodeRenderingContext ctx) {
            var tree = Aggregate.EnumerateThisAndDescendants().Select(agg => new SearchResult(agg));
            return $$"""
                #region 検索結果型
                {{tree.SelectTextTemplate(item => $$"""
                {{item.RenderCSharpDeclaring(ctx)}}
                """)}}
                #endregion 検索結果型
                """;
        }
        internal IEnumerable<IEFCoreEntity> EnumerateThisAndChildren() {
            foreach (var agg in Aggregate.EnumerateThisAndDescendants().Where(agg => agg is RootAggregate || agg is ChildrenAggregate)) {
                yield return new SearchResult(agg);
            }
        }

        private sealed class SearchResultValueMember : IInstanceValuePropertyMetadata {
            internal SearchResultValueMember(ValueMember member) {
                Member = member;
            }
            internal ValueMember Member { get; }
            public string DisplayName => Member.DisplayName;
            public ISchemaPathNode SchemaPathNode => Member;
            public string GetPropertyName(E_CsTs csts) => Member.PhysicalName;
            IValueMemberType IInstanceValuePropertyMetadata.Type => Member.Type;

            internal string RenderDeclaration() {
                return $$"""
                    public virtual {{Member.Type.CsDomainTypeName}}? {{Member.PhysicalName}} { get; set; }
                    """;
            }
        }

        private sealed class SearchResultStructureMember : IInstanceStructurePropertyMetadata {
            internal SearchResultStructureMember(string propertyName, SearchResult target, bool isArray, ISchemaPathNode schemaPathNode) {
                _propertyName = propertyName;
                _target = target;
                _isArray = isArray;
                _schemaPathNode = schemaPathNode;
            }
            private readonly string _propertyName;
            private readonly SearchResult _target;
            private readonly bool _isArray;
            private readonly ISchemaPathNode _schemaPathNode;

            public string DisplayName => _propertyName;
            public ISchemaPathNode SchemaPathNode => _schemaPathNode;
            public bool IsArray => _isArray;
            public string GetPropertyName(E_CsTs csts) => _propertyName;
            public string GetTypeName(E_CsTs csts) => _target.CsClassName;
            public IEnumerable<IInstancePropertyMetadata> GetMembers() => _target.GetMembers();

            internal string RenderDeclaration() {
                return _isArray
                    ? $$"""
                        public virtual List<{{_target.CsClassName}}>? {{_propertyName}} { get; set; }
                        """
                    : $$"""
                        public virtual {{_target.CsClassName}}? {{_propertyName}} { get; set; }
                        """;
            }
        }
    }
}
