using Nijo.CodeGenerating;
using Nijo.ImmutableSchema;
using Nijo.Util.DotnetEx;
using System.Linq;

namespace Nijo.Models.ReadModel2Modules {
    internal class SingleView {
        internal const string E_SINGLE_VIEW_TYPE = "E_SingleViewType";
        internal static string RenderSingleViewNavigationEnums() {
            return $$"""
                /// <summary>詳細画面のモード</summary>
                public enum {{E_SINGLE_VIEW_TYPE}} {
                    /// <summary>新規データ作成モード</summary>
                    New,
                    /// <summary>既存データの編集モード</summary>
                    Edit,
                    /// <summary>既存データの閲覧モード</summary>
                    ReadOnly,
                }
                """;
        }

        internal enum E_Type {
            New,
            ReadOnly,
            Edit,
        }

        internal SingleView(RootAggregate aggregate) {
            _aggregate = aggregate;
        }

        private readonly RootAggregate _aggregate;
        private const string URL_NEW = "new";
        private const string URL_DETAIL = "detail";
        private const string URL_EDIT = "edit";
        private string UrlSubDomain {
            get {
                return $"/{_aggregate.DisplayName}".ToHashedString();
            }
        }
        private string LegacySetSingleViewDisplayDataMethod => $"SettingDisplayData{_aggregate.PhysicalName}";

        public string Url => $"/{UrlSubDomain}/:mode/:key0?";
        public string ComponentPhysicalName => $"{_aggregate.PhysicalName}SingleView";

        internal string LoaderHookNameVersion2 => $"use{_aggregate.PhysicalName}SingleViewDafaultLoader";

        internal string RenderPageFrameComponent(CodeRenderingContext context) {
            var displayData = new DisplayData(_aggregate);
            var searchCondition = new SearchCondition.Entry(_aggregate);
            var keys = _aggregate.GetKeyVMs().Select((vm, i) => new {
                vm.PhysicalName,
                vm.DisplayName,
                Index = i,
            }).ToArray();

            if (context.IsLegacyCompatibilityMode()) {
                var keyParams = keys.Select(k => $"key{k.Index}").Join(", ");
                var missingKeyCondition = keys.Select(k => $"key{k.Index} === undefined").Join(" || ");
                var assignKeyFilters = keys.SelectTextTemplate(k => $$"""
searchCondition.{{SearchCondition.Entry.FILTER_TS}}.{{k.PhysicalName}}  = { from: key{{k.Index}}, to: key{{k.Index}} }
""");
                var notFoundMessage = keys.Select(k => $"{k.DisplayName}: ${{key{k.Index}}}").Join(", ");

                return $$"""
                    /** {{_aggregate.DisplayName}}の詳細画面の既定の初期表示処理。 */
                    export const {{LoaderHookNameVersion2}}: AutoGeneratedUtil.SingleViewDataLoader<{{searchCondition.TsTypeName}}, {{displayData.TsTypeName}}> = (onBeforeInit, onBeforeLoad) => {

                      const [data, setData] = React.useState<{{displayData.TsTypeName}}>()
                      const [loadState, setLoadState] = React.useState<AutoGeneratedUtil.SingleViewLoadState>()
                      const { complexPost } = Util.useHttpRequest()
                      const { load: load{{_aggregate.PhysicalName}} } = use{{_aggregate.PhysicalName}}Loader(true)
                      const dispatchMsg = Util.useMsgContext()

                      // URLから受け取った各種データを使用し、サーバーと連携して画面初期表示処理を行なう
                      const mode = AutoGeneratedUtil.useSingleViewMode() // 画面モード
                      const { pathname, search, state } = ReactRouter.useLocation() // 初期データ用のクエリパラメータ
                      const { {{keyParams}} } = ReactRouter.useParams() // 表示対象データのキー。ここのパラメータ名はReact routerのルーティング設定の箇所で決めている
                      const latestSearchIdRef = React.useRef<string>() // 最も新しい検索処理のID
                      const initializeSingleView = useEvent(async () => {

                        const thisId = UUID.generate()
                        latestSearchIdRef.current = thisId

                        setData(undefined)
                        setLoadState('loading')

                        if (mode === 'new') {
                          // ------ 画面表示時処理: 新規作成モードの場合 ------
                          let data: {{displayData.TsTypeName}}
                          data = {{displayData.TsNewObjectFunction}}()

                          // サーバー側での初期表示処理カスタマイズ
                          const initProcessResult = await complexPost<{{displayData.TsTypeName}}>(`/api/{{_aggregate.PhysicalName}}/new-display-data${search ?? ''}`, data)
                          if (!initProcessResult.ok) {
                            dispatchMsg.warn(Util.MSG.ERRC0068())
                            setLoadState('loaded(error)')
                            return
                          }
                          data = initProcessResult.data!

                          // この検索処理より新しい検索処理が走った場合
                          if (latestSearchIdRef.current !== thisId) {
                            return
                          }

                          // クライアント側での初期表示処理カスタマイズ
                          if (onBeforeInit) {
                            const initArgs = { displayData: data }
                            data = onBeforeInit(initArgs)
                          }

                          setData(data)
                          setLoadState('loaded')

                        } else if (mode === 'detail' || mode === 'edit') {
                          // ------ 画面表示時処理: 閲覧モードまたは編集モードの場合 ------
                          if ({{missingKeyCondition}}) {
                            // URLで表示対象のキーが指定されていない場合
                            dispatchMsg.warn(Util.MSG.ERRC0068())
                            setLoadState('loaded(error)')
                            return
                          }

                          // URLで指定されたキーで検索をかける。1件だけヒットするはずなのでそれを画面に初期表示する
                          const searchCondition = {{searchCondition.TsNewObjectFunction}}()

                          {{WithIndent(assignKeyFilters, "                          ")}}

                          // 画面側で初期読み込み時の検索条件を編集したいなどの場合はその処理を実行
                          onBeforeLoad?.({ searchCondition })

                          const searchResult = await load{{_aggregate.PhysicalName}}(searchCondition)
                          if (searchResult.length === 0) {
                            dispatchMsg.warn(Util.MSG.ERRC0031(`{{notFoundMessage}}`))
                            setLoadState('loaded(error)')
                            return
                          }
                          const loadedValue = searchResult[0]

                          // この検索処理より新しい検索処理が走った場合
                          if (latestSearchIdRef.current !== thisId) {
                            return
                          }

                          if (mode === 'detail') {
                            // 閲覧モード時は強制的に全項目読み取り専用
                            setData({
                              ...loadedValue,
                              {{DisplayData.READONLY_TS}}: { ...loadedValue.{{DisplayData.READONLY_TS}}, {{DisplayData.ALL_READONLY_TS}}: true },
                            })
                          } else {
                            setData(loadedValue)
                          }
                          setLoadState('loaded')
                        } else {
                          dispatchMsg.warn(Util.MSG.ERRC0002(`画面モード不正`))
                          setLoadState('loaded(error)')
                        }
                      })

                      // 画面初期表示時
                      React.useEffect(() => {
                        initializeSingleView()
                      }, [initializeSingleView, mode, {{keyParams}}, state?.SINGLE_VIEW_RELOAD_TRIGGER])

                      // リロード
                      const navigate = ReactRouter.useNavigate()
                      const reload = useEvent((options?: AutoGeneratedUtil.SingleViewNavigationOptions) => {
                        const searchParams = new URLSearchParams(search)
                        options?.editQueryParameter?.(searchParams)
                        const state = {
                          ...options?.navigatorState,
                          SINGLE_VIEW_RELOAD_TRIGGER: UUID.generate(), // 確実にリロードを発火させるために状態を強制変更する
                        }
                        navigate(`${pathname}?${searchParams.toString()}`, { state })
                      })

                      return {
                        /* 読み込まれたデータ。 */
                        data,
                        /* 読み込み状態。loadedなら読み込み完了（ただし読み込み処理の成否を問わない） */
                        loadState,
                        /* 再読み込みを実行する。 */
                        reload,
                      }
                    }

                    """;
            }

            return $$"""
                /** {{_aggregate.DisplayName}}の詳細画面の既定の初期表示処理。 */
                export const {{LoaderHookNameVersion2}} = (_onBeforeInit?: unknown, _onBeforeLoad?: unknown) => {
                  const [data, setData] = React.useState<{{displayData.TsTypeName}}>()
                  const [loadState, setLoadState] = React.useState<'loading' | 'loaded' | 'loaded(error)' | undefined>()

                  React.useEffect(() => {
                    setData(undefined)
                    setLoadState('loaded')
                  }, [])

                  return {
                    data,
                    loadState,
                    reload: () => {
                      setData(undefined)
                      setLoadState('loaded')
                    },
                  }
                }
                """;
        }
        internal string RenderSetSingleViewDisplayDataFn(CodeRenderingContext context) {
            var displayData = new DisplayData(_aggregate);

            if (context.IsLegacyCompatibilityMode()) {
                return $$"""
                    /// <summary>
                    /// 新規作成時の画面表示データを作成します。
                    /// クライアント側でクエリパラメータを指定した場合、この処理の中で参照することができます。
                    /// </summary>
                    /// <param name="queryParameter">クライアント側で指定されたクエリパラメータ</param>
                    public virtual {{displayData.CsClassName}} {{LegacySetSingleViewDisplayDataMethod}}(IEnumerable<KeyValuePair<string, StringValues>> queryParameter, IPresentationContext context) {
                        return new {{displayData.CsClassName}} {
                            {{DisplayData.UNIQUE_ID_CS}} = Guid.NewGuid().ToString(),
                        };
                    }
                    """;
            }

            return $$"""
                protected virtual {{displayData.CsClassName}} Set{{_aggregate.PhysicalName}}SingleViewDisplayData({{displayData.CsClassName}} displayData, IPresentationContext context) {
                    return displayData;
                }
                """;
        }
        internal string RenderSetSingleViewDisplayData(CodeRenderingContext context) {
            var displayData = new DisplayData(_aggregate);

            if (context.IsLegacyCompatibilityMode()) {
                return $$"""
                    /// <summary>
                    /// 新規作成時の画面表示データを作成します。
                    /// クライアント側でクエリパラメータを指定した場合、この処理の中で参照することができます。
                    /// </summary>
                    [HttpPost("new-display-data")]
                    public virtual IActionResult Setting{{_aggregate.PhysicalName}}DisplayData(ComplexPostRequest request) {
                        var context = new PresentationContext(new DisplayMessageContainer([]), new() { IgnoreConfirm = true }, _applicationService);
                        var displayData = _applicationService.{{LegacySetSingleViewDisplayDataMethod}}(HttpContext.Request.Query, context);
                        context.ReturnValue = displayData;
                        return this.JsonContent(context.GetResult().ToJsonObject());
                    }
                    """;
            }

            return $$"""
                [HttpPost("new-display-data")]
                public virtual IActionResult Set{{_aggregate.PhysicalName}}SingleViewDisplayData(ComplexPostRequest<{{displayData.CsClassName}}> request) {
                    var result = _applicationService.Set{{_aggregate.PhysicalName}}SingleViewDisplayData(request.Data, new PresentationContext(new DisplayMessageContainer([]), new(), _applicationService));
                    return this.JsonContent(result);
                }
                """;
        }
        internal string RenderNavigateFn(CodeRenderingContext context, E_Type type) {
            var displayData = new DisplayData(_aggregate);
            if (context.IsLegacyCompatibilityMode()) {
                if (type == E_Type.New) {
                    var legacyFunctionName = $"useNavigateTo{_aggregate.PhysicalName}CreateView";
                    var legacyUrl = $"/{UrlSubDomain}/{URL_NEW}";
                    return $$"""
                        /** {{_aggregate.DisplayName}}の新規作成画面へ遷移する関数を返します。 */
                        export const {{legacyFunctionName}} = () => {
                          const navigate = ReactRouter.useNavigate()

                          return React.useCallback((options?: AutoGeneratedUtil.SingleViewNavigationOptions) => {
                            if (options?.editQueryParameter) {
                              const searchParams = new URLSearchParams()
                              options.editQueryParameter(searchParams)
                              navigate(`{{legacyUrl}}?${searchParams.toString()}`, { state: options?.navigatorState })

                            } else {
                              navigate(`{{legacyUrl}}`, { state: options?.navigatorState })
                            }
                          }, [navigate])
                        }

                        """;
                } else {
                    var legacyFunctionName = $"useNavigateTo{_aggregate.PhysicalName}SingleView";
                    var readonlyUrl = $"/{UrlSubDomain}/{URL_DETAIL}";
                    var editUrl = $"/{UrlSubDomain}/{URL_EDIT}";
                    var keys = _aggregate.GetKeyVMs().Select((vm, i) => new {
                        vm.PhysicalName,
                        vm.DisplayName,
                        Index = i,
                    }).ToArray();
                    var keyDeclarations = keys.SelectTextTemplate((k, i) => $$"""
const key{{i}} = obj.values?.{{k.PhysicalName}}
""");
                    var keyChecks = keys.SelectTextTemplate((k, i) => $$"""
if (key{{i}} === undefined) throw new Error('{{k.DisplayName}}が指定されていません。')
""");
                    var encodedKeys = keys.Select((_, i) => $"${{window.encodeURIComponent(`${{key{i}}}`)}}").Join("/");
                    return $$"""
                        /** {{_aggregate.DisplayName}}の閲覧画面または編集画面へ遷移する関数を返します。 */
                        export const {{legacyFunctionName}} = () => {
                          const navigate = ReactRouter.useNavigate()

                          return React.useCallback((
                            /** URLに使用するキー項目を算出するためのオブジェクト */
                            obj: {{displayData.TsTypeName}},
                            /** 閲覧画面へ遷移するか編集画面へ遷移するか */
                            to: 'readonly' | 'edit',
                            /** 遷移時のオプション */
                            options?: AutoGeneratedUtil.SingleViewNavigationOptions
                          ) => {
                            {{WithIndent(keyDeclarations, "                            ")}}
                            {{WithIndent(keyChecks, "                            ")}}

                            // クエリパラメータ
                            const searchParams = new URLSearchParams()
                            options?.editQueryParameter?.(searchParams)
                            const queryString = searchParams.toString()

                            if (to === 'readonly') {
                              navigate(`{{readonlyUrl}}/{{encodedKeys}}?${queryString}`, { state: options?.navigatorState })
                            } else {
                              navigate(`{{editUrl}}/{{encodedKeys}}?${queryString}`, { state: options?.navigatorState })
                            }
                          }, [navigate])
                        }
                        """;
                }
            }
            var functionName = type switch {
                E_Type.New => $"useNavigateTo{_aggregate.PhysicalName}SingleViewNew",
                E_Type.ReadOnly => $"useNavigateTo{_aggregate.PhysicalName}SingleViewReadOnly",
                E_Type.Edit => $"useNavigateTo{_aggregate.PhysicalName}SingleViewEdit",
                _ => $"useNavigateTo{_aggregate.PhysicalName}SingleView",
            };
            var url = type switch {
                E_Type.New => $"/{_aggregate.PhysicalName}/{URL_NEW}",
                E_Type.ReadOnly => $"/{_aggregate.PhysicalName}/{URL_DETAIL}",
                E_Type.Edit => $"/{_aggregate.PhysicalName}/{URL_EDIT}",
                _ => $"/{_aggregate.PhysicalName}/{URL_DETAIL}",
            };

            return $$"""
                /** {{_aggregate.DisplayName}}の詳細画面へ遷移します。 */
                export const {{functionName}} = () => {
                  const navigate = ReactRouter.useNavigate()

                  return React.useCallback((_data?: {{displayData.TsTypeName}}, options?: ReactRouter.NavigateOptions) => {
                    navigate('{{url}}', options)
                  }, [navigate])
                }
                """;
        }
        internal string RenderAppSrvGetUrlMethod() {
            var displayData = new DisplayData(_aggregate);
            var keys = _aggregate
                    .GetKeyVMs()
                    .Select((vm, i) => new {
                        vm.PhysicalName,
                        vm.DisplayName,
                        TypeName = vm.Type.CsDomainTypeName,
                        IsString = vm.Type.CsDomainTypeName == "string",
                        Index = i,
                    })
                    .ToArray();

            return $$"""
                /// <summary>
                /// 詳細画面を引数のオブジェクトで表示するためのURLを作成して返します。
                /// URLにドメイン部分は含まれません。
                /// </summary>
                /// <param name="displayData">遷移先データ。このパラメータは画面モードが閲覧・編集の場合のみ参照されます。</param>
                /// <param name="mode">画面モード。新規か閲覧か編集か</param>
                public virtual string GetSingleViewUrlFromDisplayData({{displayData.CsClassName}} displayData, E_SingleViewType mode) {

                    if (mode == E_SingleViewType.New) {
                        return $"/{{UrlSubDomain}}/{{URL_NEW}}";

                    } else {
                {{keys.SelectTextTemplate(k => $$"""
                        var key{{k.Index}} = displayData.Values?.{{k.PhysicalName}}{{(k.IsString ? string.Empty : "?.ToString()")}};
                """)}}
                {{keys.SelectTextTemplate(k => $$"""
                        if (key{{k.Index}} == null) throw new ArgumentException($"{{k.PhysicalName}}が指定されていません。");
                """)}}
                {{keys.SelectTextTemplate(k => $$"""
                        key{{k.Index}} = System.Net.WebUtility.UrlEncode(key{{k.Index}});
                """)}}

                        var subdomain = mode == E_SingleViewType.Edit
                            ? "{{URL_EDIT}}"
                            : "{{URL_DETAIL}}";

                        return $"/{{UrlSubDomain}}/{subdomain}{{keys.Select(k => $"/{{key{k.Index}}}").Join("")}}";
                    }
                }
                /// <summary>
                /// 詳細画面を引数のオブジェクトで表示するためのURLを作成して返します。
                /// URLにドメイン部分は含まれません。
                /// </summary>
                {{keys.SelectTextTemplate(k => $$"""
                /// <param name="{{k.PhysicalName}}">{{k.DisplayName}}</param>
                """)}}
                /// <param name="mode">画面モード。新規か閲覧か編集か</param>
                public virtual string GetSingleViewUrlOf{{_aggregate.PhysicalName}}({{keys.Select(k => $"{k.TypeName} {k.PhysicalName}").Join(", ")}}, E_SingleViewType mode) {
                    if (mode == E_SingleViewType.New) {
                        return $"/{{UrlSubDomain}}/{{URL_NEW}}";

                    } else {
                        var subdomain = mode == E_SingleViewType.Edit
                            ? "{{URL_EDIT}}"
                            : "{{URL_DETAIL}}";

                        return $"/{{UrlSubDomain}}/{subdomain}{{keys.Select(k => $"/{{{k.PhysicalName}}}").Join("")}}";
                    }
                }
                """;
        }
    }
}
