using Nijo.Core;
using Nijo.Parts;
using Nijo.Parts.WebClient;
using Nijo.Parts.WebServer;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Reflection;
using Castle.Core.Resource;
using Nijo.Parts.BothOfClientAndServer;
using Microsoft.Extensions.Logging;

namespace Nijo.Util.CodeGenerating {
    public sealed class CodeRenderingContext {
        internal CodeRenderingContext(GeneratedProject app, NijoCodeGenerator.CodeGenerateOptions options) {
            GeneratedProject = app;
            CoreLibrary = new CoreLibrary.DirectoryEditor(this, app.CoreLibrary);
            WebApiProject = new WebApiProject.DirectoryEditor(this, app.WebApiProject);
            ReactProject = new ReactProject.DirectoryEditor(this, app.ReactProject);
            CliProject = new CliProject.DirectoryEditor(this, app.CliProject);

            Config = app.ReadConfig();
            Schema = app.BuildSchema();
            Options = options;
        }

        public GeneratedProject GeneratedProject { get; }

        public Config Config { get; }
        public AppSchema Schema { get; }
        public NijoCodeGenerator.CodeGenerateOptions Options { get; }

        /// <summary>自動生成されるC#クラスライブラリプロジェクト</summary>
        public CoreLibrary.DirectoryEditor CoreLibrary { get; }
        /// <summary>自動生成される ASP.NET Core API プロジェクト</summary>
        public WebApiProject.DirectoryEditor WebApiProject { get; }
        /// <summary>自動生成される React.js プロジェクト</summary>
        public ReactProject.DirectoryEditor ReactProject { get; }
        /// <summary>自動生成されるコンソールアプリケーションのプロジェクト</summary>
        public CliProject.DirectoryEditor CliProject { get; }

        /// <summary>ソースコードレンダリング中に少なくとも一度以上登場したモデル</summary>
        private readonly Dictionary<Type, Models.IModel> _handledModels = new();
        internal Models.IModel GetModel<T>() where T : Models.IModel, new() {
            if (!_handledModels.TryGetValue(typeof(T), out var model)) {
                model = new T();
                _handledModels.Add(typeof(T), model);
            }
            return model;
        }
        internal Models.IModel GetModel(string key) {
            // 該当のキーにヒットするモデルを検索
            var model = NijoCodeGenerator.Models
                .GetAll()
                .Single(kv => kv.Key == key)
                .Value
                .Invoke();
            var modelType = model.GetType();

            // 未登録の場合は登録する
            if (!_handledModels.TryGetValue(modelType, out var registered)) {
                _handledModels.Add(modelType, model);
            }
            return model;
        }

        /// <summary>
        /// 複数のソース生成処理が1つのファイルにまとめて書き込むような形のファイル。
        /// コード生成処理の途中でファイルの途中に挿入されるソースコードの文字列が五月雨で登録され、
        /// コード生成処理の最後で実ファイルにレンダリングされる。
        /// </summary>
        private readonly HashSet<ISummarizedFile> _summarizedFiles = new();
        /// <summary>
        /// コード生成処理の最後で <see cref="ISummarizedFile"/> のレンダリングが行われるよう予約します。
        /// </summary>
        /// <typeparam name="T">ファイルの型</typeparam>
        internal T UseSummarizedFile<T>() where T : ISummarizedFile, new() {
            var found = _summarizedFiles.SingleOrDefault(item => item.GetType() == typeof(T));
            if (found != null) return (T)found;

            var newInstance = new T();
            _summarizedFiles.Add(newInstance);
            return newInstance;
        }
        /// <summary>
        /// コード生成処理の最後で <see cref="ISummarizedFile"/> のレンダリングが行われるよう予約します。
        /// </summary>
        /// <param name="summarizedFile">複数のソース生成処理が1つのファイルにまとめて書き込むような形のファイル</param>
        internal void UseSummarizedFile(ISummarizedFile summarizedFile) {
            _summarizedFiles.Add(summarizedFile);
        }

        /// <summary>
        /// コード自動生成の最後に実行される処理。
        /// アプリケーション全体に影響するようなソースコードなどを生成する。
        /// </summary>
        internal void OnEndContext(ILogger? logger) {

            UseSummarizedFile<Configure>();

            // 区分値定義が存在する場合は EnumDefs を必ず登録する（集約ゼロのenum-onlyプロジェクト対応）
            if (Schema.EnumDefinitions.Any()) {
                UseSummarizedFile<Parts.WebServer.EnumDefs>();
            }

            Models.WriteModel2Features.CharacterTypeCheck.RenderLogic(this);

            CoreLibrary.UtilDir(utilDir => {
                var resources = EmbeddedResources
                    .Enumerate("core", "__AutoGenerated", "Util");
                foreach (var resource in resources) {
                    utilDir.CopyEmbeddedResource(resource, line => {
                        return line
                            .Replace("NIJO_APPLICATION_TEMPLATE_WebApi", Config.RootNamespace)
                            .Replace("NIJO_APPLICATION_TEMPLATE", Config.RootNamespace);
                    });
                }

                //utilDir.Generate(RuntimeSettings.Render(this));
                utilDir.Generate(RuntimeSettings.RenderInterface());

                utilDir.Generate(DotnetExtensions.RenderCoreLibrary());
                utilDir.Generate(Parts.BothOfClientAndServer.FromTo.Render(this));
                utilDir.Generate(Parts.WebServer.RegexCache.Render());

                utilDir.Generate(PresentationContext.RenderCSharp());
                utilDir.Generate(SpaceFinderConst.RenderCSharp());
            });

            WebApiProject.UtilDir(utilDir => {
                utilDir.Generate(AttachmentFileRepositoryWeb.Render());
                utilDir.Generate(SavingUploadedFilesFilter.Render());
                utilDir.Generate(ComplexPost.Render());
                utilDir.Generate(DotnetExtensions.RenderToWebApiProject());
            });

            ReactProject.AutoGeneratedDir(reactDir => {
                reactDir.Generate(VForm2ContainerQueryCss.RenderVFormContainerQuery());
            });

            ReactProject.UtilDir(reactUtilDir => {
                reactUtilDir.Generate(PresentationContext.RenderTypeScript());
                reactUtilDir.Generate(SpaceFinderConst.RenderTypeScript());
            });

            CliProject.AutoGeneratedDir(genDir => {
                //genDir.Generate(Configure.RenderCliConfigure());

                // フォルダが無いとエラーになるので回避
                if (!Directory.Exists(genDir.Path)) {
                    Directory.CreateDirectory(genDir.Path);
                }

                var resources = EmbeddedResources
                    .Enumerate("cli", "__AutoGenerated");
                foreach (var resource in resources) {
                    genDir.CopyEmbeddedResource(resource, line => {
                        return line
                            .Replace("NIJO_APPLICATION_TEMPLATE_Cli", Config.RootNamespace)
                            .Replace("NIJO_APPLICATION_TEMPLATE", Config.RootNamespace);
                    });
                }
            });


            // メンバー型のコード生成。列挙体の定義などの生成を行う。
            var allMemberTypes = Schema
                .AllAggregates()
                .SelectMany(agg => agg.GetMembers())
                .OfType<AggregateMember.ValueMember>()
                .Select(vm => vm.Options.MemberType)
                .Distinct();
            foreach (var memberType in allMemberTypes) {
                memberType.GenerateCode(this);
            }

            // 区分マスタ（動的列挙体）
            Models.DynamicEnum.GenerateSourceCode(this);

            // モデルと関係するがルート集約1個と対応しないソースコードを生成する
            foreach (var model in _handledModels.Values) {
                model.GenerateCode(this);
            }

            foreach (var summarizedFile in _summarizedFiles.OrderBy(x => x.RenderingOrder)) {
                logger?.LogInformation("複数集約ファイル生成開始: {file}", summarizedFile.GetType().Name);
                summarizedFile.OnEndGenerating(this);
            }

            // index.ts作成（これまでに作成されたファイルの数と場所に依存するのでこの位置で行なう必要がある）
            ReactProject.UtilDir(dir => {
                dir.Generate(new SourceFile {
                    FileName = "index.ts",
                    RenderContent = ctx => {
                        var filenames = Directory
                            .GetFiles(dir.Path)
                            .Select(path => Path.GetFileNameWithoutExtension(path).Replace("\"", "\\\""));
                        return $$"""
                            {{filenames.SelectTextTemplate(name => $$"""
                            export * from "./{{name}}"
                            """)}}
                            """;
                    },
                });
            });

            CleanUnhandledFilesAndDirectories();
        }

        public Assembly ExecutingAssembly => _executingAssembly ??= Assembly.GetExecutingAssembly();
        private Assembly? _executingAssembly;

        internal EmbeddedResource.Collection EmbeddedResources => _embeddedResources ??= new EmbeddedResource.Collection(ExecutingAssembly);
        private EmbeddedResource.Collection? _embeddedResources;

        #region 生成されなかったファイルの削除
        private readonly HashSet<string> _handled = new();
        internal void Handle(string fullpath) => _handled.Add(Path.GetFullPath(fullpath));
        internal bool IsHandled(string fullpath) => _handled.Contains(Path.GetFullPath(fullpath));
        private void CleanUnhandledFilesAndDirectories() {
            var allFiles = Directory.GetFiles(GeneratedProject.CoreLibrary.AutoGeneratedDir, "*", SearchOption.AllDirectories)
                .Concat(Directory.GetFiles(GeneratedProject.WebApiProject.AutoGeneratedDir, "*", SearchOption.AllDirectories))
                .Concat(Directory.GetFiles(GeneratedProject.ReactProject.AutoGeneratedDir, "*", SearchOption.AllDirectories))
                .Concat(Directory.GetFiles(GeneratedProject.CliProject.AutoGeneratedDir, "*", SearchOption.AllDirectories));
            foreach (var file in allFiles) {
                if (IsHandled(file)) continue;
                if (!File.Exists(file)) continue;
                File.Delete(file);
            }
            var allDirectories = Directory.GetDirectories(GeneratedProject.CoreLibrary.AutoGeneratedDir, "*", SearchOption.AllDirectories)
                .Concat(Directory.GetDirectories(GeneratedProject.WebApiProject.AutoGeneratedDir, "*", SearchOption.AllDirectories))
                .Concat(Directory.GetDirectories(GeneratedProject.ReactProject.AutoGeneratedDir, "*", SearchOption.AllDirectories))
                .Concat(Directory.GetDirectories(GeneratedProject.CliProject.AutoGeneratedDir, "*", SearchOption.AllDirectories));
            foreach (var dir in allDirectories) {
                if (IsHandled(dir)) continue;
                if (!Directory.Exists(dir)) continue;
                Directory.Delete(dir, true);
            }
        }
        #endregion 生成されなかったファイルの削除
    }
}
