using Nijo.CodeGenerating;
using Nijo.ImmutableSchema;
using Nijo.Parts.Common;
using Nijo.SchemaParsing;
using Nijo.Util.DotnetEx;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Linq;

namespace Nijo.Models {
    /// <summary>
    /// 旧版互換の静的区分値。
    /// 旧版の Enum.cs / autogenerated-enum.ts と同じ形式でコードを生成する。
    /// </summary>
    internal class StaticEnumModel2 : IModel {
        internal const string SCHEMA_NAME = "enum-2";
        public string SchemaName => SCHEMA_NAME;

        public void Validate(XElement rootAggregateElement, SchemaParseContext context, Action<XElement, string> addError) {
            var keyValues = new HashSet<int>();

            foreach (var valueElement in rootAggregateElement.Elements()) {
                var keyAttr = valueElement.Attribute(StaticEnumModelModules.StaticEnumValueDef.ATTR_KEY);
                if (keyAttr == null) {
                    addError(valueElement, "key属性が定義されていません。整数値を指定してください。");
                    continue;
                }

                if (!int.TryParse(keyAttr.Value, out int keyValue)) {
                    addError(valueElement, $"key属性の値「{keyAttr.Value}」は整数値である必要があります。");
                    continue;
                }

                if (!keyValues.Add(keyValue)) {
                    addError(valueElement, $"key値「{keyValue}」は既に他の値で使用されています。重複しない値を指定してください。");
                }
            }
        }

        public void GenerateCode(CodeRenderingContext ctx, RootAggregate rootAggregate) {
            if (!ctx.IsLegacyCompatibilityMode()) throw new InvalidOperationException("旧版互換モードでのみ利用可能");

            var xElement = ((ISchemaPathNode)rootAggregate).XElement;

            var items = xElement.Elements()
                .OrderBy(el => int.TryParse(el.Attribute(StaticEnumModelModules.StaticEnumValueDef.ATTR_KEY)?.Value, out var v) ? v : 0)
                .Select(el => new EnumFile2.EnumItemInfo(
                    PhysicalName: el.Name.LocalName.ToCSharpSafe(),
                    DisplayName: el.GetDisplayName(),
                    Value: int.Parse(el.Attribute(StaticEnumModelModules.StaticEnumValueDef.ATTR_KEY)?.Value ?? "0"),
                    IsEmptyDisplayName: false
                ))
                .ToArray();

            var enumDef = new EnumFile2.EnumDefInfo(
                Name: xElement.Name.LocalName.ToCSharpSafe(),
                Items: items
            );

            ctx.Use<EnumFile2>().AddEnum(enumDef);
        }

        public void GenerateCode(CodeRenderingContext ctx) {
            // ファイル全体に渡る処理はなし
        }
    }
}
