using System.Diagnostics;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml.Linq;
using Microsoft.Extensions.Logging;
using NUnit.Framework;

namespace Nijo.IntegrationTest;

/// <summary>
/// テスト実行1回分のコンテキスト情報。
/// <para>
/// 実行1回ごとにワークフォルダが作成され、
/// その中にテストケース単位のサブフォルダが作成される。
/// サブフォルダ内に、 nijo.xml と、自動生成されたコードが出力される。
/// </para>
/// <para>
/// dotnet や npm のコマンドラインツールによる操作も提供する。
/// </para>
/// </summary>
[SetUpFixture]
public class NijoTestUtil {

#pragma warning disable CS8618 // null 非許容のフィールドには、コンストラクターの終了時に null 以外の値が入っていなければなりません。'required' 修飾子を追加するか、Null 許容として宣言することを検討してください。
    /// <summary>
    /// テスト実行1回ごとに作成されるワークフォルダのパス。
    /// </summary>
    public static string BaseDirectory { get; private set; }
#pragma warning restore CS8618 // null 非許容のフィールドには、コンストラクターの終了時に null 以外の値が入っていなければなりません。'required' 修飾子を追加するか、Null 許容として宣言することを検討してください。

    [OneTimeSetUp]
    public void Setup() {
        // Nijo用のワークフォルダを作成
        BaseDirectory = Path.GetFullPath(Path.Combine(
            AppDomain.CurrentDomain.BaseDirectory, // net9.0
            $"Nijo.IntegrationTest.Log",
            $"テスト結果_{DateTime.Now:yyyyMMddHHmmss}_{Guid.NewGuid().ToString().Substring(0, 8)}"));

        // カレントディレクトリをワークフォルダに移動
        Directory.CreateDirectory(BaseDirectory);
        Directory.SetCurrentDirectory(BaseDirectory);
    }


    /// <summary>
    /// ワークフォルダ内部に、新しいNijoプロジェクトを作成して返します。
    /// </summary>
    /// <param name="nijoXmlContent">nijo.xml の内容。</param>
    public static async Task<GeneratedProjectWithTestUtil> CreateNewProjectAsync(string nijoXmlContent) {

        // テストケースごとのサブフォルダを作成
        var testName = TestContext.CurrentContext.Test.Name;
        var guid = Guid.NewGuid().ToString().Substring(0, 8);
        var projectRoot = Path.Combine(BaseDirectory, $"{testName}_{guid}");
        Directory.CreateDirectory(projectRoot);

        // nijo.xml を作成
        await File.WriteAllTextAsync(
            Path.Combine(projectRoot, "nijo.xml"),
            nijoXmlContent.ReplaceLineEndings("\n"),
            new UTF8Encoding(false));

        if (!GeneratedProject.TryOpen(projectRoot, out var project, out var errors)) {
            // ありえない
            throw new InvalidOperationException($"プロジェクトのオープンに失敗しました。エラー内容: {errors}");
        }
        return new GeneratedProjectWithTestUtil {
            Project = project,
            Logger = new FileLogger(Path.Combine(projectRoot, "RESULT.LOG")),
        };
    }

    /// <summary>
    /// ワークフォルダ内部に、旧版 nijo-old 用のプロジェクトディレクトリを作成して返します。
    /// 実運用環境のスキーマは参照できないため、旧記法 XML と旧版 generator の出力を
    /// diff 比較の基準として固定する用途を想定します。
    /// </summary>
    public static async Task<LegacyGeneratedProjectWithTestUtil> CreateLegacyProjectAsync(string legacyNijoXmlContent) {
        var testName = TestContext.CurrentContext.Test.Name;
        var guid = Guid.NewGuid().ToString().Substring(0, 8);
        var projectRoot = Path.Combine(BaseDirectory, $"{testName}_legacy_{guid}");
        Directory.CreateDirectory(projectRoot);

        await File.WriteAllTextAsync(
            Path.Combine(projectRoot, "nijo.xml"),
            legacyNijoXmlContent.ReplaceLineEndings("\n"),
            new UTF8Encoding(false));

        await File.WriteAllTextAsync(
            Path.Combine(projectRoot, "nijo.メッセージ一覧.xml"),
            BuildLegacyMessageXml(),
            new UTF8Encoding(false));

        // 旧版 generator はテンプレート一式の存在を前提とするが、現ワークスペースには含まれていない。
        // 生成コードの比較基準を作る今回のテストでは、自動生成先ディレクトリだけ先に用意して
        // generator が __AutoGenerated 以下へ出力できるようにする。
        Directory.CreateDirectory(Path.Combine(projectRoot, "core.AutoGenerated", "__AutoGenerated"));
        Directory.CreateDirectory(Path.Combine(projectRoot, "webapi", "__AutoGenerated"));
        Directory.CreateDirectory(Path.Combine(projectRoot, "react", "src", "__autoGenerated"));
        Directory.CreateDirectory(Path.Combine(projectRoot, "cli", "__AutoGenerated"));

        return new LegacyGeneratedProjectWithTestUtil {
            ProjectRoot = projectRoot,
            Logger = new FileLogger(Path.Combine(projectRoot, "RESULT.LEGACY.LOG")),
        };
    }

    /// <summary>
    /// Nijo プロジェクトを表すインスタンスと、
    /// そのテストユーティリティをまとめたクラス。
    /// </summary>
    public class GeneratedProjectWithTestUtil : IDisposable {
        /// <summary>
        /// Nijo プロジェクトのインスタンス。
        /// コード自動生成の実行などはこのインスタンスを通じて行う。
        /// </summary>
        public required GeneratedProject Project { get; init; }
        /// <summary>
        /// コード自動生成処理などの実行時には <see cref="ILogger"/> のインスタンスが必要になるが、
        /// その結果をテスト毎に作成されるワークフォルダに出力するためのもの。
        /// </summary>
        public required ILogger Logger { get; init; }

        void IDisposable.Dispose() {
            var result = TestContext.CurrentContext.Result;
            if (result.Outcome.Status == NUnit.Framework.Interfaces.TestStatus.Failed) {
                Logger.LogError("TEST FAILED: {Message}\n{StackTrace}", result.Message, result.StackTrace);
            }
        }

        /// <summary>
        /// スキーマ検証エラーを列挙する。
        /// </summary>
        public async Task<SchemaParsing.SchemaParseContext.ValidationError[]> EnumerateValidationErrorsAsync() {
            try {
                using var reader = File.OpenRead(Project.SchemaXmlPath);
                var document = await XDocument.LoadAsync(reader, LoadOptions.None, CancellationToken.None);
                var rule = SchemaParsing.SchemaParseRule.Default();
                var parseContext = new SchemaParsing.SchemaParseContext(document, rule);

                parseContext.TryBuildSchema(document, out var _, out var errors);
                return errors;
            } catch (Exception ex) {
                Logger.LogError(ex, "EnumerateValidationErrorsAsyncで例外が発生しました。");
                throw;
            }
        }

        /// <summary>
        /// <see cref="GeneratedProject.GenerateCode"/> の呼び出し方が少々煩雑なのでラップしたもの
        /// </summary>
        public async Task<bool> GenerateCodeAsync() {
            try {
                using var reader = File.OpenRead(Project.SchemaXmlPath);
                var document = await XDocument.LoadAsync(reader, LoadOptions.None, CancellationToken.None);
                var rule = SchemaParsing.SchemaParseRule.Default();
                var parseContext = new SchemaParsing.SchemaParseContext(document, rule);
                var renderingOptions = new CodeGenerating.CodeRenderingOptions {
                    AllowNotImplemented = false,
                };
                return Project.GenerateCode(parseContext, renderingOptions, Logger);
            } catch (Exception ex) {
                Logger.LogError(ex, "GenerateCodeAsyncで例外が発生しました。");
                throw;
            }
        }

        /// <summary>
        /// コンパイルエラーが発生しないかを確認する。詳細な結果はログファイルに出力される。
        ///
        /// C#: dotnet build の実行
        /// TypeScript: npm run check の実行
        /// </summary>
        public async Task<bool> CheckCompileAsync() {
            try {
                // C# や TypeScript のビルド確認用のファイルを作成
                await File.WriteAllTextAsync(
                    Path.Combine(Project.ProjectRoot, "NijoGeneratedCode.csproj"),
                    DEFAULT_CSPROJ,
                    new UTF8Encoding(false));
                await File.WriteAllTextAsync(
                    Path.Combine(Project.ProjectRoot, "package.json"),
                    DEFAULT_PACKAGE_JSON,
                    new UTF8Encoding(false));
                await File.WriteAllTextAsync(
                    Path.Combine(Project.ProjectRoot, "tsconfig.json"),
                    DEFAULT_TSCONFIG_JSON,
                    new UTF8Encoding(false));

                // このクラスだけは予め手作業で作成されていないとコンパイルが通らない
                await File.WriteAllTextAsync(
                    Path.Combine(Project.ProjectRoot, "AutoGeneratedControllerBase.cs"),
                    $$"""
                namespace {{Project.GetConfig().RootNamespace}};

                // 本来はプロジェクトテンプレートに含まれ、自動生成コードから参照されるクラス。
                // ここではコンパイルエラー確認用に最低限の内容だけを定義している。
                public abstract class AutoGeneratedControllerBase : Microsoft.AspNetCore.Mvc.ControllerBase {
                    protected Task<Microsoft.AspNetCore.Mvc.IActionResult> Handle<TMessageRoot>(Func<IPresentationContext<TMessageRoot>, Task> appSrvMethod)
                        where TMessageRoot : IMessageSetter {
                        throw new NotImplementedException();
                    }
                    protected Task<Microsoft.AspNetCore.Mvc.IActionResult> Handle<TReturnValue, TMessageRoot>(Func<IPresentationContextWithReturnValue<TReturnValue, TMessageRoot>, Task> appSrvMethod)
                        where TMessageRoot : IMessageSetter
                        where TReturnValue : new() {
                        throw new NotImplementedException();
                    }
                    protected Task<Microsoft.AspNetCore.Mvc.IActionResult> Handle<TParameter, TMessageRoot>(Func<TParameter, IPresentationContext<TMessageRoot>, Task> appSrvMethod)
                        where TMessageRoot : IMessageSetter {
                        throw new NotImplementedException();
                    }
                    protected Task<Microsoft.AspNetCore.Mvc.IActionResult> Handle<TParameter, TReturnValue, TMessageRoot>(Func<TParameter, IPresentationContextWithReturnValue<TReturnValue, TMessageRoot>, Task> appSrvMethod)
                        where TMessageRoot : IMessageSetter
                        where TReturnValue : new() {
                        throw new NotImplementedException();
                    }
                }
                """,
                    new UTF8Encoding(false));

                // 2つを並列実行して待機
                var results = await Task.WhenAll(
                    RunCommandAsync("dotnet", "build", "RESULT_CS.log"),
                    RunCommandAsync("npm", "run check", "RESULT_TS.log")
                );
                return results.All(ok => ok);
            } catch (Exception ex) {
                Logger.LogError(ex, "CheckCompileAsyncで例外が発生しました。");
                throw;
            }
        }

        private async Task<bool> RunCommandAsync(string fileName, string arguments, string logFileName) {
            return await RunCommandCoreAsync(fileName, arguments, Project.ProjectRoot, logFileName, Logger);
        }
    }

    /// <summary>
    /// 旧版 generator を外部プロセスで呼び出すためのテストユーティリティ。
    /// </summary>
    public class LegacyGeneratedProjectWithTestUtil : IDisposable {
        public required string ProjectRoot { get; init; }
        public required ILogger Logger { get; init; }

        public string CoreAutoGeneratedDir => Path.Combine(ProjectRoot, "core.AutoGenerated", "__AutoGenerated");
        public string WebApiAutoGeneratedDir => Path.Combine(ProjectRoot, "webapi", "__AutoGenerated");
        public string ReactAutoGeneratedDir => Path.Combine(ProjectRoot, "react", "src", "__autoGenerated");
        public string CliAutoGeneratedDir => Path.Combine(ProjectRoot, "cli", "__AutoGenerated");

        void IDisposable.Dispose() {
            var result = TestContext.CurrentContext.Result;
            if (result.Outcome.Status == NUnit.Framework.Interfaces.TestStatus.Failed) {
                Logger.LogError("TEST FAILED: {Message}\n{StackTrace}", result.Message, result.StackTrace);
            }
        }

        public async Task<bool> GenerateCodeAsync() {
            try {
                await EnsureLegacyGeneratorBuiltAsync();
                var legacyDll = Path.Combine(WorkspaceRoot, "nijo-old", "bin", "Debug", "net9.0", "nijo.dll");
                var succeeded = await RunCommandCoreAsync(
                    "dotnet",
                    $"\"{legacyDll}\" update \"{ProjectRoot}\"",
                    ProjectRoot,
                    "RESULT_LEGACY_GENERATE.log",
                    Logger);
                if (!succeeded) return false;

                return Directory.EnumerateFiles(CoreAutoGeneratedDir, "*.cs", SearchOption.AllDirectories).Any()
                    || Directory.EnumerateFiles(WebApiAutoGeneratedDir, "*.cs", SearchOption.AllDirectories).Any()
                    || Directory.EnumerateFiles(ReactAutoGeneratedDir, "*.ts", SearchOption.AllDirectories).Any()
                    || Directory.EnumerateFiles(ReactAutoGeneratedDir, "*.tsx", SearchOption.AllDirectories).Any()
                    || Directory.EnumerateFiles(CliAutoGeneratedDir, "*.cs", SearchOption.AllDirectories).Any();
            } catch (Exception ex) {
                Logger.LogError(ex, "Legacy GenerateCodeAsyncで例外が発生しました。");
                throw;
            }
        }

        public async Task<bool> CheckCompileAsync() {
            try {
                await File.WriteAllTextAsync(
                    Path.Combine(ProjectRoot, "LegacyGeneratedCode.csproj"),
                    BuildLegacyCompileProject(ProjectRoot),
                    new UTF8Encoding(false));

                await File.WriteAllTextAsync(
                    Path.Combine(ProjectRoot, "LegacyCompileSupport.cs"),
                    "namespace LegacyCompileSupport; public static class Placeholder { }" + Environment.NewLine,
                    new UTF8Encoding(false));

                return await RunCommandCoreAsync(
                    "dotnet",
                    "build LegacyGeneratedCode.csproj",
                    ProjectRoot,
                    "RESULT_LEGACY_CS.log",
                    Logger);
            } catch (Exception ex) {
                Logger.LogError(ex, "Legacy CheckCompileAsyncで例外が発生しました。");
                throw;
            }
        }
    }

    private static async Task EnsureLegacyGeneratorBuiltAsync() {
        var legacyDll = Path.Combine(WorkspaceRoot, "nijo-old", "bin", "Debug", "net9.0", "nijo.dll");
        if (File.Exists(legacyDll)) return;

        var logger = new FileLogger(Path.Combine(BaseDirectory, "RESULT.LEGACY.BUILD.LOG"));
        var ok = await RunCommandCoreAsync(
            "dotnet",
            $"build \"{Path.Combine(WorkspaceRoot, "nijo-old", "Nijo.csproj")}\"",
            WorkspaceRoot,
            "RESULT_LEGACY_BUILD.log",
            logger);
        if (!ok) {
            throw new InvalidOperationException("旧版 generator のビルドに失敗しました。");
        }
    }

    private static async Task<bool> RunCommandCoreAsync(string fileName, string arguments, string workingDirectory, string logFileName, ILogger logger) {
        var psi = new ProcessStartInfo {
            FileName = fileName,
            Arguments = arguments,
            WorkingDirectory = workingDirectory,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
            CreateNoWindow = true,
            StandardOutputEncoding = Encoding.UTF8,
            StandardErrorEncoding = Encoding.UTF8,
        };

        using var process = Process.Start(psi);
        if (process == null) throw new InvalidOperationException($"プロセスを開始できませんでした: {fileName} {arguments}");

        var stdout = await process.StandardOutput.ReadToEndAsync();
        var stderr = await process.StandardError.ReadToEndAsync();
        await process.WaitForExitAsync();

        var logPath = Path.Combine(workingDirectory, logFileName);
        var sb = new StringBuilder();
        sb.AppendLine($"COMMAND: {fileName} {arguments}");
        sb.AppendLine($"EXIT_CODE: {process.ExitCode}");
        sb.AppendLine("--------------------------------------------------");
        sb.AppendLine("STDOUT:");
        sb.AppendLine(stdout);
        sb.AppendLine("--------------------------------------------------");
        sb.AppendLine("STDERR:");
        sb.AppendLine(stderr);

        await File.WriteAllTextAsync(logPath, sb.ToString(), new UTF8Encoding(false));

        if (process.ExitCode != 0) {
            logger.LogError("Command failed: {FileName} {Arguments} (ExitCode: {ExitCode})", fileName, arguments, process.ExitCode);
        } else {
            logger.LogInformation("Command success: {FileName} {Arguments}", fileName, arguments);
        }

        return process.ExitCode == 0;
    }

    private static string BuildLegacyMessageXml() {
        var messageConstPath = Path.Combine(WorkspaceRoot, "nijo-old", "Features", "MessageConst", "MessageConst.cs");
        var source = File.ReadAllText(messageConstPath, Encoding.UTF8);
        var ids = Regex.Matches(source, "= \"(?<id>(?:ERRC|INFC|CNFC|INF)[A-Z0-9]+)\";")
            .Select(match => match.Groups["id"].Value)
            .Distinct()
            .OrderBy(id => id)
            .ToArray();

        var root = new XElement("Messages",
            ids.Select(id => new XElement(id, id)));
        return new XDocument(root).ToString();
    }

    private static string BuildLegacyCompileProject(string projectRoot) {
        var compileFiles = Directory.EnumerateFiles(projectRoot, "*.cs", SearchOption.AllDirectories)
            .Where(path => !path.EndsWith(Path.Combine("obj", ""), StringComparison.Ordinal))
            .Where(path => !path.Contains($"{Path.DirectorySeparatorChar}obj{Path.DirectorySeparatorChar}"))
            .Where(path => !path.Contains($"{Path.DirectorySeparatorChar}bin{Path.DirectorySeparatorChar}"))
            .Where(path => !path.Contains($"{Path.DirectorySeparatorChar}react{Path.DirectorySeparatorChar}"))
            .Select(path => Path.GetRelativePath(projectRoot, path).Replace(Path.DirectorySeparatorChar, '/'))
            .OrderBy(path => path)
            .ToArray();

        var builder = new StringBuilder();
        builder.AppendLine("<Project Sdk=\"Microsoft.NET.Sdk\">");
        builder.AppendLine("  <PropertyGroup>");
        builder.AppendLine("    <OutputType>Library</OutputType>");
        builder.AppendLine("    <TargetFramework>net9.0</TargetFramework>");
        builder.AppendLine("    <Nullable>enable</Nullable>");
        builder.AppendLine("    <ImplicitUsings>enable</ImplicitUsings>");
        builder.AppendLine("    <EnableDefaultItems>false</EnableDefaultItems>");
        builder.AppendLine("  </PropertyGroup>");
        builder.AppendLine("  <ItemGroup>");
        builder.AppendLine("    <FrameworkReference Include=\"Microsoft.AspNetCore.App\" />");
        builder.AppendLine("    <PackageReference Include=\"Microsoft.AspNetCore.OpenApi\" Version=\"9.*\" />");
        builder.AppendLine("    <PackageReference Include=\"Microsoft.EntityFrameworkCore\" Version=\"9.*\" />");
        builder.AppendLine("    <PackageReference Include=\"Microsoft.EntityFrameworkCore.Proxies\" Version=\"9.*\" />");
        builder.AppendLine("    <PackageReference Include=\"Microsoft.EntityFrameworkCore.Relational\" Version=\"9.*\" />");
        builder.AppendLine("    <PackageReference Include=\"Microsoft.Extensions.Logging.Console\" Version=\"9.*\" />");
        builder.AppendLine("    <PackageReference Include=\"System.CodeDom\" Version=\"9.*\" />");
        builder.AppendLine("  </ItemGroup>");
        builder.AppendLine("  <ItemGroup>");
        foreach (var path in compileFiles) {
            builder.AppendLine($"    <Compile Include=\"{path}\" />");
        }
        builder.AppendLine("  </ItemGroup>");
        builder.AppendLine("</Project>");
        return builder.ToString();
    }

    private static string WorkspaceRoot => _workspaceRoot ??= ResolveWorkspaceRoot();
    private static string? _workspaceRoot;

    private static string ResolveWorkspaceRoot() {
        var dir = new DirectoryInfo(AppDomain.CurrentDomain.BaseDirectory);
        while (dir != null) {
            if (File.Exists(Path.Combine(dir.FullName, "nijo.sln"))) {
                return dir.FullName;
            }
            dir = dir.Parent;
        }
        throw new InvalidOperationException("ワークスペースルート(nijo.sln)を解決できませんでした。");
    }

    /// <summary>
    /// ファイルにログを書き込む単純なロガー。
    /// </summary>
    private class FileLogger : ILogger {
        private readonly string _logFilePath;
        private readonly Lock _lock = new();

        public FileLogger(string logFilePath) {
            _logFilePath = logFilePath;
        }

        public IDisposable? BeginScope<TState>(TState state) where TState : notnull => null;

        public bool IsEnabled(LogLevel logLevel) => true;

        public void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception? exception, Func<TState, Exception?, string> formatter) {
            if (!IsEnabled(logLevel)) return;

            var message = formatter(state, exception);
            var logRecord = $"[{DateTime.Now:yyyy-MM-dd HH:mm:ss.fff}] [{logLevel}] {message}";
            if (exception != null) {
                logRecord += Environment.NewLine + exception.ToString();
            }
            logRecord += Environment.NewLine;

            lock (_lock) {
                File.AppendAllText(_logFilePath, logRecord);
            }
        }
    }

    /// <summary>
    /// C# のコンパイルエラーを確認するための最低限の .csproj ファイルの内容。
    /// </summary>
    private const string DEFAULT_CSPROJ = """
        <Project Sdk="Microsoft.NET.Sdk">
          <PropertyGroup>
            <OutputType>Library</OutputType>
            <TargetFramework>net9.0</TargetFramework>
            <Nullable>enable</Nullable>
            <ImplicitUsings>enable</ImplicitUsings>
          </PropertyGroup>
          <ItemGroup>
            <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.*" />
            <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.*" />
            <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.*" />
          </ItemGroup>
        </Project>
        """;

    /// <summary>
    /// TypeScript のコンパイルエラーを確認するための最低限の package.json ファイルの内容。
    /// </summary>
    private const string DEFAULT_PACKAGE_JSON = """
        {
          "name": "nijo-generated-code-check",
          "private": true,
          "version": "0.0.0",
          "type": "module",
          "scripts": {
            "check": "tsc --noEmit"
          },
          "devDependencies": {
            "typescript": "^5.0.0"
          }
        }
        """;

    /// <summary>
    /// TypeScript のコンパイルエラーを確認するための最低限の tsconfig.json ファイルの内容。
    /// </summary>
    private const string DEFAULT_TSCONFIG_JSON = """
        {
          "compilerOptions": {
            "target": "ES2020",
            "useDefineForClassFields": true,
            "lib": ["ES2020", "DOM", "DOM.Iterable"],
            "module": "ESNext",
            "skipLibCheck": true,
            "moduleResolution": "bundler",
            "allowImportingTsExtensions": true,
            "resolveJsonModule": true,
            "isolatedModules": true,
            "noEmit": true,
            "jsx": "react-jsx",
            "strict": true,
            "noUnusedLocals": false,
            "noUnusedParameters": false,
            "noFallthroughCasesInSwitch": true
          },
          "include": ["**/*.ts", "**/*.tsx"],
          "exclude": ["node_modules"]
        }
        """;
}
