import * as AutoGenerated from "../__autoGenerated"
import { defineAutoSearchDialog, type SearchConditionBase, type SearchDialog } from "../ui"
import { callComplexPostEndpointAsync } from "../example/callComplexPostEndpointAsync"

/**
 * 個別に定義した検索ダイアログの対応表の型。キーは外部参照先。
 * この型は空で、個別に定義した検索ダイアログのモジュールがモジュール拡張でキーと型を足す。
 *
 * 登録の例:
 * ```ts
 * export const searchDialogs = {
 *   'ref-to:従業員': 従業員検索ダイアログ,
 * }
 * declare module "（このファイルへの相対パス）" {
 *   interface 個別検索ダイアログ一覧 {
 *     'ref-to:従業員': typeof 従業員検索ダイアログ
 *   }
 * }
 * ```
 */
export interface 個別検索ダイアログ一覧 { }

/**
 * 外部参照先と検索ダイアログの対応表。
 * 画面のルートに置いた SearchDialogHost に渡す。
 *
 * 業務画面のフォルダ配下のモジュールが export する searchDialogs を集めたものに、
 * それ以外の外部参照先の、メタデータから組み立てた検索ダイアログを足したもの。
 * 個別に定義した検索ダイアログのモジュールを削除すると、その参照先はメタデータから組み立てた検索ダイアログになる。
 */
export const 検索ダイアログ一覧 = withAutoSearchDialogs(collectDefinedSearchDialogs())

// 外部参照の入力欄が、項目の name から検索ダイアログとそのパラメータの型を決められるよう、対応表の型を登録する
type 検索ダイアログ一覧 = typeof 検索ダイアログ一覧
declare module "../ui/search-dialog/SearchDialogRegistry" {
  interface SearchDialogRegistry extends 検索ダイアログ一覧 { }
}

/** 業務画面のフォルダ配下のモジュールが export する searchDialogs を1つの対応表にまとめる */
function collectDefinedSearchDialogs(): 個別検索ダイアログ一覧 {
  const modules = import.meta.glob<{ searchDialogs?: Partial<個別検索ダイアログ一覧> }>("../pages/**/*.{ts,tsx}", { eager: true })
  return Object.assign({}, ...Object.values(modules).map(module => module.searchDialogs ?? {}))
}

/** 個別に定義した検索ダイアログの対応表。キーは外部参照先 */
type DefinedSearchDialogs = { [K in AutoGenerated.ReferedQueryModelType]?: SearchDialog<any, any> }

/** メタデータから組み立てた検索ダイアログの対応表。自動で組み立てられない参照先（子孫集約への参照）は含まない */
type AutoSearchDialogs = { [K in AutoGenerated.ReferedQueryModelType]?: SearchDialog<AutoGenerated.RefTarget.TypeMap[K]> }

/**
 * 個別に定義した検索ダイアログの対応表に、それ以外の外部参照先の検索ダイアログを足して返す。
 * 足す検索ダイアログは、参照先のクエリモデルのメタデータから組み立てたもの。
 * 個別に定義した参照先については、メタデータからは組み立てない。
 */
function withAutoSearchDialogs<TDefined extends DefinedSearchDialogs>(defined: TDefined): Omit<AutoSearchDialogs, keyof TDefined> & TDefined {
  const dialogs: DefinedSearchDialogs = {}
  for (const refTo of Object.keys(AutoGenerated.RefTarget.metadata) as AutoGenerated.ReferedQueryModelType[]) {
    if (refTo in defined) continue
    const metadata = AutoGenerated.RefTarget.metadata[refTo]
    if (metadata === undefined) continue

    // 対応表に含まれる参照先はルート集約なので、参照先の名前がそのままクエリモデルの種類になる
    const queryModel = refTo.slice(REF_TO_PREFIX.length) as AutoGenerated.QueryModelType
    dialogs[refTo] = defineAutoSearchDialog<SearchConditionBase, AutoGenerated.RefTarget.TypeMap[typeof refTo]>({
      title: queryModel,
      autoGenerated: {
        metadata,
        createNewSearchCondition: AutoGenerated.SearchCondition.create[queryModel],
      },
      search: (condition, signal) => callComplexPostEndpointAsync(
        refTo,
        condition as AutoGenerated.LoadRefFeature.ParamType[typeof refTo],
        { ignoreConfirm: true, signal }),
    })
  }
  return { ...dialogs, ...defined } as Omit<AutoSearchDialogs, keyof TDefined> & TDefined
}

/** 外部参照先の名前の接頭辞 */
const REF_TO_PREFIX = 'ref-to:'
