using Nijo.Util.CodeGenerating;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Nijo.Parts.WebClient {
    /// <summary>
    /// autogenerated-menu.tsx ファイル
    /// </summary>
    internal class MenuTsx : ISummarizedFile {

        public class MenuItem {
            public required string Url { get; set; }
            public required string ImportAs { get; set; }
        }
        private readonly List<MenuItem> _menuItems = new();
        public void AddMenuItem(MenuItem menuItem) {
            _menuItems.Add(menuItem);
        }

        public void OnEndGenerating(CodeRenderingContext context) {
            context.ReactProject.AutoGeneratedDir(dir => {
                dir.Generate(Render());
            });
        }

        private SourceFile Render() => new SourceFile {
            FileName = "autogenerated-menu.tsx",
            RenderContent = context => $$"""
                import React from 'react'

                /** 自動生成された React router のルーティング設定 */
                export type IAutoGeneratedRoutes = {
                {{_menuItems.SelectTextTemplate(menu => $$"""
                  /** {{menu.ImportAs}} */
                  '{{menu.Url.Replace("'", "\\'")}}': React.ReactNode | null
                """)}}
                  /** トップページ */
                  '/': React.ReactNode | null
                  /** 設定画面 */
                  '/settings': React.ReactNode | null
                  /** Not Found */
                  '*': React.ReactNode | null
                }

                """,
        };
    }
}
