using Nijo.CodeGenerating;
using Nijo.ImmutableSchema;
using Nijo.Parts.CSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;

namespace Nijo.Models.WriteModel2Modules {
    /// <summary>
    /// WriteModel2 の一括更新処理を担当する移植先。
    /// </summary>
    internal class BatchUpdateWriteModel : IMultiAggregateSourceFile {
        private readonly Lock _lock = new();
        private readonly HashSet<RootAggregate> _rootAggregates = [];

        /// <summary>
        /// 一括更新対象のルート集約を登録する。
        /// </summary>
        /// <remarks>
        /// 実装方針: 旧版 WriteModel2Features.BatchUpdateWriteModel の登録責務を移し、
        /// ルート集約ごとの一括更新 API を model-wide の共有ファイルへ集約する。
        /// 旧版では React hook, controller action, AppSrv method の3系統をまとめて持っていたため、
        /// 現行でも shared renderer がその3出力のハブになる前提で実装する。
        /// </remarks>
        internal BatchUpdateWriteModel Register(RootAggregate rootAggregate) {
            lock (_lock) {
                _rootAggregates.Add(rootAggregate);
            }
            return this;
        }

        /// <summary>
        /// 一括更新処理が依存する共有ソースを登録する。
        /// </summary>
        /// <remarks>
        /// 実装方針: SaveContext や MessageContainer など、複数集約共有の依存をここで宣言する。
        /// </remarks>
        void IMultiAggregateSourceFile.RegisterDependencies(IMultiAggregateSourceFileManager ctx) {
            ctx.Use<SaveContext>();
            ctx.Use<DataClassForSaveBase>();
        }

        /// <summary>
        /// 一括更新処理の共通ソースを出力する。
        /// </summary>
        /// <remarks>
        /// 実装方針: 旧版の AppSrv / WebAPI / TypeScript の一括更新責務を、現行の shared rendering へ再配置する。
        /// 必要出力は少なくとも 1) react 側の batch-update helper, 2) controller action, 3) AppSrv batch update method。
        /// AppSrv では create/update/delete コマンドの仕分け、データフロー順実行、エラー時 rollback を維持する。
        /// </remarks>
        void IMultiAggregateSourceFile.Render(CodeRenderingContext ctx) {
            var roots = Snapshot()
                .OrderBy(root => root.GetIndexOfDataFlow())
                .ToArray();
            if (roots.Length == 0) return;

            if (ctx.IsLegacyCompatibilityMode()) {
                ctx.WebapiProject(autoGenerated => {
                    autoGenerated.Directory("Controller", dir => {
                        dir.Generate(new SourceFile {
                            FileName = "BatchUpdateController.cs",
                            Contents = RenderLegacyBatchUpdateController(ctx),
                        });
                    });
                });
            }
        }

        private static string RenderLegacyBatchUpdateController(CodeRenderingContext ctx) {
            return $$"""
                using Microsoft.AspNetCore.Mvc;

                namespace {{ctx.Config.RootNamespace}};

                [ApiController]
                [Route("api/batch-update")]
                public partial class BatchUpdateController : ControllerBase {
                    public BatchUpdateController(OverridedApplicationService applicationService) {
                        _applicationService = applicationService;
                    }

                    private readonly OverridedApplicationService _applicationService;

                    #region WriteModel一括更新
                    /// <summary>
                    /// 一括更新処理を実行します。
                    /// </summary>
                    /// <param name="parameter">一括更新内容</param>
                    /// <param name="ignoreConfirm">「○○ですがよろしいですか？」などのコンファームを無視します。</param>
                    [HttpPost("immediately")]
                    public virtual IActionResult ExecuteImmediately([FromBody] WriteModelsBatchUpdateParameter parameter, [FromQuery] bool ignoreConfirm) {
                        _applicationService.Log.Debug("Batch Update: {0}", Request.Form[ComplexPostRequest.PARAM_DATA].ToString());

                        var options = new {{SaveContext.SAVE_OPTIONS}} {
                            IgnoreConfirm = ignoreConfirm,
                        };
                        var result = _applicationService.BatchUpdateWriteModels(parameter.Items, options);

                        if (result.HasError()) {
                            return BadRequest(result.GetErrorDataJson());
                        }
                        return Ok();
                    }
                    public partial class WriteModelsBatchUpdateParameter {
                        public List<{{DataClassForSaveBase.SAVE_COMMAND_BASE}}> Items { get; set; } = new();
                    }
                    #endregion WriteModel一括更新
                }
                """;
        }

        private RootAggregate[] Snapshot() {
            lock (_lock) {
                return _rootAggregates.ToArray();
            }
        }
    }
}
