using Nijo.CodeGenerating;
using Nijo.ImmutableSchema;
using Nijo.Parts.CSharp;
using Nijo.Util.DotnetEx;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;

namespace Nijo.Models.WriteModel2Modules {
    /// <summary>
    /// 保存用データ型の共通基底を担当する移植先。
    /// </summary>
    internal class DataClassForSaveBase : IMultiAggregateSourceFile {
        internal const string SAVE_COMMAND_BASE = "SaveCommandBase";
        internal const string CREATE_COMMAND = "CreateCommand";
        internal const string UPDATE_COMMAND = "UpdateCommand";
        internal const string DELETE_COMMAND = "DeleteCommand";
        internal const string NO_OPERATION = "NoOperation";

        internal const string VALUES_CS = "Values";
        internal const string VALUES_TS = "values";
        internal const string VERSION_CS = "Version";
        internal const string VERSION_TS = "version";
        internal const string ADD_MOD_DEL_CS = "AddOrModOrDel";
        internal const string ADD_MOD_DEL_TS = "addOrModOrDel";
        internal const string ADD_MOD_DEL_ENUM_CS = "E_AddOrModOrDel";
        internal const string ADD_MOD_DEL_ENUM_TS = "AddOrModOrDelType";
        internal const string GET_ADD_MOD_DEL_ENUM_TS = "getAddOrModOrDelType";
        internal const string DATA_TYPE_CS = "DataType";
        internal const string DATA_TYPE_TS = "dataType";

        private readonly Lock _lock = new();
        private readonly HashSet<RootAggregate> _rootAggregates = [];

        /// <summary>
        /// 保存用共通基底型が必要なルート集約を登録する。
        /// </summary>
        /// <remarks>
        /// 実装方針: 旧版 DataClassForSaveBase の基底 DTO 群を、現行 shared file として一度だけ生成する。
        /// 対応する旧版出力は SaveCommandBase, CreateCommand, UpdateCommand, DeleteCommand, NoOperation,
        /// JSON コンバータ、および add/mod/del 判定用の enum / TypeScript 型。
        /// </remarks>
        internal DataClassForSaveBase Register(RootAggregate rootAggregate) {
            lock (_lock) {
                _rootAggregates.Add(rootAggregate);
            }
            return this;
        }

        /// <summary>
        /// 保存用共通基底型の依存ソースを登録する。
        /// </summary>
        /// <remarks>
        /// 実装方針: MessageContainer や enum など、基底 DTO が参照する shared source を宣言する。
        /// 少なくとも ApplicationService / MessageContainer / MsgFactory との接続点をここで明示する。
        /// </remarks>
        void IMultiAggregateSourceFile.RegisterDependencies(IMultiAggregateSourceFileManager ctx) {
        }

        /// <summary>
        /// 保存用共通基底型の共有ソースを出力する。
        /// </summary>
        /// <remarks>
        /// 実装方針: create/update/delete で共通に使う C# / TypeScript の基底 DTO をここで生成する。
        /// 出力先は core 側 Util 配下の共通 C# ファイルと、react 側 util 相当の TypeScript ファイルを想定する。
        /// </remarks>
        void IMultiAggregateSourceFile.Render(CodeRenderingContext ctx) {
            ctx.CoreLibrary(autoGenerated => {
                autoGenerated.Directory("Util", utilDir => {
                    utilDir.Generate(new SourceFile {
                        FileName = "SaveCommandBase.cs",
                        Contents = RenderCSharpBaseClass(ctx),
                    });
                });
            });

            ctx.ReactProject(autoGenerated => {
                autoGenerated.Directory("util", utilDir => {
                    utilDir.Generate(new SourceFile {
                        FileName = ctx.IsLegacyCompatibilityMode() ? "batch-update.ts" : "write-model2-save-command.ts",
                        Contents = RenderTypeScriptBaseTypes(),
                    });
                });
            });
        }

        private string RenderCSharpBaseClass(CodeRenderingContext ctx) {
            if (ctx.IsLegacyCompatibilityMode()) {
                return $$"""
                    using System.Text.Json.Serialization;

                    namespace {{ctx.Config.RootNamespace}};

                    /// <summary>
                    /// なんらかの集約の新規登録・更新・削除のいずれかのパラメータ。
                    /// 一括更新のWebAPIでは多種多様な種類のオブジェクトが一気に送られてくるので
                    /// どの集約の更新なのか、新規登録・更新・削除のどれなのかが混在している。
                    /// JSONからのデシリアライズ時、オブジェクトに付随している区分値を参照してそれらのうちどれなのかを判断する。
                    /// </summary>
                    public abstract class {{SAVE_COMMAND_BASE}} {
                    }

                    /// <summary>
                    /// 新規データ登録パラメータ
                    /// </summary>
                    public partial class {{CREATE_COMMAND}}<T> : {{SAVE_COMMAND_BASE}} {
                        /// <summary>新規登録内容</summary>
                        [JsonPropertyName("{{VALUES_TS}}")]
                        public required T {{VALUES_CS}} { get; init; }
                    }
                    /// <summary>
                    /// 既存データ更新パラメータ
                    /// </summary>
                    public partial class {{UPDATE_COMMAND}}<T> : {{SAVE_COMMAND_BASE}} {
                        /// <summary>更新内容</summary>
                        [JsonPropertyName("{{VALUES_TS}}")]
                        public required T {{VALUES_CS}} { get; init; }
                        /// <summary>楽観排他制御用のバージョニング情報</summary>
                        [JsonPropertyName("{{VERSION_TS}}")]
                        public required int {{VERSION_CS}} { get; init; }
                    }
                    /// <summary>
                    /// 既存データ削除パラメータ
                    /// </summary>
                    public partial class {{DELETE_COMMAND}}<T> : {{SAVE_COMMAND_BASE}} {
                        /// <summary>削除内容</summary>
                        [JsonPropertyName("{{VALUES_TS}}")]
                        public required T {{VALUES_CS}} { get; init; }
                        /// <summary>楽観排他制御用のバージョニング情報</summary>
                        [JsonPropertyName("{{VERSION_TS}}")]
                        public required int {{VERSION_CS}} { get; init; }
                    }
                    /// <summary>
                    /// 既存データを更新も削除もしない
                    /// </summary>
                    public partial class {{NO_OPERATION}}<T> : {{SAVE_COMMAND_BASE}} {
                        /// <summary>データ内容</summary>
                        [JsonPropertyName("{{VALUES_TS}}")]
                        public required T {{VALUES_CS}} { get; init; }
                        /// <summary>楽観排他制御用のバージョニング情報</summary>
                        [JsonPropertyName("{{VERSION_TS}}")]
                        public required int {{VERSION_CS}} { get; init; }
                    }
                    """;
            }

            return $$"""
                using System.Text.Json.Serialization;

                namespace {{ctx.Config.RootNamespace}};

                /// <summary>
                /// WriteModel2 の一括保存コマンドの基底型。
                /// </summary>
                public abstract class {{SAVE_COMMAND_BASE}} {
                    /// <summary>
                    /// 対象データの種類。
                    /// </summary>
                    [JsonPropertyName("{{DATA_TYPE_TS}}")]
                    public required string {{DATA_TYPE_CS}} { get; init; }

                    /// <summary>
                    /// 新規追加・更新・削除・変更なしのいずれか。
                    /// </summary>
                    [JsonPropertyName("{{ADD_MOD_DEL_TS}}")]
                    public required {{ADD_MOD_DEL_ENUM_CS}} {{ADD_MOD_DEL_CS}} { get; init; }
                }

                /// <summary>
                /// 新規データ登録パラメータ。
                /// </summary>
                public partial class {{CREATE_COMMAND}}<T> : {{SAVE_COMMAND_BASE}} {
                    [JsonPropertyName("{{VALUES_TS}}")]
                    public required T {{VALUES_CS}} { get; init; }
                }

                /// <summary>
                /// 既存データ更新パラメータ。
                /// </summary>
                public partial class {{UPDATE_COMMAND}}<T> : {{SAVE_COMMAND_BASE}} {
                    [JsonPropertyName("{{VALUES_TS}}")]
                    public required T {{VALUES_CS}} { get; init; }

                    [JsonPropertyName("{{VERSION_TS}}")]
                    public required int {{VERSION_CS}} { get; init; }
                }

                /// <summary>
                /// 既存データ削除パラメータ。
                /// </summary>
                public partial class {{DELETE_COMMAND}}<T> : {{SAVE_COMMAND_BASE}} {
                    [JsonPropertyName("{{VALUES_TS}}")]
                    public required T {{VALUES_CS}} { get; init; }

                    [JsonPropertyName("{{VERSION_TS}}")]
                    public required int {{VERSION_CS}} { get; init; }
                }

                /// <summary>
                /// 既存データを変更しないことを明示するパラメータ。
                /// </summary>
                public partial class {{NO_OPERATION}}<T> : {{SAVE_COMMAND_BASE}} {
                    [JsonPropertyName("{{VALUES_TS}}")]
                    public required T {{VALUES_CS}} { get; init; }

                    [JsonPropertyName("{{VERSION_TS}}")]
                    public required int {{VERSION_CS}} { get; init; }
                }

                /// <summary>
                /// 追加・更新・削除のいずれかを表す区分。
                /// </summary>
                public enum {{ADD_MOD_DEL_ENUM_CS}} {
                    ADD,
                    MOD,
                    DEL,
                    NONE,
                }
                """;
        }

        private string RenderTypeScriptBaseTypes() {
            var dataTypes = SnapshotRootAggregates()
                .OrderBy(root => root.PhysicalName)
                .Select(root => $"  | '{root.PhysicalName}'")
                .Join(Environment.NewLine);

            return $$"""
                /** 追加・更新・削除のいずれかを表す区分 */
                export type {{ADD_MOD_DEL_ENUM_TS}}
                  = 'ADD'
                  | 'MOD'
                  | 'DEL'
                  | 'NONE'

                /** WriteModel2 一括保存で扱うデータ種別 */
                export type WriteModel2DataType =
                {{If(string.IsNullOrWhiteSpace(dataTypes), () => "  | never").Else(() => dataTypes)}}

                /** 追加・更新・削除のいずれかを表す区分を計算します。 */
                export const {{GET_ADD_MOD_DEL_ENUM_TS}} = (item: {
                  {{ADD_MOD_DEL_TS}}?: {{ADD_MOD_DEL_ENUM_TS}}
                  existsInDb?: boolean
                  willBeChanged?: boolean
                  willBeDeleted?: boolean
                }): {{ADD_MOD_DEL_ENUM_TS}} => {
                  if (item.{{ADD_MOD_DEL_TS}}) return item.{{ADD_MOD_DEL_TS}}
                  if (!item.existsInDb) {
                    return item.willBeDeleted ? 'NONE' : 'ADD'
                  }
                  if (item.willBeDeleted) return 'DEL'
                  if (item.willBeChanged) return 'MOD'
                  return 'NONE'
                }
                """;
        }

        private RootAggregate[] SnapshotRootAggregates() {
            lock (_lock) {
                return _rootAggregates.ToArray();
            }
        }
    }
}
