using Nijo.CodeGenerating;
using Nijo.ImmutableSchema;
using Nijo.Parts.CSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;

namespace Nijo.Models.WriteModel2Modules {
    /// <summary>
    /// デバッグ用ダミーデータ生成を担当する移植先。
    /// </summary>
    internal class DummyDataGenerator : IMultiAggregateSourceFile {
        private readonly Lock _lock = new();
        private readonly HashSet<RootAggregate> _rootAggregates = [];

        /// <summary>
        /// ダミーデータ生成対象のルート集約を追加する。
        /// </summary>
        /// <remarks>
        /// 実装方針: 旧版 DummyDataGenerator のパターン生成を、
        /// 現行 RootAggregate 順序と DataClassForSave/CreateMethod へ接続する。
        /// 旧版には GenerateDummyData / DestroyAllData / pattern builder 群があったため、
        /// まず必要最小限として「データフロー順の生成」と「全件削除」の2責務を残す。
        /// </remarks>
        internal DummyDataGenerator Add(RootAggregate rootAggregate) {
            lock (_lock) {
                _rootAggregates.Add(rootAggregate);
            }
            return this;
        }

        /// <summary>
        /// ダミーデータ生成で必要な共有ソースを登録する。
        /// </summary>
        /// <remarks>
        /// 実装方針: Metadata や MessageContainer など、ダミーデータ生成の下支えとなる依存を宣言する。
        /// </remarks>
        void IMultiAggregateSourceFile.RegisterDependencies(IMultiAggregateSourceFileManager ctx) {
            ctx.Use<WriteModelMetadata>();
        }

        /// <summary>
        /// ダミーデータ生成の共有ソースを出力する。
        /// </summary>
        /// <remarks>
        /// 実装方針: 旧版の debug 用ヘルパーと create 呼び出しループを、現行 shared file にまとめてレンダリングする。
        /// 少なくとも DEBUG 条件付きの GenerateDummyData 相当と、依存順に DELETE する補助 API の生成先を決める。
        /// </remarks>
        void IMultiAggregateSourceFile.Render(CodeRenderingContext ctx) {
            var roots = Snapshot().OrderBy(root => root.GetIndexOfDataFlow()).ToArray();
            if (roots.Length == 0) return;

            ctx.CoreLibrary(autoGenerated => {
                autoGenerated.Directory("Util", utilDir => {
                    if (ctx.IsLegacyCompatibilityMode()) {
                        utilDir.Generate(new SourceFile {
                            FileName = "GenerateDummyData.cs",
                            Contents = RenderLegacyCSharp(ctx),
                        });
                        utilDir.Generate(new SourceFile {
                            FileName = "TestPatternBuilderBase.cs",
                            Contents = LegacyDummyDataGenerator.RenderTestPatternBuilderBase(ctx, roots),
                        });
                        utilDir.Generate(new SourceFile {
                            FileName = "CombinationPatternBuilder.cs",
                            Contents = LegacyDummyDataGenerator.RenderCombinationPatternBuilder(ctx),
                        });
                    } else {
                        utilDir.Generate(new SourceFile {
                            FileName = "WriteModel2DummyDataGenerator.cs",
                            Contents = RenderCSharp(ctx),
                        });
                    }
                });
            });
        }

        private string RenderLegacyCSharp(CodeRenderingContext ctx) {
            return LegacyDummyDataGenerator.RenderGenerateDummyData(ctx, Snapshot());
        }

        private string RenderCSharp(CodeRenderingContext ctx) {
            return $$"""
                namespace {{ctx.Config.RootNamespace}};

                public abstract partial class {{ApplicationService.ABSTRACT_CLASS}} {
                    public virtual Task GenerateWriteModel2DummyDataAsync() {
                        return Task.CompletedTask;
                    }

                    public virtual Task DestroyWriteModel2DummyDataAsync() {
                        return Task.CompletedTask;
                    }
                }
                """;
        }

        private RootAggregate[] Snapshot() {
            lock (_lock) {
                return _rootAggregates.ToArray();
            }
        }
    }
}
