using Nijo.CodeGenerating;
using Nijo.ImmutableSchema;
using Nijo.Parts.CSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;

namespace Nijo.Models.WriteModel2Modules {
    /// <summary>
    /// 保存処理のメッセージコンテキストを担当する移植先。
    /// </summary>
    internal class SaveContext : IMultiAggregateSourceFile {
        internal const string STATE_CLASS_NAME = "BatchUpdateState";
        internal const string BEFORE_SAVE = "BeforeSaveEventArgs";
        internal const string AFTER_SAVE_EVENT_ARGS = "AfterSaveEventArgs";
        internal const string SAVE_OPTIONS = "SaveOptions";

        private readonly Lock _lock = new();
        private readonly HashSet<RootAggregate> _writeModels = [];

        /// <summary>
        /// 保存コンテキストが必要な WriteModel2 ルート集約を登録する。
        /// </summary>
        /// <remarks>
        /// 実装方針: 旧版 SaveContext が持っていたメッセージ階層の責務を、現行 MessageContainer の shared file として移植する。
        /// 旧版の SaveOptions, BeforeSaveEventArgs<T>, AfterSaveEventArgs, BatchUpdateState のどこまでを
        /// 現行 PresentationContext / MessageContainer へ残すかをここで決める。
        /// </remarks>
        internal SaveContext AddWriteModel(RootAggregate rootAggregate) {
            lock (_lock) {
                _writeModels.Add(rootAggregate);
            }
            return this;
        }

        /// <summary>
        /// 保存コンテキスト生成に必要な依存ソースを登録する。
        /// </summary>
        /// <remarks>
        /// 実装方針: MessageContainer の具象型や関連 metadata をここで事前登録する。
        /// </remarks>
        void IMultiAggregateSourceFile.RegisterDependencies(IMultiAggregateSourceFileManager ctx) {
        }

        /// <summary>
        /// 保存コンテキストの共有ソースを出力する。
        /// </summary>
        /// <remarks>
        /// 実装方針: ルート集約ごとのエラー入れ物を統合し、AppSrv と UI の両方から利用できる共通型を生成する。
        /// 出力ファイルは util 系の shared C# ファイル 1 つを基本とし、必要なら TS 側補助型も分離して生成する。
        /// </remarks>
        void IMultiAggregateSourceFile.Render(CodeRenderingContext ctx) {
            ctx.CoreLibrary(autoGenerated => {
                autoGenerated.Directory("Util", utilDir => {
                    utilDir.Generate(new SourceFile {
                        FileName = "SaveContext.cs",
                        Contents = RenderCSharp(ctx),
                    });
                });
            });
        }

        private string RenderCSharp(CodeRenderingContext ctx) {
            if (ctx.IsLegacyCompatibilityMode()) {
                return $$"""
                    using System.Text.Json.Nodes;

                    namespace {{ctx.Config.RootNamespace}};

                    /// <summary>
                    /// 一括更新処理の細かい挙動を呼び出し元で指定できるようにするためのオプション
                    /// </summary>
                    public partial class {{SAVE_OPTIONS}} {
                        /// <summary>
                        /// trueの場合、 <see cref="AddConfirm" /> による警告があっても更新処理が続行されます。
                        /// 画面側で警告に対して「はい(Yes)」が選択されたあとのリクエストではこの値がtrueになります。
                        /// </summary>
                        public required bool IgnoreConfirm { get; init; }
                    }

                    /// <summary>
                    /// 一括更新処理のデータ1件分のコンテキスト引数。エラーメッセージや確認メッセージなどを書きやすくするためのもの。
                    /// </summary>
                    /// <typeparam name="TMessage">ユーザーに通知するメッセージデータの構造体</typeparam>
                    public partial class {{BEFORE_SAVE}}<TMessage> {
                        public {{BEFORE_SAVE}}({{PresentationContext.INTERFACE}} state, TMessage messages) {
                            _state = state;
                            Messages = messages;
                        }
                        private readonly {{PresentationContext.INTERFACE}} _state;

                        /// <inheritdoc cref="{{SAVE_OPTIONS}}" />
                        public {{SAVE_OPTIONS}} Options => _state.Options;

                        /// <summary>ユーザーに通知するメッセージデータ</summary>
                        public TMessage Messages { get; }

                        /// <summary>
                        /// <para>
                        /// 更新処理を実行してもよいかどうかをユーザーに問いかけるメッセージを追加します。
                        /// </para>
                        /// <para>
                        /// ボタンの意味を統一してユーザーが混乱しないようにするため、
                        /// 「はい(Yes)」を選択したときに処理が続行され、
                        /// 「いいえ(No)」を選択したときに処理が中断されるような文言にしてください。
                        /// </para>
                        /// <para>
                        /// <see cref="IgnoreConfirm"/> がfalseのリクエストで何らかのコンファームが発生した場合、
                        /// 更新処理は中断されます。
                        /// </para>
                        /// </summary>
                        public void AddConfirm(string message) {
                            _state.AddConfirm(message);
                        }

                        /// <summary>
                        /// 警告が1件以上あるかどうかを返します。
                        /// </summary>
                        public bool HasConfirm() {
                            return _state.HasConfirm();
                        }
                    }

                    /// <summary>
                    /// 更新後イベント引数
                    /// </summary>
                    public partial class {{AFTER_SAVE_EVENT_ARGS}} {
                        public {{AFTER_SAVE_EVENT_ARGS}}({{PresentationContext.INTERFACE}} batchUpdateState) {
                            _batchUpdateState = batchUpdateState;
                        }
                        protected readonly {{PresentationContext.INTERFACE}} _batchUpdateState;
                    }
                    """;
            }

            var writeModels = SnapshotWriteModels()
                .OrderBy(root => root.GetIndexOfDataFlow())
                .ThenBy(root => root.PhysicalName)
                .ToArray();

            return $$"""
                namespace {{ctx.Config.RootNamespace}};

                /// <summary>
                /// WriteModel2 の保存処理に関する追加オプション。
                /// </summary>
                public partial class {{SAVE_OPTIONS}} {
                    /// <summary>
                    /// true の場合、確認メッセージがあっても更新処理を継続します。
                    /// </summary>
                    public required bool IgnoreConfirm { get; init; }
                }

                /// <summary>
                /// 1 回の一括保存処理の経過状態。
                /// </summary>
                public partial class {{STATE_CLASS_NAME}} {
                    /// <summary>
                    /// 一括保存の細かい挙動を制御するオプション。
                    /// </summary>
                    public {{SAVE_OPTIONS}} Options { get; init; } = new() { IgnoreConfirm = false };

                    /// <summary>
                    /// 処理中に蓄積された確認メッセージ。
                    /// </summary>
                    public List<string> Confirms { get; } = [];

                    public void AddConfirm(string message) {
                        Confirms.Add(message);
                    }

                    public bool HasConfirm() {
                        return Confirms.Count > 0;
                    }
                }

                /// <summary>
                /// 保存前イベント引数。
                /// </summary>
                public partial class {{BEFORE_SAVE}}<TMessage> where TMessage : {{MessageContainer.SETTER_INTERFACE}} {
                    public {{BEFORE_SAVE}}({{PresentationContext.INTERFACE}} context, TMessage messages, {{STATE_CLASS_NAME}}? state = null) {
                        Context = context;
                        Messages = messages;
                        State = state ?? new {{STATE_CLASS_NAME}}();
                    }

                    public {{PresentationContext.INTERFACE}} Context { get; }
                    public TMessage Messages { get; }
                    public {{STATE_CLASS_NAME}} State { get; }
                    public {{SAVE_OPTIONS}} Options => State.Options;

                    public void AddConfirm(string message) {
                        State.AddConfirm(message);
                    }

                    public bool HasConfirm() {
                        return State.HasConfirm();
                    }
                }

                /// <summary>
                /// 保存後イベント引数。
                /// </summary>
                public partial class {{AFTER_SAVE_EVENT_ARGS}} {
                    public {{AFTER_SAVE_EVENT_ARGS}}({{PresentationContext.INTERFACE}} context, {{STATE_CLASS_NAME}}? state = null) {
                        Context = context;
                        State = state ?? new {{STATE_CLASS_NAME}}();
                    }

                    public {{PresentationContext.INTERFACE}} Context { get; }
                    public {{STATE_CLASS_NAME}} State { get; }
                    public {{SAVE_OPTIONS}} Options => State.Options;
                }

                /// <summary>
                /// SaveContext が対象とする WriteModel2 ルート集約一覧。
                /// </summary>
                public static class WriteModel2SaveContextMetadata {
                    public static readonly string[] TargetRootAggregates = [{{string.Join(", ", writeModels.Select(root => $"\"{root.PhysicalName}\""))}}];
                }
                """;
        }

        private RootAggregate[] SnapshotWriteModels() {
            lock (_lock) {
                return _writeModels.ToArray();
            }
        }
    }
}
