using Nijo.CodeGenerating;
using Nijo.ImmutableSchema;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;

namespace Nijo.Models.WriteModel2Modules {
    /// <summary>
    /// WriteModel2 のメタデータ生成を担当する移植先。
    /// </summary>
    internal class WriteModelMetadata : IMultiAggregateSourceFile {
        private readonly Lock _lock = new();
        private readonly HashSet<RootAggregate> _rootAggregates = [];

        /// <summary>
        /// メタデータ生成対象のルート集約を登録する。
        /// </summary>
        /// <remarks>
        /// 実装方針: 旧版 WriteModelMetadata が持っていた型情報や UI 向け補助情報を、現行 metadata 系 shared file へ寄せる。
        /// 最低限、全集約をデータフロー順で列挙する API と、集約ごとの表示名・テーブル名を返す API は残す。
        /// </remarks>
        internal WriteModelMetadata Register(RootAggregate rootAggregate) {
            lock (_lock) {
                _rootAggregates.Add(rootAggregate);
            }
            return this;
        }

        /// <summary>
        /// メタデータ生成に必要な依存ソースを登録する。
        /// </summary>
        /// <remarks>
        /// 実装方針: MessageContainer や enum 定義など、メタデータが参照する shared source をここで宣言する。
        /// </remarks>
        void IMultiAggregateSourceFile.RegisterDependencies(IMultiAggregateSourceFileManager ctx) {
            // 現時点では追加依存なし。
        }

        /// <summary>
        /// WriteModel2 用メタデータの共有ソースを出力する。
        /// </summary>
        /// <remarks>
        /// 実装方針: 旧版の画面編集・保存処理が参照していた補助メタデータを、現行の React / C# 双方へレンダリングする。
        /// 旧版では C# の static class 1 つだったため、まずは core 側の util 出力から始め、必要になれば TS を追加する。
        /// </remarks>
        void IMultiAggregateSourceFile.Render(CodeRenderingContext ctx) {
            var roots = Snapshot().OrderBy(root => root.GetIndexOfDataFlow()).ToArray();
            if (roots.Length == 0) return;

            ctx.CoreLibrary(autoGenerated => {
                autoGenerated.Directory("Util", utilDir => {
                    utilDir.Generate(new SourceFile {
                        FileName = ctx.IsLegacyCompatibilityMode() ? "WriteModelMetadata.cs" : "WriteModel2Metadata.cs",
                        Contents = ctx.IsLegacyCompatibilityMode()
                            ? RenderLegacyCSharp(ctx, roots)
                            : RenderCSharp(ctx, roots),
                    });
                });
            });
        }

        private string RenderLegacyCSharp(CodeRenderingContext ctx, RootAggregate[] roots) {
            var allAggregates = roots
                .SelectMany(root => root.EnumerateThisAndDescendants())
                .ToArray();

            return $$"""
                using System;
                using System.Collections.Generic;
                using System.Linq;

                namespace {{ctx.Config.RootNamespace}};

                /// <summary>
                /// WriteModelのメタデータ。
                /// ソース生成後でリフレクション的な処理をしたいときに使用する。
                /// 理論上は各カラムの桁数の定数などより細かい情報も生成可能だが、2025-06-27現在はそこまで必要なかったので生成していない。
                /// </summary>
                public static class WriteModelMetadata {

                    /// <summary>
                    /// 全ての集約の情報を、データフローの順番で返す。
                    /// 例えば、テーブルAがBへの、BがCへの外部キーを持つとき、 C, B, A の順番で列挙する。
                    /// バックアップデータを外部キー制約に引っかからないようにしつつ全テーブルへリストアしたいような状況で使用する。
                    /// </summary>
                    public static IEnumerable<AggregateInfo> EnumerateAllAggregatesOrderByDataFlow() {
                {{allAggregates.SelectTextTemplate(aggregate => $$"""
                        yield return {{aggregate.PhysicalName}};
                """)}}
                    }

                {{allAggregates.SelectTextTemplate(aggregate => $$"""
                    public static AggregateInfo {{aggregate.PhysicalName}} => new() {
                        DisplayName = "{{aggregate.DisplayName.Replace("\"", "\\\"")}}",
                        TableName = "{{aggregate.DbName}}",
                    };
                """)}}


                    #region 型定義
                    /// <summary>
                    /// 集約1個分の情報。
                    /// RDBMSで言うならばテーブル1個と対応する。
                    /// </summary>
                    public class AggregateInfo {
                        /// <summary>
                        /// 表示用名称
                        /// </summary>
                        public required string DisplayName { get; init; }
                        /// <summary>
                        /// テーブル物理名
                        /// </summary>
                        public required string TableName { get; init; }
                    }
                    #endregion 型定義
                }
                """;
        }

        private string RenderCSharp(CodeRenderingContext ctx, RootAggregate[] roots) {
            return $$"""
                namespace {{ctx.Config.RootNamespace}};

                public static class WriteModel2Metadata {
                    public static IReadOnlyList<(string PhysicalName, string DisplayName, string DbName)> RootAggregates { get; } = [
                    {{roots.SelectTextTemplate(root => $$"""
                        ("{{root.PhysicalName}}", "{{root.DisplayName.Replace("\"", "\\\"")}}", "{{root.DbName}}"),
                    """)}}
                    ];
                }
                """;
        }

        private RootAggregate[] Snapshot() {
            lock (_lock) {
                return _rootAggregates.ToArray();
            }
        }
    }
}
