using Nijo.CodeGenerating;
using Nijo.ImmutableSchema;
using Nijo.Util.DotnetEx;
using Nijo.ValueMemberTypes;
using Nijo.SchemaParsing;
using Nijo.Models.QueryModelModules;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Linq;
using Nijo.Parts.Common;

namespace Nijo.Parts.JavaScript;

/// <summary>
/// nijo.xml の定義をほぼそのまま TypeScript の定数としてレンダリングする。
/// 定数は集約ごとのソースファイルに出力され、このクラス自身はその定数の型定義を出力する。
/// 定数の各表のキーは、生成される構造体のプロパティ名をドットでつないだもの（配列の添字は含まない）であり、
/// 画面のフォームのパスから 1 回引くだけで項目のメタデータを得られる。
/// </summary>
internal class AggregateMetadata : IMultiAggregateSourceFile {

    /// <summary>集約ごとのソースファイルに出力される定数の名前</summary>
    internal const string CONST_NAME = "metadata";

    internal const string NAMESPACE = "AggregateMetadata";
    private const string TYPE_ENTRY = "Entry";
    private const string TYPE_ROOT = "Root";
    internal const string TYPE_TABLE = "Table";
    private const string TYPE_MEMBER = "Member";
    private const string TYPE_VALUE = "Value";
    private const string TYPE_REF = "Ref";
    private const string TYPE_CHILD = "Child";
    private const string TYPE_CHILDREN = "Children";
    private const string TYPE_PARENT = "Parent";
    private const string TYPE_NODE_OPTIONS = "NodeOptions";
    private const string TYPE_MEMBER_BASE = "MemberBase";

    private const string KIND_ROOT = "root";
    private const string KIND_VALUE = "value";
    private const string KIND_REF = "ref";
    private const string KIND_CHILD = "child";
    private const string KIND_CHILDREN = "children";
    private const string KIND_PARENT = "parent";

    void IMultiAggregateSourceFile.RegisterDependencies(IMultiAggregateSourceFileManager ctx) {
        // 特になし
    }

    void IMultiAggregateSourceFile.Render(CodeRenderingContext ctx) {
        ctx.ReactProject(autoGenerated => {
            autoGenerated.Generate(RenderTypeScriptType(ctx));
        });
    }

    #region 型定義
    private static SourceFile RenderTypeScriptType(CodeRenderingContext ctx) {
        var modelNames = ctx.SchemaParser.Models
            .Select(m => $"'{m.Key}'")
            .ToArray();
        var valueObjectTypes = ctx.SchemaParser.GetValueObjectMembers().Values.ToArray();
        var valueObjectLiteral = valueObjectTypes.Length == 0
            ? "never"
            : valueObjectTypes.Select(type => $"'{type.TypePhysicalName}'").Join(" | ");

        return new SourceFile {
            FileName = "aggregate-metadata.ts",
            Contents = $$"""
                import * as EnumDefs from "./enum-defs"

                /** 集約のメタデータ */
                export namespace {{NAMESPACE}} {
                  /** 1つのルート集約のメタデータ */
                  export type {{TYPE_ENTRY}} = {
                    /** ルート集約自身のメタデータ */
                    root: {{TYPE_ROOT}}
                    /** 画面表示用データのメタデータ */
                    displayData?: {{TYPE_TABLE}}
                    /** 検索条件の絞り込み条件のメタデータ。キーは絞り込み条件のプロパティ名を除いたパス */
                    searchCondition?: {{TYPE_TABLE}}
                  }

                  /** ルート集約のメタデータ */
                  export type {{TYPE_ROOT}} = {{TYPE_NODE_OPTIONS}} & {
                    kind: '{{KIND_ROOT}}'
                    /** このルート集約のモデル */
                    model: {{(modelNames.Length == 0 ? "never" : modelNames.Join(" | "))}}
                    /** XMLスキーマ上でこの要素を示す一意なID */
                    uniqueId: string
                    /** ルート集約直下のメンバーの物理名 */
                    members: readonly string[]
                  }

                  /** 構造体の全メンバーのメタデータ。キーはプロパティ名をドットでつないだパス（配列の添字は含まない） */
                  export type {{TYPE_TABLE}} = { [path: string]: {{TYPE_MEMBER}} }

                  /** 構造体のメンバーのメタデータ */
                  export type {{TYPE_MEMBER}} = {{TYPE_VALUE}} | {{TYPE_REF}} | {{TYPE_CHILD}} | {{TYPE_CHILDREN}} | {{TYPE_PARENT}}

                  /** 値のメタデータ */
                  export type {{TYPE_VALUE}} = {{TYPE_MEMBER_BASE}} & {
                    kind: '{{KIND_VALUE}}'
                    /** 値の型名。このメンバーが enum または value-ojbect の場合は undefined になる */
                    type?: {{ctx.SchemaParser.ValueMemberTypes.Select(t => $"'{t.SchemaTypeName}'").Join(" | ")}}
                    /** 列挙体の型名。このメンバーが列挙体の場合のみ */
                    enumType?: keyof EnumDefs.{{EnumFile.TS_TYPE_MAP}}
                    /** 値オブジェクトの型名。このメンバーが値オブジェクトの場合のみ */
                    valueObjectType?: {{valueObjectLiteral}}
                  }

                  /** 外部参照のメタデータ */
                  export type {{TYPE_REF}} = {{TYPE_MEMBER_BASE}} & {
                    kind: '{{KIND_REF}}'
                    /** 参照先。参照先が子孫集約の場合はルート集約からのパスのスラッシュ区切り */
                    refTo: `ref-to:${string}`
                    /** 直下のメンバーのパス */
                    members: readonly string[]
                  }

                  /** 子集約のメタデータ */
                  export type {{TYPE_CHILD}} = {{TYPE_MEMBER_BASE}} & {
                    kind: '{{KIND_CHILD}}'
                    /** 直下のメンバーのパス */
                    members: readonly string[]
                  }

                  /** 子配列のメタデータ */
                  export type {{TYPE_CHILDREN}} = {{TYPE_MEMBER_BASE}} & {
                    kind: '{{KIND_CHILDREN}}'
                    /** 直下のメンバーのパス */
                    members: readonly string[]
                  }

                  /** 子集約を外部参照したときに、参照先から見た親集約を表すメンバーのメタデータ */
                  export type {{TYPE_PARENT}} = {{TYPE_MEMBER_BASE}} & {
                    kind: '{{KIND_PARENT}}'
                    /** 直下のメンバーのパス */
                    members: readonly string[]
                  }

                  /** 構造体のメンバーのメタデータの共通部分 */
                  type {{TYPE_MEMBER_BASE}} = {{TYPE_NODE_OPTIONS}} & {
                    /** 親のメンバーのパス。構造体の直下のメンバーの場合は null */
                    parent: string | null
                    /**
                     * この項目が外部参照の境界を一度でも越えた先にあるかどうか。
                     * true の場合、ノードオプションやカスタム属性は参照先の集約で定義されたものである。
                     */
                    isOutsideTree: boolean
                    /** XMLスキーマ上でこの要素を示す一意なID */
                    uniqueId: string
                  }

                  /** XMLスキーマ上で定義されたノードオプションとカスタム属性 */
                  type {{TYPE_NODE_OPTIONS}} = {
                {{RenderNodeOptionTypes(ctx).SelectTextTemplate(source => $$"""
                    {{WithIndent(source)}}
                """)}}
                  }
                }
                """,
        };
    }
    #endregion 型定義


    #region 定数
    /// <summary>
    /// ルート集約のメタデータの定数をレンダリングする。
    /// </summary>
    /// <param name="root">ルート集約</param>
    /// <param name="displayData">画面表示用データ。生成されない場合は null</param>
    /// <param name="searchConditionFilter">検索条件の絞り込み条件部分。生成されない場合は null</param>
    internal static string RenderTsConstant(
        RootAggregate root,
        IInstancePropertyOwnerMetadata? displayData,
        IInstancePropertyOwnerMetadata? searchConditionFilter,
        CodeRenderingContext ctx) {

        return $$"""
            //#region メタデータ

            /** この集約のメタデータ */
            export const {{CONST_NAME}} = {
              root: {
                kind: '{{KIND_ROOT}}',
                model: '{{root.Model.SchemaName}}',
                uniqueId: {{ToTsString(root.XElement.Attribute(SchemaParseContext.ATTR_UNIQUE_ID)?.Value ?? string.Empty)}},
            {{RenderNodeOptions(root.XElement, ctx).SelectTextTemplate(source => $$"""
                {{WithIndent(source)}}
            """)}}
                members: [{{root.GetMembers().Select(m => ToTsString(m.PhysicalName)).Join(", ")}}],
              },
            {{If(displayData != null, () => $$"""
              displayData: {
            {{EnumerateTableMembers(displayData!).SelectTextTemplate(member => $$"""
                {{WithIndent(member.Render(ctx))}},
            """)}}
              },
            """)}}
            {{If(searchConditionFilter != null, () => $$"""
              searchCondition: {
            {{EnumerateTableMembers(searchConditionFilter!).SelectTextTemplate(member => $$"""
                {{WithIndent(member.Render(ctx))}},
            """)}}
              },
            """)}}
            } as const satisfies Util.{{NAMESPACE}}.{{TYPE_ENTRY}}

            //#endregion メタデータ
            """;
    }

    /// <summary>
    /// 構造体のメンバーを子孫も含めて再帰的に列挙する。
    /// </summary>
    private static IEnumerable<TableMember> EnumerateTableMembers(IInstancePropertyOwnerMetadata owner) {
        return EnumerateRecursively(owner, null);

        static IEnumerable<TableMember> EnumerateRecursively(IInstancePropertyOwnerMetadata owner, TableMember? parent) {
            foreach (var member in owner.GetMembers()) {
                var tableMember = new TableMember(member, parent);
                yield return tableMember;

                if (member is IInstanceStructurePropertyMetadata structure) {
                    foreach (var descendant in EnumerateRecursively(structure, tableMember)) {
                        yield return descendant;
                    }
                }
            }
        }
    }

    /// <summary>
    /// 表の 1 行。生成される構造体のメンバー 1 つと対応する。
    /// </summary>
    private class TableMember {
        internal TableMember(IInstancePropertyMetadata member, TableMember? parent) {
            _member = member;
            _parent = parent;
            Path = parent == null
                ? member.GetPropertyName(E_CsTs.TypeScript)
                : $"{parent.Path}.{member.GetPropertyName(E_CsTs.TypeScript)}";
        }
        private readonly IInstancePropertyMetadata _member;
        private readonly TableMember? _parent;

        /// <summary>表のキー</summary>
        internal string Path { get; }

        /// <summary>
        /// 外部参照の境界を一度でも越えた先にあるかどうか。
        /// 参照先が自身のツリー内の集約である場合もあるため、ルート集約の比較ではなく経路上の外部参照の有無で判定する。
        /// </summary>
        private bool IsOutsideTree => _member.SchemaPathNode
            .GetPathFromEntry()
            .SkipLast(1)
            .Any(node => node is RefToMember);

        internal string Render(CodeRenderingContext ctx) {
            var xElement = _member.SchemaPathNode.XElement;

            var kindSpecificProps = new List<string>();
            if (_member is IInstanceValuePropertyMetadata vm) {
                // 型は enum, value-object の場合はそれぞれ別の名前のプロパティで定義
                var typeProp = vm.Type switch {
                    StaticEnumMember => "enumType",
                    ValueObjectMember => "valueObjectType",
                    _ => "type",
                };
                kindSpecificProps.Add($"kind: '{KIND_VALUE}'");
                kindSpecificProps.Add($"{typeProp}: '{vm.Type.SchemaTypeName}'");

            } else if (_member is IInstanceStructurePropertyMetadata structure) {
                if (structure.SchemaPathNode is RefToMember refTo) {
                    ThrowIfCircularReference(refTo);
                    kindSpecificProps.Add($"kind: '{KIND_REF}'");
                    kindSpecificProps.Add($"refTo: {ToTsString(refTo.RefTo.RefEntryName)}");

                } else if (structure is DisplayDataRef.RefDisplayDataParentMember) {
                    kindSpecificProps.Add($"kind: '{KIND_PARENT}'");

                } else if (structure.IsArray) {
                    kindSpecificProps.Add($"kind: '{KIND_CHILDREN}'");

                } else {
                    kindSpecificProps.Add($"kind: '{KIND_CHILD}'");
                }

            } else {
                throw new NotImplementedException();
            }

            var members = _member is IInstanceStructurePropertyMetadata s
                ? s.GetMembers().Select(m => ToTsString($"{Path}.{m.GetPropertyName(E_CsTs.TypeScript)}")).ToArray()
                : null;

            return $$"""
                {{ToTsString(Path)}}: {
                  {{kindSpecificProps[0]}},
                  parent: {{(_parent == null ? "null" : ToTsString(_parent.Path))}},
                  isOutsideTree: {{(IsOutsideTree ? "true" : "false")}},
                  uniqueId: {{ToTsString(xElement.Attribute(SchemaParseContext.ATTR_UNIQUE_ID)?.Value ?? string.Empty)}},
                {{kindSpecificProps.Skip(1).SelectTextTemplate(prop => $$"""
                  {{prop}},
                """)}}
                {{RenderNodeOptions(xElement, ctx).SelectTextTemplate(source => $$"""
                  {{WithIndent(source)}}
                """)}}
                {{If(members != null, () => $$"""
                  members: [{{members!.Join(", ")}}],
                """)}}
                }
                """;
        }

        /// <summary>
        /// 外部参照の循環により展開が終わらなくなる場合は例外を送出する。
        /// </summary>
        private static void ThrowIfCircularReference(RefToMember refTo) {
            var isCircular = refTo
                .GetPathFromEntry()
                .SkipLast(1)
                .Any(node => node is RefToMember rm && rm.XElement == refTo.XElement);
            if (isCircular) {
                var path = refTo.GetPathFromEntry().Select(node => node.XElement.Name.LocalName).Join(" > ");
                throw new InvalidOperationException($"外部参照が循環しているため集約のメタデータを展開できません: {path}");
            }
        }
    }

    /// <summary>
    /// 文字列を TypeScript のシングルクォートの文字列リテラルにする。
    /// </summary>
    private static string ToTsString(string value) {
        return $"'{value.Replace("\\", "\\\\").Replace("'", "\\'")}'";
    }
    #endregion 定数


    #region オプション項目の動的レンダリング
    /// <summary>
    /// XElementで定義されたNodeOptionをTypeScriptのオブジェクトプロパティとしてレンダリングします。
    /// </summary>
    /// <param name="xElement">XML要素</param>
    /// <param name="ctx">レンダリングコンテキスト</param>
    /// <returns>TypeScriptのプロパティ定義文字列</returns>
    private static IEnumerable<string> RenderNodeOptions(XElement xElement, CodeRenderingContext ctx) {

        var options = ctx.SchemaParser.GetOptions(xElement);

        // DisplayName だけは未定義の場合は物理名を採用する。
        // メタデータを用いたカスタマイズ処理でDisplayNameの使用頻度が高いため。
        if (options.Any(o => o.AttributeName == BasicNodeOptions.DisplayNameIsEmpty.AttributeName)) {
            yield return $$"""
                {{BasicNodeOptions.DisplayName.AttributeName.ToCamelCase()}}: '',
                """;
        } else if (!options.Any(o => o.AttributeName == BasicNodeOptions.DisplayName.AttributeName)) {
            yield return $$"""
                {{BasicNodeOptions.DisplayName.AttributeName.ToCamelCase()}}: '{{ctx.SchemaParser.GetPhysicalName(xElement)}}',
                """;
        }

        // コメントがある場合はレンダリング
        var comment = xElement.GetCommentSingleLine(E_CsTs.TypeScript);
        if (!string.IsNullOrWhiteSpace(comment)) {
            yield return $$"""
                comment: '{{comment}}',
                """;
        }

        foreach (var option in options) {
            var attributeValue = xElement.Attribute(option.AttributeName)?.Value;

            // フィルタリング: 空文字の文字列をスキップ
            if ((option.Type == E_NodeOptionType.String
              || option.Type == E_NodeOptionType.Integer)
                && string.IsNullOrWhiteSpace(attributeValue)) {
                continue;
            }

            // TypeScriptプロパティ名を生成(camelCaseに変換)
            var propName = option.AttributeName.ToCamelCase();

            // TypeScriptの値をレンダリング
            var tsValue = option.Type switch {
                E_NodeOptionType.Boolean => "true",
                E_NodeOptionType.Integer => attributeValue,
                _ => $"'{attributeValue?.Replace("\\", "\\\\").Replace("'", "\\'")}'",
            };

            yield return $$"""
                {{propName}}: {{tsValue}},
                """;
        }

        // カスタム属性
        foreach (var customAttribute in NijoXmlCustomAttribute.FromXDocument(ctx.SchemaParser.Document)) {
            if (string.IsNullOrWhiteSpace(customAttribute.PhysicalName)) continue;
            if (string.IsNullOrWhiteSpace(customAttribute.UniqueId)) continue;

            var attributeValue = xElement.Attribute(customAttribute.UniqueId)?.Value;
            if (string.IsNullOrWhiteSpace(attributeValue)) continue;

            var tsValue = customAttribute.Type switch {
                NijoXmlCustomAttribute.E_Type.Boolean => "true",
                NijoXmlCustomAttribute.E_Type.Decimal => attributeValue,
                _ => $"'{attributeValue.Replace("\\", "\\\\").Replace("'", "\\'")}'",
            };

            yield return $$"""
                {{customAttribute.PhysicalName.ToCamelCase()}}: {{tsValue}},
                """;
        }
    }

    /// <summary>
    /// TypeScript型定義で使用するNodeOptionの型情報を動的に生成します
    /// </summary>
    private static IEnumerable<string> RenderNodeOptionTypes(CodeRenderingContext ctx) {
        var nodeOptions = ctx.SchemaParser.GetAllNodeOptions();

        // コメントはXMLの属性ではないので別途宣言している
        yield return $$"""
            /** XMLコメント */
            comment?: string
            """;

        foreach (var option in nodeOptions) {

            string tsType = option.Type switch {
                E_NodeOptionType.Boolean => "boolean",
                E_NodeOptionType.Integer => "number",
                _ => "string",
            };

            // DisplayName だけは必ずレンダリングされる
            var isOptional = option.AttributeName != BasicNodeOptions.DisplayName.AttributeName;

            yield return $$"""
                /** {{option.DisplayName}} */
                {{option.AttributeName.ToCamelCase()}}{{(isOptional ? "?" : "")}}: {{tsType}}
                """;
        }

        // カスタム属性
        foreach (var customAttribute in NijoXmlCustomAttribute.FromXDocument(ctx.SchemaParser.Document)) {
            if (string.IsNullOrWhiteSpace(customAttribute.PhysicalName)) continue;

            var tsType = customAttribute.Type switch {
                NijoXmlCustomAttribute.E_Type.Boolean => "boolean",
                NijoXmlCustomAttribute.E_Type.Decimal => "number",
                NijoXmlCustomAttribute.E_Type.Enum => customAttribute.EnumValues.Length == 0
                    ? "never"
                    : customAttribute.EnumValues.Select(v => $"'{v.Replace("'", "\\'")}'").Join(" | "),
                _ => "string",
            };

            yield return $$"""
                /** {{customAttribute.DisplayName}} */
                {{customAttribute.PhysicalName.ToCamelCase()}}?: {{tsType}}
                """;
        }
    }
    #endregion オプション項目の動的レンダリング
}
