using Nijo.CodeGenerating;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Nijo.Parts.JavaScript {
    /// <summary>
    /// 旧版互換モードで生成する React / TypeScript 関連ファイル。
    /// </summary>
    internal static class LegacyCompatibilityJavaScript {
        internal static void RenderReact(CodeRenderingContext ctx) {
            var hasReadModel2 = ctx.Schema.GetRootAggregates().Any(root => root.Model is Models.ReadModel2);
            ctx.ReactProject(dir => {
                dir.Generate(RenderVForm2ContainerQueryCss(ctx));
                if (hasReadModel2) {
                    dir.Generate(RenderAutoGeneratedMenu(ctx));
                }
                dir.Directory("util", utilDir => {
                    utilDir.Generate(RenderTypeScriptUtilIndex(hasReadModel2));
                    utilDir.Generate(RenderPresentationContextTypeScript());
                    if (hasReadModel2) {
                        utilDir.Generate(RenderSingleViewUtil());
                    }
                    utilDir.Generate(RenderSpaceFinderConstTypeScript(ctx));
                });
            });
        }

        private static SourceFile RenderAutoGeneratedMenu(CodeRenderingContext ctx) {
            var items = ctx.Schema.GetRootAggregates()
              .Where(root => root.Model is Models.ReadModel2)
              .SelectMany(root => {
                  var multiView = new Models.ReadModel2Modules.MultiView(root);
                  var singleView = new Models.ReadModel2Modules.SingleView(root);
                  return new[] {
                new { Url = multiView.Url, DisplayName = $"{root.DisplayName}MultiView" },
                new { Url = singleView.Url, DisplayName = $"{root.DisplayName}SingleView" },
                };
              })
              .ToArray();

            return new SourceFile {
                FileName = "autogenerated-menu.tsx",
                Contents = $$"""
              import React from 'react'

              /** 自動生成された React router のルーティング設定 */
              export type IAutoGeneratedRoutes = {
              {{items.SelectTextTemplate(item => $$"""
                /** {{item.DisplayName}} */
                '{{item.Url.Replace("'", "\\'")}}': React.ReactNode | null
              """)}}
                /** トップページ */
                '/': React.ReactNode | null
                /** 設定画面 */
                '/settings': React.ReactNode | null
                /** Not Found */
                '*': React.ReactNode | null
              }

              """,
            };
        }

        private static SourceFile RenderVForm2ContainerQueryCss(CodeRenderingContext ctx) {
            const int maxColumn = 5;
            const int maxMember = 100;
            var threshold = ctx.Config.VFormThreshold ?? 320;

            var sections = Enumerable.Range(1, maxColumn).Select(col => {
                var minmax = new List<string>();
                if (col > 1) minmax.Add($"(min-width: {(col - 1) * threshold + threshold}px)");
                if (col < maxColumn) minmax.Add($"(max-width: {col * threshold + threshold}px)");

                return $$"""
                    /* VForm2: 横{{col}}列の場合のレイアウト */
                    @container {{string.Join(" and ", minmax)}} {
                      .vform-template-column {
                        grid-template-columns: calc((1px * var(--vform-max-depth)) + var(--vform-label-width)) 1fr{{(col >= 2 ? $" repeat({col - 1}, var(--vform-label-width) 1fr)" : string.Empty)}};
                      }
                    {{Enumerable.Range(1, maxMember).SelectTextTemplate(i => $$"""

                      .vform-vertical-{{i}}-items {
                        grid-template-rows: repeat({{Math.Ceiling((decimal)i / col)}}, auto);
                      }
                    """)}}
                    }
                    """;
            });

            return new SourceFile {
                FileName = "vform2-container-query.css",
                Contents = $$"""
                    {{sections.SelectTextTemplate(source => $$"""

                    {{source}}
                    """)}}
                    """,
            };
        }

        private static SourceFile RenderTypeScriptUtilIndex(bool hasReadModel2) {
            return new SourceFile {
                FileName = "index.ts",
                Contents = $$"""
                    export * from "./MSG"
                    export * from "./constraints"
                    export * from "./presentation-context"
                    {{If(hasReadModel2, () => $$"""
                    export * from "./single-view-util"
                    """)}}
                    export * from "./space-finder-const"
                    export * from "./auth-util"
                    export * from "./index"
                    """,
            };
        }

        private static SourceFile RenderSingleViewUtil() {
            return new SourceFile {
                FileName = "single-view-util.ts",
                Contents = """
                    import React from "react"
                    import * as ReactHookForm from "react-hook-form"
                    import { useParams } from "react-router"

                    /** SingleViewがとりうるモード。新規登録、編集、閲覧モードのいずれか。 */
                    export type SingleViewModeType = 'new' | 'edit' | 'detail'

                    /**
                     * URLを解釈しSingleViewModeTypeを返します。
                     * いま表示されている画面がSingleViewではなかったり、
                     * 読み込み完了していなかったりする間はundefinedを返します。
                     */
                    export const useSingleViewMode = (): SingleViewModeType | undefined => {
                      const { mode } = useParams()
                      return React.useMemo(() => {
                        if (mode === 'new') return 'new'
                        if (mode === 'detail') return 'detail'
                        if (mode === 'edit') return 'edit'
                        return undefined
                      }, [mode])
                    }

                    // --------------------------------------

                    /**
                     * SingleViewの初期表示時のデータの読み込み状態。
                     * loadedなら読み込み完了（ただし読み込み処理の成否を問わない）
                     */
                    export type SingleViewLoadState = undefined | 'loading' | 'loaded' | 'loaded(error)'

                    /** SingleViewのナビゲーションやリロード時のオプション */
                    export type SingleViewNavigationOptions = {
                      /** クエリパラメータを加工したい場合に使用 */
                      editQueryParameter?: (searchParams: URLSearchParams) => void
                      /** React Router のnavigate関数に渡される任意の値 */
                      navigatorState?: {}
                    }

                    /** SingleViewのデータの読み込みの共通処理のReactフックの型 */
                    export type SingleViewDataLoader<TSearchCondition, TDisplayData> = (
                      onBeforeInit?: SingleViewDataLoaderOnBeforeInit<TDisplayData>,
                      onBeforeLoad?: SingleViewDataLoaderOnBeforeLoad<TSearchCondition>,
                    ) => {
                      /** 読み込まれたデータ。 */
                      data: TDisplayData | undefined
                      /** 読み込み状態。loadedなら読み込み完了（ただし読み込み処理の成否を問わない） */
                      loadState: SingleViewLoadState
                      /** 再読み込みを実行する。 */
                      reload: (options?: SingleViewNavigationOptions) => void
                    }

                    /** SingleViewの初期データ表示時、サーバー側カスタマイズ処理実行後に実行されるクライアント側カスタマイズ処理 */
                    export type SingleViewDataLoaderOnBeforeInit<TDisplayData> = (args: {
                      displayData: TDisplayData
                    }) => TDisplayData

                    /** SingleViewのデータの読み込みの共通処理の検索前に実行されるカスタマイズ処理 */
                    export type SingleViewDataLoaderOnBeforeLoad<TSearchCondition> = (args: {
                      /** 初期読み込みに使われる検索条件。この値を書き換えるとその条件で検索される。 */
                      searchCondition: TSearchCondition
                    }) => void

                    // --------------------------------------

                    /** SingleViewのデータ保存処理のReactフックの型 */
                    export type SingleViewSaveProcess<T extends ReactHookForm.FieldValues> = (
                      reactHookFormMethods: ReactHookForm.UseFormReturn<T>
                    ) => SaveFunction<T>

                    /** 引数の内容で保存処理を実行する関数。戻り値は処理成否 */
                    export type SaveFunction<T> = (data: T) => Promise<boolean>

                    """,
            };
        }

        private static SourceFile RenderPresentationContextTypeScript() {
            return new SourceFile {
                FileName = "presentation-context.ts",
                Contents = """
                    /** 更新系処理結果後のプレゼンテーション側の状態。このオブジェクトの型はサーバー側と合わせる必要がある */
                    export type PresentationContextState<T = object> = {
                      /** 処理全体の成否 */
                      ok: boolean
                      /** 処理結果の概要。「処理成功しました」など */
                      summary?: string
                      /** 確認メッセージ */
                      confirms?: string[]
                      /** 処理結果の詳細。項目ごとにメッセージが格納される。 */
                      detail?: [string, ReactHookFormMultipleErrorObject][]
                      /** アプリケーション側からプレゼンテーション側に返す任意の値 */
                      returnValue?: T
                    }

                    /**
                     * react-hook-form で1つのフィールドに複数のエラーを表示させる場合のエラーメッセージのオブジェクトの型。
                     * ただしキー名を "ERROR-" 等で始めるのは react-hook-forms ではなくこのプロジェクトの都合（警告やインフォメーションで色を分けるため）
                     */
                    export type ReactHookFormMultipleErrorObject = {
                      types: {
                        [key in `ERROR-${number | string}` | `WARN-${number | string}` | `INFO-${number | string}`]: string
                      }
                    }
                    """,
            };
        }

        private static SourceFile RenderSpaceFinderConstTypeScript(CodeRenderingContext ctx) {
            var maxFileSize = ctx.Config.MaxFileSizeMB?.ToString() ?? "undefined";
            var maxTotalFileSize = ctx.Config.MaxTotalFileSizeMB?.ToString() ?? "undefined";
            var extensions = string.IsNullOrWhiteSpace(ctx.Config.AttachmentFileExtensions)
                ? "undefined"
                : $"[{string.Join(", ", ctx.Config.AttachmentFileExtensions.Split(';', StringSplitOptions.RemoveEmptyEntries).Select(ext => $"'.{ext}'"))}]";

            return new SourceFile {
                FileName = "space-finder-const.ts",
                Contents = $$"""
                    /** Webブラウザから添付ファイルとして添付可能なファイルの制限を表す定数。 */
                    export const AttachmentFileConst = {
                      /** 添付可能なファイルの上限サイズ（メガバイト） */
                      MaxFileSizeMB: {{maxFileSize}},
                      /** 一度に複数ファイル添付する際のトータルの上限サイズ（メガバイト） */
                      MaxTotalFileSizeMB: {{maxTotalFileSize}},
                      /** 添付可能なファイルの拡張子 */
                      AttachmentFileExtensions: {{extensions}},
                    }
                    """,
            };
        }
    }
}
