using System.Text;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using NLog.Extensions.Logging;

namespace MyApp;

partial class OverridedApplicationService {

    /// <summary>ログ出力用キー名: ログインユーザーID</summary>
    public const string LOG_SCOPEPROP_LOGIN_USERID = "LoginUserId";
    /// <summary>ログ出力用キー名: 処理名</summary>
    public const string LOG_SCOPEPROP_PROCESS_NAME = "ProcessName";
    /// <summary>ログ出力用キー名: 処理1回分の識別子</summary>
    public const string LOG_SCOPEPROP_SCOPE_ID = "ScopeId";

    /// <summary>
    /// DIコンテナへのサービス登録を行う。
    /// </summary>
    /// <param name="services">DIコンテナ</param>
    /// <param name="basePath">実行時設定ファイルのベースパス（appsettings.jsonのあるフォルダ）</param>
    public static void ConfigureServices(IServiceCollection services, string basePath) {
        if (!Path.IsPathRooted(basePath)) throw new ArgumentException($"{nameof(basePath)}は絶対パスで指定してください。");

        // アプリケーションサービスをDIコンテナに登録
        services.AddScoped<OverridedApplicationService>();
        services.AddScoped<AutoGeneratedApplicationService>(sp => sp.GetRequiredService<OverridedApplicationService>());

        // 実行時設定ファイルの読み込み設定
        var myAppSection = new ConfigurationBuilder()
            .SetBasePath(basePath)
            .AddJsonFile("appsettings.json", false)
            .AddJsonFile("appsettings.Development.json", true) // 後にAddされたファイルが優先される
            .Build()
            .GetSection(RuntimeSetting.MY_APP_SECTION);
        var settings = new RuntimeSetting();
        myAppSection.Bind(settings);
        services.AddSingleton(settings);

        // DBコンテキスト登録
        services.AddScoped<AutoGeneratedDbContext, OverridedDbContext>();
        services.AddDbContext<OverridedDbContext>((services, options) => {

            // SQLiteを使用する
            var settings = services.GetRequiredService<RuntimeSetting>();
            var connStr = settings.GetCurrentProfile().ConnStr;
            options.UseSqlite(connStr, builder => {
                // マイグレーションファイルが生成されるアセンブリを指定する。
                // 既定では DbContext が宣言されているプロジェクトになる。
                builder.MigrationsAssembly(typeof(OverridedApplicationService).Assembly.FullName);
            });

            // 自動生成される登録更新処理は変更追跡オフが前提
            options.UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);
        });

        // ログ設定
        LogSettings.ConfigureServices(services, myAppSection, basePath);

        // 外部システム連携
        Configure外部システム(services, settings);
    }

    /// <summary>
    /// 外部システム連携に必要なサービスをDIコンテナに登録する。
    /// 連携する外部システムが無い場合は実装しなくてよい（実装が無ければ呼び出しごと取り除かれる）。
    /// </summary>
    /// <param name="services">DIコンテナ</param>
    /// <param name="settings">実行時設定</param>
    static partial void Configure外部システム(IServiceCollection services, RuntimeSetting settings);
}
