
namespace MyApp;

partial class OverridedDummyDataGenerator {

    public OverridedDummyDataGenerator(Func<IMessageSetter, IPresentationContext<MessageSetter>> createPresentationContext) {
        _createPresentationContext = createPresentationContext;
    }
    private readonly Func<IMessageSetter, IPresentationContext<MessageSetter>> _createPresentationContext;

    // セッションはダミーデータ不要
    protected override IEnumerable<セッションCreateCommand> CreatePatternsOfセッション(DummyDataGenerateContext context) {
        yield break;
    }

    // 商品は適当に作成
    protected override IEnumerable<商品CreateCommand> CreatePatternsOf商品(DummyDataGenerateContext context) {
        foreach (var item in Enumerable.Range(1, 50)) {
            yield return new 商品CreateCommand {
                外部システム側ID = $"C{item:0000}",
                商品名 = $"商品その{item:0000}",
                売値単価_税抜 = 1000 + item * 10,
                消費税区分 = context.Random.Next(1, 3) switch {
                    1 => 消費税区分.一般税率,
                    2 => 消費税区分.軽減税率,
                    _ => 消費税区分.非課税,
                },
            };
        }
    }

    /// <summary>
    /// テスト用の管理者ユーザーの従業員番号
    /// </summary>
    public const string ADMIN_USER_ID = "demo101-admin";

    // ユーザーは管理者 + 適当な人
    protected override IEnumerable<従業員CreateCommand> CreatePatternsOf従業員(DummyDataGenerateContext context) {
        var salt = OverridedApplicationService.GenerateSalt();

        // 固定ユーザー: demo101-admin / demo101-admin
        yield return new 従業員CreateCommand {
            従業員番号 = ADMIN_USER_ID,
            氏名 = "デモ用ユーザー",
            パスワード = OverridedApplicationService.ComputeHash("demo101-admin", salt),
            SALT = salt,
            入荷担当 = true,
            販売担当 = true,
            システム管理者 = true,
        };

        // その他適当なユーザー
        foreach (var i in Enumerable.Range(1, 10)) {
            yield return new 従業員CreateCommand {
                従業員番号 = $"user{i:000}",
                氏名 = $"ユーザー{i:000}",
                パスワード = OverridedApplicationService.ComputeHash("password", salt),
                SALT = salt,
                入荷担当 = i % 2 == 0,
                販売担当 = i % 3 == 0,
                システム管理者 = false,
            };
        }
    }

    // トランザクション系は計算が複雑なので
    // データを列挙するのではなく CommandModel による実際の更新処理を使ってデータを作る
    protected override IEnumerable<入荷CreateCommand> CreatePatternsOf入荷(DummyDataGenerateContext context) {
        yield break;
    }
    protected override IEnumerable<入荷明細CreateCommand> CreatePatternsOf入荷明細(DummyDataGenerateContext context) {
        yield break;
    }
    protected override IEnumerable<売上CreateCommand> CreatePatternsOf売上(DummyDataGenerateContext context) {
        yield break;
    }
    protected override IEnumerable<在庫調整CreateCommand> CreatePatternsOf在庫調整(DummyDataGenerateContext context) {
        yield break;
    }

    public override async Task<IMessageSetter> GenerateAsync(AutoGeneratedApplicationService applicationService, DummyDataGenerateOptions? options = null) {

        // マスタ系のダミーは標準処理を実行
        var result = await base.GenerateAsync(applicationService, options);
        if (result.HasError()) {
            result.AddError("マスタ系ダミーデータの登録に失敗しました。");
            return result;
        }

        // トランザクション系データは CommandModel 経由で登録する。
        // 途中で登録失敗したらその時点で中断。
        var presentationContext = _createPresentationContext(result);

        // 入荷新規登録のパターン
        // * 明細の数: 一度に1明細 or 複数明細
        // * 商品: 複数回入荷される商品（多め） or 1回のみ入荷される商品（まあまあ） or 一度も入荷されない商品（少し）
        for (var i = 0; i < 50; i++) {
            await applicationService.Execute入荷登録Async(new() {
                // TODO
            }, presentationContext.As<入荷詳細Messages>());

            if (presentationContext.Messages.HasError()) {
                presentationContext.Messages.AddError("入荷データの登録に失敗しました。");
                return presentationContext.Messages;
            }
        }

        // 売上新規登録 + 売上修正 のパターン
        // * 売上修正の有無: あり / なし
        // * 明細の数: 一度に1明細 or 複数明細
        // * 商品: 先ほど入荷されたものの中からピックアップ
        for (int i = 0; i < 50; i++) {

            // 売上新規登録
            await applicationService.Execute売上新規登録Async(new() {
                Values = new() {
                    // TODO
                },
            }, presentationContext.As<売上詳細Messages>());

            if (presentationContext.Messages.HasError()) {
                presentationContext.Messages.AddError("売上新規登録に失敗しました。");
                return presentationContext.Messages;
            }

            // 売上修正
            if (i % 4 == 0) continue; // 修正されない売上のパターンが欲しいので

            await applicationService.Execute売上修正Async(new() {
                Values = new() {
                    // TODO
                },
            }, presentationContext.As<売上詳細Messages>());

            if (presentationContext.Messages.HasError()) {
                presentationContext.Messages.AddError("売上修正に失敗しました。");
                return presentationContext.Messages;
            }
        }

        // 在庫調整のパターン
        // * 指定方法: 絶対数で指定 or 増減数で指定
        // * 商品: 売上登録 + 修正 で登場したものの中からピックアップ
        for (int i = 0; i < 20; i++) {
            await applicationService.Execute在庫調整登録Async(new() {
                Values = new() {
                    // TODO
                },
            }, presentationContext.As<在庫調整ParameterMessages>());

            if (presentationContext.Messages.HasError()) {
                presentationContext.Messages.AddError("在庫調整データの登録に失敗しました。");
                return presentationContext.Messages;
            }
        }

        return presentationContext.Messages;
    }
}
