
using Microsoft.EntityFrameworkCore; // Add for Include, ToListAsync

namespace MyApp;

partial class OverridedDummyDataGenerator {

    public OverridedDummyDataGenerator(Func<IMessageSetter, IPresentationContext<MessageSetter>> createPresentationContext) {
        _createPresentationContext = createPresentationContext;
    }
    private readonly Func<IMessageSetter, IPresentationContext<MessageSetter>> _createPresentationContext;

    // セッションはダミーデータ不要
    protected override IEnumerable<セッションCreateCommand> CreatePatternsOfセッション(DummyDataGenerateContext context) {
        yield break;
    }

    // 商品は適当に作成
    protected override IEnumerable<商品CreateCommand> CreatePatternsOf商品(DummyDataGenerateContext context) {
        foreach (var item in Enumerable.Range(1, 50)) {
            yield return new 商品CreateCommand {
                外部システム側ID = $"C{item:0000}",
                商品名 = $"商品その{item:0000}",
                売値単価_税抜 = 1000 + item * 10,
                消費税区分 = context.Random.Next(1, 3) switch {
                    1 => 消費税区分.一般税率,
                    2 => 消費税区分.軽減税率,
                    _ => 消費税区分.非課税,
                },
            };
        }
    }

    /// <summary>
    /// テスト用の管理者ユーザーの従業員番号
    /// </summary>
    public const string ADMIN_USER_ID = "admin";
    /// <summary>
    /// テスト用の管理者ユーザーのパスワード
    /// </summary>
    public const string DUMMY_USER_PASSWORD = "password123";

    // ユーザーは管理者 + 適当な人
    protected override IEnumerable<従業員CreateCommand> CreatePatternsOf従業員(DummyDataGenerateContext context) {
        var salt = OverridedApplicationService.GenerateSalt();

        // 固定ユーザー: admin / admin
        yield return new 従業員CreateCommand {
            従業員番号 = ADMIN_USER_ID,
            氏名 = "デモ用ユーザー",
            パスワード = OverridedApplicationService.ComputeHash(DUMMY_USER_PASSWORD, salt),
            SALT = salt,
            入荷担当 = true,
            販売担当 = true,
            システム管理者 = true,
        };

        // その他適当なユーザー
        foreach (var i in Enumerable.Range(1, 10)) {
            yield return new 従業員CreateCommand {
                従業員番号 = $"user{i:000}",
                氏名 = $"ユーザー{i:000}",
                パスワード = OverridedApplicationService.ComputeHash(DUMMY_USER_PASSWORD, salt),
                SALT = salt,
                入荷担当 = i % 2 == 0,
                販売担当 = i % 3 == 0,
                システム管理者 = false,
            };
        }
    }

    // トランザクション系は計算が複雑なので
    // データを列挙するのではなく CommandModel による実際の更新処理を使ってデータを作る
    protected override IEnumerable<入荷CreateCommand> CreatePatternsOf入荷(DummyDataGenerateContext context) {
        yield break;
    }
    protected override IEnumerable<入荷明細CreateCommand> CreatePatternsOf入荷明細(DummyDataGenerateContext context) {
        yield break;
    }
    protected override IEnumerable<売上CreateCommand> CreatePatternsOf売上(DummyDataGenerateContext context) {
        yield break;
    }
    protected override IEnumerable<在庫調整CreateCommand> CreatePatternsOf在庫調整(DummyDataGenerateContext context) {
        yield break;
    }

    public override async Task<IMessageSetter> GenerateAsync(AutoGeneratedApplicationService applicationService, DummyDataGenerateOptions? options = null) {

        // マスタ系のダミーは標準処理を実行
        var result = await base.GenerateAsync(applicationService, options);
        if (result.HasError()) {
            result.AddError("マスタ系ダミーデータの登録に失敗しました。");
            return result;
        }

        var db = applicationService.DbContext;
        var allItems = await db.商品DbSet.ToListAsync();
        var adminUser = await db.従業員DbSet.SingleAsync(e => e.従業員番号 == ADMIN_USER_ID);
        var rand = new Random(0);

        var adminUserRef = new 従業員RefRefTarget {
            従業員番号 = adminUser.従業員番号,
            氏名 = adminUser.氏名,
        };

        // トランザクション系データは CommandModel 経由で登録する。
        // 途中で登録失敗したらその時点で中断。
        var presentationContext = _createPresentationContext(result);

        // この後の処理には入荷や売上の権限を持ったユーザーでログインしておく必要がある。
        // 通常のログイン処理を通すとHTTPヘッダのCookieを参照してしまうので、リフレクションで無理矢理書き換える
        var loginUserCache = typeof(OverridedApplicationService).GetField("_loginUserCache", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance)!;
        var isLoginUserLoaded = typeof(OverridedApplicationService).GetField("_isLoginUserLoaded", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance)!;

        loginUserCache.SetValue(applicationService, new Core.Authorization.LoginUser {
            従業員番号 = ADMIN_USER_ID,
            氏名 = DUMMY_USER_PASSWORD,
            Isシステム管理者 = true,
            CanUse入荷登録 = true,
            CanUse売上登録 = true,
        });
        isLoginUserLoaded.SetValue(applicationService, true);

        // 全商品を少なくとも1回は入荷する（売上データ作成時に在庫不足エラーにならないようにするため）
        foreach (var item in allItems) {
            var details = new List<入荷商品一覧DisplayData>();
            details.Add(new 入荷商品一覧DisplayData {
                Values = new 入荷商品一覧DisplayDataValues {
                    商品 = new 商品RefTarget {
                        商品SEQ = item.商品SEQ,
                        外部システム側ID = item.外部システム側ID,
                        商品名 = item.商品名,
                        売値単価_税抜 = item.売値単価_税抜,
                        消費税区分 = item.消費税区分,
                    },
                    数量 = 100, // 確実に在庫を持たせる
                    仕入単価_税抜 = item.売値単価_税抜 * 0.7m,
                    消費税区分 = item.消費税区分,
                    備考 = "初期在庫",
                }
            });

            await applicationService.Execute入荷登録Async(new() {
                Values = new() {
                    入荷日時 = DateTime.Now.AddDays(-30),
                    担当者 = adminUserRef,
                    備考 = "初期在庫入荷",
                },
                入荷商品一覧 = details,
            }, presentationContext.As<入荷詳細Messages>());

            if (presentationContext.Messages.HasError()) {
                presentationContext.Messages.AddError("初期在庫の登録に失敗しました。");
                return presentationContext.Messages;
            }
        }

        // 入荷新規登録のパターン
        // * 明細の数: 一度に1明細 or 複数明細
        // * 商品: 複数回入荷される商品（多め） or 1回のみ入荷される商品（まあまあ）
        for (var i = 0; i < 50; i++) {
            var details = new List<入荷商品一覧DisplayData>();
            var itemCount = rand.Next(1, 6); // 1〜5個の商品
            for (var j = 0; j < itemCount; j++) {
                var item = allItems[rand.Next(allItems.Count)];
                details.Add(new 入荷商品一覧DisplayData {
                    Values = new 入荷商品一覧DisplayDataValues {
                        商品 = new 商品RefTarget {
                            商品SEQ = item.商品SEQ,
                            外部システム側ID = item.外部システム側ID,
                            商品名 = item.商品名,
                            売値単価_税抜 = item.売値単価_税抜,
                            消費税区分 = item.消費税区分,
                        },
                        数量 = rand.Next(1, 100),
                        仕入単価_税抜 = item.売値単価_税抜 * 0.7m,
                        消費税区分 = item.消費税区分,
                        備考 = $"テスト入荷明細 {i}-{j}",
                    }
                });
            }

            await applicationService.Execute入荷登録Async(new() {
                Values = new() {
                    入荷日時 = DateTime.Now.AddDays(-rand.Next(0, 30)),
                    担当者 = adminUserRef,
                    備考 = $"自動生成された入荷データ {i}",
                },
                入荷商品一覧 = details,
            }, presentationContext.As<入荷詳細Messages>());

            if (presentationContext.Messages.HasError()) {
                presentationContext.Messages.AddError("入荷データの登録に失敗しました。");
                return presentationContext.Messages;
            }
        }

        // 売上新規登録 + 売上修正 のパターン
        // * 売上修正の有無: あり / なし
        // * 明細の数: 一度に1明細 or 複数明細
        // * 商品: 先ほど入荷されたものの中からピックアップ
        for (int i = 0; i < 50; i++) {

            var details = new List<売上詳細の売上明細DisplayData>();
            var itemCount = rand.Next(1, 4);
            for (var j = 0; j < itemCount; j++) {
                var item = allItems[rand.Next(allItems.Count)];
                details.Add(new 売上詳細の売上明細DisplayData {
                    Values = new 売上詳細の売上明細DisplayDataValues {
                        商品 = new 商品RefTarget {
                            商品SEQ = item.商品SEQ,
                            外部システム側ID = item.外部システム側ID,
                            商品名 = item.商品名,
                            売値単価_税抜 = item.売値単価_税抜,
                            消費税区分 = item.消費税区分,
                        },
                        区分 = 売上明細区分.売上,
                        売上数量 = rand.Next(1, 5),
                    }
                });
            }

            // 売上新規登録
            await applicationService.Execute売上新規登録Async(new() {
                Values = new() {
                    売上日時 = DateTime.Now.AddDays(-rand.Next(0, 10)),
                    担当者 = adminUserRef,
                    備考 = $"自動生成された売上 {i}",
                },
                売上詳細の売上明細 = details,
            }, presentationContext.As<売上詳細Messages>());

            if (presentationContext.Messages.HasError()) {
                presentationContext.Messages.AddError("売上新規登録に失敗しました。");
                return presentationContext.Messages;
            }

            // 売上修正
            if (i % 4 == 0) {
                continue; // 修正されない売上のパターンが欲しいので
            }

            // 直前に登録された売上を取得
            var lastSales = await db.売上DbSet
                                  .OrderByDescending(s => s.売上SEQ)
                                  .Include(s => s.売上の売上明細)
                                  .ThenInclude(d => d.商品)
                                  .FirstOrDefaultAsync();

            if (lastSales != null) {
                var updateDetails = new List<売上詳細の売上明細DisplayData>();
                foreach (var d in lastSales.売上の売上明細) {
                    var dItem = d.商品;
                    updateDetails.Add(new 売上詳細の売上明細DisplayData {
                        Values = new 売上詳細の売上明細DisplayDataValues {
                            明細ID = d.明細ID,
                            商品 = dItem != null ? new 商品RefTarget {
                                商品SEQ = dItem.商品SEQ,
                                外部システム側ID = dItem.外部システム側ID,
                                商品名 = dItem.商品名,
                                売値単価_税抜 = dItem.売値単価_税抜,
                                消費税区分 = dItem.消費税区分
                            } : new(),
                            区分 = d.区分,
                            売上数量 = d.売上数量,
                            売上総額_税込_手修正 = d.売上総額_税込,
                        },
                        ExistsInDatabase = true,
                    });
                }

                await applicationService.Execute売上修正Async(new() {
                    Values = new() {
                        売上SEQ = lastSales.売上SEQ,
                        売上日時 = lastSales.売上日時,
                        担当者 = adminUserRef,
                        備考 = lastSales.備考 + " (修正済み)",
                    },
                    売上詳細の売上明細 = updateDetails,
                    ExistsInDatabase = true,
                }, presentationContext.As<売上詳細Messages>());

                if (presentationContext.Messages.HasError()) {
                    presentationContext.Messages.AddError("売上修正に失敗しました。");
                    return presentationContext.Messages;
                }
            }
        }

        // 在庫調整のパターン
        // * 指定方法: 絶対数で指定 or 増減数で指定
        // * 商品: 売上登録 + 修正 で登場したものの中からピックアップ
        for (int i = 0; i < 20; i++) {
            var item = allItems[rand.Next(allItems.Count)];
            var useAbsolute = rand.Next(2) == 0;

            int? fluctuation = null;
            int? absolute = null;

            if (useAbsolute) {
                // 現在の在庫数と偶然一致してしまって「変更がありません」エラーになるのを避けるため、
                // ランダムな値を生成しつつ、もしエラーならそれはテストとしては無視したいが、
                // ここでは簡易的に、あまり在庫数としてありえなさそうな大きな値を設定することで回避を試みる。
                // (前段の処理で100個程度の在庫が入っているはず)
                absolute = rand.Next(10000, 20000);
            } else {
                // 0だと「変更がありません」エラーになるので0以外にする
                do {
                    fluctuation = rand.Next(-10, 11);
                } while (fluctuation == 0);
            }

            await applicationService.Execute在庫調整登録Async(new() {
                Values = new() {
                    商品 = new 商品RefTarget {
                        商品SEQ = item.商品SEQ,
                        外部システム側ID = item.外部システム側ID,
                        商品名 = item.商品名,
                        売値単価_税抜 = item.売値単価_税抜,
                        消費税区分 = item.消費税区分,
                    },
                    在庫調整理由 = $"ダミー在庫調整 {i}",
                    増減数 = fluctuation,
                    絶対数 = absolute,
                },
            }, presentationContext.As<在庫調整ParameterMessages>());

            if (presentationContext.Messages.HasError()) {
                presentationContext.Messages.AddError("在庫調整データの登録に失敗しました。");
                return presentationContext.Messages;
            }
        }

        return presentationContext.Messages;
    }
}
