import * as RHF from "react-hook-form"
import * as EG2 from "@halllky/editable-grid"
import type { AggregateMetadata } from "../../__autoGenerated"
import { findMemberMetadata, type GridBinding } from "../form/FormBinding"
import { assertValueMember, inputFrameClassName, toRegisterRules, type ColumnOptionsBase, type InputPropsBase, type WithFormBinding, useSelectAllOnFocus } from "./InputProps"
import { createTextCellEditor, defineCellColumn, findCellMemberMetadata } from "./GridCell"

/*
 * 文章（複数行の文字列）の入力欄。
 * フォーム用とグリッド用で以下の仕様を共有する。
 *
 * - 改行を入力できる。グリッドでは Shift+Enter で改行し、Enter で編集を確定する。
 * - 最大長はメタデータから決める。
 * - 値の確定時に前後の空白を削除し、Unicode正規化（NFKC）を行う。最大長を超える部分は切り捨てる。
 * - スペルチェックとオートコンプリートは無効。
 * - 検索条件のフォームでは、改行を入力できない1行の入力欄になる。
 */

//#region フォーム用

export type TextAreaProps<TValues extends RHF.FieldValues> = InputPropsBase<TValues> & {
  /** 未入力のときに表示する文字列 */
  placeholder?: string
}

/** 文章の入力欄（フォーム用）。内容の行数に合わせて高さが伸びる。上限は className の max-height で指定する */
export function TextArea<TValues extends RHF.FieldValues>(props: WithFormBinding<TextAreaProps<TValues>, TValues>): React.ReactNode {
  const { binding, name, isReadOnly, rules, className, placeholder } = props
  const formPath = binding.toFormPath(name)
  const member = assertValueMember(findMemberMetadata(binding.metadata, name), name, 'TextArea', isDescriptionMember)
  const maxLength = maxLengthOf(member)

  const { field } = RHF.useController({
    name: formPath,
    control: binding.formMethods.control,
    rules: toRegisterRules({ rules }),
  })
  const selectAllOnFocus = useSelectAllOnFocus()

  const handleBlur: React.FocusEventHandler<HTMLInputElement | HTMLTextAreaElement> = e => {
    const normalized = normalizeDescription(e.target.value, maxLength)
    if (normalized !== (field.value ?? '')) field.onChange(normalized)
    field.onBlur()
  }

  const commonProps = {
    name: field.name,
    value: field.value ?? '',
    onChange: (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => field.onChange(e.target.value),
    onBlur: handleBlur,
    readOnly: isReadOnly,
    maxLength,
    placeholder: isReadOnly ? undefined : placeholder,
    spellCheck: false,
    autoComplete: 'off',
  }

  // 検索条件では改行を入力できない1行の入力欄にする
  return binding.kind === 'search-condition' ? (
    <input
      type="text"
      ref={field.ref}
      {...commonProps}
      {...selectAllOnFocus}
      className={`block px-1 py-px outline-none ${inputFrameClassName(isReadOnly)} ${className ?? ''}`}
    />
  ) : (
    <textarea
      ref={field.ref}
      {...commonProps}
      className={`block w-full px-1 py-px outline-none resize-none field-sizing-content ${inputFrameClassName(isReadOnly)} ${className ?? ''}`}
    />
  )
}

//#endregion フォーム用

//#region グリッド用

export type TextAreaColumnOptions<TRow> = ColumnOptionsBase<TRow> & {
  /** セルの中で折り返して全文を表示するかどうか。未指定の場合は折り返さず、1行に収まらない部分は省略する */
  wrap?: boolean
}

/** 文章の列（グリッド用） */
export function textAreaColumn<TRow>(
  binding: GridBinding,
  path: RHF.Path<TRow>,
  options?: TextAreaColumnOptions<TRow>,
): EG2.EditableGridLeafColumn<TRow> {
  const member = assertValueMember(findCellMemberMetadata(binding, path), path, 'textArea 列', isDescriptionMember)
  const maxLength = maxLengthOf(member)
  const { wrap, ...columnOptions } = options ?? {}

  return defineCellColumn(binding, path, columnOptions, {
    render: ({ value }) => typeof value === 'string' ? value : '',
    editor: DESCRIPTION_CELL_EDITOR,
    toText: value => typeof value === 'string' ? value : '',
    fromText: text => ({ value: normalizeDescription(text, maxLength) }),
    wrap,
  })
}

/** 文章のセルエディタ。参照を使い回すためモジュールのトップレベルで作る */
const DESCRIPTION_CELL_EDITOR = createTextCellEditor({ multiline: true })

//#endregion グリッド用

//#region フォームとグリッドで共有する仕様

function isDescriptionMember(member: AggregateMetadata.Value): boolean {
  return member.type === 'description'
}

/**
 * メタデータから最大長を求める。制限が無い場合は undefined。
 * ノードオプションの最大長はデータベースの桁数の定義に使うものなので見ず、画面制御用のカスタム属性の最大長を使う。
 */
function maxLengthOf(member: AggregateMetadata.Member): number | undefined {
  return member.customMaxLength !== undefined && member.customMaxLength > 0
    ? member.customMaxLength
    : undefined
}

/** 値の確定時の正規化 */
function normalizeDescription(value: string, maxLength: number | undefined): string {
  const normalized = value.trim().normalize('NFKC')
  return maxLength === undefined ? normalized : normalized.slice(0, maxLength)
}

//#endregion フォームとグリッドで共有する仕様
