import * as RHF from "react-hook-form"
import * as EG2 from "@halllky/editable-grid"
import type { AggregateMetadata } from "../../__autoGenerated"
import { findMemberMetadata, type GridBinding } from "../form/FormBinding"
import { assertValueMember, inputFrameClassName, toRegisterRules, type ColumnOptionsBase, type InputPropsBase, type WithFormBinding, useSelectAllOnFocus } from "./InputProps"
import { createTextCellEditor, defineCellColumn, findCellMemberMetadata } from "./GridCell"

/*
 * 単語（1行の文字列）の入力欄。
 * フォーム用とグリッド用で以下の仕様を共有する。
 *
 * - 最大長はメタデータから決める。
 * - 値の確定時（フォームはフォーカスアウト、グリッドはセル編集の確定と貼り付け）に、
 *   前後の空白を削除し、Unicode正規化（NFKC）を行う。最大長を超える部分は切り捨てる。
 * - スペルチェックとオートコンプリートは無効。
 * - 検索条件のフォームで、メタデータの検索挙動が範囲指定の項目は、範囲指定（下限〜上限）の2つの入力欄になる。
 *   それ以外の項目は1つの入力欄で、一致方法（部分一致など）はサーバー側が決める。
 */

//#region フォーム用

export type TextBoxProps<TValues extends RHF.FieldValues> = InputPropsBase<TValues> & {
  /** 未入力のときに表示する文字列 */
  placeholder?: string
  /** 入力内容を伏せ字で表示するかどうか。パスワードなどに使う。 */
  masked?: boolean
}

/** 単語の入力欄（フォーム用） */
export function TextBox<TValues extends RHF.FieldValues>(props: WithFormBinding<TextBoxProps<TValues>, TValues>): React.ReactNode {
  const { binding, name, isReadOnly, rules, className, placeholder, masked } = props
  const formPath = binding.toFormPath(name)
  const member = assertValueMember(findMemberMetadata(binding.metadata, name), name, 'TextBox', isWordMember)
  const maxLength = maxLengthOf(member)

  // 画面表示用データと、範囲指定でない検索条件では1つの入力欄
  if (binding.kind === 'display-data' || member.stringSearchBehavior !== STRING_SEARCH_BEHAVIOR_RANGE) {
    return (
      <WordInput
        formPath={formPath}
        control={binding.formMethods.control}
        rules={toRegisterRules({ rules })}
        maxLength={maxLength}
        isReadOnly={isReadOnly}
        placeholder={placeholder}
        masked={masked}
        className={className}
      />
    )
  }

  // 範囲指定の検索条件。範囲全体に対する検証は下限の入力欄に付ける
  return (
    <div className={`flex items-center gap-1 ${className ?? ''}`}>
      {/* 下限 */}
      <WordInput
        formPath={`${formPath}.from`}
        control={binding.formMethods.control}
        rules={toRegisterRules({
          rules,
          itemValueOf: (_, formValues) => RHF.get(formValues, formPath),
          validators: [range => validateWordRange(range as WordRange | undefined)],
        })}
        maxLength={maxLength}
        isReadOnly={isReadOnly}
        placeholder={placeholder}
        className="flex-1 min-w-0"
      />
      <span className="select-none">～</span>
      {/* 上限 */}
      <WordInput
        formPath={`${formPath}.to`}
        control={binding.formMethods.control}
        rules={toRegisterRules({ rules: undefined })}
        maxLength={maxLength}
        isReadOnly={isReadOnly}
        placeholder={placeholder}
        className="flex-1 min-w-0"
      />
    </div>
  )
}

/** 1つの単語の入力欄。フォーカスアウト時に値を正規化する */
function WordInput({ formPath, control, rules, maxLength, isReadOnly, placeholder, masked, className }: {
  formPath: string
  control: RHF.Control<RHF.FieldValues>
  rules: Pick<RHF.RegisterOptions, 'validate'>
  maxLength: number | undefined
  isReadOnly: boolean | undefined
  placeholder: string | undefined
  masked?: boolean
  className?: string
}) {
  const { field } = RHF.useController({ name: formPath, control, rules })
  const selectAllOnFocus = useSelectAllOnFocus()

  const handleBlur: React.FocusEventHandler<HTMLInputElement> = e => {
    const normalized = normalizeWord(e.target.value, maxLength)
    if (normalized !== (field.value ?? '')) field.onChange(normalized)
    field.onBlur()
  }

  return (
    <input
      type={masked ? "password" : "text"}
      ref={field.ref}
      name={field.name}
      value={field.value ?? ''}
      onChange={e => field.onChange(e.target.value)}
      onBlur={handleBlur}
      {...selectAllOnFocus}
      readOnly={isReadOnly}
      maxLength={maxLength}
      placeholder={isReadOnly ? undefined : placeholder}
      spellCheck={false}
      autoComplete="off"
      className={`block px-1 py-px outline-none ${inputFrameClassName(isReadOnly)} ${className ?? ''}`}
    />
  )
}

//#endregion フォーム用

//#region グリッド用

export type TextColumnOptions<TRow> = ColumnOptionsBase<TRow>

/** 単語の列（グリッド用） */
export function textColumn<TRow>(
  binding: GridBinding,
  path: RHF.Path<TRow>,
  options?: TextColumnOptions<TRow>,
): EG2.EditableGridLeafColumn<TRow> {
  const member = assertValueMember(findCellMemberMetadata(binding, path), path, 'text 列', isWordMember)
  const maxLength = maxLengthOf(member)

  return defineCellColumn(binding, path, options, {
    render: ({ value }) => typeof value === 'string' ? value : '',
    editor: WORD_CELL_EDITOR,
    toText: value => typeof value === 'string' ? value : '',
    fromText: text => ({ value: normalizeWord(text, maxLength) }),
  })
}

/** 単語のセルエディタ。参照を使い回すためモジュールのトップレベルで作る */
const WORD_CELL_EDITOR = createTextCellEditor({ multiline: false })

//#endregion グリッド用

//#region フォームとグリッドで共有する仕様

function isWordMember(member: AggregateMetadata.Value): boolean {
  return member.type === 'word'
}

/**
 * メタデータから最大長を求める。制限が無い場合は undefined。
 * ノードオプションの最大長はデータベースの桁数の定義に使うものなので見ず、画面制御用のカスタム属性の最大長を使う。
 */
function maxLengthOf(member: AggregateMetadata.Member): number | undefined {
  return member.customMaxLength !== undefined && member.customMaxLength > 0
    ? member.customMaxLength
    : undefined
}

/** メタデータの検索挙動のうち、範囲指定を表す値。ui フォルダ内部でのみ使用する */
export const STRING_SEARCH_BEHAVIOR_RANGE = 'Range'

/** 検索条件の範囲指定の値 */
type WordRange = { from?: string | null, to?: string | null }

/** 範囲指定の下限が上限を超えていればエラーメッセージを返す。大小は文字コードの順で比べる */
function validateWordRange(range: WordRange | undefined): string | undefined {
  const from = range?.from ?? ''
  const to = range?.to ?? ''
  if (from === '' || to === '') return undefined
  return from > to ? '下限が上限を超えています。' : undefined
}

/** 値の確定時の正規化 */
function normalizeWord(value: string, maxLength: number | undefined): string {
  const normalized = value.trim().normalize('NFKC')
  return maxLength === undefined ? normalized : normalized.slice(0, maxLength)
}

//#endregion フォームとグリッドで共有する仕様
