using Microsoft.EntityFrameworkCore;
using MyApp.Debugging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Reflection;
using System.Collections;
using System.Diagnostics.CodeAnalysis;
using Microsoft.Extensions.Logging;

namespace MyApp.UnitTest;

partial class DB接続あり_更新なし {

    /// <summary>
    /// LINQ式をSQLに変換できないときはこの例外メッセージになる
    /// </summary>
    private const string CANNOT_TRANSRATE_TO_SQL = @"could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.";

    [Category("無条件検索でエラーが発生しないか（一覧検索）")]
    [TestCaseSource(typeof(MetadataBasedTestCases), nameof(MetadataBasedTestCases.無条件検索テストケース))]
    public async Task 無条件検索でエラーが発生しないか(
        string testCasePhysicalName,
        Type messageContainerType,
        Func<AutoGeneratedApplicationService, IPresentationContext, Task<IEnumerable<object>>> test) {

        // ダミーデータ投入
        var scope = TestUtilImpl.Instance.CreateScope($"{nameof(無条件検索でエラーが発生しないか)}_{testCasePhysicalName}");

        var generator = new OverridedDummyDataGenerator();
        await generator.GenerateAsync(scope.App);

        // 無条件検索を実行
        try {
            var presentationContext = new PresentationContextInUnitTest {
                ValidationOnly = false,
                Messages = MessageSetter.GetImpl(messageContainerType, [], new()),
                Confirms = [],
            };
            var result = await test(scope.App, presentationContext);
            scope.App.Log.LogDebug("取得したデータ: {0}", scope.App.SerializeForLog(result));
            Assert.Pass("例外発生せず");

        } catch (InvalidOperationException ex) when (ex.Message.Contains(CANNOT_TRANSRATE_TO_SQL)) {
            if (testCasePhysicalName == "アクション結果"
             || testCasePhysicalName == "在庫調査報告") {
                Assert.Inconclusive(
                    "この集約は式が複雑すぎてSQLに変換できないが（EFCoreの制約）、" +
                    "自動生成されたコードでコンパイルエラーが出ないことを確認したいので、あえて残している。" +
                    "通常の運用では、参照経路が深くなりすぎないよう、RefTo用のQueryModelを別途定義し、それを参照させることで回避する。");
            } else {
                throw;
            }
        }
    }

    [Category("無条件検索でエラーが発生しないか（外部参照検索）")]
    [TestCaseSource(typeof(MetadataBasedTestCases), nameof(MetadataBasedTestCases.無条件外部参照検索テストケース))]
    public async Task 無条件外部参照検索でエラーが発生しないか(
        string testCasePhysicalName,
        Type messageContainerType,
        Func<AutoGeneratedApplicationService, IPresentationContext, Task<IEnumerable<object>>> test) {

        // ダミーデータ投入
        var scope = TestUtilImpl.Instance.CreateScope($"{nameof(無条件外部参照検索でエラーが発生しないか)}_{testCasePhysicalName}");

        var generator = new OverridedDummyDataGenerator();
        await generator.GenerateAsync(scope.App);

        // 無条件外部参照検索を実行
        try {
            var presentationContext = new PresentationContextInUnitTest {
                ValidationOnly = false,
                Messages = MessageSetter.GetImpl(messageContainerType, [], new()),
                Confirms = [],
            };
            var result = await test(scope.App, presentationContext);
            scope.App.Log.LogDebug("取得したデータ: {0}", scope.App.SerializeForLog(result));
            Assert.Pass("例外発生せず");

        } catch (InvalidOperationException ex) when (ex.Message.Contains(CANNOT_TRANSRATE_TO_SQL)) {
            if (testCasePhysicalName == "アクション") {
                Assert.Inconclusive(
                    "この集約は式が複雑すぎてSQLに変換できないが（EFCoreの制約）、" +
                    "自動生成されたコードでコンパイルエラーが出ないことを確認したいので、あえて残している。" +
                    "通常の運用では、参照経路が深くなりすぎないよう、RefTo用のQueryModelを別途定義し、それを参照させることで回避する。");
            } else {
                throw;
            }
        }
    }
}

/// <summary>
/// リフレクションを使って Query Model の検索処理を呼び出すテストケースを生成するクラス
/// </summary>
public static class MetadataBasedTestCases {

    /// <summary>
    /// 無条件検索（通常の一覧検索）
    /// </summary>
    public static IEnumerable<TestCaseData> 無条件検索テストケース() {
        const string SEARCH_CONDITION_SUFFIX = "SearchCondition";

        var loadMethods = typeof(AutoGeneratedApplicationService)
            .GetMethods(BindingFlags.Public | BindingFlags.Instance)
            .Where(m => m.Name == nameof(AutoGeneratedApplicationService.LoadAsync));

        foreach (var method in loadMethods) {
            if (!TryGetSearchParameterTypes(method, out var searchConditionType, out var messageContainerType)) continue;

            // 検索条件の型名から集約の物理名を求める
            var name = searchConditionType.Name.EndsWith(SEARCH_CONDITION_SUFFIX)
                ? searchConditionType.Name[..^SEARCH_CONDITION_SUFFIX.Length]
                : searchConditionType.Name;

            yield return new TestCaseData(
                name,
                messageContainerType,
                CreateUnconditionalSearch(method, searchConditionType, messageContainerType, name))
                .SetName($"無条件検索_{name}");
        }
    }

    /// <summary>
    /// 無条件検索（参照検索）
    /// </summary>
    public static IEnumerable<TestCaseData> 無条件外部参照検索テストケース() {
        // 外部参照検索のメソッド名パターンを収集
        var refSearchMethods = new Dictionary<string, (Type searchConditionType, Type messageContainerType, MethodInfo method)>();

        // AutoGeneratedApplicationServiceから LoadRefs で始まるメソッドを取得
        var appServiceType = typeof(AutoGeneratedApplicationService);
        var refMethods = appServiceType.GetMethods(BindingFlags.Public | BindingFlags.Instance)
            .Where(m => m.Name.StartsWith("LoadRefs") && m.Name.EndsWith("Async"))
            .ToList();

        foreach (var method in refMethods) {
            if (!TryGetSearchParameterTypes(method, out var searchConditionType, out var messageContainerType)) continue;

            // メソッド名から対象名を抽出（LoadRefs{対象名}Async）
            var targetName = method.Name.Substring(8, method.Name.Length - 13); // "LoadRefs"と"Async"を除去
            refSearchMethods[targetName] = (searchConditionType, messageContainerType, method);
        }

        foreach (var (targetName, (searchConditionType, messageContainerType, method)) in refSearchMethods) {
            yield return new TestCaseData(
                targetName,
                messageContainerType,
                CreateUnconditionalSearch(method, searchConditionType, messageContainerType, targetName))
                .SetName($"無条件Ref検索_{targetName}");
        }
    }

    /// <summary>
    /// 引数が検索条件と <see cref="IPresentationContext{TMessageRoot}"/> の 2 つである検索処理であれば、それぞれの型を返す。
    /// </summary>
    private static bool TryGetSearchParameterTypes(
        MethodInfo method,
        [NotNullWhen(true)] out Type? searchConditionType,
        [NotNullWhen(true)] out Type? messageContainerType) {

        searchConditionType = null;
        messageContainerType = null;

        var parameters = method.GetParameters();
        if (parameters.Length != 2) return false;

        var contextType = parameters[1].ParameterType;
        if (!contextType.IsGenericType || contextType.GetGenericTypeDefinition() != typeof(IPresentationContext<>)) return false;

        searchConditionType = parameters[0].ParameterType;
        messageContainerType = contextType.GetGenericArguments()[0];
        return true;
    }

    /// <summary>
    /// 検索条件を何も指定せずに検索処理を呼び出し、1ページ目の結果を返す関数を作成する。
    /// </summary>
    private static Func<AutoGeneratedApplicationService, IPresentationContext, Task<IEnumerable<object>>> CreateUnconditionalSearch(
        MethodInfo method,
        Type searchConditionType,
        Type messageContainerType,
        string name) {

        return async (app, presentationContext) => {
            // SearchConditionのインスタンスを作成
            var searchCondition = Activator.CreateInstance(searchConditionType);

            // Takeプロパティを設定
            var takeProperty = searchConditionType.GetProperty("Take");
            takeProperty?.SetValue(searchCondition, 10);

            // PresentationContextをキャスト
            var castMethod = typeof(IPresentationContext).GetMethod(nameof(IPresentationContext.As))!.MakeGenericMethod(messageContainerType);
            var castedContext = castMethod.Invoke(presentationContext, null);

            // 検索処理を呼び出し
            var task = (Task)method.Invoke(app, [searchCondition, castedContext])!;
            await task;

            // 結果を取得
            var resultProperty = task.GetType().GetProperty(nameof(Task<object>.Result))!;
            var result = resultProperty.GetValue(task) ?? throw new Exception($"結果が取得できません: {name}");

            // CurrentPageItemsを取得
            var currentPageItemsProperty = result
                .GetType()
                .GetProperty(nameof(LoadReturnType<object>.CurrentPageItems))
                ?? throw new Exception($"CurrentPageItemsプロパティが見つかりません: {name}");
            var currentPageItems = (IEnumerable?)currentPageItemsProperty.GetValue(result)
                ?? throw new Exception($"CurrentPageItemsの値が取得できません: {name}");

            return currentPageItems.Cast<object>();
        };
    }
}
