using Microsoft.EntityFrameworkCore;
using MyApp.Debugging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Reflection;
using System.Collections;

namespace MyApp.UnitTest;

partial class DB接続あり_更新なし {

    /// <summary>
    /// LINQ式をSQLに変換できないときはこの例外メッセージになる
    /// </summary>
    private const string CANNOT_TRANSRATE_TO_SQL = @"could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.";

    [Category("無条件検索でエラーが発生しないか（一覧検索）")]
    [TestCaseSource(typeof(MetadataBasedTestCases), nameof(MetadataBasedTestCases.無条件検索テストケース))]
    public async Task 無条件検索でエラーが発生しないか(
        string testCasePhysicalName,
        Type messageContainerType,
        Func<AutoGeneratedApplicationService, IPresentationContext, Task<IEnumerable<object>>> test) {

        // ダミーデータ投入
        var scope = TestUtilImpl.Instance.CreateScope($"{nameof(無条件検索でエラーが発生しないか)}_{testCasePhysicalName}", messageContainerType);

        var generator = new OverridedDummyDataGenerator();
        var dbDescriptor = new DummyDataDbOutput(scope.App.DbContext);
        await generator.GenerateAsync(dbDescriptor);

        // 無条件検索を実行
        try {
            var result = await test(scope.App, scope.PresentationContext);
            scope.App.Log.Debug("取得したデータ: {0}", scope.App.Configuration.ToJson(result));
            Assert.Pass("例外発生せず");

        } catch (InvalidOperationException ex) when (ex.Message.Contains(CANNOT_TRANSRATE_TO_SQL)) {
            if (testCasePhysicalName == "アクション結果"
             || testCasePhysicalName == "在庫調査報告") {
                Assert.Inconclusive(
                    "この集約は式が複雑すぎてSQLに変換できないが（EFCoreの制約）、" +
                    "自動生成されたコードでコンパイルエラーが出ないことを確認したいので、あえて残している。" +
                    "通常の運用では、参照経路が深くなりすぎないよう、RefTo用のQueryModelを別途定義し、それを参照させることで回避する。");
            } else {
                throw;
            }
        }
    }

    [Category("無条件検索でエラーが発生しないか（外部参照検索）")]
    [TestCaseSource(typeof(MetadataBasedTestCases), nameof(MetadataBasedTestCases.無条件外部参照検索テストケース))]
    public async Task 無条件外部参照検索でエラーが発生しないか(
        string testCasePhysicalName,
        Type messageContainerType,
        Func<AutoGeneratedApplicationService, IPresentationContext, Task<IEnumerable<object>>> test) {

        // ダミーデータ投入
        var scope = TestUtilImpl.Instance.CreateScope($"{nameof(無条件外部参照検索でエラーが発生しないか)}_{testCasePhysicalName}", messageContainerType);

        var generator = new OverridedDummyDataGenerator();
        var dbDescriptor = new DummyDataDbOutput(scope.App.DbContext);
        await generator.GenerateAsync(dbDescriptor);

        // 無条件外部参照検索を実行
        try {
            var result = await test(scope.App, scope.PresentationContext);
            scope.App.Log.Debug("取得したデータ: {0}", scope.App.Configuration.ToJson(result));
            Assert.Pass("例外発生せず");

        } catch (InvalidOperationException ex) when (ex.Message.Contains(CANNOT_TRANSRATE_TO_SQL)) {
            if (testCasePhysicalName == "アクション") {
                Assert.Inconclusive(
                    "この集約は式が複雑すぎてSQLに変換できないが（EFCoreの制約）、" +
                    "自動生成されたコードでコンパイルエラーが出ないことを確認したいので、あえて残している。" +
                    "通常の運用では、参照経路が深くなりすぎないよう、RefTo用のQueryModelを別途定義し、それを参照させることで回避する。");
            } else {
                throw;
            }
        }
    }
}

/// <summary>
/// 自動生成されたメタデータを使い、リフレクションを使って Query Model の　LoadAsync を呼び出すテストケースを生成するクラス
/// </summary>
public static class MetadataBasedTestCases {

    /// <summary>
    /// 無条件検索（通常の一覧検索）
    /// </summary>
    public static IEnumerable<TestCaseData> 無条件検索テストケース() {

        // 自動生成されたクラスがあるアセンブリ
        var assembly = typeof(AutoGeneratedApplicationService).Assembly;

        foreach (var (name, structureMetadata) in MetadataForPage.GetAll()) {

            // QueryModelまたはGenerateDefaultQueryModelがtrueのDataModelのみ対象
            if (structureMetadata.Model != MetadataForPage.E_ModelType.QueryModel
            && (structureMetadata.Model != MetadataForPage.E_ModelType.DataModel
            || !structureMetadata.GenerateDefaultQueryModel)) {
                continue;
            }

            // 型を動的に取得
            var searchConditionType = assembly.GetType($"MyApp.Core.{name}SearchCondition")
                ?? throw new Exception($"SearchConditionTypeが見つかりません: {name}");
            var messageContainerType = assembly.GetType($"MyApp.Core.{name}SearchConditionMessages")
                ?? throw new Exception($"MessageContainerTypeが見つかりません: {name}");

            // 呼び出し処理を定義
            Func<AutoGeneratedApplicationService, IPresentationContext, Task<IEnumerable<object>>> CallLoadAsync = async (app, presentationContext) => {
                // SearchConditionのインスタンスを作成
                var searchCondition = Activator.CreateInstance(searchConditionType);

                // Takeプロパティを設定
                var takeProperty = searchConditionType.GetProperty("Take");
                takeProperty?.SetValue(searchCondition, 10);

                // LoadAsyncメソッドを動的に呼び出し
                var loadAsyncMethod = app.GetType().GetMethod(
                    nameof(AutoGeneratedApplicationService.LoadAsync),
                    [
                        searchConditionType,
                        typeof(IPresentationContext<>).MakeGenericType(messageContainerType)
                    ])
                    ?? throw new Exception($"LoadAsyncメソッドが見つかりません: {name}");

                // PresentationContextをキャスト
                var castMethod = typeof(IPresentationContext).GetMethod("Cast")!.MakeGenericMethod(messageContainerType);
                var castedContext = castMethod.Invoke(presentationContext, null);

                // LoadAsyncを呼び出し
                var task = (Task)loadAsyncMethod.Invoke(app, [searchCondition, castedContext])!;
                await task;

                // 結果を取得
                var resultProperty = task.GetType().GetProperty(nameof(Task<object>.Result))!;
                var result = resultProperty?.GetValue(task) ?? throw new Exception($"結果が取得できません: {name}");

                // CurrentPageItemsを取得
                var currentPageItemsProperty = result
                    .GetType()
                    .GetProperty(nameof(LoadReturnType<object>.CurrentPageItems))
                    ?? throw new Exception($"CurrentPageItemsプロパティが見つかりません: {name}");
                var currentPageItems = (IEnumerable?)currentPageItemsProperty.GetValue(result)
                    ?? throw new Exception($"CurrentPageItemsの値が取得できません: {name}");

                return currentPageItems.Cast<object>();
            };

            yield return new TestCaseData(
                name,
                messageContainerType,
                CallLoadAsync)
                .SetName($"無条件検索_{name}");
        }
    }

    /// <summary>
    /// 無条件検索（参照検索）
    /// </summary>
    public static IEnumerable<TestCaseData> 無条件外部参照検索テストケース() {
        var metadata = MetadataForPage.GetAll();

        // 外部参照検索のメソッド名パターンを収集
        var refSearchMethods = new Dictionary<string, (Type searchConditionType, Type messageContainerType, MethodInfo method)>();

        // AutoGeneratedApplicationServiceから LoadRefs で始まるメソッドを取得
        var appServiceType = typeof(AutoGeneratedApplicationService);
        var refMethods = appServiceType.GetMethods(BindingFlags.Public | BindingFlags.Instance)
            .Where(m => m.Name.StartsWith("LoadRefs") && m.Name.EndsWith("Async"))
            .ToList();

        foreach (var method in refMethods) {
            var parameters = method.GetParameters();
            if (parameters.Length == 2) {
                var searchConditionType = parameters[0].ParameterType;
                var contextType = parameters[1].ParameterType;

                // メソッド名から対象名を抽出（LoadRefs{対象名}Async）
                var targetName = method.Name.Substring(8, method.Name.Length - 13); // "LoadRefs"と"Async"を除去

                if (contextType.IsGenericType && contextType.GetGenericTypeDefinition() == typeof(IPresentationContext<>)) {
                    var messageContainerType = contextType.GetGenericArguments()[0];
                    refSearchMethods[targetName] = (searchConditionType, messageContainerType, method);
                }
            }
        }

        foreach (var (targetName, (searchConditionType, messageContainerType, method)) in refSearchMethods) {
            yield return new TestCaseData(
                targetName,
                messageContainerType,
                new Func<AutoGeneratedApplicationService, IPresentationContext, Task<IEnumerable<object>>>(async (app, presentationContext) => {
                    // SearchConditionのインスタンスを作成
                    var searchCondition = Activator.CreateInstance(searchConditionType);

                    // Takeプロパティを設定
                    var takeProperty = searchConditionType.GetProperty("Take");
                    if (takeProperty != null) {
                        takeProperty.SetValue(searchCondition, 10);
                    }

                    // PresentationContextをキャスト
                    var castMethod = typeof(IPresentationContext).GetMethod("Cast")!.MakeGenericMethod(messageContainerType);
                    var castedContext = castMethod.Invoke(presentationContext, null);

                    // LoadRefsメソッドを呼び出し
                    var task = (Task)method.Invoke(app, [searchCondition, castedContext])!;
                    await task;

                    // 結果を取得
                    var resultProperty = task.GetType().GetProperty(nameof(Task<object>.Result))!;
                    var result = resultProperty.GetValue(task) ?? throw new Exception($"結果が取得できません: {targetName}");

                    // CurrentPageItemsを取得
                    var currentPageItemsProperty = result
                        .GetType()
                        .GetProperty(nameof(LoadReturnType<object>.CurrentPageItems))
                        ?? throw new Exception($"CurrentPageItemsプロパティが見つかりません: {targetName}");
                    var currentPageItems = (IEnumerable?)currentPageItemsProperty.GetValue(result)
                        ?? throw new Exception($"CurrentPageItemsの値が取得できません: {targetName}");

                    return currentPageItems.Cast<object>();
                }))
                .SetName($"無条件Ref検索_{targetName}");
        }
    }
}
