using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Net;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Threading.Tasks;
using MyApp.WebApi.Base;

// nijo.xml で指定されているルート名前空間と一致させる必要がある
namespace MyApp;

/// <summary>
/// 自動生成されるコントローラーの基底クラス。
/// このクラス自体は手動実装される必要がある。
/// 実装内容自体は自由に変更してよいが、以下の機能を提供する必要がある。
///
/// <list type="bullet">
/// <item>HTTPリクエストおよびレスポンスとC#アプリケーションサービスの引数および戻り値の変換</item>
/// <item>アクションの実行</item>
/// <item>エラーハンドリングやHTTPログ出力といった横断的関心事の処理</item>
/// <item>アプリケーション毎に特有のオプションがある場合はその処理</item>
/// </list>
/// </summary>
public abstract class AutoGeneratedControllerBase : ControllerBase {

    /// <summary>
    /// 自動生成されたアクションが利用するハンドラーメソッド。（引数なし、戻り値なし）
    /// </summary>
    protected async Task<IActionResult> Handle<TMessageRoot>(Func<IPresentationContext<TMessageRoot>, Task> appSrvMethod)
        where TMessageRoot : IMessageSetter {

        return await HandleCore<object /* 引数なし */, PresentationContextInWebApi<TMessageRoot>, TMessageRoot>(async (parameter, msgs, ignoreConfirm) => {
            var context = new PresentationContextInWebApi<TMessageRoot> { Messages = msgs, IgnoreConfirm = ignoreConfirm, Confirms = [] };
            await appSrvMethod(context);
            return context;
        });
    }

    /// <summary>
    /// 自動生成されたアクションが利用するハンドラーメソッド。（引数なし、戻り値あり）
    /// </summary>
    protected async Task<IActionResult> Handle<TReturnValue, TMessageRoot>(Func<IPresentationContextWithReturnValue<TReturnValue, TMessageRoot>, Task> appSrvMethod)
        where TMessageRoot : IMessageSetter
        where TReturnValue : new() {

        return await HandleCore<object /* 引数なし */, PresentationContextInWebApi<TReturnValue, TMessageRoot>, TMessageRoot>(async (parameter, msgs, ignoreConfirm) => {
            var context = new PresentationContextInWebApi<TReturnValue, TMessageRoot> { Messages = msgs, IgnoreConfirm = ignoreConfirm, Confirms = [] };
            await appSrvMethod(context);
            return context;
        });
    }

    /// <summary>
    /// 自動生成されたアクションが利用するハンドラーメソッド。（引数あり、戻り値なし）
    /// </summary>
    protected async Task<IActionResult> Handle<TParameter, TMessageRoot>(Func<TParameter, IPresentationContext<TMessageRoot>, Task> appSrvMethod)
        where TMessageRoot : IMessageSetter {

        return await HandleCore<TParameter, PresentationContextInWebApi<TMessageRoot>, TMessageRoot>(async (parameter, msgs, ignoreConfirm) => {
            var context = new PresentationContextInWebApi<TMessageRoot> { Messages = msgs, IgnoreConfirm = ignoreConfirm, Confirms = [] };
            await appSrvMethod(parameter, context);
            return context;
        });
    }

    /// <summary>
    /// 自動生成されたアクションが利用するハンドラーメソッド。（引数あり、戻り値あり）
    /// </summary>
    protected async Task<IActionResult> Handle<TParameter, TReturnValue, TMessageRoot>(Func<TParameter, IPresentationContextWithReturnValue<TReturnValue, TMessageRoot>, Task> appSrvMethod)
        where TMessageRoot : IMessageSetter
        where TReturnValue : new() {

        return await HandleCore<TParameter, PresentationContextInWebApi<TReturnValue, TMessageRoot>, TMessageRoot>(async (parameter, msgs, ignoreConfirm) => {
            var context = new PresentationContextInWebApi<TReturnValue, TMessageRoot> { Messages = msgs, IgnoreConfirm = ignoreConfirm, Confirms = [] };
            await appSrvMethod(parameter, context);
            return context;
        });
    }

    /// <summary>
    /// 上記4つのハンドラーメソッドの共通処理。
    /// </summary>
    private async Task<IActionResult> HandleCore<TParameter, TPresentationContext, TMessageRoot>(
        Func<TParameter,
            TMessageRoot,
            bool,
            Task<PresentationContextInWebApi<TMessageRoot>>> callAppSrvMethodAsync)
        where TMessageRoot : IMessageSetter
        where TPresentationContext : IPresentationContext {

        var services = HttpContext.RequestServices;
        var logger = services.GetService<ILogger<AutoGeneratedControllerBase>>();
        var stopwatch = Stopwatch.StartNew();

        try {
            // ---------------------------------------------------------
            // HTTPリクエストボディをC#側アプリケーションサービスの引数のクラスのインスタンスに変換する
            // ---------------------------------------------------------

            // クライアント側から送られてきたパラメータは
            // Content-Type: multipart/form-data
            // のリクエストボディのこの名前のセクションにJSONで入っているのでそこから取得する
            const string PARAM_DATA = "complex-post-request-body";

            var appConfig = new OverridedApplicationConfigure();
            var jsonOptions = appConfig.EditDefaultJsonSerializerOptions(new JsonSerializerOptions());

            if (!Request.HasFormContentType || !Request.Form.TryGetValue(PARAM_DATA, out var dataSection)) {
                logger?.LogWarning("リクエストに '{ParamData}' セクションが含まれていません。", PARAM_DATA);
                return BadRequest($"リクエストのContent-Typeは multipart/form-data で、セクション '{PARAM_DATA}' を含んでいる必要があります。");
            }

            TParameter requestData;
            if (typeof(TParameter) == typeof(object)) {
                // 便宜上、TParameterがobjectの場合は引数なしとみなす
                requestData = default!;
            } else {
                // リクエストボディのログ出力
                var strDataSection = dataSection.ToString();
                logger?.LogDebug("HTTP REQUEST BODY DATA: {DataSection}", strDataSection);

                // JSONをデシリアライズしてC#側の引数のクラスのインスタンスを作成する
                try {
                    requestData = JsonSerializer.Deserialize<TParameter>(strDataSection, jsonOptions)
                        ?? throw new InvalidOperationException("リクエストの型が不正です。");

                } catch (JsonException jsonEx) {
                    logger?.LogWarning(jsonEx, "{ParameterType} 型へのデシリアライズに失敗しました。", typeof(TParameter).FullName);
                    return BadRequest($"リクエストの型が不正です。{typeof(TParameter).FullName} 型として認識できません。");
                }
            }
            // ---------------------------------------------------------
            // Presentation Context のインスタンスを作成する
            // ---------------------------------------------------------

            // HTTPリクエストが送られる際にこの名前のクエリパラメータが付される
            const string PARAM_IGNORE_CONFIRM = "ignore-confirm";

            bool blnIgnoreConfirm;
            if (!Request.Query.TryGetValue(PARAM_IGNORE_CONFIRM, out var strIgnoreConfirm)) {
                blnIgnoreConfirm = false;
            } else if (!bool.TryParse(strIgnoreConfirm, out var b)) {
                blnIgnoreConfirm = false;
            } else {
                blnIgnoreConfirm = b;
            }

            // ---------------------------------------------------------
            // アプリケーションサービスのメソッドを実行する
            // ---------------------------------------------------------
            var context = await callAppSrvMethodAsync(
                requestData,
                MessageSetter.GetImpl<TMessageRoot>([], new MessageContainer()),
                blnIgnoreConfirm);

            // ---------------------------------------------------------
            // Presentation Context に処理結果が格納されているので、HTTPレスポンスに変換する
            // ---------------------------------------------------------

            // レスポンスボディ。
            // データ構造は NijoAppScaffold として何か決まりがあるわけではなく、
            // レスポンスをハンドリングする JavaScript 側処理と整合性がとれていればよい。
            var responseBody = new JsonObject();
            if (context.ReturnValue != null) {
                responseBody["returnValue"] = JsonSerializer.SerializeToNode(context.ReturnValue, jsonOptions);
            }
            var confirms = new JsonArray();
            foreach (var text in context.Confirms) {
                confirms.Add(text);
            }

            responseBody["confirms"] = confirms;

            var messageContainer = context.Messages.GetState();
            responseBody["detail"] = messageContainer == null ? new JsonObject() : ToJsonObject(messageContainer);

            // ステータスコード。
            // NijoAppScaffold として何か決まりがあるわけではなく、
            // JavaScript側でレスポンスを受け取ったあとの処理と整合性がとれていればよい。
            var objectResult = new ObjectResult(JsonSerializer.Serialize(responseBody, jsonOptions));
            if (context.Messages.HasError() || !blnIgnoreConfirm) {
                objectResult.StatusCode = (int)HttpStatusCode.Accepted;
            } else {
                objectResult.StatusCode = (int)HttpStatusCode.OK;
            }

            stopwatch.Stop();

            var messageState = context.Messages.GetState()?.DescendantsAndSelf().ToArray() ?? [];
            logger?.LogDebug("{Method} 処理完了: {Elapsed}ms, Status: {StatusCode}, メッセージ件数: info {InfoCount} warn {WarnCount} err {ErrorCount} confirm {ConfirmCount}",
                Request.Method,
                stopwatch.ElapsedMilliseconds,
                objectResult.StatusCode,
                messageState.Sum(x => x.Infos.Count),
                messageState.Sum(x => x.Warns.Count),
                messageState.Sum(x => x.Errors.Count),
                context.Confirms.Count);

            return objectResult;

        } catch (Exception ex) {
            stopwatch.Stop();
            logger?.LogError(ex, "Unhandled exception in request processing: {Method} {Path}", Request.Method, Request.Path);

            // 例外発生時のレスポンス
            return new ObjectResult(new { message = $"システムエラーが発生しました（{ex.Message}）" }) {
                StatusCode = (int)HttpStatusCode.InternalServerError
            };
        }
    }

    /// <summary>
    /// このインスタンスをJsonNode型に変換します。
    /// オブジェクトの構造はクライアント側でのメッセージ表示処理に合わせた形になっています。
    ///
    /// <list type="bullet">
    /// <item>このメソッドは、このオブジェクトおよび子孫オブジェクトが持っているメッセージを再帰的に集め、以下のようなJSONオブジェクトに変換します。</item>
    /// <item>メッセージコンテナは、エラー、警告、インフォメーションの3種類のメッセージを、それぞれ配列として持ちます。</item>
    /// <item>エラーだけ持っているなど、一部の種類のメッセージのみ持っている場合、他の種類の配列は配列自体が存在しなくなります。</item>
    /// <item>子要素は children という名前のオブジェクトにまとめて格納されます。</item>
    /// <item>
    /// 3種類のメッセージのいずれも持っていない項目のプロパティは存在しません。
    /// 例えば以下のオブジェクトで「項目A」「項目B」以外に「項目X」が存在するが、Xにはメッセージが発生していない場合、Xのプロパティは存在しません。
    /// </item>
    /// <item>ネストされたオブジェクトのメッセージも生成されます。（下記「子オブジェクトのメッセージ」）</item>
    /// <item>
    /// 配列は、配列インデックスをキーとしたオブジェクトになります。（下記「子配列のメッセージ」）
    /// 配列インデックスか否かは、 children 直下のオブジェクトのキーが半角整数のみから成るか否かで判定できます。
    /// </item>
    /// </list>
    /// <code>
    /// {
    ///   "error": ["xxxがエラーです"],
    ///   "children": {
    ///     "項目A": { "error": ["xxxがエラーです"], "warn": ["xxxという警告があります"], "info": ["xxxという情報があります"] },
    ///     "項目B": { "error": ["xxxがエラーです", "yyyがエラーです"], "warn": ["xxxという警告があります"], "info": ["xxxという情報があります"] },
    ///     "子オブジェクトのメッセージ": {
    ///       "children": {
    ///         "項目C": { "error": ["xxxがエラーです"] },
    ///         "項目D": { "error": ["xxxがエラーです"] },
    ///       },
    ///     },
    ///     "子配列のメッセージ": {
    ///       "error": ["xxxがエラーです"],
    ///       "children": {
    ///         "1": {
    ///           "children": {
    ///             "項目E": { "error": ["xxxがエラーです"] },
    ///           },
    ///         },
    ///         "5": {
    ///           "error": ["xxxがエラーです"],
    ///           "children": {
    ///             "項目E": { "error": ["xxxがエラーです"] },
    ///           },
    ///         },
    ///       },
    ///     }
    ///   }
    /// }
    /// </code>
    /// </summary>
    internal static JsonObject ToJsonObject(IReadOnlyMessageContainer messageContainer) {
        var result = new JsonObject();

        if (messageContainer.Errors.Any()) {
            var strArray = new JsonArray();
            foreach (var str in messageContainer.Errors) strArray.Add(str);
            result["error"] = strArray;
        }
        if (messageContainer.Warns.Any()) {
            var strArray = new JsonArray();
            foreach (var str in messageContainer.Warns) strArray.Add(str);
            result["warn"] = strArray;
        }
        if (messageContainer.Infos.Any()) {
            var strArray = new JsonArray();
            foreach (var str in messageContainer.Infos) strArray.Add(str);
            result["info"] = strArray;
        }

        var children = new JsonObject();
        foreach (var child in messageContainer.Children) {
            var childJson = ToJsonObject(child.Value);
            if (childJson != null) children[child.Key] = childJson;
        }
        if (children.Count > 0) result["children"] = children;

        return result;
    }
}
