import React from 'react'
import * as ReactRouter from 'react-router-dom'
import ReactDOM from 'react-dom/client'
import { getRouterForAutoGeneratedApplication } from './pages-reflection/MainLayout.Sidebar'

import './main.css'
import 'allotment/dist/style.css'
import QueryCommandDebugger from './reflection-debugger'

function App() {
  return (
    <QueryCommandDebugger className="h-full w-full p-4 border" />
  )

  const router = React.useMemo(() => {
    return ReactRouter.createBrowserRouter([getRouterForAutoGeneratedApplication()])
  }, [])

  return (
    <ReactRouter.RouterProvider router={router} />
  )
}

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
