using Nijo.CodeGenerating;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace Nijo.Parts.CSharp {
    public class ApplicationService : IMultiAggregateSourceFile {
        public const string ABSTRACT_CLASS = "AutoGeneratedApplicationService";

        public const string CURRENT_TIME = "CurrentTime";
        public const string CURRENT_USER = "CurrentUser";
        public const string SERIALIZE_FOR_LOG = "SerializeForLog";

        private readonly Lock _lock = new();
        private readonly List<string> _sourceCode = [];

        public ApplicationService Add(string sourceCode) {
            lock (_lock) {
                _sourceCode.Add(sourceCode);
                return this;
            }
        }

        public void RegisterDependencies(IMultiAggregateSourceFileManager ctx) {
            // 特になし
        }

        public void Render(CodeRenderingContext ctx) {
            if (ctx.IsLegacyCompatibilityMode() && _sourceCode.Count == 0) {
                return;
            }

            ctx.CoreLibrary(dir => {
                dir.Generate(RenderDeclaring(ctx));
            });
        }

        private SourceFile RenderDeclaring(CodeRenderingContext ctx) {
            if (ctx.IsLegacyCompatibilityMode()) {
                var rootOrder = ctx.Schema.GetRootAggregates()
                    .Select((root, index) => new { root.PhysicalName, Index = index })
                    .ToDictionary(x => x.PhysicalName, x => x.Index, StringComparer.Ordinal);

                int GetCategoryPriority(string source) {
                    if (source.Contains("GetMultiViewUrlFromDisplayData", StringComparison.Ordinal)) return 0;
                    if (source.Contains("GetSingleViewUrlFromDisplayData(", StringComparison.Ordinal)) return 1;
                    if (source.Contains("GetSingleViewUrlOf", StringComparison.Ordinal)) return 2;
                    if (source.Contains("GetAuthorizedLevel(", StringComparison.Ordinal)) return 3;
                    if (source.Contains("CreateSearchResultExcelBook(", StringComparison.Ordinal)) return 4;
                    return 100;
                }

                int GetBlockPriority(string source) {
                    var category = GetCategoryPriority(source);
                    return category switch {
                        <= 2 => 0,
                        3 => 1,
                        4 => 2,
                        _ => 3,
                    };
                }

                int GetRootPriority(string source) {
                    foreach (var pair in rootOrder) {
                        if (source.Contains(pair.Key, StringComparison.Ordinal)) {
                            return pair.Value;
                        }
                    }
                    return int.MaxValue;
                }

                var orderedLegacySources = _sourceCode
                    .Select((source, index) => new { Source = source.Trim(), Index = index })
                    .Where(x => !string.IsNullOrWhiteSpace(x.Source))
                    .OrderBy(x => GetBlockPriority(x.Source))
                    .ThenBy(x => GetRootPriority(x.Source))
                    .ThenBy(x => GetCategoryPriority(x.Source))
                    .ThenBy(x => x.Index)
                    .Select(x => x.Source)
                    .ToArray();

                return new SourceFile {
                    FileName = "AutoGeneratedApplicationService.cs",
                    Contents = $$"""
                        namespace {{ctx.Config.RootNamespace}} {
                            using Microsoft.Extensions.DependencyInjection;
                            using {{ctx.Config.RootNamespace}};
                            using NLog;

                            public partial class {{ABSTRACT_CLASS}} {
                                public {{ABSTRACT_CLASS}}(string procId, IServiceProvider serviceProvider) {
                                    ProcId = procId;
                                    ServiceProvider = serviceProvider;
                                }

                                /// <summary>
                                /// 処理ID。
                                /// WebであればHTTPリクエスト1回分、コマンドラインアプリケーションであればexe処理1回分ごとに振られる。
                                /// </summary>
                                public string ProcId { get; }

                                public IServiceProvider ServiceProvider { get; }

                                private {{ctx.Config.DbContextName}}? _dbContext;
                                public virtual {{ctx.Config.DbContextName}} DbContext => _dbContext ??= ServiceProvider.GetRequiredService<{{ctx.Config.DbContextName}}>();

                                /// <summary>
                                /// ログ出力はこのプロパティを通して行われる想定
                                /// </summary>
                                public Logger Log => _logger ??= ServiceProvider.GetRequiredService<Logger>();
                                private Logger? _logger;

                                /// <summary>
                                /// <para>
                                /// 現在時刻。データ更新時の更新時刻の記録などに使用。
                                /// <see cref="DateTime.Now"/> を使ってしまうと現在時刻に依存する処理のテストが困難になるので、基本的にはこのプロパティを使うこと。
                                /// </para>
                                /// <para>
                                /// 同一のリクエストの中では、たとえ実時刻に多少のずれがあったとしてもすべて同じ時刻（リクエスト開始時点の時刻）になる。
                                /// 理由は、例えば深夜0時前後の処理で処置の途中で日付が変わることでロジックに影響が出る、などといった事象を防ぐため。
                                /// </para>
                                /// <para>
                                /// ちなみにログ出力の時刻にはこのプロパティが用いられず、正確な現在時刻が出力される。
                                /// </para>
                                /// </summary>
                                public virtual DateTime {{CURRENT_TIME}} => _currentTime ??= DateTime.Now;
                                private DateTime? _currentTime;

                                /// <summary>
                                /// 現在操作中のユーザーの名前。データ更新時の更新者の記録などに使用。
                                /// </summary>
                                public virtual string {{CURRENT_USER}} => "UNDEFINED";

                                /// <summary>
                                /// 現在のセッションの識別子。ログ出力に使用。
                                /// </summary>
                                public virtual string? LogSessionKey => null;

                        {{orderedLegacySources.SelectTextTemplate(line => $$"""

                                {{WithIndent(line)}}
                        """)}}
                            }
                        }
                        """,
                };
            }

            return new SourceFile {
                FileName = ctx.IsLegacyCompatibilityMode() ? "AutoGeneratedApplicationService.cs" : "ApplicationService.cs",
                Contents = $$"""
                    using Microsoft.Extensions.DependencyInjection;
                    using Microsoft.Extensions.Logging;

                    namespace {{ctx.Config.RootNamespace}};

                    /// <summary>
                    /// アプリケーションのための各種機能を提供する。
                    /// </summary>
                    public abstract partial class {{ABSTRACT_CLASS}} {
                        protected {{ABSTRACT_CLASS}}(IServiceProvider serviceProvider) {
                            ServiceProvider = serviceProvider;
                        }

                        public IServiceProvider ServiceProvider { get; }

                        private {{ctx.Config.DbContextName}}? _dbContext;
                        public {{ctx.Config.DbContextName}} DbContext => _dbContext ??= ServiceProvider.GetRequiredService<{{ctx.Config.DbContextName}}>();

                        /// <summary>
                        /// ログ出力はこのプロパティを通して行われる想定
                        /// </summary>
                        public ILogger Log => _logger ??= ServiceProvider.GetRequiredService<ILogger<{{ABSTRACT_CLASS}}>>();
                        private ILogger? _logger;

                        /// <summary>
                        /// <para>
                        /// 現在時刻。データ更新時の更新時刻の記録などに使用。
                        /// <see cref="DateTime.Now"/> を使ってしまうと現在時刻に依存する処理のテストが困難になるので、基本的にはこのプロパティを使うこと。
                        /// </para>
                        /// <para>
                        /// 同一のリクエストの中では、たとえ実時刻に多少のずれがあったとしてもすべて同じ時刻（リクエスト開始時点の時刻）になる。
                        /// 理由は、例えば深夜0時前後の処理で処置の途中で日付が変わることでロジックに影響が出る、などといった事象を防ぐため。
                        /// </para>
                        /// <para>
                        /// ちなみにログ出力の時刻にはこのプロパティが用いられず、正確な現在時刻が出力される。
                        /// </para>
                        /// </summary>
                        public virtual DateTime {{CURRENT_TIME}} => _currentTime ??= DateTime.Now;
                        private DateTime? _currentTime;

                        /// <summary>
                        /// 現在操作中のユーザーの名前。データ更新時の更新者の記録などに使用。
                        /// </summary>
                        public virtual string {{CURRENT_USER}} => "UNDEFINED";

                        /// <summary>
                        /// ログ出力用にオブジェクトをシリアライズする。
                        /// </summary>
                        public virtual string {{SERIALIZE_FOR_LOG}}<T>(T obj) {
                            return System.Text.Json.JsonSerializer.Serialize(obj, new System.Text.Json.JsonSerializerOptions {
                                // Unicode文字のエスケープを抑制
                                Encoder = System.Text.Encodings.Web.JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
                                WriteIndented = false,
                            });
                        }

                        /// <summary>
                        /// 現在のセッションの識別子。ログ出力に使用。
                        /// </summary>
                        public virtual string? LogSessionKey => null;
                    {{_sourceCode.OrderBy(source => source).SelectTextTemplate(source => $$"""

                        {{WithIndent(source)}}
                    """)}}
                    }
                    """,
            };
        }
    }
}
