using Nijo.CodeGenerating;
using Nijo.Util.DotnetEx;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Threading;

namespace Nijo.Parts.CSharp {
    public class DbContextClass : IMultiAggregateSourceFile {

        private readonly List<IEFCoreEntity> _efCoreEntities = [];
        private readonly List<string> _additionalMethods = [];
        private readonly Lock _lock = new();

        internal DbContextClass AddEntities(IEnumerable<IEFCoreEntity> eFCoreEntities) {
            lock (_lock) {
                _efCoreEntities.AddRange(eFCoreEntities);
                return this;
            }
        }
        public DbContextClass AddAdditionalMethod(string sourceCode) {
            lock (_lock) {
                _additionalMethods.Add(sourceCode);
                return this;
            }
        }

        void IMultiAggregateSourceFile.RegisterDependencies(IMultiAggregateSourceFileManager ctx) {
            // 汎用参照テーブル用のビュー情報提供メソッド。
            // Nijoの空テンプレートにこのメソッドの使用例を含めるため、
            // スキーマ定義に汎用参照テーブルが存在するか否かにかかわらずメソッドを生成する。
            ctx.Use<Models.DataModelModules.GenericLookupViewsInfoProvider>();
        }

        void IMultiAggregateSourceFile.Render(CodeRenderingContext ctx) {
            if (ctx.IsLegacyCompatibilityMode()) return;

            ctx.CoreLibrary(dir => {
                dir.Directory(ctx.IsLegacyCompatibilityMode() ? "EntityFramework" : "Util", efcoreDir => {
                    efcoreDir.Generate(Render(ctx));
                });
            });
        }

        private SourceFile Render(CodeRenderingContext ctx) {
            var efCoreEntitiesOrderByDataFlow = _efCoreEntities
                .OrderBy(e => e.Aggregate.GetRoot().GetIndexOfDataFlow())
                .ThenBy(e => e.Aggregate.GetOrderInTree())
                .ToArray();

            return new SourceFile {
                FileName = ctx.IsLegacyCompatibilityMode() ? "EFCoreDbContext.cs" : $"{ctx.Config.DbContextName.ToFileNameSafe()}.cs",
                Contents = $$"""
                    using Microsoft.EntityFrameworkCore;

                    namespace {{ctx.Config.RootNamespace}};

                    public abstract partial class {{ctx.Config.DbContextName}} : DbContext {

                    #pragma warning disable CS8618 // DbSetはEFCore側で自動的に設定されるため問題なし
                        /// <summary>
                        /// DBコンテキスト。Entity Framework Core の中核的な仕組み。
                        /// </summary>
                        /// <param name="options">EFCoreのオプション</param>
                        public {{ctx.Config.DbContextName}}(DbContextOptions options) : base(options) {
                        }
                    #pragma warning restore CS8618 // DbSetはEFCore側で自動的に設定されるため問題なし

                    {{efCoreEntitiesOrderByDataFlow.SelectTextTemplate(entity => $$"""
                        public virtual DbSet<{{entity.CsClassName}}> {{entity.DbSetName}} { get; set; }
                    """)}}

                        /// <inheritdoc />
                        protected override void OnModelCreating(ModelBuilder modelBuilder) {
                    {{efCoreEntitiesOrderByDataFlow.SelectTextTemplate(entity => $$"""
                            {{entity.OnModelCreatingAutoGenerated}}(modelBuilder);
                    """)}}
                        }
                    {{_additionalMethods.SelectTextTemplate(method => $$"""

                        {{WithIndent(method)}}
                    """)}}
                    }
                    """,
            };
        }
    }
}
