using Nijo.CodeGenerating;
using Nijo.ImmutableSchema;
using Nijo.Models;
using Nijo.SchemaParsing;
using Nijo.Util.DotnetEx;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Nijo.Parts.CSharp {
    /// <summary>
    /// Entity Framework Core のエンティティ
    /// </summary>
    internal class EFCoreEntity : IInstancePropertyOwnerMetadata, IEFCoreEntity {

        internal EFCoreEntity(AggregateBase aggregate, bool isDeletedTable = false) {
            Aggregate = aggregate;
            IsDeletedTable = isDeletedTable;
        }
        public AggregateBase Aggregate { get; }
        internal bool IsDeletedTable { get; }

        public string CsClassName => IsDeletedTable
            ? $"{Aggregate.PhysicalName}DeletedDbEntity"
            : $"{Aggregate.PhysicalName}DbEntity";
        public string DbSetName => IsDeletedTable
            ? $"{Aggregate.PhysicalName}DeletedDbSet"
            : $"{Aggregate.PhysicalName}DbSet";
        public string TableDbName => IsDeletedTable
            ? $"{Aggregate.DbName}_DELETED"
            : Aggregate.DbName;

        /// <summary>
        /// 作成日時、更新日時、作成者、更新者のカラムを持つかどうか
        /// </summary>
        public bool HasTimestampColumns => true;
        /// <summary>
        /// 楽観排他用のバージョンを持つかどうか
        /// </summary>
        public bool HasVersionColumn {
            get {
                // 更新は常にルート集約の単位
                if (Aggregate is not RootAggregate rootAggregate) return false;

                // QueryModelのビューの場合は読み取り専用のためバージョンカラムは不要
                if (rootAggregate.Model is QueryModel && rootAggregate.IsView) return false;

                return true;
            }
        }

        /// <summary>楽観排他制御用のバージョニング用カラムの名前</summary>
        internal const string VERSION = "Version";
        /// <summary>データが新規作成された日時</summary>
        internal const string CREATED_AT = "CreatedAt";
        /// <summary>データが更新された日時</summary>
        internal const string UPDATED_AT = "UpdatedAt";
        /// <summary>データを新規作成したユーザー</summary>
        internal const string CREATE_USER = "CreateUser";
        /// <summary>データを更新したユーザー</summary>
        internal const string UPDATE_USER = "UpdateUser";
        /// <summary>論理削除時に採番されるUUID</summary>
        internal const string DELETED_UUID = "DeletedUuid";
        /// <summary>論理削除日時</summary>
        internal const string DELETED_AT = "DeletedAt";
        /// <summary>論理削除を行ったユーザー</summary>
        internal const string DELETED_USER = "DeletedUser";

        /// <summary>主キーが一致するかどうかを調べるメソッドの名前</summary>
        internal const string KEYEQUALS = "KeyEquals";

        public string OnModelCreatingAutoGenerated => IsDeletedTable
            ? $"OnModelCreating{Aggregate.PhysicalName}Deleted"
            : $"OnModelCreating{Aggregate.PhysicalName}";

        /// <summary>
        /// <list type="bullet">
        /// <item>自身の<see cref="ValueMember"/>: 列挙する</item>
        /// <item>親のキー: 列挙する</item>
        /// <item>参照先のキー: 列挙する</item>
        /// <item>Child, Children: 列挙しない</item>
        /// <item>ナビゲーションプロパティ: 列挙しない</item>
        /// </list>
        /// </summary>
        public IEnumerable<EFCoreEntityColumn> GetColumns() {
            var columns = new List<EFCoreEntityColumn>();

            // 論理削除用の追加カラム
            if (IsDeletedTable && Aggregate is RootAggregate) {
                columns.Add(new DeletedUuidColumn());
            }

            // 親のキー
            var parent = Aggregate.GetParent();
            if (parent != null) {
                foreach (var parentKey in EnumerateKeysRecursively(true, parent, null, ["Parent"])) {
                    columns.Add(parentKey);
                }
            }

            // スキーマで定義されている列（ValueMember, RefToMember）
            foreach (var member in Aggregate.GetMembers()) {
                if (member is ValueMember vm) {
                    // 自身のキー
                    var isNotKey = IsDeletedTable && Aggregate is RootAggregate; // 論理削除テーブルのルートは専用のUUIDがキー
                    var forceNullable = IsDeletedTable
                        && (!vm.IsKey || Aggregate is RootAggregate);
                    columns.Add(new OwnColumnMember(vm, isKey: isNotKey ? false : null, isNotNull: forceNullable ? false : null));

                } else if (member is RefToMember refTo) {
                    foreach (var refToKey in EnumerateKeysRecursively(false, refTo.RefTo, refTo, [refTo.PhysicalName])) {
                        columns.Add(refToKey);
                    }
                }
            }

            return columns;

            // 親や参照先の集約のキーを辿る。
            // 子孫テーブルは祖先のキーを継承する。
            // 参照元は参照先のキーを継承する（FOREIGN KEY）。
            IEnumerable<EFCoreEntityColumn> EnumerateKeysRecursively(bool isParent, AggregateBase parentOrRef, RefToMember? refEntry, IEnumerable<string> path) {
                // 親のさらに親
                var ancestor = parentOrRef.GetParent();
                if (ancestor != null) {
                    foreach (var ancestorKey in EnumerateKeysRecursively(true, ancestor, refEntry, [.. path, "Parent"])) {
                        yield return ancestorKey;
                    }
                }

                // 論理削除テーブルのルート集約の場合、DeletedUuidもキーとして追加
                if (IsDeletedTable && refEntry == null && parentOrRef is RootAggregate) {
                    yield return new DeletedUuidColumn();
                }

                // 親や参照先の集約のキー
                foreach (var member in parentOrRef.GetMembers()) {
                    if (member is ValueMember vm) {

                        if (vm.IsKey && refEntry != null) {
                            // 参照先が子孫テーブルの場合の、その参照先から見た親のキー
                            yield return new RefKeyMember(
                                refEntry,
                                vm,
                                path,
                                isParent,
                                forceKey: IsDeletedTable ? false : null,
                                forceNotNull: IsDeletedTable ? false : null);

                        } else if (vm.IsKey && refEntry == null) {
                            // 親自身のキー
                            var isNullable = IsDeletedTable && parentOrRef is RootAggregate;
                            yield return new ParentKeyMember(
                                vm,
                                path,
                                forceKey: isNullable ? false : null,
                                forceNotNull: isNullable ? false : null);

                        }

                    } else if (member is RefToMember refTo && refTo.IsKey) {
                        foreach (var refToKey in EnumerateKeysRecursively(isParent, refTo.RefTo, refEntry ?? refTo, [.. path, refTo.PhysicalName])) {
                            yield return refToKey;
                        }
                    }
                }
            }
        }

        /// <summary>
        /// ナビゲーションプロパティを列挙する
        /// </summary>
        public IEnumerable<NavigationProperty> GetNavigationProperties() {
            var parent = Aggregate.GetParent();
            if (parent != null) {
                yield return new NavigationProperty.NavigationOfParentChild(parent, Aggregate, IsDeletedTable);
            }

            foreach (var member in Aggregate.GetMembers()) {
                if (member is ChildAggregate child) {
                    yield return new NavigationProperty.NavigationOfParentChild(Aggregate, child, IsDeletedTable);

                } else if (member is ChildrenAggregate children) {
                    yield return new NavigationProperty.NavigationOfParentChild(Aggregate, children, IsDeletedTable);

                } else if (member is RefToMember refTo) {
                    if (!IsDeletedTable) yield return new NavigationProperty.NavigationOfRef(refTo);
                }
            }

            if (IsDeletedTable) yield break;

            foreach (var refFrom in Aggregate.GetRefFroms()) {
                // DBの実体をもたないクエリモデルやコマンドモデルから参照された場合はナビゲーションプロパティを張らない
                var refFromRoot = refFrom.Owner.GetRoot();
                var hasDbEntity = refFromRoot.Model is DataModel
                               || refFromRoot.Model is QueryModel
                               && refFromRoot.IsView;

                if (hasDbEntity) {
                    yield return new NavigationProperty.NavigationOfRef(refFrom);
                }
            }
        }

        /// <summary>
        /// 同ツリー内のEFCoreEntityを列挙する
        /// </summary>
        internal IEnumerable<EFCoreEntity> EnumerateThisAndDescendants() {
            return new[] { this }.Concat(Aggregate.EnumerateDescendants().Select(e => new EFCoreEntity(e, IsDeletedTable)));
        }

        IEnumerable<IInstancePropertyMetadata> IInstancePropertyOwnerMetadata.GetMembers() {
            foreach (var col in GetColumns()) {
                yield return col;
            }
            foreach (var nav in GetNavigationProperties()) {
                if (nav.Principal.ThisSide == Aggregate) yield return nav.Principal;
                if (nav.Relevant.ThisSide == Aggregate) yield return nav.Relevant;
            }
        }


        #region レンダリング
        internal static string RenderClassDeclaring(EFCoreEntity rootEfCoreEntity, CodeRenderingContext ctx) {
            if (rootEfCoreEntity.Aggregate is not RootAggregate) throw new InvalidOperationException();

            var tree = rootEfCoreEntity
                .EnumerateThisAndDescendants()
                .ToArray();

            return $$"""
                #region Entity Framework Core エンティティ定義
                {{tree.SelectTextTemplate(efCoreEntity => $$"""
                {{efCoreEntity.RenderClassDeclaring(ctx)}}
                """)}}

                partial class {{ctx.Config.DbContextName}} {
                {{tree.SelectTextTemplate(efCoreEntity => $$"""
                    {{WithIndent(EFCoreOnModelCreating.RenderOnModelCreating(efCoreEntity, ctx), "    ")}}
                """)}}
                }
                #endregion Entity Framework Core エンティティ定義
                """;
        }
        private string RenderClassDeclaring(CodeRenderingContext ctx) {
            var columns = GetColumns().ToArray();
            var keys = columns
                .Where(col => col.IsKey)
                .ToArray();

            var navigations = GetNavigationProperties().ToArray();
            var navigationsForDeclaring = navigations
                .Select(nav => {
                    // Principa と Relevant のうちどちらがこちら側の集約かを決める
                    NavigationProperty.PrincipalOrRelevant thisSide;
                    if (nav.Principal.ThisSide == Aggregate) thisSide = nav.Principal;
                    else if (nav.Relevant.ThisSide == Aggregate) thisSide = nav.Relevant;
                    else throw new InvalidOperationException(); // ありえない

                    // メタデータの列挙に使用するノードを決める
                    ISchemaPathNode nodeForMetadata;
                    if (nav is NavigationProperty.NavigationOfParentChild) {
                        // 親子のナビゲーションは相手側のノードを使用
                        nodeForMetadata = thisSide.OtherSide;
                    } else if (nav is NavigationProperty.NavigationOfRef navRef) {
                        // 参照のナビゲーションはref-toの関係性自体を使用
                        nodeForMetadata = navRef.Relation;
                    } else {
                        throw new InvalidOperationException(); // ありえない
                    }

                    return new { ThisSide = thisSide, NodeForMetadata = nodeForMetadata };
                });
            // 親子のナビゲーションは親側のOnModelCreatingで定義
            var navigationsForConfiguringChildren = navigations
                .Where(nav => nav is NavigationProperty.NavigationOfParentChild && nav.Principal.ThisSide == Aggregate);
            // 外部参照のナビゲーションは参照元側のOnModelCreatingで定義
            var navigationsForConfigureRefTo = navigations
                .Where(nav => nav is NavigationProperty.NavigationOfRef && nav.Relevant.ThisSide == Aggregate);

            return $$"""
                /// <summary>
                {{If(IsDeletedTable, () => $$"""
                /// 論理削除された{{Aggregate.DisplayName}}の Entity Framework Core エンティティ型。RDBMSのテーブル定義と対応。
                """).Else(() => $$"""
                /// {{Aggregate.DisplayName}}の Entity Framework Core エンティティ型。RDBMSのテーブル定義と対応。
                """)}}
                /// </summary>
                {{NijoAttr.RenderAttributeValues(ctx, Aggregate)}}
                public partial class {{CsClassName}} {
                {{columns.SelectTextTemplate(col => $$"""
                    /// <summary>{{col.DisplayName}}</summary>
                {{If(col.Member != null, () => $$"""
                    {{NijoAttr.RenderAttributeValues(ctx, col.Member!)}}
                """)}}
                    public {{col.CsType}}? {{col.PhysicalName}} { get; set; }
                """)}}
                    /// <summary>データが新規作成された日時</summary>
                    public DateTime? {{CREATED_AT}} { get; set; }
                    /// <summary>データが更新された日時</summary>
                    public DateTime? {{UPDATED_AT}} { get; set; }
                {{If(IsDeletedTable && Aggregate is RootAggregate, () => $$"""
                    /// <summary>論理削除日時</summary>
                    public DateTime? {{DELETED_AT}} { get; set; }
                """)}}
                    /// <summary>データを新規作成したユーザー</summary>
                    public string? {{CREATE_USER}} { get; set; }
                    /// <summary>データを更新したユーザー</summary>
                    public string? {{UPDATE_USER}} { get; set; }
                {{If(IsDeletedTable && Aggregate is RootAggregate, () => $$"""
                    /// <summary>論理削除を行ったユーザー</summary>
                    public string? {{DELETED_USER}} { get; set; }
                """)}}
                {{If(HasVersionColumn, () => $$"""
                    /// <summary>楽観排他制御用のバージョニング用カラム</summary>
                    public int? {{VERSION}} { get; set; }
                """)}}

                {{navigationsForDeclaring.SelectTextTemplate(nav => $$"""
                    {{NijoAttr.RenderAttributeValues(ctx, nav.NodeForMetadata)}}
                    public virtual {{nav.ThisSide.GetOtherSideCsTypeName(true)}} {{nav.ThisSide.OtherSidePhysicalName}} { get; set; }{{nav.ThisSide.GetInitializerStatement()}}
                """)}}

                    /// <summary>このオブジェクトと比較対象のオブジェクトの主キーが一致するかを返します。</summary>
                    public bool {{KEYEQUALS}}({{CsClassName}} entity) {
                {{keys.SelectTextTemplate(col => $$"""
                        if (entity.{{col.PhysicalName}} != this.{{col.PhysicalName}}) return false;
                """)}}
                        return true;
                    }
                }
                """;
        }
        #endregion レンダリング


        #region メンバー
        internal abstract class EFCoreEntityColumn : IInstanceValuePropertyMetadata {
            internal abstract ValueMember? Member { get; }
            internal abstract IValueMemberType MemberType { get; }
            internal abstract string CsType { get; }
            internal abstract string PhysicalName { get; }
            internal abstract string DisplayName { get; }
            internal abstract string DbName { get; }
            internal abstract bool IsKey { get; }
            internal abstract bool IsNotNull { get; }

            ISchemaPathNode IInstancePropertyMetadata.SchemaPathNode => Member ?? ISchemaPathNode.Empty;
            string IInstancePropertyMetadata.GetPropertyName(E_CsTs csts) => PhysicalName;
            IValueMemberType IInstanceValuePropertyMetadata.Type => MemberType;

            public override string ToString() {
                // デバッグ用
                return $"{DisplayName}({CsType})";
            }
        }
        /// <summary>
        /// 集約自身に定義されている属性で、テーブルに直接属するカラム
        /// </summary>
        internal class OwnColumnMember : EFCoreEntityColumn {
            internal OwnColumnMember(
                ValueMember member,
                string? physicalName = null,
                string? dbName = null,
                bool? isKey = null,
                bool? isNotNull = null) {

                Member = member;
                CsType = member.Type.CsPrimitiveTypeName;
                PhysicalName = physicalName ?? member.PhysicalName;
                DisplayName = member.DisplayName;
                DbName = dbName ?? member.DbName;
                IsKey = isKey ?? member.IsKey;
                IsNotNull = isNotNull ?? (isKey ?? member.IsKey) || Member.IsNotNull;
            }
            internal override ValueMember Member { get; }
            internal override IValueMemberType MemberType => Member.Type;
            internal override string CsType { get; }
            internal override string PhysicalName { get; }
            internal override string DisplayName { get; }
            internal override string DbName { get; }
            internal override bool IsKey { get; }
            internal override bool IsNotNull { get; }
        }
        /// <summary>
        /// 子テーブルに定義される、親テーブルの主キーを継承したカラム
        /// </summary>
        internal class ParentKeyMember : EFCoreEntityColumn {
            internal ParentKeyMember(ValueMember member, string physicalName, string dbName, bool? forceKey = null, bool? forceNotNull = null) {
                Member = member;
                PhysicalName = physicalName;
                DbName = dbName;
                _isKey = forceKey ?? true;
                _isNotNull = forceNotNull ?? true;
            }
            internal ParentKeyMember(ValueMember member, IEnumerable<string> path, bool? forceKey = null, bool? forceNotNull = null) {
                Member = member;
                PhysicalName = $"{path.Join("_")}_{member.PhysicalName}";
                DbName = $"{path.Join("_")}_{member.DbName}";
                _isKey = forceKey ?? true;
                _isNotNull = forceNotNull ?? true;
            }
            internal override ValueMember Member { get; }
            internal override IValueMemberType MemberType => Member.Type;
            internal override string CsType => Member.Type.CsPrimitiveTypeName;
            internal override string PhysicalName { get; }
            internal override string DisplayName => Member.DisplayName;
            internal override string DbName { get; }
            private readonly bool _isKey;
            private readonly bool _isNotNull;
            internal override bool IsKey => _isKey;
            internal override bool IsNotNull => _isNotNull;
        }
        /// <summary>
        /// 外部参照がある場合の、参照先のキーを継承したカラム
        /// </summary>
        internal class RefKeyMember : EFCoreEntityColumn {
            internal RefKeyMember(RefToMember refEntry, ValueMember member, string physicalName, string dbName, bool isParentKey, bool? forceKey = null, bool? forceNotNull = null) {
                RefEntry = refEntry;
                Member = member;
                PhysicalName = physicalName;
                DbName = dbName;
                IsParentKey = isParentKey;
                _isKey = forceKey ?? RefEntry.IsKey;
                _isNotNull = forceNotNull ?? RefEntry.IsKey || RefEntry.IsNotNull;
            }
            internal RefKeyMember(RefToMember refEntry, ValueMember member, IEnumerable<string> path, bool isParentKey, bool? forceKey = null, bool? forceNotNull = null) {
                RefEntry = refEntry;
                Member = member;
                PhysicalName = $"{path.Join("_")}_{member.PhysicalName}";
                DbName = $"{path.Join("_")}_{member.DbName}";
                IsParentKey = isParentKey;
                _isKey = forceKey ?? RefEntry.IsKey;
                _isNotNull = forceNotNull ?? RefEntry.IsKey || RefEntry.IsNotNull;
            }
            internal RefToMember RefEntry { get; }
            internal override ValueMember Member { get; }
            internal override IValueMemberType MemberType => Member.Type;
            internal override string CsType => Member.Type.CsPrimitiveTypeName;
            internal override string PhysicalName { get; }
            internal override string DisplayName => Member.DisplayName;
            internal override string DbName { get; }
            private readonly bool _isKey;
            private readonly bool _isNotNull;
            internal override bool IsKey => _isKey;
            internal override bool IsNotNull => _isNotNull;
            /// <summary>
            /// この参照先キーが同時に <see cref="ParentKeyMember"/> であるかどうか。
            /// </summary>
            internal bool IsParentKey { get; }
        }

        /// <summary>
        /// 論理削除テーブルの、論理削除用UUIDカラム
        /// </summary>
        internal class DeletedUuidColumn : EFCoreEntityColumn {
            internal override ValueMember? Member => null;
            internal override IValueMemberType MemberType => new ValueMemberTypes.Word();
            internal override string CsType => "Guid";
            internal override string PhysicalName => DELETED_UUID;
            internal override string DisplayName => "論理削除UUID";
            internal override string DbName => DELETED_UUID;
            internal override bool IsKey => true;
            internal override bool IsNotNull => true;
        }
        #endregion メンバー


        /// <summary>
        /// 子孫要素をIncludeする式をレンダリングします。
        /// また、 1:N のリレーションが複数登場する場合、パフォーマンスに問題が出るのを防ぐため
        /// AsSplitQuery() を呼び出すようにします。
        /// </summary>
        internal IEnumerable<string> RenderInclude() {
            var descendants = Aggregate.EnumerateDescendants().ToArray();

            // 1:N のリレーションが2個以上存在する場合は AsSplitQuery() を追加
            if (descendants.Count(agg => agg is ChildrenAggregate) >= 2) {
                yield return ".AsSplitQuery() // パフォーマンスの問題を防ぐため、テーブル毎に個別にSQLを発行して取得する";
            }

            foreach (var agg in descendants) {
                var fullPath = agg.GetPathFromEntry().Skip(1).ToArray();

                for (int i = 0; i < fullPath.Length; i++) {
                    var parent = (AggregateBase?)fullPath[i].PreviousNode ?? throw new InvalidOperationException("ありえない");
                    var child = (AggregateBase?)fullPath[i] ?? throw new InvalidOperationException("ありえない");
                    var nav = new NavigationProperty.NavigationOfParentChild(parent, child);

                    yield return i == 0
                        ? $".Include(e => e!.{nav.Principal.OtherSidePhysicalName})"      // クエリのエンティティ直下の場合はInclude
                        : $".ThenInclude(e => e!.{nav.Principal.OtherSidePhysicalName})"; // クエリのエンティティ直下でない場合はThenInclude
                }
            }
        }
    }
}
