using Microsoft.EntityFrameworkCore;
using Nijo.CodeGenerating;
using Nijo.ImmutableSchema;
using Nijo.Models;
using Nijo.Util.DotnetEx;
using Nijo.ValueMemberTypes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Nijo.Parts.CSharp;

/// <summary>
/// Entity Framework Core の OnModelCreating をレンダリングする
/// </summary>
internal static class EFCoreOnModelCreating {

    internal static string RenderOnModelCreating(EFCoreEntity entity, CodeRenderingContext ctx) {
        var columns = entity.GetColumns().ToArray();
        var keys = columns
            .Where(col => col.IsKey)
            .ToArray();

        var navigations = entity.GetNavigationProperties().ToArray();
        var navigationsForDeclaring = navigations
            .Select(nav => {
                if (nav.Principal.ThisSide == entity.Aggregate) return nav.Principal;
                if (nav.Relevant.ThisSide == entity.Aggregate) return nav.Relevant;
                throw new InvalidOperationException(); // ありえない
            });
        // 親子のナビゲーションは親側のOnModelCreatingで定義
        var navigationsForConfiguringChildren = navigations
            .Where(nav => nav is NavigationProperty.NavigationOfParentChild && nav.Principal.ThisSide == entity.Aggregate);
        // 外部参照のナビゲーションは参照元側のOnModelCreatingで定義
        var navigationsForConfigureRefTo = navigations
            .Where(nav => nav is NavigationProperty.NavigationOfRef && nav.Relevant.ThisSide == entity.Aggregate);

        var rootAggregate = entity.Aggregate.GetRoot();
        var isView = rootAggregate.IsView;

        return $$"""
                /// <summary>
                /// テーブルやカラムの詳細を定義します。
                /// 参考: "Fluent API" （Entity FrameWork Core の仕組み）
                /// </summary>
                public virtual void {{entity.OnModelCreatingAutoGenerated}}({{ctx.Config.DbContextName}} dbContext, ModelBuilder modelBuilder) {
                    modelBuilder.Entity<{{entity.CsClassName}}>(entity => {
                {{If(isView, () => $$"""
                        entity.ToView("{{entity.Aggregate.DbName}}");
                """).Else(() => $$"""
                        entity.ToTable("{{entity.Aggregate.DbName}}");
                """)}}

                {{If(keys.Length > 0, () => $$"""
                        entity.HasKey(e => new {
                {{keys.SelectTextTemplate(col => $$"""
                            e.{{col.PhysicalName}},
                """)}}
                        })
                        .HasName("PK_{{entity.Aggregate.DbName}}");

                """).Else(() => $$"""
                        entity.HasNoKey();

                """)}}
                {{columns.SelectTextTemplate((col, ix) => $$"""
                        entity.Property(e => e.{{col.PhysicalName}})
                            .HasColumnName("{{col.DbName}}")
                {{If(col.Member.TotalDigit != null, () => $$"""
                            .HasPrecision({{col.Member.TotalDigit}}, {{col.Member.DecimalPlace ?? 0}})
                """)}}
                {{If(col.Member.MaxLength != null, () => $$"""
                            .HasMaxLength({{col.Member.MaxLength}})
                """)}}
                            .IsRequired({{(col.IsKey || col.Member.IsRequired ? "true" : "false")}})
                            .HasColumnOrder({{ix}});
                {{If(col.Member.Type is SequenceMember, () => $$"""
                        {{SequenceMember.CONFIGURE_MEMBER}}(modelBuilder, entity, entity.Property(e => e.{{col.PhysicalName}}), "{{col.Member.SequenceName}}");

                """)}}
                """)}}
                {{If(entity.HasTimestampColumns, () => $$"""
                        entity.Property(e => e.{{EFCoreEntity.CREATED_AT}})
                            .HasColumnName("{{ctx.Config.CreatedAtDbColumnName.Replace("\"", "\\\"")}}")
                            .IsRequired(false)
                            .HasColumnOrder({{columns.Length + 0}});
                        entity.Property(e => e.{{EFCoreEntity.CREATE_USER}})
                            .HasColumnName("{{ctx.Config.CreateUserDbColumnName.Replace("\"", "\\\"")}}")
                            .IsRequired(false)
                            .HasColumnOrder({{columns.Length + 1}});
                        entity.Property(e => e.{{EFCoreEntity.UPDATED_AT}})
                            .HasColumnName("{{ctx.Config.UpdatedAtDbColumnName.Replace("\"", "\\\"")}}")
                            .IsRequired(false)
                            .HasColumnOrder({{columns.Length + 2}});
                        entity.Property(e => e.{{EFCoreEntity.UPDATE_USER}})
                            .HasColumnName("{{ctx.Config.UpdateUserDbColumnName.Replace("\"", "\\\"")}}")
                            .IsRequired(false)
                            .HasColumnOrder({{columns.Length + 3}});
                """)}}
                {{If(entity.HasVersionColumn, () => $$"""
                        entity.Property(e => e.{{EFCoreEntity.VERSION}})
                            .HasColumnName("{{ctx.Config.VersionDbColumnName.Replace("\"", "\\\"")}}")
                            .IsRequired(true)
                            .IsConcurrencyToken(true)
                            .HasColumnOrder({{columns.Length + 4}});
                """)}}
                {{navigationsForConfiguringChildren.SelectTextTemplate(nav => $$"""

                        entity.{{(nav.Principal.OtherSideIsMany ? "HasMany" : "HasOne")}}(e => e.{{nav.Principal.OtherSidePhysicalName}})
                            .{{(nav.Relevant.OtherSideIsMany ? "WithMany" : "WithOne")}}(e => e.{{nav.Relevant.OtherSidePhysicalName}})
                            .HasForeignKey{{(nav.IsOneToOne ? $"<{nav.Principal.GetOtherSideCsTypeName()}>" : "")}}(e => new {
                {{nav.GetRelevantForeignKeys().SelectTextTemplate(fk => $$"""
                                e.{{fk.PhysicalName}},
                """)}}
                            })
                            .IsRequired(false)
                            .OnDelete({{nameof(DeleteBehavior)}}.{{nav.PrincipalDeletedBehavior}})
                            .HasConstraintName("{{nav.GetConstraintName().Replace("\"", "\\\"")}}");
                """)}}
                {{navigationsForConfigureRefTo.SelectTextTemplate(nav => $$"""

                        entity.HasOne(e => e.{{nav.Relevant.OtherSidePhysicalName}})
                            .{{(nav.Principal.OtherSideIsMany ? "WithMany" : "WithOne")}}(e => e.{{nav.Principal.OtherSidePhysicalName}})
                            .HasForeignKey{{(nav.IsOneToOne ? $"<{nav.Principal.GetOtherSideCsTypeName()}>" : "")}}(e => new {
                {{nav.GetRelevantForeignKeys().SelectTextTemplate(fk => $$"""
                                e.{{fk.PhysicalName}},
                """)}}
                            })
                            .OnDelete({{nameof(DeleteBehavior)}}.{{nav.PrincipalDeletedBehavior}})
                            .HasConstraintName("{{nav.GetConstraintName().Replace("\"", "\\\"")}}");
                """)}}

                        // 自動生成されない設定の手動定義（インデックス、ユニーク制約、デフォルト値など）
                        {{EFCoreEntity.ON_MODEL_CREATING_CUSTOMIZE}}(entity);
                    });
                }
                """;
    }
    internal static string RenderConfigureAbstractMethod(EFCoreEntity entity) {
        return $$"""
                /// <summary>
                /// 自動生成されない初期設定がある場合はこのメソッドをオーバーライドして設定してください。
                /// （インデックス、ユニーク制約、デフォルト値など）
                /// </summary>
                public virtual void {{EFCoreEntity.ON_MODEL_CREATING_CUSTOMIZE}}(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<{{entity.CsClassName}}> entity) {
                }
                """;
    }

}
