using Microsoft.EntityFrameworkCore;
using Nijo.CodeGenerating;
using Nijo.ImmutableSchema;
using Nijo.ValueMemberTypes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Nijo.Parts.CSharp;

/// <summary>
/// Entity Framework Core の OnModelCreating をレンダリングする
/// </summary>
internal static class EFCoreOnModelCreating {

    internal static string RenderOnModelCreating(IEFCoreEntity entity, CodeRenderingContext ctx) {
        var columns = entity.GetColumns().ToArray();
        var keys = columns
            .Where(col => col.IsKey)
            .ToArray();
        var uniqueIndexes = entity.Aggregate.GetUniqueConstraints()
            .Select(c => (Constraint: c, Columns: ResolveUniqueColumns(c, columns).ToArray()))
            .Where(x => x.Columns.Length > 0)
            .ToArray();

        var efCoreEntity = entity as EFCoreEntity;
        var isDeletedTable = efCoreEntity?.IsDeletedTable == true;
        if (isDeletedTable) uniqueIndexes = Array.Empty<(AggregateBase.UniqueConstraint Constraint, string[] Columns)>();

        var navigations = entity.GetNavigationProperties().ToArray();
        var navigationsForDeclaring = isDeletedTable
            ? Array.Empty<NavigationProperty.PrincipalOrRelevant>()
            : navigations
                .Select(nav => {
                    if (nav.Principal.ThisSide == entity.Aggregate) return nav.Principal;
                    if (nav.Relevant.ThisSide == entity.Aggregate) return nav.Relevant;
                    throw new InvalidOperationException(); // ありえない
                });
        // 親子のナビゲーションは親側のOnModelCreatingで定義
        var navigationsForConfiguringChildren = navigations
                .Where(nav => nav is NavigationProperty.NavigationOfParentChild && nav.Principal.ThisSide == entity.Aggregate);
        // 外部参照のナビゲーションは参照元側のOnModelCreatingで定義
        var navigationsForConfigureRefTo = isDeletedTable
            ? Array.Empty<NavigationProperty>()
            : navigations
                .Where(nav => nav is NavigationProperty.NavigationOfRef && nav.Relevant.ThisSide == entity.Aggregate);

        var rootAggregate = entity.Aggregate.GetRoot();
        var isView = rootAggregate.IsView;
        var tableName = efCoreEntity?.TableDbName ?? entity.Aggregate.DbName;

        static IEnumerable<string> ResolveUniqueColumns(AggregateBase.UniqueConstraint constraint, EFCoreEntity.EFCoreEntityColumn[] cols) {
            var result = new List<string>();

            foreach (var member in constraint.Members) {
                switch (member) {
                    case ValueMember vm:
                        var ownColumn = cols
                            .OfType<EFCoreEntity.OwnColumnMember>()
                            .FirstOrDefault(c => c.Member == vm);
                        if (ownColumn == null) return Array.Empty<string>();
                        result.Add(ownColumn.PhysicalName);
                        break;

                    case RefToMember refTo:
                        var fkColumns = cols
                            .OfType<EFCoreEntity.RefKeyMember>()
                            .Where(c => c.RefEntry == refTo)
                            .ToArray();
                        if (fkColumns.Length == 0) return Array.Empty<string>();
                        result.AddRange(fkColumns.Select(c => c.PhysicalName));
                        break;

                    default:
                        return Array.Empty<string>();
                }
            }

            return result.Distinct(StringComparer.Ordinal);
        }

        var pkName = isDeletedTable
            ? $"PK_{entity.Aggregate.DbName}_DELETED"
            : $"PK_{entity.Aggregate.DbName}";

        return $$"""
            /// <summary>
            /// テーブルやカラムの詳細を定義します。
            /// 参考: "Fluent API" （Entity FrameWork Core の仕組み）
            /// </summary>
            protected virtual void {{entity.OnModelCreatingAutoGenerated}}(ModelBuilder modelBuilder) {
                modelBuilder.Entity<{{entity.CsClassName}}>(entity => {
            {{If(isView && !isDeletedTable, () => $$"""
                    entity.ToView("{{tableName}}");
            """).Else(() => $$"""
                    entity.ToTable("{{tableName}}");
            """)}}

            {{If(keys.Length > 0, () => $$"""
                    entity.HasKey(e => new {
            {{keys.SelectTextTemplate(col => $$"""
                        e.{{col.PhysicalName}},
            """)}}
                    })
                    .HasName("{{pkName}}");

            """).Else(() => $$"""
                    entity.HasNoKey();

            """)}}
            {{columns.SelectTextTemplate((col, ix) => $$"""
                    entity.Property(e => e.{{col.PhysicalName}})
                        .HasColumnName("{{col.DbName}}")
            {{If(col.Member?.TotalDigit != null, () => $$"""
                        .HasPrecision({{col.Member!.TotalDigit}}, {{col.Member.DecimalPlace ?? 0}})
            """)}}
            {{If(col.Member?.MaxLength != null, () => $$"""
                        .HasMaxLength({{col.Member!.MaxLength}})
            """)}}
                        .IsRequired({{(col.IsNotNull ? "true" : "false")}})
                        .HasColumnOrder({{ix}});
            {{If(col.Member is not null && col.Member.Type is SequenceMember, () => $$"""
                    {{SequenceMember.CONFIGURE_MEMBER}}(modelBuilder, entity, entity.Property(e => e.{{col.PhysicalName}}), "{{col.Member!.SequenceName}}");

            """)}}
            """)}}
            {{If(entity.HasTimestampColumns, () => $$"""
                    entity.Property(e => e.{{EFCoreEntity.CREATED_AT}})
                        .HasColumnName("{{ctx.Config.CreatedAtDbColumnName.Replace("\"", "\\\"")}}")
                        .IsRequired(false)
                        .HasColumnOrder({{columns.Length + 0}});
                    entity.Property(e => e.{{EFCoreEntity.CREATE_USER}})
                        .HasColumnName("{{ctx.Config.CreateUserDbColumnName.Replace("\"", "\\\"")}}")
                        .IsRequired(false)
                        .HasColumnOrder({{columns.Length + 1}});
                    entity.Property(e => e.{{EFCoreEntity.UPDATED_AT}})
                        .HasColumnName("{{ctx.Config.UpdatedAtDbColumnName.Replace("\"", "\\\"")}}")
                        .IsRequired(false)
                        .HasColumnOrder({{columns.Length + 2}});
                    entity.Property(e => e.{{EFCoreEntity.UPDATE_USER}})
                        .HasColumnName("{{ctx.Config.UpdateUserDbColumnName.Replace("\"", "\\\"")}}")
                        .IsRequired(false)
                        .HasColumnOrder({{columns.Length + 3}});
            """)}}
            {{If(entity.HasVersionColumn, () => $$"""
                    entity.Property(e => e.{{EFCoreEntity.VERSION}})
                        .HasColumnName("{{ctx.Config.VersionDbColumnName.Replace("\"", "\\\"")}}")
                        .IsRequired({{(isDeletedTable ? "false" : "true")}})
                        .IsConcurrencyToken({{(isDeletedTable ? "false" : "true")}})
                        .HasColumnOrder({{columns.Length + 4}});
            """)}}
            {{If(uniqueIndexes.Length > 0, () => $$"""

                    // ユニーク制約
            {{uniqueIndexes.SelectTextTemplate(idx => $$"""
                    entity.HasIndex(e => new {
            {{idx.Columns.SelectTextTemplate(col => $$"""
                        e.{{col}},
            """)}}
                    })
                    .IsUnique();
            """)}}
            """)}}
            {{navigationsForConfiguringChildren.SelectTextTemplate(nav => $$"""

                    entity.{{(nav.Principal.OtherSideIsMany ? "HasMany" : "HasOne")}}(e => e.{{nav.Principal.OtherSidePhysicalName}})
                        .{{(nav.Relevant.OtherSideIsMany ? "WithMany" : "WithOne")}}(e => e.{{nav.Relevant.OtherSidePhysicalName}})
                        .HasForeignKey{{(nav.IsOneToOne ? $"<{nav.Principal.GetOtherSideCsTypeName()}>" : "")}}(e => new {
            {{nav.GetRelevantForeignKeys().SelectTextTemplate(fk => $$"""
                            e.{{fk.PhysicalName}},
            """)}}
                        })
                        .IsRequired(false)
                        .OnDelete({{nameof(DeleteBehavior)}}.{{nav.PrincipalDeletedBehavior}})
                        .HasConstraintName("{{nav.GetConstraintName().Replace("\"", "\\\"")}}");
            """)}}
            {{navigationsForConfigureRefTo.SelectTextTemplate(nav => $$"""

                    entity.HasOne(e => e.{{nav.Relevant.OtherSidePhysicalName}})
                        .{{(nav.Principal.OtherSideIsMany ? "WithMany" : "WithOne")}}(e => e.{{nav.Principal.OtherSidePhysicalName}})
                        .HasForeignKey{{(nav.IsOneToOne ? $"<{nav.Principal.GetOtherSideCsTypeName()}>" : "")}}(e => new {
            {{nav.GetRelevantForeignKeys().SelectTextTemplate(fk => $$"""
                            e.{{fk.PhysicalName}},
            """)}}
                        })
                        .OnDelete({{nameof(DeleteBehavior)}}.{{nav.PrincipalDeletedBehavior}})
                        .HasConstraintName("{{nav.GetConstraintName().Replace("\"", "\\\"")}}");
            """)}}
                });
            }
            """;
    }
}
