
import React from "react"
import * as RHF from "react-hook-form"

// 集約ごとのメタデータの型
import type { AggregateMetadata } from "./__autoGenerated"

import * as 入荷詳細 from "./__autoGenerated/models/入荷詳細"
import * as 従業員Ref from "./__autoGenerated/models/従業員Ref"
import { callComplexPostEndpointAsync } from "./example/callComplexPostEndpointAsync"
import { EditableGrid, EditableGridColumn, EditableGridLeafColumn, EditableGridProps, EditableGridRowUpdate } from "@halllky/editable-grid"
import { getTextCellEditor } from "./ui/grid/GridCell.Text"
import { QuestionMarkCircleIcon } from "@heroicons/react/24/solid"

// ------------------------------
// 入荷詳細.ts のつもりのファイル
// ------------------------------

// 入荷詳細とその子孫とそれらの参照先のメタ情報を新たに追加したい
function getMetadata() {
  return {
    "入荷詳細": {
      uniqueId: 'bf2453f1-2a89-4209-ab79-00d526fd15a9',
      type: 'RootAggregate',
      model: 'structure-model',
      displayName: '入荷詳細',
      comment: '入荷詳細画面のデータ構造。',
      members: [ // 子（メンバー）への参照をもつ
        "入荷詳細.入荷ID",
        "入荷詳細.入荷日時",
        "入荷詳細.担当者",
        // ... 略
      ],
    },
    "入荷詳細.入荷ID": {
      parent: "入荷詳細", // 親（オーナー）への参照をもつ
      uniqueId: '3e481d8e-1940-4827-a8fa-f19f31c19b43',
      type: 'word',
      displayName: '入荷ID',
      comment: '非表示。UUID。自動採番',
    },
    // ... 略

    // ...従業員Ref.getMetadata(), // ref-to 先のメタ情報も含む。循環参照の可能性を考慮して function にしている
  }
}

// ------------------------------
// useDisplayDataForm.tsx
// ------------------------------

// 最終的にはこのようにメタ情報から簡単に画面を組み立てられるようにしたい
function useDisplayDataForm<T extends RHF.FieldValues>(autoGenerated: {
  // getMetadata: (() => { /* メタ情報 */ }) // 本当はこれも必要
  createNewDisplayData: () => T
}) {

  const treeMetadata = React.useMemo((): AggregateMetadata.Table => {
    return {} // 本当はここで return autoGenerated.getMetadate() をする
  }, [])

  const formMethods = RHF.useForm<T>({
    defaultValues: async () => Promise.resolve(autoGenerated.createNewDisplayData()),
  })

  // サーバー側で発生したエラー。
  // RHFのerrorsとの合成はこのフックの中で行う
  const [serverErrors, setServerErrors] = React.useState<ServerMessage>({})
  const clearServerErrors = React.useCallback(() => {
    setServerErrors({})
  }, [])

  // 自動生成されたソースと密接に関連した入力コンポーネント
  const UI = React.useMemo(() => {
    const TextBox = ({ name }: { name: RHF.Path<T>, isReadOnly?: boolean, className?: string }) => {
      const { isKey, isNotNull, customMaxLength } = treeMetadata[name]

      return (
        <input type="text"
          {...formMethods.register(name, {
            required: isKey || isNotNull,
            maxLength: customMaxLength,
          })}
        />
      )
    }
    return {
      TextBox,
      // ... 他にもいろいろなUIを用意する
    }
  }, [autoGenerated, formMethods])

  /**
   * パラメータ内の配列を EditableGrid で編集するためのフック。
   * 戻り値の props を EditableGrid にスプレッドして使う。
   * getColumns が画面側の値を参照する場合はそれを deps に列挙すること。
   *
   * このフックが扱うのはグリッドとフォームの値の橋渡しだけで、行の追加・削除・並べ替えの手段は提供しない。
   * それらが必要な場合は同じ配列に対して react-hook-form の useFieldArray を併用すること。
   * フォームの値の変更は購読を通じてグリッドに反映されるので、useFieldArray の操作はそのまま画面に反映される。
   *
   * 行は instanceId で識別する（グリッドの rowKey = instanceId）。行を複製する場合は instanceId を新しく振り直すこと。
   * グリッドが渡す rowIndex は画面上の位置であり、絞り込み・並び替えをすると配列の添字と一致しない。
   * useFieldArray の remove や swap など配列の添字を受け取る操作には、rowKey から求めた添字を渡すこと。
   */
  const useEditableGrid = <TArrayPath extends RHF.ArrayPath<T>>(
    name: TArrayPath,
    getColumns: (col: GridColumnHelper<GridRow<T, TArrayPath>>) => EditableGridColumn<GridRow<T, TArrayPath>>[],
    deps: React.DependencyList,
    options?: {
      /**
       * 画面に表示する行を絞り込み・並び替えて返す関数。
       * 引数の配列は最新の値のコピーなので、破壊的変更（sort など）をしてよい。
       * 未指定の場合は全行を配列の順に表示する。
       */
      selectDisplayRows?: (rows: GridRow<T, TArrayPath>[]) => GridRow<T, TArrayPath>[]
    },
  ) => {
    type TRow = GridRow<T, TArrayPath>

    const arrayPath = name as RHF.Path<T>
    const getRows = () => (formMethods.getValues(arrayPath) ?? []) as TRow[]

    // 列定義
    const columns = React.useMemo((): EditableGridColumn<TRow>[] => getColumns({
      text: (path, options) => {
        const { header, ...restOptions } = options ?? {}
        // メタデータは配列の要素ごとではなく配列全体で1つなので、インデックス抜きのパスで引く
        const { displayName, customMaxLength } = treeMetadata[`${name}.${path}`]
        return {
          columnId: path,
          editor: getTextCellEditor(customMaxLength),
          renderHeader: () => (
            <div className="px-1 py-px truncate text-gray-700">{header ?? displayName}</div>
          ),
          getValuesForRender: row => [RHF.get(row, path) as unknown],
          renderBody: ({ deps: [value] }) => (
            <div className="px-1 py-px truncate">
              {value?.toString()}
            </div>
          ),
          cellToText: row => (RHF.get(row, path) as unknown)?.toString() ?? '',
          textToCell: (row, text) => {
            const clone = structuredClone(row)
            RHF.set(clone, path, text)
            return clone
          },
          ...restOptions,
        }
      },
    }), [name, ...deps])

    // 画面に表示する行
    const selectRowKeys = (rows: TRow[]): string[] => {
      const displayRows = options?.selectDisplayRows?.([...rows]) ?? rows
      return displayRows.map(row => row.instanceId)
    }
    // フォームの値の変化で表示行の並びが変わったときに再レンダリングさせる。
    // compute の結果が前回と同じなら再レンダリングは起きないので、表示行に影響しない値の変化では画面全体が描画し直されない。
    RHF.useWatch({
      control: formMethods.control,
      name: arrayPath,
      compute: rows => selectRowKeys((rows ?? []) as TRow[]),
    })
    // 表示行そのものはレンダリングのたびに最新の値から求める。
    // 画面側の state による絞り込み条件の変化はフォームの値の変化を伴わず、上の購読では拾えないため。
    const rowKeys = selectRowKeys(getRows())

    // instanceId から配列の添字を引くためのキャッシュ。描画には影響しないので ref で持ち、
    // 引いた位置の行の instanceId が一致しなければ（行の増減・並び替えがあった）作り直す。
    // 行の削除直後、グリッドが新しい rowKeys で再描画される前に削除済みの行を問い合わせてくることがあるため、
    // 見つからない場合は例外にせず undefined を返す。
    const rowIndexCache = React.useRef(new Map<string, number>())
    const findRowIndex = React.useCallback((rowKey: string): number | undefined => {
      const rows = getRows()
      const cached = rowIndexCache.current.get(rowKey)
      if (cached !== undefined && rows[cached]?.instanceId === rowKey) return cached

      rowIndexCache.current = new Map(rows.map((row, index) => [row.instanceId, index]))
      return rowIndexCache.current.get(rowKey)
    }, [name])

    const getLatestRowObject = React.useCallback((_: number, rowKey: string): TRow => {
      const index = findRowIndex(rowKey)
      return (index === undefined ? undefined : getRows()[index]) as TRow
    }, [findRowIndex])

    const subscribe = React.useCallback((onChange: () => void) => {
      return formMethods.subscribe({
        name: arrayPath,
        formState: { values: true },
        callback: onChange,
      })
    }, [arrayPath])

    const onRowsChange = React.useCallback((updates: EditableGridRowUpdate<TRow>[]) => {
      for (const { rowKey, row } of updates) {
        const index = findRowIndex(rowKey)
        if (index === undefined) continue
        formMethods.setValue(
          `${name}.${index}` as RHF.Path<T>,
          row as RHF.PathValue<T, RHF.Path<T>>,
          { shouldDirty: true },
        )
      }
    }, [name, findRowIndex])

    const editableGridProps: EditableGridProps<TRow> = {
      rowKeys,
      getLatestRowObject,
      subscribe,
      onRowsChange,
      columns,
    }
    return editableGridProps
  }

  // どの項目とも対応しないエラー。
  // root に出たエラーと、表示領域がないエラーを表示する。
  // （DisplayData の全項目が必ず画面上に存在するとは限らない）
  // RHF と server error の両方が対象
  const RootErrors = React.useCallback(() => {
    const { formState: { errors: { root: rootError } } } = formMethods
    return rootError?.message && (
      <span className="text-rose-600">
        {rootError.message}
      </span>
    )
  }, [formMethods])

  // 特定の項目のラベル。
  // displayName, 必須マーク、ヘルプテキスト（まだないけど...）を表示する。
  // 特定の項目の脇に表示するエラーがあればそれも表示する。（RHF と server error の両方が対象。いったんRHFだけ見せている）
  const FieldLabel = React.useCallback(({ name, vertical, afterLabel, children, className: propsClassName }: {
    name: RHF.Path<T>
    vertical?: boolean
    afterLabel?: React.ReactNode
    children?: React.ReactNode
    className?: string
  }) => {
    const { displayName, isKey, isNotNull, comment } = treeMetadata[name]
    const { getFieldState, formState } = formMethods
    const { error } = getFieldState(name, formState)

    let className = vertical
      ? "flex flex-col items-stretch"
      : "flex"
    if (propsClassName) className += " " + propsClassName

    return (
      <label className={className}>
        <div className="flex flex-wrap">
          <span className="select-none">
            {displayName}
          </span>
          {/* 必須マーク */}
          {(isKey || isNotNull) && (
            <span className="text-rose-600 select-none">*</span>
          )}
          {/* ヘルプテキスト（コメント） */}
          {comment && (
            <QuestionMarkCircleIcon className="w-4 h-4 cursor-help" title={comment} />
          )}
        </div>
        <div className="flex-1">
          {error?.message && (
            <span className="text-rose-600">
              {error.message}
            </span>
          )}
        </div>
      </label>
    )
  }, [formMethods, treeMetadata])

  return {
    UI,
    useEditableGrid,
    RootErrors,
    FieldLabel,
    formMethods,
    setServerErrors,
    clearServerErrors,
  }
}

// RHFのerrorsと異なりサーバーから返されるもの。
// メッセージのクリアのライフサイクルがRHFと違う
// キーは DisplayData の instanceId 。
// どの項目とも紐づかないなら "root" が表示される。
type ServerMessage = {
  [instanceId: string | "root"]: {
    errors: string[]
    warnings: string[]
    informations: string[]
  }
}

/** グリッドの1行。行の識別に instanceId を使う */
type GridRow<TDisplayData extends RHF.FieldValues, TArrayPath extends RHF.ArrayPath<TDisplayData>>
  = RHF.FieldArray<TDisplayData, TArrayPath> & { instanceId: string }

/**
 * コマンドパラメータの明細グリッドの列定義ヘルパー。
 * 見出しと入力制約は自動生成されたメタデータから決まる。
 */
export type GridColumnHelper<TRow> = {
  /** 文字列テキストボックス列 */
  text: (
    path: RHF.Path<TRow>,
    options?: Omit<Partial<EditableGridLeafColumn<TRow>>, 'wrap'> & {
      /** 列見出し。未指定の場合はメタデータの表示用名称、それも無ければパスの末尾 */
      header?: string
    }
  ) => EditableGridLeafColumn<TRow>
}

// ------------------------------
// 画面.tsx
// ------------------------------

// 最終的にはこのようにメタ情報から簡単に画面を組み立てられるようにしたい
function SamplePage() {
  const {
    UI,
    useEditableGrid,
    RootErrors,
    FieldLabel,
    formMethods: { handleSubmit },
    setServerErrors,
  } = useDisplayDataForm(入荷詳細)

  // 更新前後のハンドリング。
  // RHFのエラーが何か起きている場合はここまで来ない
  const onSubmit: RHF.SubmitHandler<入荷詳細.DisplayData> = async data => {
    const res = await callComplexPostEndpointAsync("入荷修正", data)

    // キャンセルされた場合は何もしない
    if (res.type === "canceled") {
      return
    }
    // エラーの場合は画面上に表示
    if (res.type === "error") {
      setServerErrors({}) // 本当は res.detail を設定する。型定義が合わないので割愛
      return
    }
    // ここまできたら更新成功
    window.location.reload()
  }

  const itemsGridProps = useEditableGrid("入荷商品一覧", col => [
    col.text("商品.商品SEQ", { header: "商品SEQ", defaultWidth: 80 }),
    col.text("商品.商品名", { header: "商品名", defaultWidth: 160 }),
  ], [])

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="flex flex-col">
      <RootErrors />

      <FieldLabel name="入荷ID">
        <UI.TextBox name="入荷ID" />
      </FieldLabel>
      <FieldLabel name="備考">
        <UI.TextBox name="備考" />
      </FieldLabel>

      {/* 入荷商品一覧 */}
      <EditableGrid {...itemsGridProps} />
    </form>
  )
}
