using Nijo.CodeGenerating;
using Nijo.Util.DotnetEx;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace Nijo.Parts.Common {
    /// <summary>
    /// 旧版互換の区分値ファイル。
    /// 旧版の Enum.cs / autogenerated-enum.ts と同じ形式でコードを生成する。
    /// </summary>
    internal class EnumFile2 : IMultiAggregateSourceFile {

        internal record EnumItemInfo(
            string PhysicalName,
            string DisplayName,
            int Value,
            bool IsEmptyDisplayName);

        internal record EnumDefInfo(
            string Name,
            IReadOnlyList<EnumItemInfo> Items);

        private readonly List<EnumDefInfo> _enumDefs = [];
        private readonly List<string> _sourceCodes = [];
        private readonly Lock _lock = new();

        internal EnumFile2 AddEnum(EnumDefInfo enumDef) {
            lock (_lock) {
                _enumDefs.Add(enumDef);
                return this;
            }
        }

        internal EnumFile2 AddSourceCode(string sourceCode) {
            lock (_lock) {
                _sourceCodes.Add(sourceCode);
                return this;
            }
        }

        void IMultiAggregateSourceFile.RegisterDependencies(IMultiAggregateSourceFileManager ctx) {
            // 特になし
        }

        void IMultiAggregateSourceFile.Render(CodeRenderingContext ctx) {
            if (_enumDefs.Count == 0 && _sourceCodes.Count == 0) return;

            var orderedDefs = _enumDefs.OrderBy(d => d.Name).ToArray();
            var orderedSourceCodes = _sourceCodes
                .Select((source, index) => new { Source = source, Index = index })
                .OrderBy(x => GetSourcePriority(x.Source))
                .ThenBy(x => x.Index)
                .Select(x => x.Source)
                .ToArray();

            ctx.CoreLibrary(dir => {
                dir.Generate(new SourceFile {
                    FileName = "Enum.cs",
                    Contents = $$"""
                    namespace {{ctx.Config.RootNamespace}} {
                        using System.ComponentModel.DataAnnotations;

                    {{orderedDefs.SelectTextTemplate(def => $$"""
                        public enum {{def.Name}} {
                    {{def.Items.SelectTextTemplate(item => $$"""
                    {{If(!string.IsNullOrWhiteSpace(item.DisplayName), () => $$"""
                            [Display(Name = "{{(item.IsEmptyDisplayName ? string.Empty : item.DisplayName.Replace("\"", "\\\""))}}")]
                    """)}}
                            {{item.PhysicalName}} = {{item.Value}},
                    """)}}
                        }
                    """)}}
                    {{orderedSourceCodes.SelectTextTemplate(source => $$"""

                        {{WithIndent(source, "    ")}}
                    """)}}
                    }
                    """,
                });

                // Oracle用のenum定義（事業PFへの公開テーブルで区分値の名称をとるのに使う）
                // ※ここのディレクトリ名はマイグレーションスクリプト生成コマンドと一致させる必要がある
                dir.Directory("..\\MigrationsScript", migrationDir => {
                    migrationDir.Generate(GetOracleGetNameFunction(orderedDefs));
                });
            });

            static int GetSourcePriority(string source) {
                if (source.Contains("public enum E_BoolSearchCondition", StringComparison.Ordinal)) return 0;
                if (source.Contains("SearchCondition", StringComparison.Ordinal)) return 1;
                if (source.Contains("public enum E_SingleViewType", StringComparison.Ordinal)) return 2;
                if (source.Contains("public enum E_AuthLevel", StringComparison.Ordinal)) return 3;
                if (source.Contains("public enum E_AddOrModOrDel", StringComparison.Ordinal)) return 4;
                return 100;
            }

            ctx.ReactProject(dir => {
                dir.Generate(new SourceFile {
                    FileName = "autogenerated-enum.ts",
                    Contents = $$"""
                    /** 自動生成された列挙体の型 */
                    export interface EnumTypes {
                    {{orderedDefs.SelectTextTemplate(def => $$"""
                      {{def.Name}}: {{def.Items.Select(item => $"'{(item.IsEmptyDisplayName ? string.Empty : item.DisplayName.Replace("'", "\\'"))}'").Join(" | ")}}
                    """)}}
                    }

                    /** 自動生成された列挙体の名前と型のマッピング */
                    export interface EnumTypeMap {
                    {{orderedDefs.SelectTextTemplate(def => $$"""
                      '{{def.Name}}': EnumTypes['{{def.Name}}']
                    """)}}
                    }

                    /** 自動生成された列挙体の値（画面表示用データ） */
                    export const EnumValues = {
                    {{orderedDefs.SelectTextTemplate(def => $$"""
                      '{{def.Name}}': [
                    {{def.Items.SelectTextTemplate(item => $$"""
                        '{{(item.IsEmptyDisplayName ? string.Empty : item.DisplayName.Replace("'", "\\'"))}}',
                    """)}}
                      ] satisfies EnumTypes['{{def.Name}}'][],
                    """)}}
                    }

                    /** 自動生成された列挙体の値（検索条件） */
                    export const EnumValuesForSearchCondition = {
                    {{orderedDefs.SelectTextTemplate(def => $$"""
                      '{{def.Name}}': [
                    {{def.Items.SelectTextTemplate(item => $$"""
                        '{{item.DisplayName.Replace("'", "\\'")}}',
                    """)}}
                      ] satisfies (keyof EnumTypesOfSearchCondition['{{def.Name}}'])[],
                    """)}}
                    }

                    /** 自動生成された列挙体の検索条件用オブジェクトの値 */
                    export type EnumTypesOfSearchCondition = {
                    {{orderedDefs.SelectTextTemplate(def => $$"""
                      '{{def.Name}}': {
                    {{def.Items.SelectTextTemplate(item => $$"""
                        '{{item.DisplayName.Replace("'", "\\'")}}'?: boolean
                    """)}}
                      }
                    """)}}
                    }
                    """,
                });
            });
        }

        private static SourceFile GetOracleGetNameFunction(IReadOnlyList<EnumDefInfo> enumDefs) {
            return new SourceFile {
                FileName = "Enum名取得関数（事業PF公開テーブル用）.sql",
                Contents = $$"""
                    {{enumDefs.SelectTextTemplate(enm => $$"""
                    {{Render(enm)}}
                    /

                    """)}}
                    """,
            };

            static string Render(EnumDefInfo enm) {
                var functionName = $"GET_{enm.Name.ToCSharpSafe()}_NAME";
                const string args = "p_value";

                return $$"""
                    CREATE OR REPLACE FUNCTION {{functionName}}({{args}} IN NVARCHAR2) RETURN NVARCHAR2
                    IS
                    BEGIN
                    {{If(enm.Items.Count == 0, () => $$"""
                        RETURN NULL;
                    """).Else(() => $$"""
                    {{enm.Items.SelectTextTemplate((item, ix) => $$"""
                        {{(ix == 0 ? "IF" : "ELSIF")}} {{args}} = '{{item.Value}}' THEN
                            RETURN N'{{item.DisplayName.Replace("'", "\\'")}}';
                    """)}}
                        ELSE
                            RETURN NULL;
                        END IF;
                    """)}}
                    END;
                    """;
            }
        }
    }
}
