using Nijo.CodeGenerating;
using Nijo.ImmutableSchema;
using Nijo.Util.DotnetEx;
using Nijo.ValueMemberTypes;
using Nijo.SchemaParsing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Xml.Linq;

namespace Nijo.Parts.Common;

/// <summary>
/// 画面の自動生成のためのメタデータ。
/// <see cref="Metadata"/> と役割が相当部分重複している。
///
/// ※ こちらはC#側のモジュールが生成されない。
/// </summary>
internal class MetadataForPage : IMultiAggregateSourceFile {

    private readonly List<AggregateBase> _entries = new();
    private readonly Lock _lock = new();
    internal MetadataForPage Add(AggregateBase aggregate) {
        lock (_lock) {
            _entries.Add(aggregate);
            return this;
        }
    }

    void IMultiAggregateSourceFile.RegisterDependencies(IMultiAggregateSourceFileManager ctx) {
        // 特になし
    }

    void IMultiAggregateSourceFile.Render(CodeRenderingContext ctx) {
        ctx.ReactProject(autoGenerated => {
            autoGenerated.Directory("util", dir => {
                dir.Generate(RenderTypeScript(ctx));
            });
        });
    }

    private SourceFile RenderTypeScript(CodeRenderingContext ctx) {
        var entriesOrderByDataFlow = _entries
            .OrderBy(agg => agg.GetRoot().GetIndexOfDataFlow())
            .Select(aggregate => (ITypeScriptModule)new StructureMetadata(aggregate, isEntry: true));

        return new SourceFile {
            FileName = "metadata-for-page.ts",
            Contents = $$"""

                import { {{CommandQueryMappings.DATA_MODEL_TYPE}}, {{CommandQueryMappings.QUERY_MODEL_TYPE}}, {{CommandQueryMappings.COMMAND_MODEL_TYPE}}, {{CommandQueryMappings.REFERED_QUERY_MODEL_TYPE}} } from ".."
                import * as EnumDefs from "../enum-defs"

                /** 画面の自動生成のためのメタデータ */
                export namespace MetadataForPage {
                  {{WithIndent(StructureMetadata.RenderType(ctx), "  ")}}

                  {{WithIndent(ValueMetadata.RenderType(ctx), "  ")}}

                  {{WithIndent(RefMetadata.RenderType(ctx), "  ")}}

                  /** 画面の自動生成のためのメタデータ取得関数 */
                  export const getAll = (): { [k in ( {{CommandQueryMappings.DATA_MODEL_TYPE}} | {{CommandQueryMappings.QUERY_MODEL_TYPE}} | {{CommandQueryMappings.COMMAND_MODEL_TYPE}})]: {{StructureMetadata.TYPE_NAME}} } => ({
                {{entriesOrderByDataFlow.SelectTextTemplate(entry => $$"""
                    {{WithIndent(entry.Render(ctx), "    ")}}
                """)}}
                  })
                }
                """,
        };
    }

    /// <summary>
    /// 構造体のメタデータ
    /// </summary>
    internal class StructureMetadata : ITypeScriptModule {
        internal StructureMetadata(AggregateBase aggregate, bool isEntry) {
            _aggregate = aggregate;
            _isEntry = isEntry;
        }
        private readonly AggregateBase _aggregate;
        private readonly bool _isEntry;

        string ITypeScriptModule.Render(CodeRenderingContext ctx) {
            var type = _aggregate switch {
                RootAggregate => "RootAggregate",
                ChildAggregate => "ChildAggregate",
                ChildrenAggregate => "ChildrenAggregate",
                _ => throw new NotImplementedException(),
            };

            static ITypeScriptModule GetImpl(IAggregateMember member) {
                return member switch {
                    ValueMember vm => new ValueMetadata(vm),
                    RefToMember rm => new RefMetadata(rm),
                    ChildAggregate child => new StructureMetadata(child, isEntry: false),
                    ChildrenAggregate children => new StructureMetadata(children, isEntry: false),
                    _ => throw new NotImplementedException(),
                };
            }

            var body = $$"""
                {
                  uniqueId: '{{_aggregate.XElement.Attribute(nameof(Ui.XmlElementItem.UniqueId))?.Value.Replace("'", "\\'")}}',
                  type: '{{type}}',
                  model: '{{_aggregate.GetRoot().Model.SchemaName}}',
                {{RenderNodeOptions(_aggregate.XElement, ctx).SelectTextTemplate(source => $$"""
                  {{WithIndent(source, "  ")}}
                """)}}
                  members: {
                {{_aggregate.GetMembers().SelectTextTemplate(m => $$"""
                    {{WithIndent(GetImpl(m).Render(ctx), "    ")}},
                """)}}
                  },
                }
                """;

            if (_isEntry) {
                return $$"""
                    '{{_aggregate.PhysicalName}}': {{body}},
                    """;
            } else {
                return $$"""
                    '{{_aggregate.PhysicalName}}': {{body}}
                    """;
            }
        }

        internal const string TYPE_NAME = "StructureMetadata";
        internal const string TYPE_MEMBER = "StructureMetadataMember";

        internal static string RenderType(CodeRenderingContext ctx) {

            var modelNames = ctx.SchemaParser.Models
                .Select(m => $"'{m.Key}'")
                .ToArray();

            return $$"""
                /** 構造体のメタデータ */
                export type {{TYPE_NAME}} = {
                  /** XMLスキーマ上でこの要素を示す一意なID */
                  uniqueId: string
                  /** 集約の種類 */
                  type: 'RootAggregate' | 'ChildAggregate' | 'ChildrenAggregate'
                  /** この集約のモデル。子孫集約の場合も値が入る。 */
                  model: {{(modelNames.Length == 0 ? "never" : modelNames.Join(" | "))}}
                  /** この構造体のメンバー */
                  members: { [key: string]: {{TYPE_MEMBER}} }
                {{RenderNodeOptionTypes(ctx).SelectTextTemplate(source => $$"""
                  {{WithIndent(source, "  ")}}
                """)}}
                }

                /** 構造体のメタデータのメンバー */
                export type {{TYPE_MEMBER}} = {{TYPE_NAME}} | {{ValueMetadata.TYPE_NAME}} | {{RefMetadata.TYPE_NAME}}
                """;
        }
    }
    /// <summary>
    /// 値のメタデータ
    /// </summary>
    internal class ValueMetadata : ITypeScriptModule {
        internal ValueMetadata(ValueMember vm) {
            _vm = vm;
        }
        private readonly ValueMember _vm;

        string ITypeScriptModule.Render(CodeRenderingContext ctx) {

            // 型は enum, value-object の場合はそれぞれ別の名前のプロパティで定義
            var typeProp = _vm.Type switch {
                StaticEnumMember => "enumType",
                ValueObjectMember => "valueObjectType",
                _ => "type",
            };

            return $$"""
                '{{_vm.PhysicalName}}': {
                  uniqueId: '{{_vm.XElement.Attribute(nameof(Ui.XmlElementItem.UniqueId))?.Value.Replace("'", "\\'")}}',
                  {{typeProp}}: '{{_vm.Type.SchemaTypeName}}',
                {{RenderNodeOptions(_vm.XElement, ctx).SelectTextTemplate(source => $$"""
                  {{WithIndent(source, "  ")}}
                """)}}
                }
                """;
        }

        internal const string TYPE_NAME = "ValueMetadata";

        internal static string RenderType(CodeRenderingContext ctx) {
            var characterTypes = ctx.GetCharacterTypes().ToArray();
            var charTypeLiteral = characterTypes.Length == 0
                ? "never"
                : characterTypes.Select(type => $"'{type.Replace("'", "\\'")}'").Join(" | ");

            var valueObjectTypes = ctx.SchemaParser.GetValueObjectMembers().Values.ToArray();
            var valueObjectLiteral = valueObjectTypes.Length == 0
                ? "never"
                : valueObjectTypes.Select(type => $"'{type.TypePhysicalName}'").Join(" | ");

            return $$"""
                /** 値のメタデータ */
                export type {{TYPE_NAME}} = {
                  /** XMLスキーマ上でこの要素を示す一意なID */
                  uniqueId: string
                  /** 値の型名。このメンバーが enum または value-ojbect の場合は undefined になる */
                  type?: {{ctx.SchemaParser.ValueMemberTypes.Select(t => $"'{t.SchemaTypeName}'").Join(" | ")}}
                  /** 列挙体の型名。このメンバーが列挙体の場合のみ */
                  enumType?: keyof EnumDefs.{{EnumFile.TS_TYPE_MAP}}
                  /** 値オブジェクトの型名。このメンバーが値オブジェクトの場合のみ */
                  valueObjectType?: {{valueObjectLiteral}}
                {{RenderNodeOptionTypes(ctx).SelectTextTemplate(source => $$"""
                  {{WithIndent(source, "  ")}}
                """)}}
                }
                """;
        }
    }
    /// <summary>
    /// 外部参照のメタデータ
    /// </summary>
    internal class RefMetadata : ITypeScriptModule {
        internal RefMetadata(RefToMember refTo) {
            _refTo = refTo;
        }
        private readonly RefToMember _refTo;

        string ITypeScriptModule.Render(CodeRenderingContext ctx) {

            return $$"""
                '{{_refTo.PhysicalName}}': {
                  uniqueId: '{{_refTo.XElement.Attribute(nameof(Ui.XmlElementItem.UniqueId))?.Value.Replace("'", "\\'")}}',
                  type: 'ref-to',
                  refTo: '{{_refTo.RefTo.RefEntryName}}',
                {{RenderNodeOptions(_refTo.XElement, ctx).SelectTextTemplate(source => $$"""
                  {{WithIndent(source, "  ")}}
                """)}}
                }
                """;
        }

        internal const string TYPE_NAME = "RefMetadata";

        internal static string RenderType(CodeRenderingContext ctx) {
            return $$"""
                /** 外部参照のメタデータ */
                export type {{TYPE_NAME}} = {
                  /** XMLスキーマ上でこの要素を示す一意なID */
                  uniqueId: string
                  /** 型 */
                  type: 'ref-to'
                  /** 参照先。参照先が子孫集約の場合はルート集約からのパスのスラッシュ区切り */
                  refTo: {{CommandQueryMappings.REFERED_QUERY_MODEL_TYPE}}
                {{RenderNodeOptionTypes(ctx).SelectTextTemplate(source => $$"""
                  {{WithIndent(source, "  ")}}
                """)}}
                }
                """;
        }
    }


    /// <summary>
    /// TypeScriptの構造体
    /// </summary>
    internal interface ITypeScriptModule {
        string Render(CodeRenderingContext ctx);
    }


    #region オプション項目の動的レンダリング
    /// <summary>
    /// XElementで定義されたNodeOptionをTypeScriptのオブジェクトプロパティとしてレンダリングします。
    /// </summary>
    /// <param name="xElement">XML要素</param>
    /// <param name="ctx">レンダリングコンテキスト</param>
    /// <returns>TypeScriptのプロパティ定義文字列</returns>
    internal static IEnumerable<string> RenderNodeOptions(XElement xElement, CodeRenderingContext ctx) {

        var options = ctx.SchemaParser.GetOptions(xElement);

        // DisplayName だけは未定義の場合は物理名を採用する。
        // メタデータを用いたカスタマイズ処理でDisplayNameの使用頻度が高いため。
        if (!options.Any(o => o.AttributeName == BasicNodeOptions.DisplayName.AttributeName)) {
            yield return $$"""
                {{BasicNodeOptions.DisplayName.AttributeName.ToCamelCase()}}: '{{ctx.SchemaParser.GetPhysicalName(xElement)}}',
                """;
        }

        // コメントがある場合はレンダリング
        var comment = ctx.SchemaParser.GetComment(xElement, E_CsTs.TypeScript);
        if (!string.IsNullOrWhiteSpace(comment)) {
            yield return $$"""
                comment: '{{comment.Replace("'", "\\'")}}',
                """;
        }

        foreach (var option in options) {
            var attributeValue = xElement.Attribute(option.AttributeName)?.Value;

            // フィルタリング: 空文字の文字列をスキップ
            if (option.Type == E_NodeOptionType.String && string.IsNullOrWhiteSpace(attributeValue)) {
                continue;
            }

            // TypeScriptプロパティ名を生成（camelCaseに変換）
            var propName = option.AttributeName.ToCamelCase();

            // TypeScriptの値をレンダリング
            var tsValue = option.Type == E_NodeOptionType.Boolean
                ? "true"
                : $"'{attributeValue?.Replace("'", "\\'")}'";

            yield return $$"""
                {{propName}}: {{tsValue}},
                """;
        }
    }

    /// <summary>
    /// TypeScript型定義で使用するNodeOptionの型情報を動的に生成します
    /// </summary>
    internal static IEnumerable<string> RenderNodeOptionTypes(CodeRenderingContext ctx) {
        var nodeOptions = ctx.SchemaParser.GetAllNodeOptions();

        // コメントはXMLの属性ではないので別途宣言している
        yield return $$"""
            /** XMLコメント */
            comment?: string
            """;

        foreach (var option in nodeOptions) {

            // CharacterTypeの場合は特別な型を生成
            string tsType;
            if (option.AttributeName == BasicNodeOptions.CharacterType.AttributeName) {
                var characterTypes = ctx.GetCharacterTypes().ToArray();
                tsType = characterTypes.Length == 0
                    ? "never"
                    : characterTypes.Select(type => $"'{type.Replace("'", "\\'")}'").Join(" | ");
            } else {
                tsType = option.Type == E_NodeOptionType.Boolean ? "boolean" : "string";
            }

            // DisplayName だけは必ずレンダリングされる
            var isOptional = option.AttributeName != BasicNodeOptions.DisplayName.AttributeName;

            yield return $$"""
                /** {{option.DisplayName}} */
                {{option.AttributeName.ToCamelCase()}}{{(isOptional ? "?" : "")}}: {{tsType}}
                """;
        }
    }


    #endregion オプション項目の動的レンダリング
}
