// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApp;

#nullable disable

namespace MyApp.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250923002832_00001_Init2")]
    partial class _00001_Init2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("MyApp.アカウントDbEntity", b =>
                {
                    b.Property<string>("アカウントID")
                        .HasColumnType("TEXT")
                        .HasColumnName("アカウントID")
                        .HasColumnOrder(0);

                    b.Property<string>("CreateUser")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreateUser")
                        .HasColumnOrder(3);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt")
                        .HasColumnOrder(2);

                    b.Property<string>("UpdateUser")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdateUser")
                        .HasColumnOrder(5);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedAt")
                        .HasColumnOrder(4);

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Version")
                        .HasColumnOrder(6);

                    b.Property<string>("アカウント名")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("アカウント名")
                        .HasColumnOrder(1);

                    b.HasKey("アカウントID")
                        .HasName("PK_アカウント");

                    b.ToTable("アカウント", (string)null);
                });

            modelBuilder.Entity("MyApp.チャンネルDbEntity", b =>
                {
                    b.Property<string>("チャンネルID")
                        .HasColumnType("TEXT")
                        .HasColumnName("チャンネルID")
                        .HasColumnOrder(0);

                    b.Property<string>("CreateUser")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreateUser")
                        .HasColumnOrder(3);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt")
                        .HasColumnOrder(2);

                    b.Property<string>("UpdateUser")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdateUser")
                        .HasColumnOrder(5);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedAt")
                        .HasColumnOrder(4);

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Version")
                        .HasColumnOrder(6);

                    b.Property<string>("チャンネル名")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("チャンネル名")
                        .HasColumnOrder(1);

                    b.HasKey("チャンネルID")
                        .HasName("PK_チャンネル");

                    b.ToTable("チャンネル", (string)null);
                });

            modelBuilder.Entity("MyApp.メッセージDbEntity", b =>
                {
                    b.Property<int>("メッセージSEQ")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("メッセージSEQ")
                        .HasColumnOrder(0)
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<string>("CreateUser")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreateUser")
                        .HasColumnOrder(8);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt")
                        .HasColumnOrder(7);

                    b.Property<string>("UpdateUser")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdateUser")
                        .HasColumnOrder(10);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedAt")
                        .HasColumnOrder(9);

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Version")
                        .HasColumnOrder(11);

                    b.Property<string>("チャンネル_チャンネルID")
                        .HasColumnType("TEXT")
                        .HasColumnName("チャンネル_チャンネルID")
                        .HasColumnOrder(3);

                    b.Property<bool?>("チャンネル直下か")
                        .HasColumnType("INTEGER")
                        .HasColumnName("チャンネル直下か")
                        .HasColumnOrder(4);

                    b.Property<string>("本文")
                        .HasColumnType("TEXT")
                        .HasColumnName("本文")
                        .HasColumnOrder(1);

                    b.Property<bool?>("編集済みか")
                        .HasColumnType("INTEGER")
                        .HasColumnName("編集済みか")
                        .HasColumnOrder(6);

                    b.Property<string>("記載者_アカウントID")
                        .HasColumnType("TEXT")
                        .HasColumnName("記載者_アカウントID")
                        .HasColumnOrder(2);

                    b.Property<string>("返信先メッセージSEQ")
                        .HasColumnType("TEXT")
                        .HasColumnName("返信先メッセージSEQ")
                        .HasColumnOrder(5);

                    b.HasKey("メッセージSEQ")
                        .HasName("PK_メッセージ");

                    b.HasIndex("チャンネル_チャンネルID");

                    b.HasIndex("記載者_アカウントID");

                    b.ToTable("メッセージ", (string)null);
                });

            modelBuilder.Entity("MyApp.メッセージDbEntity", b =>
                {
                    b.HasOne("MyApp.チャンネルDbEntity", "チャンネル")
                        .WithMany("RefFromメッセージ_チャンネル")
                        .HasForeignKey("チャンネル_チャンネルID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_チャンネル_メッセージ_XCC521C9");

                    b.HasOne("MyApp.アカウントDbEntity", "記載者")
                        .WithMany("RefFromメッセージ_記載者")
                        .HasForeignKey("記載者_アカウントID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_アカウント_メッセージ_XA91C946");

                    b.Navigation("チャンネル");

                    b.Navigation("記載者");
                });

            modelBuilder.Entity("MyApp.アカウントDbEntity", b =>
                {
                    b.Navigation("RefFromメッセージ_記載者");
                });

            modelBuilder.Entity("MyApp.チャンネルDbEntity", b =>
                {
                    b.Navigation("RefFromメッセージ_チャンネル");
                });
#pragma warning restore 612, 618
        }
    }
}
