import * as React from "react"
import * as ReactHookForm from "react-hook-form"
import * as Layout from "../layout"
import FormLayout from "../layout/FormLayout"
import * as Input from "../input"
import * as AutoGenerated from "../__autoGenerated"
import * as EnumDefs from "../__autoGenerated/enum-defs"
import { MetadataForPage } from "../__autoGenerated/util/metadata-for-page"
import { MetadataSchema } from "./getSchema"
import { ReflectionFormContext } from "./Parts.FormContext"
import { ReflectionGridInSingleView } from "./Parts.Grid"
import { RefTo, RefToSearchCondition } from "./Parts.SearchDialog"
/**
 * 構造体のメタデータを受け取って FormLayout のルートを構築して返すコンポーネント
 */
export const ReflectionForm = ({ mode, metadataPhysicalName, metadata, schema, formMethods }: {
  mode: ReflectionFormContext["mode"]
  metadataPhysicalName: string
  metadata: MetadataForPage.StructureMetadata
  schema: MetadataSchema
  formMethods: ReactHookForm.UseFormReturn<ReactHookForm.FieldValues>
}) => {
  const formContextValue = React.useMemo<ReflectionFormContext>(() => ({
    rootAggregate: metadataPhysicalName as AutoGenerated.QueryModelType,
    mode,
    schema,
    formMethods,
  }), [mode, schema, formMethods, metadataPhysicalName])

  return (
    <ReflectionFormContext.Provider value={formContextValue}>
      <FormLayout.Root
        valueWidthPx={mode === "search-condition"
          ? 340 // 日付の範囲検索ぐらいの幅
          : 240}
      >
        <MemberComponentsGroupedByBreakPoint owner={metadata} ancestorsPath="" />
      </FormLayout.Root>
    </ReflectionFormContext.Provider>
  )
}

/** FormLayoutのラベルと値の組を折り返しの単位でグルーピングしたもの */
const MemberComponentsGroupedByBreakPoint = ({ owner, ancestorsPath }: {
  ancestorsPath: string
  owner: MetadataForPage.StructureMetadata
}) => {

  // メンバーを折り返しの単位でグルーピングする
  type MemberGroup = FullWidthMember | NonFullWidthMember
  type FullWidthMember = { fullWidth: true, physicalName: string, member: MetadataForPage.StructureMetadataMember }
  type NonFullWidthMember = {
    fullWidth: false
    firstColumn: { physicalName: string, member: MetadataForPage.StructureMetadataMember }[]
    secondColumn: { physicalName: string, member: MetadataForPage.StructureMetadataMember }[]
  }

  const groups = React.useMemo(() => {
    const members = Object.entries(owner.members).map(([key, member]) => ({ physicalName: key, member }))
    const grouped = members.reduce((acc, member) => {
      // Child, Children は横幅いっぱいとる
      if (member.member.type === "ChildAggregate" || member.member.type === "ChildrenAggregate") {
        acc.push({ fullWidth: true, physicalName: member.physicalName, member: member.member })
        return acc
      }

      // それ以外はグルーピングする
      const lastGroup = acc[acc.length - 1]
      if (lastGroup === undefined || lastGroup.fullWidth) {
        acc.push({ fullWidth: false, firstColumn: [{ physicalName: member.physicalName, member: member.member }], secondColumn: [] })
      } else {
        lastGroup.firstColumn.push({ physicalName: member.physicalName, member: member.member })
      }
      return acc
    }, [] as MemberGroup[])

    // 折り返しが発生するグループについて、要素数の半分でfirstColumnとsecondColumnに分割する
    for (const group of grouped) {
      if (group.fullWidth) continue
      const half = Math.ceil(group.firstColumn.length / 2)
      const arr = [...group.firstColumn, ...group.secondColumn]
      group.firstColumn = arr.slice(0, half)
      group.secondColumn = arr.slice(half)
    }

    return grouped
  }, [owner])

  return (
    <>
      {groups.map((group, index) => (
        <React.Fragment key={index}>

          {index > 0 && (
            <FormLayout.Separator />
          )}

          {group.fullWidth ? (
            // 横幅いっぱいとるグループ
            <MemberComponent
              ancestorsPath={ancestorsPath}
              memberName={group.physicalName}
              member={group.member}
            />
          ) : (
            // 折り返しが発生するグループ
            <FormLayout.ResponsiveColumnGroup>
              {/* 左列 */}
              <FormLayout.ResponsiveColumn>
                {group.firstColumn.map((member) => (
                  <MemberComponent
                    key={member.physicalName}
                    ancestorsPath={ancestorsPath}
                    memberName={member.physicalName}
                    member={member.member}
                  />
                ))}
              </FormLayout.ResponsiveColumn>

              {/* 右列 */}
              {group.secondColumn.length > 0 && (
                <FormLayout.ResponsiveColumn>
                  {group.secondColumn.map((member) => (
                    <MemberComponent
                      key={member.physicalName}
                      ancestorsPath={ancestorsPath}
                      memberName={member.physicalName}
                      member={member.member}
                    />
                  ))}
                </FormLayout.ResponsiveColumn>
              )}
            </FormLayout.ResponsiveColumnGroup>
          )}
        </React.Fragment>
      ))}
    </>
  )
}

/** FormLayoutのラベルと値の組 */
const MemberComponent = ({ memberName, member, ancestorsPath }: {
  /** 祖先のパス。XML上の物理名をピリオドで繋いだもの */
  ancestorsPath: string
  /** メンバーの物理名 */
  memberName: string
  /** メンバー */
  member: MetadataForPage.StructureMetadataMember
}): React.ReactNode => {

  const {
    mode,
    formMethods: { control },
  } = React.useContext(ReflectionFormContext)

  // Root
  if (member.type === "RootAggregate") {
    return undefined // Rootはトップで処理済み。この分岐には来ない
  }

  // Child
  if (member.type === "ChildAggregate") {
    return (
      <FormLayout.Item fullWidth label={member.displayName}>
        <MemberComponentsGroupedByBreakPoint
          ancestorsPath={ancestorsPath ? `${ancestorsPath}.${memberName}` : memberName}
          owner={member}
        />
      </FormLayout.Item>
    )
  }

  // Children
  if (member.type === "ChildrenAggregate") {
    // このメンバーの子孫（直下の子ではなく子孫再帰的に）にさらにChildrenが含まれるならばフォームのリスト。
    // 子孫にChildrenがいないならばグリッドで表示する。
    let hasChildren = false
    const checkRecursive = (childMembers: MetadataForPage.StructureMetadataMember[]) => {
      for (const childMember of childMembers) {
        if (childMember.type === "ChildrenAggregate") {
          hasChildren = true
          return
        }
        if (childMember.type === "ChildAggregate") {
          checkRecursive(Object.values(childMember.members))
        }
      }
    }
    checkRecursive(Object.values(member.members))

    // 子孫にChildrenがいるならばフォームのリスト
    if (hasChildren || mode === "search-condition") {
      return (
        <FormLayout.Item fullWidth label={member.displayName}>
          <MemberComponentsGroupedByBreakPoint
            ancestorsPath={ancestorsPath ? `${ancestorsPath}.${memberName}` : memberName}
            owner={member}
          />
        </FormLayout.Item>
      )
    }

    // 子孫にChildrenがいないのでグリッドで表示する
    return (
      <ReflectionGridInSingleView
        ancestorsPath={ancestorsPath}
        ownerPhysicalName={memberName}
        owner={member}
        className="border border-gray-300"
      />
    )
  }

  // SingleViewの場合、DisplayDataの値メンバーはvaluesという名前のオブジェクトの中にある
  const valuesMemberPath = mode === "single-view"
    ? `${ancestorsPath}.values.${memberName}`
    : `${ancestorsPath}.${memberName}`

  // 外部参照
  if (member.type === "ref-to") {
    return (
      <FormLayout.Item
        label={member.displayName}
        labelEnd={member.required && mode === "single-view" && (
          <Layout.RequiredChip />
        )}
      >
        {mode === "single-view" ? (
          <RefTo
            valuesMemberPath={valuesMemberPath}
            metadata={member}
            control={control}
          />
        ) : (
          <RefToSearchCondition
            valuesMemberPath={valuesMemberPath}
            metadata={member}
            control={control}
          />
        )}
      </FormLayout.Item>
    )
  }

  // 一般ValueMember
  if (member.type !== undefined) {

    // 単語
    if (member.type === "word") {
      return (
        <FormLayout.Item
          label={member.displayName}
          labelEnd={member.required && mode === "single-view" && (
            <Layout.RequiredChip />
          )}
        >
          <Input.Word
            control={control}
            name={valuesMemberPath}
          />
        </FormLayout.Item>
      )
    }

    // 文章
    if (member.type === "description") {
      return mode === "single-view" ? (
        <FormLayout.Item
          label={member.displayName}
          labelEnd={member.required && mode === "single-view" && (
            <Layout.RequiredChip />
          )}
        >
          <Input.Description
            control={control}
            name={valuesMemberPath}
          />
        </FormLayout.Item>
      ) : (
        // 部分一致検索なので、入力欄はWord型と同じ
        <FormLayout.Item label={member.displayName}>
          <Input.Word
            control={control}
            name={valuesMemberPath}
          />
        </FormLayout.Item>
      )
    }

    // 数値
    if (member.type === "int" || member.type === "decimal") {
      return mode === "single-view" ? (
        <FormLayout.Item
          label={member.displayName}
          labelEnd={member.required && (
            <Layout.RequiredChip />
          )}
        >
          <Input.NumberInput
            control={control}
            name={valuesMemberPath}
          />
        </FormLayout.Item>
      ) : (
        // 範囲検索
        <FormLayout.Item label={member.displayName}>
          <div className="flex flex-wrap items-center gap-1">
            <Input.NumberInput
              control={control}
              name={`${valuesMemberPath}.from`}
              className="max-w-24"
            />
            ～
            <Input.NumberInput
              control={control}
              name={`${valuesMemberPath}.to`}
              className="max-w-24"
            />
          </div>
        </FormLayout.Item>
      )
    }

    // 年月、日付、日付時刻
    if (member.type === "yearmonth" || member.type === "date" || member.type === "datetime") {
      return mode === "single-view" ? (
        <FormLayout.Item
          label={member.displayName}
          labelEnd={member.required && (
            <Layout.RequiredChip />
          )}
        >
          <Input.DateInput
            control={control}
            name={valuesMemberPath}
            yearMonth={member.type === "yearmonth"}
          />
        </FormLayout.Item>
      ) : (
        // 範囲検索
        <FormLayout.Item label={member.displayName}>
          <div className="flex flex-wrap items-center gap-1">
            <Input.DateInput
              control={control}
              name={`${valuesMemberPath}.from`}
              yearMonth={member.type === "yearmonth"}
              className="max-w-40"
            />
            ～
            <Input.DateInput
              control={control}
              name={`${valuesMemberPath}.to`}
              yearMonth={member.type === "yearmonth"}
              className="max-w-40"
            />
          </div>
        </FormLayout.Item>
      )
    }

    // チェックボックス
    if (member.type === "bool") {
      return mode === "single-view" ? (
        <FormLayout.Item
          label={member.displayName}
          labelEnd={member.required && (
            <Layout.RequiredChip />
          )}
        >
          <Input.CheckBox
            control={control}
            name={valuesMemberPath}
          />
        </FormLayout.Item>
      ) : (
        // 検索条件
        <FormLayout.Item label={member.displayName}>
          <div className="flex flex-wrap gap-x-2 gap-y-1">
            <Input.CheckBox
              control={control}
              name={`${valuesMemberPath}.trueのみ`}
            >
              Trueのみ
            </Input.CheckBox>
            <Input.CheckBox
              control={control}
              name={`${valuesMemberPath}.falseのみ`}
            >
              Falseのみ
            </Input.CheckBox>
          </div>
        </FormLayout.Item>
      )
    }

    return (
      <FormLayout.Item label={member.displayName}>
        TODO
      </FormLayout.Item>
    )
  }

  // 列挙型
  if (member.enumType !== undefined) {
    const enumValues = EnumDefs.EnumValueMap[member.enumType]()

    return mode === "single-view" ? (
      <FormLayout.Item
        label={member.displayName}
        labelEnd={member.required && (
          <Layout.RequiredChip />
        )}
      >
        <Input.EnumSelect
          type={member.enumType}
          control={control}
          name={valuesMemberPath}
        />
      </FormLayout.Item>
    ) : (
      // 検索条件
      <FormLayout.Item label={member.displayName}>
        <div className="flex flex-wrap gap-x-2 gap-y-1">
          {enumValues.map((value) => (
            <Input.CheckBox
              key={value}
              control={control}
              name={`${valuesMemberPath}.${value}`}
            >
              {value}
            </Input.CheckBox>
          ))}
        </div>
      </FormLayout.Item>
    )
  }

  // 値オブジェクト（UIは単語型のそれに倣う）
  if (member.valueObjectType !== undefined) {
    return (
      <FormLayout.Item
        label={member.displayName}
        labelEnd={member.required && mode === "single-view" && (
          <Layout.RequiredChip />
        )}
      >
        <Input.Word
          control={control}
          name={valuesMemberPath}
        />
      </FormLayout.Item>
    )
  }
}
