import React, { useEffect, useState } from "react"
import { useForm } from "react-hook-form"
import { callComplexPostEndpointAsync } from "../example/callComplexPostEndpointAsync"
import { WordTextBox } from "../input/WordTextBox"
import { Button } from "../input/Button"
import { FormLabel } from "../layout/FormLabel"
import { PageTitle } from "../layout/PageTitle"
import { ログインParameterDisplayData } from "../__autoGenerated/ログインParameter"
import { ログインユーザー情報, createNewログインユーザー情報 } from "../__autoGenerated/ログインユーザー情報"
import デバッグメニュー from "../debug-rooms/デバッグメニュー"
import * as DetailMessage from "../util/DetailMessageContext"

const SESSION_STORAGE_KEY = "nijo-login-user"

/**
 * ログイン画面。
 * ログインしていない状態の場合はこのコンポーネント自身が定義するUIを表示。
 * ログインしている状態の場合は、props.childrenで指定されたアプリケーション本体の画面を表示する。
 *
 * ログイン状態は sessionStorage を使ってブラウザの複数タブ間で共有する。
 */
export function P001_ログイン(props: {
  /**
   * ログイン後画面。
   * ログインしていない状態では表示されない。
   */
  children: React.ReactNode
}) {
  const [loginUser, setLoginUser] = useState<ログインユーザー情報 | null>(() => {
    const json = sessionStorage.getItem(SESSION_STORAGE_KEY)
    return json ? JSON.parse(json) : null
  })

  // 他のタブでのログイン状態変更を検知
  useEffect(() => {
    const handler = (e: StorageEvent) => {
      if (e.key === SESSION_STORAGE_KEY) {
        if (e.newValue) {
          setLoginUser(JSON.parse(e.newValue))
        } else {
          setLoginUser(null)
        }
      }
    }
    window.addEventListener("storage", handler)
    return () => window.removeEventListener("storage", handler)
  }, [])

  const { register, handleSubmit, control } = useForm<ログインParameterDisplayData>()
  const { replaceMessages } = DetailMessage.useSetter()

  const onSubmit = async (data: ログインParameterDisplayData) => {
    const result = await callComplexPostEndpointAsync('ログイン', data)

    if (result.type === 'ok') {
      const user: ログインユーザー情報 = {
        ...createNewログインユーザー情報(),
        ...result.returnValue.values,
      }
      sessionStorage.setItem(SESSION_STORAGE_KEY, JSON.stringify(user))
      setLoginUser(user)
    } else if (result.type === 'error') {
      replaceMessages(result.detail)
    } else if (result.type === 'unknown') {
      alert(result.message)
    }
  }

  // ログインしていない場合はログイン画面を表示
  if (!loginUser) return (
    <div className="min-h-screen flex items-center justify-center bg-gray-100">
      <div className="bg-white p-8 rounded shadow-md w-full max-w-md">
        <div className="mb-6">
          <PageTitle>ログイン</PageTitle>
          <DetailMessage.Rest />
        </div>
        <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
          <div>
            <FormLabel>従業員番号</FormLabel>
            <WordTextBox {...register("values.従業員番号")} className="w-full" />
            <DetailMessage.Of name="values.従業員番号" control={control} />
          </div>
          <div>
            <FormLabel>パスワード</FormLabel>
            <WordTextBox {...register("values.パスワード")} type="password" className="w-full" />
            <DetailMessage.Of name="values.パスワード" control={control} />
          </div>
          <div className="pt-4">
            <Button submit fill className="w-full justify-center">ログイン</Button>
          </div>
        </form>
      </div>

      {import.meta.env.DEV && (
        <div className="fixed top-0 left-0 m-2">
          <デバッグメニュー />
        </div>
      )}

    </div>
  )

  // ログインしている場合は、子コンポーネントを表示
  return <>{props.children}</>
}
