import React from "react"
import * as ReactRouter from "react-router"
import { useNavigate } from "react-router-dom"
import { useForm } from "react-hook-form"
import { SearchPageBase } from "../layout/SearchPageBase"
import { FormLabel } from "../layout/FormLabel"
import { DataTableColumn } from "../layout/DataTable"
import { NumericTextBox } from "../input/NumericTextBox"
import { WordTextBox } from "../input/WordTextBox"
import { 売上一覧SearchCondition, createNew売上一覧SearchCondition, 売上一覧DisplayData } from "../__autoGenerated/売上一覧"
import * as UI from "../input/Field"
import useEvent from "react-use-event-hook"

export const URL = "/uriage"

/**
 * P100_売上 へ遷移するためのフック
 */
export function useNavigateToP100売上() {
  const navigate = useNavigate()
  return React.useCallback(() => {
    navigate(URL)
  }, [navigate])
}

/**
 * ルーティング定義
 */
export default {
  path: URL,
  element: <P100_売上 />,
  loader: undefined,
} satisfies ReactRouter.RouteObject

/**
 * P100 売上
 */
function P100_売上() {
  const { register, handleSubmit, reset, control } = useForm<売上一覧SearchCondition>({
    defaultValues: createNew売上一覧SearchCondition(),
  })

  // 検索結果のカラム定義
  const columns: DataTableColumn<売上一覧DisplayData>[] = React.useMemo(() => [
    { header: "売上SEQ", render: row => row.values.売上SEQ, widthPx: 100 },
    { header: "売上日時", render: row => row.values.売上日時, widthPx: 200 },
    { header: "担当者", render: row => `${row.values.担当者.従業員番号 ?? ''} ${row.values.担当者.氏名 ?? ''}` },
    { header: "備考", render: row => row.values.備考 },
    { header: "売上総額(税込)", render: row => row.values.売上総額_税込?.toLocaleString(), widthPx: 120, className: "text-right" },
    { header: "売上数量合計", render: row => row.values.売上数量合計?.toLocaleString(), widthPx: 120, className: "text-right" },
  ], [])

  const handleClear = useEvent(() => {
    reset(createNew売上一覧SearchCondition())
  })

  return (
    <SearchPageBase
      queryModelType="売上一覧"
      pageTitle="売上"
      searchConditionDefaultSize={160}
      onClear={handleClear}
      onSubmit={handleSubmit}
      searchCondition={(
        <div className="h-full py-1 flex flex-col lg:flex-row lg:items-start gap-x-8 gap-y-2">

          {/* 左列 */}
          <div className="grid grid-cols-[112px_360px] gap-2">

            <FormLabel className="text-right">売上SEQ</FormLabel>
            <UI.Field name="filter.売上SEQ" control={control} />

            <FormLabel className="text-right">売上日時</FormLabel>
            <UI.Field name="filter.売上日時" type="date" control={control} />

            <FormLabel className="text-right">担当者</FormLabel>
            <div className="flex gap-2">
              <WordTextBox {...register("filter.担当者.従業員番号")} placeholder="従業員番号" className="w-1/3" />
              <WordTextBox {...register("filter.担当者.氏名")} placeholder="氏名" className="flex-1" />
            </div>
          </div>

          {/* 右列 */}
          <div className="grid grid-cols-[112px_360px] gap-2">

            <FormLabel className="text-right">備考</FormLabel>
            <UI.Field name="filter.備考" control={control} />

            <FormLabel className="text-right">売上総額(税込)</FormLabel>
            <UI.Field name="filter.売上総額_税込" type="numeric" control={control} />

            <FormLabel className="text-right">売上数量合計</FormLabel>
            <UI.Field name="filter.売上数量合計" type="numeric" control={control} />
          </div>
        </div>
      )}
      searchResultColumns={columns}
    />
  )
}
