import * as ReactRouter from "react-router-dom"
import { Link } from "react-router-dom"
import { FieldColumn, FieldGroup, ReadOnlyColumn, SearchPageBase, useSearchConditionForm, type SortComboItem } from "../ui"
import { callComplexPostEndpointAsync } from "../example/callComplexPostEndpointAsync"
import * as 売上一覧 from "../__autoGenerated/models/売上一覧"
import { getLinkUrlToP101売上詳細 } from "./P101_売上詳細"

export const URL = "/uriage"

/**
 * ルーティング定義
 */
export default {
  path: URL,
  element: <P100_売上 />,
} satisfies ReactRouter.RouteObject

/**
 * P100 売上
 */
function P100_売上() {

  // 検索条件のフォーム
  const form = useSearchConditionForm(売上一覧)
  const { Input, FieldLabel } = form

  return (
    <SearchPageBase
      form={form}
      pageTitle="売上"
      searchConditionDefaultSize={160}
      sortOptions={SORT_OPTIONS}
      createInitialCondition={createInitialCondition}
      search={(condition, signal) => callComplexPostEndpointAsync('売上一覧', condition, { ignoreConfirm: true, signal })}
      header={(
        <Link to={getLinkUrlToP101売上詳細()} className="text-teal-600 underline">
          新規登録
        </Link>
      )}
      searchCondition={(
        <FieldGroup labelWidth="7rem">
          {/* 売上の識別と担当 */}
          <FieldColumn>
            <FieldLabel name="売上SEQ">
              <Input.NumericTextBox name="売上SEQ" />
            </FieldLabel>
            <FieldLabel name="売上日時">
              <Input.DateInput name="売上日時" />
            </FieldLabel>
            <FieldLabel name="担当者">
              <Input.RefTo name="担当者" />
            </FieldLabel>
          </FieldColumn>

          {/* 内容と金額 */}
          <FieldColumn>
            <FieldLabel name="備考">
              <Input.TextArea name="備考" />
            </FieldLabel>
            <FieldLabel name="合計金額">
              <Input.NumericTextBox name="合計金額" />
            </FieldLabel>
            <FieldLabel name="売上数量合計">
              <Input.NumericTextBox name="売上数量合計" />
            </FieldLabel>
          </FieldColumn>
        </FieldGroup>
      )}
      defineSearchResultColumns={[() => [
        ReadOnlyColumn.interactive<売上一覧.DisplayData>('', row => (
          <Link
            className="text-sky-600 underline"
            to={getLinkUrlToP101売上詳細(row.売上SEQ)}>
            詳細
          </Link>
        ), { columnId: '詳細リンク', defaultWidth: 60, disableResizing: true, isFixed: true }),
        ReadOnlyColumn.text<売上一覧.DisplayData>('売上SEQ', row => row.売上SEQ, { columnId: '売上SEQ' }),
        ReadOnlyColumn.text<売上一覧.DisplayData>('売上日時', row => row.売上日時, { columnId: '売上日時' }),
        ReadOnlyColumn.text<売上一覧.DisplayData>('担当者', row => row.担当者.従業員番号, { columnId: '担当者.従業員番号', defaultWidth: 96 }),
        ReadOnlyColumn.text<売上一覧.DisplayData>('', row => row.担当者.氏名, { columnId: '担当者.氏名', defaultWidth: 144 }),
        ReadOnlyColumn.numeric<売上一覧.DisplayData>('売上総額(税込)', row => row.合計金額, { columnId: '合計金額', defaultWidth: 136, suffix: '円' }),
        ReadOnlyColumn.numeric<売上一覧.DisplayData>('売上数量合計', row => row.売上数量合計, { columnId: '売上数量合計', defaultWidth: 120, suffix: '個' }),
        ReadOnlyColumn.text<売上一覧.DisplayData>('備考', row => row.備考, { columnId: '備考', defaultWidth: 300 }),
      ], []]}
    />
  )
}

/** 並び順の選択肢 */
const SORT_OPTIONS: SortComboItem<売上一覧.SortableMember>[] = [
  { key: '売上一覧.売上SEQ', label: '売上SEQ' },
  { key: '売上一覧.売上日時', label: '売上日時' },
  { key: '売上一覧.担当者.従業員Ref.従業員番号', label: '担当者' },
  { key: '売上一覧.担当者.従業員Ref.氏名', label: '担当者氏名' },
  { key: '売上一覧.備考', label: '備考' },
  // SQLite はdecimalのソートができない
  // { key: '売上一覧.売上総額_税込', label: '売上総額(税込)' },
  { key: '売上一覧.売上数量合計', label: '売上数量合計' },
]

/** 画面を開いたときとクリアしたときの検索条件。新しい売上から順に表示する */
function createInitialCondition(): 売上一覧.SearchCondition {
  return {
    ...売上一覧.createNewSearchCondition(),
    sort: ['売上一覧.売上日時（降順）'],
  }
}
