import React from "react"
import * as RHF from "react-hook-form"
import * as ReactRouter from "react-router-dom"
import useEvent from "react-use-event-hook"
import { EditableGrid } from "@halllky/editable-grid"
import dayjs from "dayjs"
import { UUID } from "uuidjs"
import { Button, FieldColumn, FieldGroup, PageBase, ReadOnlyColumn, useDisplayDataForm } from "../ui"
import { callComplexPostEndpointAsync } from "../example/callComplexPostEndpointAsync"
import { toWillBeChangedApplied } from "../example/toWillBeChangedApplied"
import * as 売上詳細 from "../__autoGenerated/models/売上詳細"
import * as 売上詳細画面初期表示Parameter from "../__autoGenerated/models/売上詳細画面初期表示Parameter"

/**
 * P101_売上詳細 へ遷移するためのリンクURLを取得する関数
 */
export function getLinkUrlToP101売上詳細(売上SEQ?: string | null) {
  if (売上SEQ) {
    return `/uriage/edit/${売上SEQ}`
  } else {
    return `/uriage/new`
  }
}

/**
 * ルーティング定義
 */
export default [
  {
    path: "/uriage/new",
    element: <P101_売上詳細 mode="new" />,
    loader: async () => {
      const parameter = 売上詳細画面初期表示Parameter.createNewDisplayData()
      parameter.新規登録モード = true
      const result = await callComplexPostEndpointAsync('売上詳細画面初期表示', parameter, {
        ignoreConfirm: true,
      })
      if (result.type !== 'ok') throw result
      return result.returnValue
    },
  },
  {
    path: "/uriage/edit/:id",
    element: <P101_売上詳細 mode="edit" />,
    loader: async ({ params }) => {
      const parameter = 売上詳細画面初期表示Parameter.createNewDisplayData()
      parameter.新規登録モード = false
      parameter.売上SEQ = params.id ?? ''

      const result = await callComplexPostEndpointAsync('売上詳細画面初期表示', parameter, {
        ignoreConfirm: true,
      })
      if (result.type !== 'ok') throw result
      return result.returnValue
    },
  },
] satisfies ReactRouter.RouteObject[]

/**
 * P101 売上詳細
 */
function P101_売上詳細(props: {
  mode: 'new' | 'edit'
}) {
  const loaderData = ReactRouter.useLoaderData() as 売上詳細.DisplayData
  const { revalidate } = ReactRouter.useRevalidator()
  const navigate = ReactRouter.useNavigate()

  // フォーム
  const {
    formMethods,
    Input,
    FieldLabel,
    RootErrors,
    useEditableGrid,
    setServerMessages,
  } = useDisplayDataForm(売上詳細, {
    defaultValues: loaderData,
  })
  const { control, getValues, setValue, reset, handleSubmit, formState: { isDirty, isSubmitting } } = formMethods

  // ルーターがデータを読み込み直したら（保存後の再読み込みなど）、フォームの内容をそのデータに置き換える
  React.useEffect(() => {
    reset(loaderData)
  }, [loaderData, reset])

  // 明細の行の追加・削除。グリッドはこれらの手段を持たないので useFieldArray を併用する。
  // DBに保存済みの明細は読み取り専用で削除もできない。取り消す場合は取消の明細を追加する
  const { append: appendDetailRow, remove: removeDetailRow } = RHF.useFieldArray({ control, name: '売上詳細の売上明細' })
  const handleAddDetailRow = () => {
    const newDetail = 売上詳細.createNewDisplayData_売上詳細の売上明細()
    newDetail.明細ID = UUID.generate()
    newDetail.区分 = '売上'
    newDetail.売上数量 = '1'
    appendDetailRow(newDetail, { shouldFocus: false })
  }
  // グリッドが渡す行の位置は画面上の位置なので、配列インデックスは instanceId から求める
  const handleRemoveDetailRow = useEvent((instanceId: string) => {
    const index = getValues('売上詳細の売上明細').findIndex(row => row.instanceId === instanceId)
    if (index !== -1) removeDetailRow(index)
  })

  // 明細のグリッド
  const [detailGridProps, detailRowMessages] = useEditableGrid('売上詳細の売上明細', {
    columns: col => [
      col.enumeration('区分', { defaultWidth: 80 }),
      col.refTo('商品', { defaultWidth: 360 }),
      col.numeric('商品.売値単価_税抜', { header: '単価(税抜)', defaultWidth: 120, isReadOnly: true }),
      col.numeric('売上数量', { header: '数量', defaultWidth: 100 }),
      col.enumeration('商品.消費税区分', { defaultWidth: 110, isReadOnly: true }),
      // 自動計算の金額は表示専用。手修正の金額が入っている場合はそちらが優先されるので打ち消し線で表示する
      ReadOnlyColumn.numeric('金額(税込)', row => row.売上総額_税込_自動計算, {
        columnId: '売上総額_税込_自動計算',
        defaultWidth: 140,
        suffix: '円',
        getClassName: row => row.売上総額_税込_手修正 ? 'line-through opacity-30' : '',
      }),
      col.numeric('売上総額_税込_手修正', { header: '手修正', defaultWidth: 140 }),
      col.button('削除', (_, rowKey) => handleRemoveDetailRow(rowKey), { defaultWidth: 64, disableResizing: true }),
    ],
  }, [])

  // 自動計算金額（計算処理の実体はサーバー側）
  const totalAmount = RHF.useWatch({ name: '合計金額', control })
  const abortControllerRef = React.useRef<AbortController | null>(null)
  const triggerRecalculation = React.useCallback(async () => {
    // 計算処理の重複実行対策
    abortControllerRef.current?.abort()
    abortControllerRef.current = new AbortController()

    const result = await callComplexPostEndpointAsync('売上金額シミュレート', getValues(), {
      ignoreConfirm: true,
      signal: abortControllerRef.current.signal,
    })
    if (result.type !== 'ok') return
    if (abortControllerRef.current?.signal.aborted) return

    setValue('合計金額', result.returnValue.合計金額)

    const currentArray = getValues().売上詳細の売上明細
    for (const detail of result.returnValue.売上詳細の売上明細) {
      const index = currentArray.findIndex(d => d.明細ID === detail.明細ID)
      if (index === -1) continue
      setValue(`売上詳細の売上明細.${index}.売上総額_税込_自動計算`, detail.売上総額_税込_自動計算)
    }
  }, [getValues, setValue])

  // 自動計算のトリガーとなる項目が何かしら変更されたら、サーバー側の計算処理と同期する
  const watchedDetails = RHF.useWatch({ name: "売上詳細の売上明細", control })
  const recalculateTrigger = JSON.stringify((watchedDetails ?? []).flatMap(detail => [
    detail.明細ID,
    detail.区分,
    detail.商品.外部システム側ID,
    detail.売上数量,
    detail.売上総額_税込_手修正,
  ]))
  React.useEffect(() => {
    triggerRecalculation()
  }, [recalculateTrigger, triggerRecalculation])

  // 保存。検証（外部参照のコードの照合を含む）を通過したら呼ばれる
  const handleSave = handleSubmit(async values => {
    const currentValues = toWillBeChangedApplied(loaderData, values, 売上詳細.deepEqual)

    if (props.mode === 'new') {
      const result = await callComplexPostEndpointAsync('売上新規登録', currentValues)
      if (result.type === 'ok') {
        // 編集中でない状態に戻してから遷移する。戻さないと離脱確認が出る
        reset(values)
        navigate(getLinkUrlToP101売上詳細(result.returnValue.売上SEQ))
      } else if (result.type === 'error') {
        setServerMessages(result.detail)
      }

    } else {
      const result = await callComplexPostEndpointAsync('売上修正', currentValues)
      if (result.type === 'ok') {
        setServerMessages(result.detail)
        revalidate()
      } else if (result.type === 'error') {
        setServerMessages(result.detail)
      }
    }
  })

  // 画面タイトル
  const [browserTitle, pageTitle] = React.useMemo(() => {
    if (props.mode === 'new') {
      return ["売上登録", "売上登録"]
    } else {
      const date = dayjs(loaderData.売上日時).format('YYYY-MM-DD')
      return [
        `売上 No.${loaderData.売上SEQ} (${date})`,
        `売上 No.${loaderData.売上SEQ}`
      ]
    }
  }, [props.mode, loaderData])

  return (
    <PageBase
      browserTitle={browserTitle}
      isDirty={isDirty}
      className="gap-2 px-8 py-2"
      contents={(
        <div className="h-full max-w-6xl flex flex-col gap-y-2 overflow-hidden">

          {/* 画面タイトルと保存ボタン */}
          <div className="flex items-center gap-1">
            <h1 className="flex-1 text-lg font-bold">
              {pageTitle}
            </h1>
            <Button fill onClick={handleSave} loading={isSubmitting}>
              保存
            </Button>
          </div>

          {/* どの項目にも表示されないメッセージ */}
          <RootErrors />

          {/* ヘッダ部 */}
          <FieldGroup labelWidth="5rem">
            <FieldColumn>
              <FieldLabel name="売上日時">
                <Input.DateInput name="売上日時" />
              </FieldLabel>
            </FieldColumn>
            <FieldColumn>
              <FieldLabel name="担当者">
                <Input.RefTo name="担当者" />
              </FieldLabel>
            </FieldColumn>
            <FieldLabel name="備考">
              <Input.TextArea name="備考" className="min-h-16 max-h-28" />
            </FieldLabel>
          </FieldGroup>

          {/* 合計金額 */}
          <div className="flex justify-end font-bold">
            合計: {totalAmount}円
          </div>

          {/* 明細部。明細全体に対するメッセージはラベルの下に、各行に対するメッセージはグリッドの下の一覧とセルに表示される */}
          <FieldLabel
            name="売上詳細の売上明細"
            vertical
            afterLabel={(
              <Button mini outline onClick={handleAddDetailRow}>行追加</Button>
            )}
          >
            {detailRowMessages}
          </FieldLabel>
          <EditableGrid
            {...detailGridProps}
            isReadOnly={row => !!row.existsInDatabase}
            getRowClassName={row => row.区分 === '取消' ? 'text-rose-700' : ''}
            className="flex-1 min-h-32 border border-gray-300"
          />
        </div>
      )}
    />
  )
}
