import * as ReactRouter from "react-router-dom"
import { Link } from "react-router-dom"
import * as Icon from "@heroicons/react/24/solid"
import { FieldColumn, FieldGroup, ReadOnlyColumn, SearchPageBase, useSearchConditionForm, type SortComboItem } from "../ui"
import { callComplexPostEndpointAsync } from "../example/callComplexPostEndpointAsync"
import * as 入荷一覧 from "../__autoGenerated/models/入荷一覧"
import { getLinkUrlToP201入荷詳細 } from "./P201_入荷詳細"
import type { RootNavigationItem } from "../navigationItems"

export const URL = "/nyuka"

/**
 * ルートナビゲーションに表示する項目
 */
export const navigationItem = { to: URL, label: "入荷", icon: Icon.TruckIcon } satisfies RootNavigationItem

/**
 * ルーティング定義
 */
export default {
  path: URL,
  element: <P200_入荷 />,
} satisfies ReactRouter.RouteObject

/**
 * P200 入荷
 */
function P200_入荷() {

  // 検索条件のフォーム
  const form = useSearchConditionForm(入荷一覧)
  const { Input, FieldLabel } = form

  return (
    <SearchPageBase
      form={form}
      pageTitle="入荷"
      searchConditionDefaultSize={160}
      sortOptions={SORT_OPTIONS}
      createInitialCondition={createInitialCondition}
      search={(condition, signal) => callComplexPostEndpointAsync('入荷一覧', condition, { ignoreConfirm: true, signal })}
      header={(
        <Link to={getLinkUrlToP201入荷詳細()} className="text-teal-600 underline">
          新規登録
        </Link>
      )}
      searchCondition={(
        <FieldGroup labelWidth="7rem">
          {/* 入荷の識別と担当 */}
          <FieldColumn>
            <FieldLabel name="入荷ID">
              <Input.TextBox name="入荷ID" />
            </FieldLabel>
            <FieldLabel name="入荷日時">
              <Input.DateInput name="入荷日時" />
            </FieldLabel>
            <FieldLabel name="担当者">
              <Input.RefTo name="担当者" />
            </FieldLabel>
          </FieldColumn>

          {/* 内容と数量 */}
          <FieldColumn>
            <FieldLabel name="備考">
              <Input.TextArea name="備考" />
            </FieldLabel>
            <FieldLabel name="明細件数">
              <Input.NumericTextBox name="明細件数" />
            </FieldLabel>
            <FieldLabel name="入荷数量合計">
              <Input.NumericTextBox name="入荷数量合計" />
            </FieldLabel>
          </FieldColumn>
        </FieldGroup>
      )}
      defineSearchResultColumns={[() => [
        ReadOnlyColumn.interactive<入荷一覧.DisplayData>('', row => (
          <Link
            className="text-sky-600 underline"
            to={getLinkUrlToP201入荷詳細(row.入荷ID)}>
            詳細
          </Link>
        ), { columnId: '詳細リンク', defaultWidth: 60, disableResizing: true, isFixed: true }),
        ReadOnlyColumn.text<入荷一覧.DisplayData>('入荷ID', row => row.入荷ID, { columnId: '入荷ID', defaultWidth: 180 }),
        ReadOnlyColumn.text<入荷一覧.DisplayData>('入荷日時', row => row.入荷日時, { columnId: '入荷日時' }),
        ReadOnlyColumn.text<入荷一覧.DisplayData>('担当者', row => row.担当者.従業員番号, { columnId: '担当者.従業員番号', defaultWidth: 96 }),
        ReadOnlyColumn.text<入荷一覧.DisplayData>('', row => row.担当者.氏名, { columnId: '担当者.氏名', defaultWidth: 144 }),
        ReadOnlyColumn.numeric<入荷一覧.DisplayData>('明細件数', row => row.明細件数, { columnId: '明細件数', defaultWidth: 96 }),
        ReadOnlyColumn.numeric<入荷一覧.DisplayData>('入荷数量合計', row => row.入荷数量合計, { columnId: '入荷数量合計', defaultWidth: 120, suffix: '個' }),
        ReadOnlyColumn.text<入荷一覧.DisplayData>('備考', row => row.備考, { columnId: '備考', defaultWidth: 300 }),
      ], []]}
    />
  )
}

/** 並び順の選択肢 */
const SORT_OPTIONS: SortComboItem<入荷一覧.SortableMember>[] = [
  { key: '入荷一覧.入荷ID', label: '入荷ID' },
  { key: '入荷一覧.入荷日時', label: '入荷日時' },
  { key: '入荷一覧.担当者.従業員Ref.従業員番号', label: '担当者' },
  { key: '入荷一覧.担当者.従業員Ref.氏名', label: '担当者氏名' },
  { key: '入荷一覧.備考', label: '備考' },
  { key: '入荷一覧.明細件数', label: '明細件数' },
  { key: '入荷一覧.入荷数量合計', label: '入荷数量合計' },
]

/** 画面を開いたときとクリアしたときの検索条件。新しい入荷から順に表示する */
function createInitialCondition(): 入荷一覧.SearchCondition {
  return {
    ...入荷一覧.createNewSearchCondition(),
    sort: ['入荷一覧.入荷日時（降順）'],
  }
}
