import React from "react"
import * as RHF from "react-hook-form"
import * as ReactRouter from "react-router-dom"
import useEvent from "react-use-event-hook"
import { EditableGrid } from "@halllky/editable-grid"
import dayjs from "dayjs"
import { UUID } from "uuidjs"
import { Button, FieldColumn, FieldGroup, PageBase, useDisplayDataForm, useLoginLogout } from "../ui"
import { callComplexPostEndpointAsync } from "../example/callComplexPostEndpointAsync"
import * as 入荷詳細 from "../__autoGenerated/models/入荷詳細"
import * as 入荷詳細画面初期表示Parameter from "../__autoGenerated/models/入荷詳細画面初期表示Parameter"
import type * as ログインユーザー情報 from "../__autoGenerated/models/ログインユーザー情報"

/**
 * P201_入荷詳細 へ遷移するためのリンクURLを取得する関数
 */
export function getLinkUrlToP201入荷詳細(入荷ID?: string | null) {
  if (入荷ID) {
    return `/nyuka/edit/${入荷ID}`
  } else {
    return `/nyuka/new`
  }
}

/**
 * ルーティング定義
 */
export default [
  {
    path: "/nyuka/new",
    element: <P201_入荷詳細 mode="new" />,
    loader: () => {
      return Promise.resolve(入荷詳細.createNewDisplayData())
    },
  },
  {
    path: "/nyuka/edit/:id",
    element: <P201_入荷詳細 mode="edit" />,
    loader: async ({ params }) => {
      const parameter = 入荷詳細画面初期表示Parameter.createNewDisplayData()
      parameter.入荷ID = params.id ?? ''

      const result = await callComplexPostEndpointAsync('入荷詳細画面初期表示', parameter, {
        ignoreConfirm: true,
      })
      if (result.type === 'ok') {
        return result.returnValue
      }
      console.error('入荷詳細画面初期表示エラー:', result)
      const msg = result.type === 'error' ? JSON.stringify(result.detail) : 'データの取得に失敗しました。'
      throw new Error(msg)
    }
  },
] satisfies ReactRouter.RouteObject[]

/**
 * P201 入荷詳細
 */
function P201_入荷詳細(props: {
  mode: 'new' | 'edit'
}) {
  const loaderData = ReactRouter.useLoaderData() as 入荷詳細.DisplayData
  const { loginUser } = useLoginLogout()
  const { revalidate } = ReactRouter.useRevalidator()
  const navigate = ReactRouter.useNavigate()

  // フォームの初期値。新規登録の場合は、入荷日時と担当者に現在日時とログインユーザーを入れる
  const initialValues = React.useMemo(
    () => createInitialValues(loaderData, props.mode, loginUser),
    [loaderData, props.mode, loginUser])

  // フォーム
  const {
    formMethods,
    Input,
    FieldLabel,
    RootErrors,
    useEditableGrid,
    setServerMessages,
  } = useDisplayDataForm(入荷詳細, {
    defaultValues: initialValues,
  })
  const { control, getValues, setValue, reset, handleSubmit, formState: { isDirty, isSubmitting } } = formMethods

  // ルーターがデータを読み込み直したら（保存後の再読み込みなど）、フォームの内容をそのデータに置き換える
  React.useEffect(() => {
    reset(initialValues)
  }, [initialValues, reset])

  // 商品を選んだ行のうち、消費税区分が未入力のものには商品の消費税区分を入れる。
  // 外部参照のセルには値の変更を受け取る手段が無いため、フォームの値の変化を購読して行う
  React.useEffect(() => formMethods.subscribe({
    name: '入荷商品一覧',
    formState: { values: true },
    callback: () => {
      getValues('入荷商品一覧').forEach((row, index) => {
        if (!row.消費税区分 && row.商品.消費税区分) {
          setValue(`入荷商品一覧.${index}.消費税区分`, row.商品.消費税区分, { shouldDirty: true })
        }
      })
    },
  }), [formMethods, getValues, setValue])

  // 明細の行の追加・削除。グリッドはこれらの手段を持たないので useFieldArray を併用する
  const { append: appendDetailRow, remove: removeDetailRow } = RHF.useFieldArray({ control, name: '入荷商品一覧' })
  const handleAddDetailRow = () => {
    const newDetail = 入荷詳細.createNewDisplayData_入荷商品一覧()
    newDetail.入荷明細ID = UUID.generate()
    newDetail.数量 = '1'
    appendDetailRow(newDetail, { shouldFocus: false })
  }
  // グリッドが渡す行の位置は画面上の位置なので、配列インデックスは instanceId から求める
  const handleRemoveDetailRow = useEvent((instanceId: string) => {
    const index = getValues('入荷商品一覧').findIndex(row => row.instanceId === instanceId)
    if (index !== -1) removeDetailRow(index)
  })

  // 明細のグリッド
  const [detailGridProps, detailRowMessages] = useEditableGrid('入荷商品一覧', {
    columns: col => [
      col.refTo('商品', { defaultWidth: 360 }),
      col.numeric('数量', { defaultWidth: 110 }),
      col.numeric('仕入単価_税抜', { header: '仕入単価(税抜)', defaultWidth: 150 }),
      col.enumeration('消費税区分', { defaultWidth: 120 }),
      col.textArea('備考', { defaultWidth: 280, wrap: true }),
      col.button('削除', (_, rowKey) => handleRemoveDetailRow(rowKey), { defaultWidth: 64, disableResizing: true }),
    ],
  }, [])

  // 保存。検証（外部参照のコードの照合を含む）を通過したら呼ばれる
  const handleSave = handleSubmit(async values => {
    if (props.mode === 'new') {
      const result = await callComplexPostEndpointAsync('入荷登録', values)
      if (result.type === 'ok') {
        // 編集中でない状態に戻してから遷移する。戻さないと離脱確認が出る
        reset(values)
        navigate(getLinkUrlToP201入荷詳細(result.returnValue.入荷ID))
      } else if (result.type === 'error') {
        setServerMessages(result.detail)
      }

    } else {
      const result = await callComplexPostEndpointAsync('入荷修正', values)
      if (result.type === 'ok') {
        setServerMessages(result.detail)
        revalidate()
      } else if (result.type === 'error') {
        setServerMessages(result.detail)
      }
    }
  })

  // 画面タイトル
  const [browserTitle, pageTitle] = React.useMemo(() => {
    if (props.mode === 'new') {
      return ["入荷登録", "入荷登録"]
    } else {
      const date = dayjs(loaderData.入荷日時).format('YYYY-MM-DD')
      return [
        `入荷 No.${loaderData.入荷ID} (${date})`,
        `入荷 No.${loaderData.入荷ID}`
      ]
    }
  }, [props.mode, loaderData])

  return (
    <PageBase
      browserTitle={browserTitle}
      isDirty={isDirty}
      className="gap-2 px-8 py-2"
      contents={(
        <div className="h-full max-w-5xl flex flex-col gap-y-2 overflow-hidden">

          {/* 画面タイトルと保存ボタン */}
          <div className="flex items-center gap-1">
            <h1 className="flex-1 text-lg font-bold">
              {pageTitle}
            </h1>
            <Button fill onClick={handleSave} loading={isSubmitting}>
              保存
            </Button>
          </div>

          {/* どの項目にも表示されないメッセージ */}
          <RootErrors />

          {/* ヘッダ部 */}
          <FieldGroup labelWidth="5rem">
            <FieldColumn>
              <FieldLabel name="入荷日時">
                <Input.DateInput name="入荷日時" />
              </FieldLabel>
            </FieldColumn>
            <FieldColumn>
              <FieldLabel name="担当者">
                <Input.RefTo name="担当者" />
              </FieldLabel>
            </FieldColumn>
            <FieldLabel name="備考">
              <Input.TextArea name="備考" className="min-h-16 max-h-28" />
            </FieldLabel>
          </FieldGroup>

          {/* 明細部。明細全体に対するメッセージはラベルの下に、各行に対するメッセージはグリッドの下の一覧とセルに表示される */}
          <FieldLabel
            name="入荷商品一覧"
            vertical
            afterLabel={(
              <Button mini outline onClick={handleAddDetailRow}>行追加</Button>
            )}
          >
            {detailRowMessages}
          </FieldLabel>
          <EditableGrid
            {...detailGridProps}
            className="flex-1 min-h-32 border border-gray-300"
          />
        </div>
      )}
    />
  )
}

/** フォームの初期値。新規登録の場合は、入荷日時と担当者に現在日時とログインユーザーを入れる */
function createInitialValues(
  loaderData: 入荷詳細.DisplayData,
  mode: 'new' | 'edit',
  loginUser: ログインユーザー情報.DisplayData | null,
): 入荷詳細.DisplayData {
  if (mode === 'edit') return loaderData

  const values = window.structuredClone(loaderData)
  values.入荷日時 = dayjs().format('YYYY-MM-DDTHH:mm')
  values.担当者.従業員番号 = loginUser?.従業員番号 ?? ''
  values.担当者.氏名 = loginUser?.氏名 ?? ''
  return values
}
