import React from "react"
import * as ReactRouter from "react-router"
import { useNavigate, Link } from "react-router-dom"
import { SearchPageBase, SortComboItem } from "../layout/SearchPageBase"
import { FormLabel } from "../layout/FormLabel"
import { 商品一覧SearchCondition, createNew商品一覧SearchCondition } from "../__autoGenerated/商品一覧"
import * as UI from "../input/Field"
import { UseFormReturn } from "react-hook-form"

export const URL = "/shohin"

/**
 * P300_商品 へ遷移するためのフック
 */
export function useNavigateToP300商品() {
  const navigate = useNavigate()
  return React.useCallback(() => {
    navigate(URL)
  }, [navigate])
}

/**
 * ルーティング定義
 */
export default {
  path: URL,
  element: <P300_商品 />,
  loader: undefined,
} satisfies ReactRouter.RouteObject

/**
 * P300 商品
 */
function P300_商品() {
  const sortOptions = React.useMemo((): SortComboItem<"商品一覧">[] => [
    { key: '商品一覧.商品SEQ', label: '商品SEQ' },
    { key: '商品一覧.外部システム側ID', label: '外部システム側ID' },
    { key: '商品一覧.商品名', label: '商品名' },
    { key: '商品一覧.売値単価_税抜', label: '売値単価(税抜)' },
    { key: '商品一覧.消費税区分', label: '消費税区分' },
    { key: '商品一覧.在庫数', label: '在庫数' },
  ], [])

  const createInitialCondition = React.useCallback((): 商品一覧SearchCondition => ({
    ...createNew商品一覧SearchCondition(),
    sort: ['商品一覧.商品SEQ（昇順）'],
  }), [])

  return (
    <SearchPageBase
      queryModelType="商品一覧"
      pageTitle="商品"
      searchConditionDefaultSize={160}
      sortOptions={sortOptions}
      createInitialCondition={createInitialCondition}
      renderSearchCondition={SearchCondition}
      defineSearchResultColumns={[columnFor => [
        {
          header: '',
          widthPx: 60,
          render: row => (
            <Link
              className="text-sky-600 underline"
              to={`/shohin/${row.values.商品SEQ}`}>
              詳細
            </Link>
          ),
        },
        columnFor('values.外部システム側ID', { widthPx: 152 }),
        columnFor('values.商品名', { widthPx: 300 }),
        columnFor('values.売値単価_税抜', { header: '売値単価(税抜)', widthPx: 140 }),
        columnFor('values.消費税区分', { widthPx: 120 }),
        columnFor('values.在庫数'),
      ], []]}
    />
  )
}

function SearchCondition({ register, control, setFocus }: UseFormReturn<商品一覧SearchCondition>): React.ReactNode {

  React.useEffect(() => {
    setFocus("filter.外部システム側ID")
  }, [setFocus])

  return (
    <div className="h-full py-1 flex flex-col lg:flex-row lg:items-start gap-x-8 gap-y-2">

      {/* 左列 */}
      <div className="grid grid-cols-[10rem_12rem] gap-2">

        <FormLabel className="text-right">外部システム側ID</FormLabel>
        <UI.Field name="filter.外部システム側ID" control={control} />

        <FormLabel className="text-right">商品名</FormLabel>
        <UI.Field name="filter.商品名" control={control} />
      </div>

      {/* 右列 */}
      <div className="grid grid-cols-[10rem_24rem] gap-2">

        <FormLabel className="text-right">売値単価(税抜)</FormLabel>
        <UI.Field name="filter.売値単価_税抜" type="numeric" control={control} />

        <FormLabel className="text-right">消費税区分</FormLabel>
        <UI.Field name="filter.消費税区分" control={control} />

        <FormLabel className="text-right">在庫数</FormLabel>
        <UI.Field name="filter.在庫数" type="numeric" control={control} />
      </div>
    </div>
  )
}
