import React from "react"
import * as ReactRouter from "react-router-dom"
import { Link } from "react-router-dom"
import * as Icon from "@heroicons/react/24/solid"
import { Button, FieldColumn, FieldGroup, ReadOnlyColumn, SearchPageBase, useSearchConditionForm, type SortComboItem } from "../ui"
import { callComplexPostEndpointAsync } from "../example/callComplexPostEndpointAsync"
import * as 商品一覧 from "../__autoGenerated/models/商品一覧"
import * as 商品 from "../__autoGenerated/models/商品"
import { getLinkUrlToP301商品詳細 } from "./P301_商品詳細"
import { 在庫調整ダイアログ, toProductRefTarget } from "./shared/在庫調整ダイアログ"
import type { RootNavigationItem } from "../navigationItems"

export const URL = "/shohin"

/**
 * ルートナビゲーションに表示する項目
 */
export const navigationItem = { to: URL, label: "商品", icon: Icon.CubeIcon } satisfies RootNavigationItem

/**
 * ルーティング定義
 */
export default {
  path: URL,
  element: <P300_商品 />,
} satisfies ReactRouter.RouteObject

/**
 * P300 商品
 */
function P300_商品() {

  // 在庫調整ダイアログで在庫を調整する商品。ダイアログを表示していない間は undefined
  const [stockAdjTarget, setStockAdjTarget] = React.useState<商品.RefTarget>()

  // 検索条件のフォーム
  const form = useSearchConditionForm(商品一覧)
  const { Input, FieldLabel } = form

  return (
    <>
      <SearchPageBase
        form={form}
        pageTitle="商品"
        searchConditionDefaultSize={160}
        sortOptions={SORT_OPTIONS}
        createInitialCondition={createInitialCondition}
        search={(condition, signal) => callComplexPostEndpointAsync('商品一覧', condition, { ignoreConfirm: true, signal })}
        searchCondition={(
          <FieldGroup labelWidth="10rem">
            {/* 商品の識別 */}
            <FieldColumn>
              <FieldLabel name="外部システム側ID">
                <Input.TextBox name="外部システム側ID" />
              </FieldLabel>
              <FieldLabel name="商品名">
                <Input.TextBox name="商品名" />
              </FieldLabel>
            </FieldColumn>

            {/* 価格と在庫 */}
            <FieldColumn>
              <FieldLabel name="売値単価_税抜">
                <Input.NumericTextBox name="売値単価_税抜" />
              </FieldLabel>
              <FieldLabel name="消費税区分">
                <Input.EnumSelection name="消費税区分" />
              </FieldLabel>
              <FieldLabel name="在庫数">
                <Input.NumericTextBox name="在庫数" />
              </FieldLabel>
            </FieldColumn>
          </FieldGroup>
        )}
        defineSearchResultColumns={[() => [
          ReadOnlyColumn.interactive<商品一覧.DisplayData>('', row => (
            <Link
              className="text-sky-600 underline"
              to={getLinkUrlToP301商品詳細(row.商品SEQ)}>
              詳細
            </Link>
          ), { columnId: '詳細リンク', defaultWidth: 60, disableResizing: true, isFixed: true }),
          ReadOnlyColumn.text<商品一覧.DisplayData>('外部システム側ID', row => row.外部システム側ID, { columnId: '外部システム側ID', defaultWidth: 152 }),
          ReadOnlyColumn.text<商品一覧.DisplayData>('商品名', row => row.商品名, { columnId: '商品名', defaultWidth: 300 }),
          ReadOnlyColumn.numeric<商品一覧.DisplayData>('売値単価(税抜)', row => row.売値単価_税抜, { columnId: '売値単価_税抜', defaultWidth: 140, suffix: '円' }),
          ReadOnlyColumn.text<商品一覧.DisplayData>('消費税区分', row => row.消費税区分, { columnId: '消費税区分', defaultWidth: 120 }),
          ReadOnlyColumn.numeric<商品一覧.DisplayData>('在庫数', row => row.在庫数, { columnId: '在庫数' }),
          ReadOnlyColumn.interactive<商品一覧.DisplayData>('', row => (
            <Button outline mini onClick={() => setStockAdjTarget(toProductRefTarget(row))}>
              在庫調整
            </Button>
          ), { columnId: '在庫調整ボタン', defaultWidth: 96, disableResizing: true }),
        ], []]}
      />

      {/* 在庫調整ダイアログ */}
      {stockAdjTarget && (
        <在庫調整ダイアログ
          product={stockAdjTarget}
          onClose={() => setStockAdjTarget(undefined)}
        />
      )}
    </>
  )
}

/** 並び順の選択肢 */
const SORT_OPTIONS: SortComboItem<商品一覧.SortableMember>[] = [
  { key: '商品一覧.商品SEQ', label: '商品SEQ' },
  { key: '商品一覧.外部システム側ID', label: '外部システム側ID' },
  { key: '商品一覧.商品名', label: '商品名' },
  { key: '商品一覧.売値単価_税抜', label: '売値単価(税抜)' },
  { key: '商品一覧.消費税区分', label: '消費税区分' },
  { key: '商品一覧.在庫数', label: '在庫数' },
]

/** 画面を開いたときとクリアしたときの検索条件 */
function createInitialCondition(): 商品一覧.SearchCondition {
  return {
    ...商品一覧.createNewSearchCondition(),
    sort: ['商品一覧.商品SEQ（昇順）'],
  }
}
