import React from "react"
import * as ReactRouter from "react-router-dom"
import { Link, useSearchParams } from "react-router-dom"
import { EditableGrid } from "@halllky/editable-grid"
import dayjs from "dayjs"
import { Button, PageBase, Pager, ReadOnlyColumn } from "../ui"
import { callComplexPostEndpointAsync } from "../example/callComplexPostEndpointAsync"
import * as 商品一覧 from "../__autoGenerated/models/商品一覧"
import * as 商品在庫増減履歴 from "../__autoGenerated/models/商品在庫増減履歴"
import { getLinkUrlToP101売上詳細 } from "./P101_売上詳細"
import { getLinkUrlToP201入荷詳細 } from "./P201_入荷詳細"
import { 在庫調整ダイアログ, toProductRefTarget } from "./shared/在庫調整ダイアログ"

/**
 * P301_商品詳細 へ遷移するためのリンクURLを取得する関数
 */
export function getLinkUrlToP301商品詳細(商品SEQ: string | null | undefined) {
  return `/shohin/${商品SEQ ?? ''}`
}

type LoaderData = {
  product: 商品一覧.DisplayData
  history: 商品在庫増減履歴.DisplayData[]
  historyTotalCount: number
}

const PAGING_HISTORY_TAKE = 20

/**
 * ルーティング定義
 */
export default {
  path: "/shohin/:id",
  element: <P301_商品詳細 />,
  loader: async ({ params, request }) => {
    const id = params.id
    if (!id) throw new Error("商品IDが指定されていません")

    // 商品情報の取得
    const productCondition = 商品一覧.createNewSearchCondition()
    productCondition.filter.商品SEQ = { from: id, to: id }
    const productPromise = callComplexPostEndpointAsync('商品一覧', productCondition, {
      ignoreConfirm: true
    })

    // 履歴情報の取得
    const url = new URL(request.url)
    const historySkip = url.searchParams.get("historySkip") || "0"
    const historyCondition = 商品在庫増減履歴.createNewSearchCondition()
    historyCondition.filter.商品SEQ = { from: id, to: id }
    historyCondition.sort = ['商品在庫増減履歴.日時（降順）']
    historyCondition.skip = historySkip
    historyCondition.take = PAGING_HISTORY_TAKE.toString()
    const historyPromise = callComplexPostEndpointAsync('商品在庫増減履歴', historyCondition, {
      ignoreConfirm: true
    })

    const [productResult, historyResult] = await Promise.all([productPromise, historyPromise])

    if (productResult.type !== 'ok' || historyResult.type !== 'ok') {
      throw new Error("データの取得に失敗しました")
    }

    if (productResult.returnValue.totalCount === 0) {
      throw new Error("商品が見つかりません")
    }

    return {
      product: productResult.returnValue.currentPageItems[0],
      history: historyResult.returnValue.currentPageItems,
      historyTotalCount: historyResult.returnValue.totalCount,
    } satisfies LoaderData
  },
} satisfies ReactRouter.RouteObject

/**
 * P301 商品詳細
 */
function P301_商品詳細() {
  const data = ReactRouter.useLoaderData() as LoaderData
  const { product, history, historyTotalCount } = data
  const [searchParams, setSearchParams] = useSearchParams()
  const revalidator = ReactRouter.useRevalidator()

  // 在庫調整ダイアログを表示しているかどうか
  const [isStockAdjDialogOpen, setIsStockAdjDialogOpen] = React.useState(false)

  // 在庫増減履歴のページング。現在のページは URL の検索パラメータで持つ
  const historySkip = Number(searchParams.get("historySkip") || "0")
  const historyPageIndex = Math.floor(historySkip / PAGING_HISTORY_TAKE)
  const handleHistoryPageChange = (newPage: number) => {
    setSearchParams(prev => {
      const newSearchParams = new URLSearchParams(prev)
      newSearchParams.set("historySkip", (newPage * PAGING_HISTORY_TAKE).toString())
      return newSearchParams
    })
  }

  // 在庫増減履歴のグリッド
  const historyColumns = React.useMemo(() => [
    ReadOnlyColumn.text<商品在庫増減履歴.DisplayData>('日時', row => row.日時 ? dayjs(row.日時).format('YYYY-MM-DD HH:mm') : '', { columnId: '日時', defaultWidth: 150 }),
    ReadOnlyColumn.text<商品在庫増減履歴.DisplayData>('事由', row => row.事由, { columnId: '事由', defaultWidth: 140 }),
    ReadOnlyColumn.numeric<商品在庫増減履歴.DisplayData>('増減数', row => row.増減数, { columnId: '増減数', defaultWidth: 100 }),
    ReadOnlyColumn.interactive<商品在庫増減履歴.DisplayData>('関連伝票', row => (
      <div className="flex flex-wrap gap-4 items-start">
        {/* 入荷へのリンク */}
        {row.増減履歴引当元売上一覧.length === 0 && row.入荷ID && (
          <Link
            to={getLinkUrlToP201入荷詳細(row.入荷ID)}
            className="text-blue-600 hover:underline flex items-center gap-1"
          >
            <span>入荷 No.{row.入荷ID}</span>
          </Link>
        )}

        {/* 売上へのリンク */}
        {row.増減履歴引当元売上一覧.map((sales, j) => (
          <Link
            key={j}
            to={getLinkUrlToP101売上詳細(sales.売上SEQ)}
            className="text-blue-600 hover:underline flex items-center gap-1"
          >
            <span>売上 No.{sales.売上SEQ}</span>
          </Link>
        ))}
      </div>
    ), { columnId: '関連伝票', defaultWidth: 320, wrap: true }),
  ], [])
  const historyRowKeys = React.useMemo(() => history.map((_, index) => index.toString()), [history])
  const getLatestHistoryRowObject = React.useCallback((index: number) => history[index], [history])

  return (
    <PageBase
      browserTitle={`商品詳細: ${product.商品名}`}
      className="max-w-5xl gap-2 overflow-hidden pb-1"
      header={
        <>
          {/* 商品名とコード */}
          <h1 className="text-xl font-bold flex items-center gap-2">
            {product.商品名}
            <span className="text-gray-500 text-sm font-normal">
              商品コード: {product.外部システム側ID}
            </span>
          </h1>
          <Button outline onClick={() => setIsStockAdjDialogOpen(true)}>在庫調整</Button>
        </>
      }
      contents={
        <>
          {/* 価格と在庫 */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="flex flex-col">
              <span className="text-xs text-gray-500">標準売単価</span>
              <span className="text-lg font-bold">{product.売値単価_税抜} 円</span>
            </div>
            <div className="flex flex-col">
              <span className="text-xs text-gray-500">消費税</span>
              <span className="text-lg">{product.消費税区分}</span>
            </div>
            <div className="flex flex-col">
              <span className="text-xs text-gray-500">現在庫数</span>
              <span className="text-lg font-bold">{product.在庫数}</span>
            </div>
          </div>

          {/* 在庫増減履歴一覧 */}
          <div className="flex-1 flex flex-col gap-2 overflow-hidden mt-2">
            <h2 className="text-xs text-gray-500">在庫増減履歴</h2>

            <EditableGrid
              rowKeys={historyRowKeys}
              getLatestRowObject={getLatestHistoryRowObject}
              columns={historyColumns}
              className="flex-1 border border-gray-300"
            />
          </div>

          {/* 在庫増減履歴のページング */}
          <Pager
            pageIndex={historyPageIndex}
            pageSize={PAGING_HISTORY_TAKE}
            totalCount={historyTotalCount}
            onPageChange={handleHistoryPageChange}
          />

          {/* 在庫調整ダイアログ */}
          {isStockAdjDialogOpen && (
            <在庫調整ダイアログ
              product={toProductRefTarget(product)}
              onClose={() => setIsStockAdjDialogOpen(false)}
              onSuccess={() => revalidator.revalidate()}
            />
          )}
        </>
      } />
  )
}
