import React from "react"
import * as RHF from "react-hook-form"
import * as ReactRouter from "react-router-dom"
import useEvent from "react-use-event-hook"
import { EditableGrid } from "@halllky/editable-grid"
import { Button, FieldColumn, FieldGroup, PageBase, PageTitle, useDisplayDataForm, useSearchConditionForm } from "../ui"
import { callComplexPostEndpointAsync } from "../example/callComplexPostEndpointAsync"
import { toWillBeChangedApplied } from "../example/toWillBeChangedApplied"
import * as 従業員マスタ from "../__autoGenerated/models/従業員マスタ"
import * as 従業員一括更新Parameter from "../__autoGenerated/models/従業員一括更新Parameter"

export const URL = "/jugyoin"

/**
 * ルーティング定義
 */
export default {
  path: URL,
  element: <P400_従業員 />,
  // 画面を開いたときは、絞り込まずに検索した結果を表示する
  loader: () => search従業員(従業員マスタ.createNewSearchCondition()),
} satisfies ReactRouter.RouteObject

/**
 * P400 従業員。
 * 検索した従業員を一覧で編集し、まとめて保存する。
 */
function P400_従業員() {
  const loaderData = ReactRouter.useLoaderData() as 従業員一括更新Parameter.DisplayData

  // 検索条件のフォーム
  const searchForm = useSearchConditionForm(従業員マスタ)

  // 一覧編集のフォーム
  const {
    formMethods,
    useEditableGrid,
    RootErrors,
    setServerMessages,
  } = useDisplayDataForm(従業員一括更新Parameter, {
    defaultValues: loaderData,
  })
  const { control, getValues, setValue, reset, handleSubmit, formState: { isDirty, isSubmitting } } = formMethods

  // 検索した時点のデータ。保存時に、どの行が変更されたかを判定するのに使う
  const searchedDataRef = React.useRef(loaderData)

  // 検索実行。編集中の内容は破棄して検索結果に置き換える
  const handleSearch = searchForm.formMethods.handleSubmit(async condition => {
    const data = await search従業員(condition)
    searchedDataRef.current = data
    reset(data)
  })

  // 行の追加・削除。グリッドはこれらの手段を持たないので useFieldArray を併用する。
  // DBに保存済みの行は削除フラグを立てるだけにして（保存時に削除される）、復元できるようにする。新規追加した行は配列から取り除く
  const { append, remove } = RHF.useFieldArray({ control, name: '更新対象従業員一覧' })
  const handleAddRow = () => {
    append(従業員一括更新Parameter.createNewDisplayData_更新対象従業員一覧())
  }
  // グリッドが渡す行の位置は画面上の位置なので、配列インデックスは instanceId から求める
  const handleRemoveRow = useEvent((instanceId: string) => {
    const index = getValues('更新対象従業員一覧').findIndex(row => row.instanceId === instanceId)
    if (index === -1) return
    if (getValues(`更新対象従業員一覧.${index}.existsInDatabase`)) {
      setValue(`更新対象従業員一覧.${index}.willBeDeleted`, true, { shouldDirty: true })
    } else {
      remove(index)
    }
  })
  const handleRestoreRow = useEvent((instanceId: string) => {
    const index = getValues('更新対象従業員一覧').findIndex(row => row.instanceId === instanceId)
    if (index !== -1) setValue(`更新対象従業員一覧.${index}.willBeDeleted`, false, { shouldDirty: true })
  })

  // 一覧のグリッド。削除フラグの立った行は、復元ボタン以外を読み取り専用にする
  const [gridProps, rowMessages] = useEditableGrid('更新対象従業員一覧', {
    columns: col => [
      col.button('削除', (_, rowKey) => handleRemoveRow(rowKey), { isFixed: true, isReadOnly: row => row.willBeDeleted }),
      col.button('復元', (_, rowKey) => handleRestoreRow(rowKey), { isFixed: true, isReadOnly: row => !row.willBeDeleted }),
      col.text('従業員.従業員番号', { defaultWidth: 160, isReadOnly: row => row.existsInDatabase || row.willBeDeleted }),
      col.text('従業員.氏名', { defaultWidth: 240, isReadOnly: row => row.willBeDeleted }),
      col.checkBox('従業員.入荷担当', { defaultWidth: 88, isReadOnly: row => row.willBeDeleted }),
      col.checkBox('従業員.販売担当', { defaultWidth: 88, isReadOnly: row => row.willBeDeleted }),
      col.checkBox('従業員.システム管理者', { header: '管理者', defaultWidth: 88, isReadOnly: row => row.willBeDeleted }),
    ],
  }, [])

  // 保存。保存できたら、同じ検索条件で検索し直して最新の状態（Version等）を表示する
  const handleSave = handleSubmit(async values => {
    const data = toWillBeChangedApplied(searchedDataRef.current, values, 従業員一括更新Parameter.deepEqual)
    const result = await callComplexPostEndpointAsync('従業員一括更新', data)
    if (result.type === 'ok') {
      const searched = await search従業員(searchForm.formMethods.getValues())
      searchedDataRef.current = searched
      reset(searched)
      setServerMessages(result.detail)
    } else if (result.type === 'error') {
      setServerMessages(result.detail)
    }
  })

  return (
    <PageBase
      browserTitle="従業員"
      isDirty={isDirty}
      className="gap-2 px-8 py-2"
      header={(
        <>
          <PageTitle>従業員</PageTitle>
          <div className="flex-1"></div>
          <Button fill loading={isSubmitting} onClick={handleSave}>保存</Button>
        </>
      )}
      contents={(
        <div className="flex-1 flex flex-col gap-4">

          {/* 検索条件エリア */}
          <form noValidate onSubmit={handleSearch} className="border p-2 rounded bg-gray-50 flex flex-col gap-2">
            <searchForm.RootErrors />
            <div className="flex gap-4 items-end">
              <FieldGroup labelWidth="4rem" className="flex-1">
                <FieldColumn>
                  <searchForm.FieldLabel name="氏名">
                    <searchForm.Input.TextBox name="氏名" />
                  </searchForm.FieldLabel>
                </FieldColumn>
              </FieldGroup>
              <Button outline submit>検索</Button>
            </div>
          </form>

          {/* どの項目にも表示されないメッセージ */}
          <RootErrors />

          {/* 一覧編集エリア */}
          <div className="flex-1 min-h-0 flex flex-col gap-2">
            <div>
              <Button outline mini onClick={handleAddRow}>＋ 行追加</Button>
            </div>
            {rowMessages}
            <EditableGrid
              {...gridProps}
              getRowClassName={row => row.willBeDeleted ? "bg-red-50 opacity-60" : ""}
              className="flex-1 border border-gray-300"
            />
          </div>
        </div>
      )}
    />
  )
}

/** 従業員を検索し、一覧編集のフォームの値にして返す。検索に失敗した場合は空の一覧を返す */
async function search従業員(condition: 従業員マスタ.SearchCondition): Promise<従業員一括更新Parameter.DisplayData> {
  const data = 従業員一括更新Parameter.createNewDisplayData()
  const result = await callComplexPostEndpointAsync('従業員マスタ', condition, {
    ignoreConfirm: true,
  })
  if (result.type !== 'ok') return data

  data.更新対象従業員一覧 = result.returnValue.currentPageItems.map(item => {
    const row = 従業員一括更新Parameter.createNewDisplayData_更新対象従業員一覧()
    row.従業員 = item
    row.existsInDatabase = true
    row.willBeChanged = false
    return row
  })
  return data
}
