using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Text;
using System.Threading.Tasks;

namespace Nijo.CodeGenerating {
    /// <summary>
    /// 自動生成されるソースコードのファイル1個分
    /// </summary>
    public class SourceFile {
        /// <summary>
        /// 自動生成されるソースコードのファイル1個分を表すクラスを作成します。
        /// </summary>
        /// <param name="callerFilePath">このソースファイルがどのファイルから生成されたか（コンパイル時に自動的に設定される）</param>
        /// <param name="callerMemberName">このソースファイルがどのメソッドから生成されたか（コンパイル時に自動的に設定される）</param>
        public SourceFile([CallerFilePath] string? callerFilePath = null, [CallerMemberName] string? callerMemberName = null) {
            CallerFilePath = callerFilePath;
            CallerMemberName = callerMemberName;
        }

        /// <summary>このソースファイルがどのファイルから生成されたか</summary>
        public string? CallerFilePath { get; }
        /// <summary>このソースファイルがどのメソッドから生成されたか</summary>
        public string? CallerMemberName { get; }

        /// <summary>生成されるファイルの名前</summary>
        public required string FileName { get; init; }
        /// <summary>生成されるファイルの内容</summary>
        public required string Contents { get; init; }

        internal void Render(string filepath) {

            // 出力ファイルの形式を決める
            var ext = Path.GetExtension(filepath).ToLower();
            var encoding = ext == ".cs" || ext == ".sql"
                ? Encoding.UTF8 // With BOM
                : new UTF8Encoding(false);
            var newLine = ext == ".cs" || ext == ".sql"
                ? "\r\n"
                : "\n";
            var comment = ext switch {
                ".sql" => "--",
                ".css" => "",
                _ => "//",
            };
            using var sw = new StreamWriter(filepath, append: false, encoding) {
                NewLine = newLine,
            };

            // ファイル先頭の注意書き
            if (ext != ".md" && !CodeRenderingContext.CurrentContext.Config.SuppressAutoGeneratedComment) {
                sw.WriteLine($$"""
                    {{(ext == ".css" ? "/*" : "")}}
                    {{comment}} このファイルは自動生成されました。このファイルの内容を直接書き換えても、次回の自動生成処理で上書きされるのでご注意ください。
                    {{(CallerFilePath != null ? $"{comment} ※ このファイルを生成したクラス  : {Path.GetFileName(CallerFilePath)}" : "")}}
                    {{(CallerMemberName != null ? $"{comment} ※ このファイルを生成したメソッド: {CallerMemberName}" : "")}}
                    {{(ext == ".css" ? "*/" : "")}}
                    """.ReplaceLineEndings(newLine));
            }

            // WithIndent 用のスタック
            var indentStack = new Stack<string>();
            var splitted = Contents.Split(["\r\n", "\n"], StringSplitOptions.None);
            var endsWithNewLine = Contents
                .ReplaceLineEndings(newLine)
                .EndsWith(newLine, StringComparison.Ordinal);

            for (var i = 0; i < splitted.Length; i++) {
                var rawLine = splitted[i];
                var containsSkipMarker = rawLine.Contains(SKIP_MARKER);
                var currentIndent = string.Concat(indentStack.Reverse());
                var line = rawLine
                    .Replace(SKIP_MARKER, string.Empty)
                    .Replace(INDENT_START_MARKER, string.Empty)
                    .Replace(INDENT_END_MARKER, string.Empty);
                var concatted = currentIndent + line;

                // ループや条件分岐の空展開で発生する余計な空行だけ抑止し、通常の空行は保持する
                if (!containsSkipMarker || !string.IsNullOrWhiteSpace(line)) {
                    sw.Write(string.IsNullOrWhiteSpace(concatted) ? string.Empty : concatted);
                    if (i < splitted.Length - 1 || endsWithNewLine) {
                        sw.WriteLine();
                    }
                }
                UpdateIndentStack(indentStack, rawLine);
            }
        }

        /// <summary>
        /// <see cref="TemplateTextHelper.WithIndent"/> の仕組みを実現するための仕組み。
        /// インデントスタックを更新します。
        /// WithIndentでインデント開始マーカーが見つかったら、その位置までの文字列をスタックに積みます。
        /// WithIndentでインデント終了マーカーが見つかったら、スタックから1つ取り出します。
        /// </summary>
        private static void UpdateIndentStack(Stack<string> indentStack, string line) {
            var searchIndex = 0;

            while (searchIndex < line.Length) {
                var nextStart = line.IndexOf(INDENT_START_MARKER, searchIndex, StringComparison.Ordinal);
                var nextEnd = line.IndexOf(INDENT_END_MARKER, searchIndex, StringComparison.Ordinal);

                if (nextStart < 0 && nextEnd < 0) {
                    break;
                }

                if (nextEnd >= 0 && (nextStart < 0 || nextEnd < nextStart)) {
                    if (indentStack.Count == 0) {
                        throw new InvalidOperationException("インデント終了マーカーに対応する開始マーカーがありません。");
                    }

                    indentStack.Pop();
                    searchIndex = nextEnd + INDENT_END_MARKER.Length;
                    continue;
                }

                indentStack.Push(line[..nextStart]);
                searchIndex = nextStart + INDENT_START_MARKER.Length;
            }
        }
    }
}
