import type { DisplayDataDeepEqualOption } from '../__autoGenerated/util/DisplayDataDeepEqualOption'

/**
 * クライアント側での更新処理確定時、
 * サーバーに更新パラメータを送る直前に通す必要がある、
 * willBeChanged 最新化処理。
 *
 * defaultValues （画面表示時の値）と currentValues （現在の値）をディープイコール関数で比較し、
 * 実際に変更されたインスタンスの willBeChanged だけ true に設定した
 * currentValues のディープクローンを返す。
 *
 * null / undefined / '' はすべて「未入力」として同一視する。
 */
export function toWillBeChangedApplied<T>(
  defaultValues: T,
  currentValues: T,
  deepEqualFn: (left: T, right: T, option?: DisplayDataDeepEqualOption) => boolean
): T {
  const clone = structuredClone(currentValues)
  deepEqualFn(defaultValues, clone, {
    setRightObjectWillBeChanged: true,
    compareFunction: (...args) => {
      const [, left, right] = args
      const isEmpty = (v: unknown) => v === null || v === undefined || v === ''
      return (isEmpty(left) && isEmpty(right)) || Object.is(left, right)
    },
  })
  return clone
}
