import { UUID } from "uuidjs"
import * as AutoGenerated from "../__autoGenerated"
import { callAspNetCoreApiAsync } from "./callAspNetCoreApiAsync"

/**
 * 自動生成された以下のエンドポイントを呼び出す。
 * - 一覧検索
 * - 一覧検索（外部参照）
 * - コマンド実行
 * - 一括更新
 */

// 一覧検索
export async function callComplexPostEndpointAsync<
  TQueryModelType extends AutoGenerated.QueryModelType,
  TSearchCondition extends AutoGenerated.LoadFeature.ParamType[TQueryModelType],
  TSearchResult extends AutoGenerated.LoadFeature.ReturnType[TQueryModelType],
>(
  type: TQueryModelType,
  requestBody: TSearchCondition,
  options?: ComplexPostOptions,
): Promise<CompolexPostResult<TSearchResult>>;

// 一覧検索（外部参照）
export async function callComplexPostEndpointAsync<
  TQueryModelType extends AutoGenerated.ReferedQueryModelType,
  TSearchCondition extends AutoGenerated.LoadRefFeature.ParamType[TQueryModelType],
  TSearchResult extends AutoGenerated.LoadRefFeature.ReturnType[TQueryModelType],
>(
  type: TQueryModelType,
  requestBody: TSearchCondition,
  options?: ComplexPostOptions,
): Promise<CompolexPostResult<TSearchResult>>;

// コマンド実行
export async function callComplexPostEndpointAsync<
  TCommandModelType extends AutoGenerated.CommandModelType,
  TCommandParameter extends AutoGenerated.ExecuteFeature.ParamType[TCommandModelType],
  TCommandResult extends AutoGenerated.ExecuteFeature.ReturnType[TCommandModelType],
>(
  type: TCommandModelType,
  requestBody: TCommandParameter,
  options?: ComplexPostOptions,
): Promise<CompolexPostResult<TCommandResult>>;

// 一括更新
export async function callComplexPostEndpointAsync<
  TBatchUpdateModelType extends AutoGenerated.BatchUpdatableQueryModelType,
  TBatchUpdateParameter extends AutoGenerated.BatchUpdateFeature.ParamType[TBatchUpdateModelType],
>(
  type: TBatchUpdateModelType,
  requestBody: TBatchUpdateParameter,
  options?: ComplexPostOptions,
): Promise<CompolexPostResult<unknown>>;

export async function callComplexPostEndpointAsync(
  type: string,
  requestBody: unknown,
  options?: ComplexPostOptions,
): Promise<CompolexPostResult<unknown>> {

  try {
    // 添付ファイルを処理する。
    // リクエスト全体は Content-Type: multipart/form-data で送信する。
    // リクエスト本体は "complex-post-request-body" という名前のフィールドにJSONをまるごと格納する。
    // 添付ファイルは、ファイル1件ごとにUUIDを発番し、そのUUIDをキーとしてファイル本体のバイナリをそのフィールドに格納する。
    const formData = new FormData()
    const stringifiedRequestBody = JSON.stringify(requestBody, (key, value) => {
      // FileListならばこのタイミングでファイル1件ごとにUUIDを発番し、別フィールドにファイルの実体（Blob）を格納する
      if (value instanceof FileList) {
        const fileMetadataList: FileAttachmentMetadata[] = []
        for (const file of value) {
          const uuid = UUID.generate()
          formData.append(uuid, file)
          fileMetadataList.push({
            id: uuid,
            fileName: file.name,
            fileSize: file.size,
          })
        }
        return fileMetadataList
      }
      return value
    })
    formData.append('complex-post-request-body', stringifiedRequestBody)

    // -------------------------
    // 「～しますがよろしいですか？」の確認メッセージが表示される前の、エラーチェックのみを行なうHTTPリクエストでは、
    // クエリパラメータに `ignoreConfirm` を指定しない。
    // 確認メッセージが承諾された後の本処理を行なうHTTPリクエストでは、クエリパラメータに `ignoreConfirm=true` を指定する。
    // オプションで確認メッセージ無視が指定されている場合は1巡目からignoreConfirmを指定する。
    const searchParams = new URLSearchParams()
    if (options?.ignoreConfirm) {
      searchParams.append('ignore-confirm', 'true')
    }

    while (true) {
      const subDirectory = {
        ...AutoGenerated.LoadFeature.Endpoint,
        ...AutoGenerated.LoadRefFeature.Endpoint,
        ...AutoGenerated.ExecuteFeature.Endpoint,
        ...AutoGenerated.BatchUpdateFeature.Endpoint,
      }[type]

      const url = subDirectory + '?' + searchParams.toString()
      const response = await callAspNetCoreApiAsync(url, {
        method: 'POST',
        body: formData,
        signal: options?.signal,
      })

      // HTTPステータスコードが200-299でない場合はエラー。
      // ここで言うエラーは、必須入力漏れなどのエラーが発生したことを示すものではなく、
      // サーバーからの応答が無い、サーバー側で復旧不可のエラーが発生した、などといったものを示す。
      if (!response.ok) {
        return {
          type: 'unknown',
          message: await toDisplayErrorText(response),
        }
      }

      // HTTPステータスコードが200-299の場合はレスポンスをJSONとしてパースする
      const json = await response.json() as PresentationContextResponse<unknown>

      // レスポンスのエラー詳細情報フィールドに値がある場合はそれを表示
      if (json.detail && Object.keys(json.detail).length > 0) {
        return {
          type: 'error',
          detail: json.detail,
        }
      }

      // 確認メッセージがある場合はそれを表示
      if (json.confirms.length > 0) {
        if (window.confirm(json.confirms.join('\n'))) {
          // 承諾された場合はignoreConfirmをtrueにしてHTTPリクエスト2巡目に進む
          searchParams.set(IGNORE_CONFIRM, 'true')
          continue
        } else {
          // 承諾されなかった場合はリクエストを中止
          return { type: 'canceled' }
        }
      }

      return { type: 'ok', returnValue: json.returnValue }
    }

  } catch (error) {
    if (error instanceof DOMException && error.name === 'AbortError') {
      return { type: 'canceled' }
    }
    return { type: 'unknown', message: handleUnknownError(error) }
  }
}

// -----------------------------
// 内部処理用ヘルパー関数等

/** ComplexPostの結果 */
export type CompolexPostResult<TSuccess>
  = { type: 'ok', returnValue: TSuccess }
  | { type: 'canceled' }
  | { type: 'error', detail: DetailMessagesContainer }
  | { type: 'unknown', message: string }

/**
 * 未知のエラーを、画面上に表示できる文字列に変換する。
 */
const handleUnknownError = (error: unknown): string => {
  if (error instanceof Error) {
    return error.message
  } else if (typeof error === 'string') {
    return error
  } else {
    return JSON.stringify(error)
  }
}

/**
 * 未知のレスポンスを、画面上に表示できる文字列に変換する。
 */
const toDisplayErrorText = async (response: Response): Promise<string> => {
  // ok の場合はここに来ないはず
  if (response.ok) {
    return '不明なエラーが発生しました'
  }

  try {
    const bodyText = await response.clone().text()
    try {
      const json: unknown = JSON.parse(bodyText)

      if (typeof json === 'string') {
        return json
      } else if (typeof (json as { message: string }).message === 'string') {
        return (json as { message: string }).message
      } else {
        return bodyText
      }
    } catch {
      return bodyText
    }
  } catch (error) {
    return `HTTP ${response.status} ${response.statusText}`
  }
}

/**
 * ComplexPost（ASP.NET Core 側のPresentationContextの仕組みと統合されたPOSTリクエスト）で使われるクエリパラメータの名前。
 * 「～しますがよろしいですか？」の確認メッセージが表示される前の、エラーチェックのみを行なうHTTPリクエストでは付されず、
 * 確認メッセージが承諾された後の本処理を行なうHTTPリクエストではtrueが指定される。
 */
const IGNORE_CONFIRM = "ignore-confirm"

export type ComplexPostOptions = {
  /** 確認メッセージを表示しない */
  ignoreConfirm?: true
  /** 中断用シグナル */
  signal?: AbortSignal
}

/**
 * ComplexPost（ASP.NET Core 側のPresentationContextの仕組みと統合されたPOSTリクエスト）の戻り値。
 * C#側の `PresentationContextInWebApi` クラスの型と合わせる必要がある。
 */
type PresentationContextResponse<T> = {
  /** 詳細メッセージ。パラメータの型と同じ構造をもち、フィールドごとにそのフィールドに対するメッセージが格納される。 */
  detail: DetailMessagesContainer
  /** 確認メッセージ */
  confirms: string[]
  /** トーストメッセージ */
  toastMessage?: string
  /** バックエンドからの戻り値 */
  returnValue: T
}

/**
 * 詳細メッセージの型。
 * パラメータの型と同じ構造をもち、フィールドごとにそのフィールドに対するメッセージが格納される。
 */
export type DetailMessagesContainer = {
  error?: string[]
  warn?: string[]
  info?: string[]
  children?: { [key: string]: DetailMessagesContainer }
}

/**
 * エラー・警告・情報メッセージのオブジェクトを項目単位に変換する。
 * 例えば以下のオブジェクトは ['aaa.1.bbb: エラー1, 情報1'] に変換される。
 *
 * ```
 * {
 *   children: {
 *     aaa: {
 *       children: {
 *         '1': {
 *           children: {
 *             bbb: {
 *               error: ['エラー1'],
 *               info: ['情報1']
 *             }
 *           }
 *         }
 *       }
 *     }
 *   }
 * }
 * ```
 */
export const toFlattenStringList = (detail: DetailMessagesContainer): string[] => {
  const result: string[] = []
  const collectMessagesRecursively = (path: string[], current: DetailMessagesContainer) => {
    // error, warn, info を全部まとめて表示
    const allMessages = [...(current.error ?? []), ...(current.warn ?? []), ...(current.info ?? [])]
    if (allMessages.length > 0) {
      const key = path.join('.')
      if (key === '') {
        result.push(allMessages.join(', '))
      } else {
        result.push(`${key}: ${allMessages.join(', ')}`)
      }
    }

    // 子要素を再帰的に処理
    if (current.children) {
      for (const [key, child] of Object.entries(current.children)) {
        collectMessagesRecursively([...path, key], child)
      }
    }
  }
  collectMessagesRecursively([], detail)
  return result
}

/**
 * 添付ファイルのメタデータ。
 * ファイル1件ごとに発番されるID、ファイル名、ファイルサイズを保持する。
 */
type FileAttachmentMetadata = {
  id: string
  fileName: string
  fileSize: number
}
