using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MyApp;

/// <summary>
/// アプリケーションサービス。
/// 主要なロジックはこのクラスに記述される。
/// プレゼンテーション層（UI、スケジューラー、ユニットテスト）から呼び出される。
///
/// このクラスは、デザインパターンの一種である Generation Gap パターンを採用している。
/// つまり、自動生成された基底クラス自動生成されたクラスと齟齬がある場合はコンパイルエラーが発生する作りになっている。
/// （例えば実装必須のメソッドを実装していないなど。）
///
/// 逆に言うとコンパイルエラーが出ない限りは実際のシステムの要件に合わせて自由に修正してよい。
/// </summary>
public partial class OverridedApplicationService : AutoGeneratedApplicationService {

    /// <summary>
    /// コンストラクタ。
    /// DIコンテナから呼び出される。
    /// </summary>
    public OverridedApplicationService(IServiceProvider serviceProvider) : base(serviceProvider) {
    }

    /// <summary>
    /// Entity Framework Core の DBコンテキスト。
    /// DB接続はこのプロパティを通じて行う。
    /// </summary>
    public new OverridedDbContext DbContext => (OverridedDbContext)base.DbContext;

    /// <summary>
    /// 実行時設定。サーバーに配置された appsettings.json の値。
    /// このプロパティを使用しない場合は削除可能。
    /// </summary>
    public RuntimeSetting Settings => ServiceProvider.GetRequiredService<RuntimeSetting>();
}
