using Nijo.Parts.WebServer;
using Nijo.Util.CodeGenerating;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Nijo.Models.CommandModelFeatures {
    /// <summary>
    /// <see cref="CommandModel"/> のすべてのコマンドのWebエンドポイントはこのController内に定義される
    /// </summary>
    internal static class CommandController {

        internal const string CLASSNAME = "AutoGeneratedCommandController";
        internal const string SUBDOMAIN = "command";

        internal static SourceFile Render() {
            return new SourceFile {
                FileName = "Commands.cs",
                RenderContent = ctx => {
                    var appSrv = new ApplicationService();

                    return $$"""
                        using System;
                        using System.Linq;
                        using Microsoft.AspNetCore.Mvc;
                        using System.Text.Json;
                        using System.Text.Json.Nodes;
                        using System.Text.Json.Serialization;

                        namespace {{ctx.Config.RootNamespace}};

                        /// <summary>
                        /// 各種コマンドの呼び出し用Webエンドポイントを提供する ASP.NET Core のコントローラー
                        /// </summary>
                        [ApiController]
                        [Route("{{Controller.SUBDOMAIN}}/{{SUBDOMAIN}}")]
                        public partial class {{CLASSNAME}} : ControllerBase {
                            public {{CLASSNAME}}({{appSrv.ConcreteClassName}} applicationService) {
                                _applicationService = applicationService;
                            }
                            protected readonly {{appSrv.ConcreteClassName}} _applicationService;
                        }
                        """;
                },

            };
        }
    }
}
