import React from 'react'
import { useForm, SubmitHandler } from 'react-hook-form'
import { Modal } from '../../ui/Modal'
import { Button } from '../../ui/Button'
import { FormLabel } from '../../ui/FormLabel'
import { NumericTextBox } from '../../ui/NumericTextBox'
import { DescriptionTextArea } from '../../ui/DescriptionTextArea'
import { numericPropsOf } from '../../app/fieldMetadata'
import * as DetailMessage from "../../app/DetailMessageContext"
import { callComplexPostEndpointAsync, toFlattenStringList } from '../../example/callComplexPostEndpointAsync'
import * as 在庫調整Parameter from "../../__autoGenerated/models/在庫調整Parameter"
import * as 商品 from "../../__autoGenerated/models/商品"

type Props = {
  isOpen: boolean
  onClose: () => void
  onSuccess?: () => void
  product: 商品.RefTarget
}

/**
 * 在庫調整ダイアログ。
 * 複数の画面から呼ばれる
 */
export function StockAdjustmentDialog({ isOpen, onClose, onSuccess, product }: Props) {

  const { handleSubmit, register, reset, formState: { isSubmitting } } = useForm<在庫調整Parameter.Structure>({
    defaultValues: 在庫調整Parameter.createNewStructure(),
  })

  React.useEffect(() => {
    if (isOpen) {
      const init = 在庫調整Parameter.createNewStructure()
      init.商品 = product
      reset(init)
    }
  }, [isOpen, product, reset])

  const { replaceMessages } = DetailMessage.useSetter()
  const onSubmit: SubmitHandler<在庫調整Parameter.Structure> = async (data) => {
    const parameter = 在庫調整Parameter.createNewDisplayData()
    parameter.商品 = data.商品
    parameter.増減数 = data.増減数
    parameter.絶対数 = data.絶対数
    parameter.在庫調整理由 = data.在庫調整理由

    const result = await callComplexPostEndpointAsync('在庫調整登録', parameter)

    if (result.type === 'ok') {
      onSuccess?.()
      onClose()
    } else if (result.type === 'error') {
      replaceMessages(result.detail)
    } else if (result.type === 'canceled') {
      // 何もしない
    }
  }

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title={`在庫調整: ${product.商品名 ?? ''}`}
      widthClass="max-w-xl"
    >
      <div className="p-4">
        <form onSubmit={handleSubmit(onSubmit)} className="flex flex-col gap-4">

          <div className="grid grid-cols-[8rem_1fr] gap-2 items-center">
            <FormLabel className="text-right">商品コード</FormLabel>
            <div className="px-2 py-1 bg-gray-100 rounded text-sm">
              {product.外部システム側ID}
            </div>

            <FormLabel className="text-right">商品名</FormLabel>
            <div className="px-2 py-1 bg-gray-100 rounded text-sm">
              {product.商品名}
            </div>

            <div className="col-span-2 border-t my-2"></div>

            <DetailMessage.Rest className="col-span-2" />

            <FormLabel className="text-right">増減数</FormLabel>
            <NumericTextBox {...register("増減数")} {...numericPropsOf(在庫調整Parameter.metadata.displayData, "増減数")} />

            <FormLabel className="text-right">絶対数</FormLabel>
            <NumericTextBox {...register("絶対数")} {...numericPropsOf(在庫調整Parameter.metadata.displayData, "絶対数")} />

            <FormLabel className="text-right">在庫調整理由</FormLabel>
            <DescriptionTextArea {...register("在庫調整理由")} />
          </div>

          <div className="flex justify-end gap-2 mt-4">
            <Button outline onClick={onClose} disabled={isSubmitting}>キャンセル</Button>
            <Button fill submit loading={isSubmitting}>実行</Button>
          </div>
        </form>
      </div>
    </Modal>
  )
}
