import type * as AutoGenerated from "../../__autoGenerated"
import type { BreadcrumbItem } from "../../ui"

/*
 * メタデータから組み立てた画面の URL。
 * 一覧の画面と各画面が互いにリンクするので、どちらの画面のモジュールにも置かずここにまとめる。
 */

/** 自動生成画面一覧の URL */
export const AUTO_INDEX_PAGE_URL = "/auto"

/** 自動一覧検索画面の URL */
export const getAutoSearchPageUrl = (queryModel: AutoGenerated.QueryModelType) => `${AUTO_INDEX_PAGE_URL}/search/${encodeURIComponent(queryModel)}`

/** 自動コマンド実行画面の URL */
export const getAutoCommandPageUrl = (commandModel: AutoGenerated.CommandModelType) => `${AUTO_INDEX_PAGE_URL}/command/${encodeURIComponent(commandModel)}`

/** 自動生成画面一覧の下にある各画面のパンくずリスト */
export const AUTO_PAGE_BREADCRUMB: BreadcrumbItem[] = [
  { label: '自動生成画面', to: AUTO_INDEX_PAGE_URL },
]
