import * as ReactRouter from "react-router-dom"
import { Link } from "react-router-dom"
import * as AutoGenerated from "../../__autoGenerated"
import { PageBase, PageTitle } from "../../ui"
import { AUTO_INDEX_PAGE_URL, getAutoCommandPageUrl, getAutoSearchPageUrl } from "./自動生成画面URL"

export const URL = AUTO_INDEX_PAGE_URL

/**
 * ルーティング定義
 */
export default {
  path: URL,
  element: <自動生成画面一覧 />,
} satisfies ReactRouter.RouteObject

/**
 * メタデータから組み立てた画面の一覧。
 * すべてのクエリモデルの一覧検索画面と、すべてのコマンドの実行画面へのリンクを並べる。
 */
function 自動生成画面一覧() {
  return (
    <PageBase
      browserTitle="自動生成画面"
      header={(
        <PageTitle>自動生成画面</PageTitle>
      )}
      contents={(
        <div className="h-full overflow-auto flex flex-wrap items-start gap-12 px-8 py-4">

          {/* 一覧検索画面 */}
          <section className="flex flex-col gap-1">
            <h2 className="font-bold text-gray-700 select-none">Query Model</h2>
            {AutoGenerated.getQueryModelTypeList().map(queryModel => (
              <Link key={queryModel} to={getAutoSearchPageUrl(queryModel)} className="text-sky-600 underline">
                {queryModel}
              </Link>
            ))}
          </section>

          {/* コマンド実行画面 */}
          <section className="flex flex-col gap-1">
            <h2 className="font-bold text-gray-700 select-none">Command Model</h2>
            {AutoGenerated.getCommandModelTypeList().map(commandModel => (
              <Link key={commandModel} to={getAutoCommandPageUrl(commandModel)} className="text-sky-600 underline">
                {commandModel}
              </Link>
            ))}
          </section>
        </div>
      )}
    />
  )
}
