using Nijo.CodeGenerating;
using Nijo.ImmutableSchema;
using Nijo.Parts.Common;
using Nijo.Parts.CSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;

namespace Nijo.Models.CommandModelModules {
    /// <summary>
    /// コマンド処理
    /// </summary>
    internal class CommandProcessing {
        internal CommandProcessing(RootAggregate aggregate) {
            _rootAggregate = aggregate;
        }
        private readonly RootAggregate _rootAggregate;


        private const string CONTROLLER_ACTION_EXECUTE = "execute";
        private const string EXECUTE_METHOD = "Execute";


        #region TypeScript用
        internal static string RenderTsTypeMap(IEnumerable<RootAggregate> commandModels) {

            var items = commandModels.Select(rootAggregate => {
                var controller = new AspNetController(rootAggregate);

                return new {
                    EscapedPhysicalName = rootAggregate.PhysicalName.Replace("'", "\\'"),
                    Endpoint = controller.GetActionNameForClient(CONTROLLER_ACTION_EXECUTE),
                    ParamType = rootAggregate.GetParameterStructure()?.TsTypeName ?? "Record<string, never> // 引数なし",
                    ReturnType = rootAggregate.GetReturnValueStructure()?.TsTypeName ?? "Record<string, never> // 戻り値なし",
                };
            }).ToArray();

            return $$"""
                /** コマンド起動処理 */
                export namespace ExecuteFeature {
                  /** コマンドの実行エンドポイントの一覧 */
                  export const Endpoint: { [key in {{CommandQueryMappings.COMMAND_MODEL_TYPE}}]: string } = {
                {{items.SelectTextTemplate(x => $$"""
                    '{{x.EscapedPhysicalName}}': '{{x.Endpoint}}',
                """)}}
                  }

                  /** コマンドのパラメータ型の一覧 */
                  export interface ParamType {
                {{items.SelectTextTemplate(x => $$"""
                    '{{x.EscapedPhysicalName}}': {{x.ParamType}}
                """)}}
                  }

                  /** コマンドのサーバーからの戻り値の型の一覧 */
                  export interface ReturnType {
                {{items.SelectTextTemplate(x => $$"""
                    '{{x.EscapedPhysicalName}}': {{x.ReturnType}}
                """)}}
                  }
                }
                """;
        }
        #endregion TypeScript用

        internal string RenderAspNetCoreControllerAction(CodeRenderingContext ctx) {
            var paramStructure = _rootAggregate.GetParameterStructure();

            var paramTypeName = paramStructure?.CsClassName ?? "object";
            var paramMessageTypeName = paramStructure != null
                ? new StructureModelModules.StructureTypeMessageContainer(((StructureModel.StructureType)paramStructure).Aggregate).CsClassName
                : MessageContainer.CONCRETE_CLASS;

            return $$"""
                /// <summary>
                /// {{_rootAggregate.DisplayName}}のWebからの実行用のエンドポイント
                /// </summary>
                [HttpPost("{{CONTROLLER_ACTION_EXECUTE}}"), {{AspNetController.AUTOGENERATED_ENDPOINT}}({{CommandQueryMappings.E_COMMAND_QUERY_TYPE}}.{{_rootAggregate.PhysicalName}}, {{E_AutoGeneratedActionType.ENUM_NAME}}.{{E_AutoGeneratedActionType.WRITE}})]
                public async Task<IActionResult> Execute(
                    [ModelBinder(BinderType = typeof({{AspNetController.COMPLEX_REQUEST_BODY_BINDER}}<{{paramTypeName}}>))] {{paramTypeName}} {{AspNetController.DATA}},
                    [ModelBinder(BinderType = typeof({{AspNetController.PRESENTATION_CONTEXT_BINDER}}<{{paramMessageTypeName}}>))] {{PresentationContext.INTERFACE}}<{{paramMessageTypeName}}> {{AspNetController.CONTEXT}}) {
                    var returnValue = await _applicationService.{{EXECUTE_METHOD}}(data, context);
                    return _webConfigure.{{AspNetController.TO_ACTION_RESULT}}(returnValue, context);
                }
                """;
        }

        internal string RenderAppSrvMethods(CodeRenderingContext ctx) {
            var paramStructure = _rootAggregate.GetParameterStructure();
            var returnStructure = _rootAggregate.GetReturnValueStructure();

            var paramTypeName = paramStructure?.CsClassName ?? "object";
            var returnTypeName = returnStructure?.CsClassName ?? "object";
            var paramMessageTypeName = paramStructure != null
                ? new StructureModelModules.StructureTypeMessageContainer(((StructureModel.StructureType)paramStructure).Aggregate).CsClassName
                : MessageContainer.CONCRETE_CLASS;

            return $$"""
                /// <summary>
                /// {{_rootAggregate.DisplayName}}処理実行
                /// </summary>
                /// <param name="param">処理パラメータ</param>
                /// <param name="context">実行時コンテキスト。エラーメッセージを保持したり、起動時オプションを持っていたりする。</param>
                public abstract Task<{{returnTypeName}}> {{EXECUTE_METHOD}}({{paramTypeName}} param, {{PresentationContext.INTERFACE}}<{{paramMessageTypeName}}> context);
                """;
        }
    }
}
