import React from "react"
import * as DetailMessage from "../util/DetailMessageContext"
import { callComplexPostEndpointAsync } from "../example/callComplexPostEndpointAsync"
import { createNewログインユーザー情報DisplayData, ログインユーザー情報DisplayData } from "../__autoGenerated/ログインユーザー情報"
import { ログインParameterDisplayData } from "../__autoGenerated/ログインParameter"

/**
 * ログインユーザー情報をセッションストレージに保存するためのキー。
 * セッションストレージに保存することによる複数タブ間でのログイン状態共有を実現する。
 */
const SESSION_STORAGE_KEY = "nijo-login-user"

type LoginUserContextType = {
  loginUser: ログインユーザー情報DisplayData | null
  loginAsync: (data: ログインParameterDisplayData) => Promise<void>
  logoutAsync: () => Promise<void>
}

const LoginUserContext = React.createContext<LoginUserContextType>({
  loginUser: null,
  loginAsync: async () => { },
  logoutAsync: async () => { },
})

/**
 * ログイン処理、ログアウト処理、ログイン中ユーザー情報を提供する。
 */
export function useLoginLogout() {
  return React.useContext(LoginUserContext)
}

export function LoginUserProvider({ children }: { children: React.ReactNode }) {
  const [loginUser, setLoginUser] = React.useState<ログインユーザー情報DisplayData | null>(() => {
    const json = sessionStorage.getItem(SESSION_STORAGE_KEY)
    return json ? JSON.parse(json) as ログインユーザー情報DisplayData : null
  })

  // 他のタブでのログイン状態変更を検知
  React.useEffect(() => {
    const handler = (e: StorageEvent) => {
      if (e.key === SESSION_STORAGE_KEY) {
        if (e.newValue) {
          setLoginUser(JSON.parse(e.newValue))
        } else {
          setLoginUser(null)
        }
      }
    }
    window.addEventListener("storage", handler)
    return () => window.removeEventListener("storage", handler)
  }, [])

  const { replaceMessages } = DetailMessage.useSetter()
  const contextValue = React.useMemo((): LoginUserContextType => {

    // ログイン
    const loginAsync = async (data: ログインParameterDisplayData) => {
      const result = await callComplexPostEndpointAsync('ログイン', data, {
        ignoreConfirm: true,
      })

      if (result.type === 'ok') {
        const user: ログインユーザー情報DisplayData = {
          ...createNewログインユーザー情報DisplayData(),
          ...result.returnValue,
        }
        sessionStorage.setItem(SESSION_STORAGE_KEY, JSON.stringify(user))
        setLoginUser(user)
      } else if (result.type === 'error') {
        replaceMessages(result.detail)
      } else if (result.type === 'unknown') {
        alert(result.message)
      }
    }

    // ログアウト
    const logoutAsync = async () => {
      const result = await callComplexPostEndpointAsync('ログアウト', {}, {
        ignoreConfirm: true,
      })

      if (result.type === 'ok') {
        sessionStorage.removeItem(SESSION_STORAGE_KEY)
        setLoginUser(null)
      } else if (result.type === 'error') {
        replaceMessages(result.detail)
        return
      } else if (result.type === 'unknown') {
        alert(result.message)
        return
      }
    }

    return { loginUser, loginAsync, logoutAsync }
  }, [loginUser, replaceMessages])

  return (
    <LoginUserContext.Provider value={contextValue}>
      {children}
    </LoginUserContext.Provider>
  )
}
